### ISSUE TITLE
Developer Labs / next Twitter API version

### ISSUE THREAD

**Issue by andypiper** [linvi/tweetinvi#1007]
Hello from Twitter Developer Relations!

First of all: Thank You, Thomas, for building on our API, and for supporting our developer communities! You, and many projects like this one, are among the reasons why Twitter data is much-appreciated by developers. We historically haven't built libraries and SDKs - the communities, YOU, have done so - and I'm here to tell you how much we appreciate that, and that we know you're around!

We're currently building a brand new API platform that (over time) will replace the current one. I would love to connect with you on any plans to add support for Twitter Developer Labs! We're looking to be much more focused on proper API versioning, and are basing our specification on OpenAPI.

As we hope you know, we list Tweetinvi as the top library for .NET developers on our libraries page https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries and we would really love to continue to do so as you continue to help the .NET community. Thank you, again!

**Comment by linvi** [comment]
Hi @andypiper ,

I am currently finishing up the version 5.0 of Tweetinvi which will be a good foundation to move to the new version of the api.

I am aware of the new API and look forward to work on it. This might actually be the focus of Tweetinvi 5.1/6.0 after I have completed the [remaining task of current version](https://github.com/linvi/tweetinvi/milestone/19).

I will update this ticket when starting to work on it.

Thanks again for your continuous support :)

Cheers,
Linvi

**Comment by linvi** [comment]
Version 5.0 now supports Twitter API v2. Release coming up coming up.
