### ISSUE TITLE
Trends, Location and Language

### ISSUE THREAD

**Issue by komBAS** [linvi/tweetinvi#101]
Hi,
I use your trends example, which works technically.
```
var trends = Trends.GetTrendsAt(638242);

var trendTermToSearch = trends.Trends.ToList()[0].Name;
var tweets = Search.SearchTweets(trendTermToSearch);
```
With the Yahoo GEO ID 638242 I get all trends for Berlin, Germany. Works perfect.
But the
```
Search.SearchTweets(trendTermToSearch); 
```
ist location independant which delivers wrong tweet results in my opinion.
Let's say a trend keyword for Berlin, Germany is "starwars". If I do a tweet search with this keyword I get only non german tweets. I guess I get the worldwide tweets for this keyword instead.

Thanks,
Kay

**Comment by linvi** [comment]
The code and the result you experience are correct.
`GetTrends` retrieve the trends at a specific location. 
`SearchTweets` searches tweets all around the world if not specified otherwise via the `GeoCode` field.

Because StarWars is quite famous around the world, and you have not specified any location filter for your search, youreceive results from all around the world.

``` c#
// When you search for Tweets you will need to specify the coordinates and the radius for your search.
// Unfortunately Twitter does not allow to search with a Yahoo GEO ID
var tweets = Search.SearchTweets(new TweetSearchParameters("StarWars")
{
    GeoCode = new GeoCode(13.23, 52.31, 20, DistanceMeasure.Miles)
});
```

**Comment by komBAS** [comment]
Hi linvi,

of course this is not your fault, but the bavior of the Twitter API is a bit strange and so is the way a user needs to work with that.

If I MUST use the WOEID to get the trends, it is strange that in the next step I need to use geo coordinates to get the related tweets. Trend keyword alone are a bit useless without tweets I think.

So to realize this task I need to use the Yahoo GeoPlanet API which, from what I saw with a quick search in the online documentation, seems to deliver latitude and longitude too:

https://developer.yahoo.com/geo/geoplanet/guide/concepts.html#positional-consistency

Kay

**Comment by linvi** [comment]
Yes, sorry that I not suggested that, I thought you were aware of this API.
I agree with you concerning the Yahoo GEO ID, it does not make much sense.

Feel free to come back here if you need more help regarding the subject.

**Comment by ebonak** [comment]
That service seems to be down for good, any other way to get current trending topics for US/Europe or other regions with tweetinvi?

https://stackoverflow.com/questions/15780064/yahoo-api-is-geo-api-closed-formerly-where-yahooapis-com
