### ISSUE TITLE
Image profile URL 400x400 not using https

### ISSUE THREAD

**Issue by dev-bre** [linvi/tweetinvi#1013]
Would be useful to get from the authenticated user data the image profile 400x400 in https. There is a property for https, but the image resolution is very low.

I have to apply string manipulation to use https for that 400x400 prop.

**Comment by linvi** [comment]
Your problem is that you don't have any method to fetch a users profile image in 400x400 using the http url?

Please confirm.

**Comment by dev-bre** [comment]
No, the problem is that the 400x400 property does not return an https url.

**Comment by linvi** [comment]
This will be available in version 5.0
