### ISSUE TITLE
Search private posts

### ISSUE THREAD

**Issue by Laionik** [linvi/tweetinvi#103]
Hello, I've just installed your package into my project and I hope it will be rly nice cooperation (its my thesis) ;)
But at the very begining if user with protected tweets will grant permission to my twitter app i should be able to check his posts, right?
Im using Search.SearchTweets("lechtyperdev") to serach posts and i granted permission. Unfortunatelly im not able to get searched post :(

**Comment by linvi** [comment]
You can see his tweets but you cannot search for them. Twitter Search API only searches public tweets.

If you want to get the tweets of a user from whom you have the credentials, you need to use the `Timeline.UserTimeline`.

**Comment by Laionik** [comment]
Oh crap...  thanks for answer, will need more help from twitter users in this case cuz the list of "players" can change all the time.  Thanks for help :)
