### ISSUE TITLE
Use DateTimeOffset

### ISSUE THREAD

**Issue by WorldMaker** [linvi/tweetinvi#1030]
It looks like Twitter APIs return ISO timezone offset information, but as far as I can tell from the DTOs here the offset is lost because all the dates and times are represented as `DateTime` rather than `DateTimeOffset`. It may be as simple as updating the DTOs to `DateTimeOffset` anywhere `DateTime` was used and letting JSON.NET handle the rest.

(I'm currently debugging some timezone related stuff in an app and this "lost" information would be useful.)

**Comment by linvi** [comment]
Hello there,

I was supposed to have closed all entries for version 5.0 but I may add this one there.

Thanks for your feedback,
Linvi

**Comment by linvi** [comment]
Hello @WorldMaker 

Could you share a unit test case highlighting this issue.
I would like to make that this is properly addressed.

Thanks,
Linvi

**Comment by linvi** [comment]
Hello here,

Any problem with the request? I would need to get a failing test from you to make sure that the fix will be working for you.

Thanks,
Linvi

**Comment by WorldMaker** [comment]
Sorry, it is a need for a work project that is currently between development phases and has no remaining budget. I'll try to take a look at it tomorrow; I don't know if I'll have time to get up to speed on your unit testing approach in the time I'll have available.

**Comment by linvi** [comment]
Hi there,

I don't actually need a unit test working directly inside my unit test. You can just write a unit test code with any technology that you'd like.

In the meantime, I have started to perform the changes and I will write some tests on my side.

Cheers,
Linvi

**Comment by linvi** [comment]
Hi @WorldMaker,

I have tried to reproduce this issue without success.
Waiting for your code snippet.

Cheers,
Linvi

**Comment by WorldMaker** [comment]
At a high level, `DateTimeOffset` round-trips a full ISO 8601 datetime string where `DateTime` only pretends to. Round-trips as in the re-serialized output is what was deserialized down to especially the detail of what time zone offset. Take for example a JSON document like:

```json
{
  "example_date": "2020-04-10T12:03:55.4525649-04:30"
}
```

It is useful to use an odd or rare offset like `-04:30` in testing here because it should make it more obvious the cases where `DateTime`'s "pretend" (the hack known as `DateTimeKind`) falls down. `DateTime` works okay in the cases where the offset matches UTC (`Z` or `+00:00` or `-00:00`) or the system local time (whatever your timezone is on your machine).

```c#
var date = DateTimeOffset.Parse("2020-04-10T12:03:55.4525649-04:30");
Debug.Assert(date.ToString("o") == "2020-04-10T12:03:55.4525649-04:30");
Debug.Assert(date.Offset.Hours == -4);
Debug.Assert(date.Offset.Minutes == -30);
```

Well, in checking example output from Twitter it is entirely possible that Twitter is just sending UTC for every time field and this is maybe moot because `DateTimeKind` may be "sufficient" in that case.

**Comment by linvi** [comment]
@WorldMaker Do you agree that if all the Twitter json dates uses UTC the DateTimeOffset is not useful and that I can close this ticket?

**Comment by WorldMaker** [comment]
@linvi In terms of my specific debugging need at the time I posted the issue, we solved that elsewhere and it wasn't specifically a Tweetinvi problem.

I'm still worried about addressing the question of "what time offset did the user post this in?" and I'm surprised that information doesn't seem to be easily included in Twitter's API responses as I would have expected given they are returning ISO 8601 dates, but I realize now that is a Twitter API problem and not a Tweetinvi problem in that case.

I think even in the case where Twitter JSON uses UTC everywhere, as they still use ISO 8601 strings it is still useful to know the date was UTC specifically and the ISO 8601 string is represented in .NET exactly as it was parsed. Several years of working with a number of APIs and globally distributed timezone behaviors have led me to believe that DateTimeOffset should be default in .NET applications and libraries and DateTime considered deprecated, but I realize my experience is maybe uncommon still. More libraries using DateTimeOffset by default I think is better for the overall .NET ecosystem, but ideals aren't always "useful".

In the unlikely (?) event that Twitter were to start sending other timestamp offsets in their ISO 8601 dates (for instance, to better represented the time offset in which the user created a tweet), it could be useful preparation to make a switch to DateTimeOffset today rather than after such a Twitter change, but that may still be an unknown hypothetical more than a scenario to prepare for.

I wish Twitter better documented their API specifically with regards to the implicit assumption that they will always return UTC dates. I did find a direct mention of it, but only specifically in regards to [the Twitter Ads API Getting Started](https://developer.twitter.com/en/docs/ads/general/guides/getting-started), where they do state, at least for the Ads API:

> Datetime values are always returned in UTC time

It's an easy change to switch all uses of DateTime for DateTimeOffset, but it is a breaking change, so I can understand hesitancy to move forward with the change. My experience says it is a change worth making, even if it won't be "fully useful" today or even hypothetically tomorrow (depending on Twitter's relationship with timezones). I do understand if you want to assume Twitter will continue to only return UTC dates and not make the change because you don't have to.

**Comment by linvi** [comment]
Thanks @WorldMaker this is very good insight. I will definitely consider this before moving the library to 5.0 beta stage.

Thanks

**Comment by linvi** [comment]
Thanks for taking the time to provide your knowledge on the topic, I have decided to use DateTimeOffset and you will have access to it in Tweetinvi 5.0-beta1 :)

**Comment by TRON-N** [comment]
Hi @linvi 

We've decided to use your library for a project. It greatly simplifies twitter api access! Thanks for the great work, keep it up! 

With that being said, I suspect the conversion to DateTimeOffset might not be totally complete:

Consider this example in: src\Tweetinvi.Core\Public\Events\AccountActivity\AccountActivityEvent.cs

```
    public class AccountActivityEvent
    {
        public AccountActivityEvent()
        {
            EventDate = new DateTime();
        }

        public long AccountUserId { get; set; }
        public DateTimeOffset EventDate { get; set; }
        public string Json { get; set; }
    }
```

The constructor still initializes EventDate to DateTime instead of DateTimeOffset. This causes the following error when events are sent through from a webhook:

![image](https://user-images.githubusercontent.com/26257545/102183993-6935c180-3eb7-11eb-896a-2ff0282e695e.png)

Changing it to the following solves the problem:
```
     public class AccountActivityEvent
    {
        public AccountActivityEvent()
        {
            EventDate = new DateTimeOffset();
        }

        public long AccountUserId { get; set; }
        public DateTimeOffset EventDate { get; set; }
        public string Json { get; set; }
    }
```

I'm looking forward to your response!

Regards

**Comment by linvi** [comment]
Thanks for the update and the fix.
