### ISSUE TITLE
Use AuthFlow.InitAuthentication in Async Mode

### ISSUE THREAD

**Issue by firephantomassasin** [linvi/tweetinvi#1043]
Hi,

How to use AuthFlow.InitAuthentication in asynchronous approach?

**Comment by linvi** [comment]
Hello,

For `Async` please use Tweetinvi 5.0. It is currently in alpha but being actively worked upon.
Tweetinvi 4.0 was not designed for Async.

You can learn more about authentication in 5.0 here: https://linvi.github.io/tweetinvi/dist/authentication/authentication.html

**Comment by investagrams** [comment]
When will it be ready for production?

**Comment by linvi** [comment]
Hello,

I do not like to give dates as I usually get them wrong. What I can say though is that this alpha has been properly tested and I would like to see Tweetinvi 5.0 getting released by the end of the month.

What changes can happen before release:

* `DateTime` changed to `DateTimeOffset`: https://github.com/linvi/tweetinvi/issues/1030 (likely)
* Methods renamed (unlikely)
* Properties renamed (unlikely)

Currently I am focusing on writing the documentation. As soon as this is done and the issue above is complete this will be pushed in beta.

From your perspective, I would say it is quite safe to proceed with using alpha already as its already very advanced in the development phase (only 1 actual "issue" has not been resolved out of 130 issues).

I hope this helps you make a decision.

**Comment by investagrams** [comment]
Thanks! Will gonna try it after we have migrate our main code to async approach.

**Comment by firephantomassasin** [comment]
Hi! I saw that there is a nuget library already of v5.0, is it stable so far? Do you recommend to update to that version already? So far our code base is slowly migrating to Task based async as well.

**Comment by firephantomassasin** [comment]
@linvi hi linvi, i have some questions regarding the v5.0, do you use and reuse the http client and http client factory in this library? Since there is a common issue in .net http client that causes socket / port exhaustion.

**Comment by linvi** [comment]
Yes this is using the HttpClient as Tweetinvi supports all platforms. 
If you can share a specific article mentioning this it could help me to stay on top of this issue.
