### ISSUE TITLE
TypeInitializationException when using anything in the Auth class (0.9.10.1)

### ISSUE THREAD

**Issue by SpireHex** [linvi/tweetinvi#105]
The Auth class seems to throw this exception every time in 0.9.10.1, I downgraded back to 0.9.10 to test and it didn't throw it anymore, possibly broken something!?

**Comment by linvi** [comment]
Would that be possible to plan a Skype session together during this weekend?
I have added you on gitter.

**Comment by linvi** [comment]
Also would you please share the full stack trace as well as the code you are using (I need to see if you are invoking anything before `Auth.`.

Does the error happens consistently?
Which type of project are you using (ASP.NET, WPF, Console, Windows 10 App)?

**Comment by linvi** [comment]
I need some news from you in order to fix this problem, please reply anywhere, Twitter, Gitter, Github, Codeplex, but please reply!

Thanks

**Comment by SpireHex** [comment]
Sadly it wont give me the stack trace as I need to use it in ASynchronized methods and also its in WUP10, sadly I don't have anything else from there

**Comment by linvi** [comment]
Hello there, would you please try the following to install nuget package:

`Install-Package tweetinviapi -version 0.9.10.2-w10-uap -pre`

Let me know if this worked out for you.

**Comment by SpireHex** [comment]
What ever you did, it fixed it :)

**Comment by linvi** [comment]
Good! I hope you'll like this library!

See you
