### ISSUE TITLE
last two digits of tweet id get zero

### ISSUE THREAD

**Issue by fightlikeagirl** [linvi/tweetinvi#1052]
Hello ,
I have just noticed that last two digits of tweet id get zero. For example: while a tweet url is : 
https://twitter.com/xxxx/status/1265901465186504704
and tweet id is : 1265901465186504700 .
First I thought this error might occur about my class , but I declare it as long which higher values than these ids. How can I solve this ? Thanks.

**Comment by linvi** [comment]
Could you share some code to reproduce?

**Comment by fightlikeagirl** [comment]
Sure.
This is my Tweet class (TweetDTO class) : 
`       public long Idd { get; set; }  // Problem is here
        public string FullName { get; set; }
        public string NickName { get; set; }
        public string ProfilImageUrl { get; set; }
        public string TweetUrl { get; set; }
`

And this is how I get tweet : 
` _stream.MatchingTweetReceived += (sender, data) =>
            {
                TweetDTO stream = new TweetDTO()
                    {
                        Idd = data.Tweet.Id,    // while debugging I get ID 1265901465186504700
                        Tweet = data.Tweet.Text,
                        TweetUrl = data.Tweet.Url,  // and URL is https://twitter.com/xxxx/status/1265901465186504704

                  }}`

**Comment by fightlikeagirl** [comment]
Hello, version is 4.0.3

**Comment by linvi** [comment]
Hello there,

Are you still experiencing this issue?

Thanks,
Linvi

**Comment by linvi** [comment]
I have tested the apis and both API v1 and Stream API are returning expected results.

Closing
