### ISSUE TITLE
AddFollow() does nothing in 4.0 and throws a TwitterException in 5.0 (Filtered Streams)

### ISSUE THREAD

**Issue by NorthwestAlpineSystems** [linvi/tweetinvi#1053]
Hi!

"AddTrack" works for a filtered stream, but "AddFollow" does not.  All I'm trying to do is get an event when "Reuters" tweets something.  Here is the repro. 

1.  Use real credentials in Auth.SetUserCredentials()
2.  Start the program.  Notice no tweets received ([Reuters tweets every few minutes](https://twitter.com/Reuters)).  Stop the program.
3.  If you uncomment the AddTrack, you'll notice you start getting tweets for "software".  However, you still never get tweets from Reuters.

```
using System;
using System.Threading;
using Tweetinvi;
using Tweetinvi.Models;

namespace TweetinviTest
{
    class Program
    {
        static void Main(string[] args)
        {
            ExceptionHandler.SwallowWebExceptions = false;
            TweetinviConfig.CurrentThreadSettings.TweetMode = TweetMode.Extended;
            Auth.SetUserCredentials("removed", "removed", "removed", "removed");

            var stream = Stream.CreateFilteredStream();
            //stream.AddTrack("software");  // This works!
            stream.AddFollow(new UserIdentifier("Reuters")); // This does NOT work
            stream.MatchingTweetReceived += (sender, args) => Console.WriteLine(args.Tweet.FullText);
            stream.StartStreamMatchingAnyCondition();

            Thread.Sleep(Int32.MaxValue);
        }
    }
}

```

In the latest 5.0.0 version, the below code throws the TwitterException with Message: "No filter parameters found. Expect at least one parameter: follow track locations".  **Is it possible to only receive tweets from a single user like this?**

```
using System;
using System.Threading.Tasks;
using Tweetinvi;
using Tweetinvi.Models;

namespace TweetinviTest
{
    class Program
    {
        public static async Task Main(string[] args)
        {
            var credentials = new TwitterCredentials("removed", "removed", "removed", "removed");
            var client = new TwitterClient(credentials);

            var stream = client.Streams.CreateFilteredStream();
            stream.AddFollow(new UserIdentifier("Reuters"));
            stream.MatchingTweetReceived += (sender, args) => Console.WriteLine("Reuters tweet: " + args.Tweet.FullText);
            await stream.StartMatchingAnyConditionAsync(); // throws TwitterException with Message "No filter parameters found. Expect at least one parameter: follow track locations"
        }
    }
}

```
**Thank you!**

**Comment by NorthwestAlpineSystems** [comment]
Hi @linvi , are you aware of this issue?  Thank you

**Comment by AniaBerthelot** [comment]
Hi @NorthwestAlpineSystems have you tried to provide a userID directly?

**Comment by NorthwestAlpineSystems** [comment]
Hi @AniaBerthelot , thanks for your reply.  I don't understand what you are suggesting.  Can you point me to the line of code you are referring to?

**Comment by linvi** [comment]
@NorthwestAlpineSystems thanks for sharing, I will be looking into this.

**Comment by AniaBerthelot** [comment]
Unfortunately I can't help as I'm facing the same issue @NorthwestAlpineSystems and I'm waiting impatiently for @linvi's fix

**Comment by AniaBerthelot** [comment]
Here's the error (V5alpha6) I'm getting in VS2019 output window :

`fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
--- Date : 8/12/2020 10:51:27 PM
URL : https://stream.twitter.com/1.1/statuses/filter.json?track=covid
Code : -1
Error documentation description : 
Error message : <html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 401 Unauthorized</title>`

**Comment by gabenotgave** [comment]
Really hope this issue can be solved soon, @linvi. Project won't work without it lol.

**Comment by AniaBerthelot** [comment]
I do agree with you @gabenotgave streaming is an essential feature, and all my dev work is dependent on it.

**Comment by gabenotgave** [comment]
@AniaBerthelot Yup. Luckily for me, however, I was able to get AddFollow to work simply by putting the account ID in the parameters... It's an extra step, but for my project, it ended up working. Definitely not as good as putting the screen name, though, and I definitely see how this would be inconvenient in other projects.

**Comment by AniaBerthelot** [comment]
@gabenotgave are you using 
- TweetInvi V5 alpha6? 
- Are you using Twitter developer V2?
I keep having this message "Error 401 Unauthorized", my creds are ok, I even get streamSample response with the same credentials.

**Comment by gabenotgave** [comment]
@Ania No. I am using the last stable release, which would be 4.0.3. What are you doing to get that message? AddFollow?

**Comment by linvi** [comment]
Hi there,

Sorry for the long wait. I changed job and required some time to get approval to work on Tweetinvi.

I have been able to reproduce the issue. Will issue a fix soon.

Thanks,
Linvi

**Comment by linvi** [comment]
Ok, so the issue comes from the fact that you are trying to add followers by name.
This is not possible as the filtered stream (differently from other endpoints) do not take username as an input. Only user ids are allowed.

Here is a working version.

``` c#
var client = new TwitterClient(creds);
var reuters = await client.Users.GetUserAsync("Reuters");
var stream = client.Streams.CreateFilteredStream();
stream.AddFollow(reuters);

stream.MatchingTweetReceived += (sender, args) =>
{
    System.Console.WriteLine("Reuters tweet: " + args.Tweet.FullText);
};
await stream.StartMatchingAnyConditionAsync();
```

I will get back here to let you know with the changes I want to make. This will be either:

* Fail early when a `UserIdentifier` is added with only the username
* Let the request fail at execution so that any changes to Twitter api in the future are not blocked by Tweetinvi implementation.

**Comment by AniaBerthelot** [comment]
@linvi is there an integrated way to create a tweet object from V2 lab stream endpoint JSON response?

**Comment by linvi** [comment]
@AniaBerthelot 

At the moment there is not but you can see how easy you can query labs with Tweetinvi here:

https://linvi.github.io/tweetinvi/dist/more/twitter-labs.html

I hope this helps

**Comment by linvi** [comment]
Picked: **[EASY TO RELEASE]** Fail early when a UserIdentifier is added with only the username.

Will be available in `alpha-9`.
