### ISSUE TITLE
FilteredStream returns most of the tweets in NonMatchingTweetReceived instead of MatchingTweetReceived

### ISSUE THREAD

**Issue by jxlarrea** [linvi/tweetinvi#1055]
I originally posted this in #869 but it's been a while so I figured I'd open a new issue.

In version 5.0 alpha 6, `FilteredStreams` return most of the tweets in `NonMatchingTweetReceived` instead of `MatchingTweetReceived`. Not sure if this is related to the `LanguageFilter` #869 but the like I mentioned, the tweets are indeed received but as `NonMatchingTweetReceived`.

Reverting to Tweetinvi version 2.1 fixes the problem.

**Comment by linvi** [comment]
Hello,

Thank you for reporting the issue. Would you mind sharing the code containing the filters so that I can reproduce the issue.

Cheers,
Linvi

**Comment by linvi** [comment]
The bug fixes will happen in version 5.0.0-alpha-9 or 5.0.0-beta-1.
