### ISSUE TITLE
﻿System.PlatformNotSupportedException: Property UseCookies is not supported.

### ISSUE THREAD

**Issue by AniaBerthelot** [linvi/tweetinvi#1056]
![image](https://user-images.githubusercontent.com/59117177/86613810-ff30fc00-bfa9-11ea-96fd-fad7ab78a7cf.png)
I'm using Blazor WebAssembly

**Comment by linvi** [comment]
Hi @AniaBerthelot,

Could you please share information about your platform, .NET version...

Thanks,
Linvi

**Comment by joscha999** [comment]
Hey @linvi, got any Update on this issue or need anything specific?
I just played around some with Blazor and ran into the same problem - it can be reproduced by creating a new Blazor WebAssembly project, adding the TweetinviAPI package and then trying to authenticate from OnInitializedAsync.

Tried on Win10 x64, VS2019 Community 16.6.0 and using .net Standard 2.1 as target framework, 3.0 for the razor lang version and version 3.2.0 of the Microsoft.AspNetCore.Components.WebAssembly.* packages - basically the current template when using VS and creating a new Blazor ASP hosted WebAssembly project.

Let me know if you need any further info!

**Comment by linvi** [comment]
Thanks for sharing @joscha999 I will try it out.

**Comment by linvi** [comment]
The issue seems to come from a problem of Blazor not fully supporting custom `HttpClientHandler`.
I have opened a bug but this issue cannot be stopping the release of version 5.0.

**Comment by campersau** [comment]
FYI: twitter does not allow CORS requests so using the twitter API inside the browser and thus WebAssembly will not work.
See https://stackoverflow.com/a/35898961/9663233

**Comment by IEvangelist** [comment]
Hi @linvi - I too am seeing this issue now. I've love for this to be addressed. The `HttClientHandler` for Blazor WebAssembly comes from mono:

- [HttpClientHandler.UseCookies](https://github.com/mono/mono/blob/main/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.xi.cs#L41-L44) - `throw new PlatformNotSupportedException();`
- [HttpClientHandler.UseDefaultCredentials](https://github.com/mono/mono/blob/main/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.xi.cs#L101-L104) - `throw new PlatformNotSupportedException();`

Both of these `throw`, if you're to adjust the assignment of the following code -- it should solve the problem.

```csharp
public TwitterClientHandler(IOAuthWebRequestGenerator oAuthWebRequestGenerator)
{
    try
    {
        UseCookies = false;
        UseDefaultCredentials = false;
    }
    catch (PlatformNotSupportedException)
    {
        // If the platform is not supported for these two things we're trying to toggle off, they're already off.
    }

    WebRequestGenerator = oAuthWebRequestGenerator;
}
```

See [`TwitterClientHandler.ctor`](https://github.com/linvi/tweetinvi/blob/master/src/Tweetinvi.WebLogic/TwitterClientHandler.cs#L22-L23)
