### ISSUE TITLE
Getting Started docs don't compile

### ISSUE THREAD

**Issue by harryovers** [linvi/tweetinvi#1057]
I have followed exactly what it says on the ["Getting Started"](https://linvi.github.io/tweetinvi/dist/intro/getting-started.html) docs.

I get the following error:
`Program.cs(14,34): error CS0246: The type or namespace name 'TwitterClient' could not be found (are you missing a using directive or an assembly reference?) [/home/username/src/tweetinvi-hello-world/tweetinvi-hello-world.csproj]

The build failed. Fix the build errors and run again.`

**Comment by dumbgamedev** [comment]
What version of the package do you have installed? Did you get it from Nuget?

Did you make sure to add the using reference at the top of your script?

`using System;
using System.Threading.Tasks;
using Tweetinvi;`

**Comment by linvi** [comment]
Please open the `Program.cs` link in the doc you will see the following:

``` c#
using System;
using System.Threading.Tasks;

// You need to add the tweetinvi namespace
using Tweetinvi;

namespace tweetinvi_hello_world
{
    class Program
    {
        static async Task Main(string[] args)
        {
            // we create a client with your user's credentials
            var userClient = new TwitterClient("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

            // request the user's information from Twitter API
            var user = await userClient.Users.GetAuthenticatedUserAsync();
            Console.WriteLine("Hello " + user);

            // publish a tweet
            var tweet = await userClient.Tweets.PublishTweetAsync("Hello tweetinvi world!");
            Console.WriteLine("You published the tweet : " + tweet);
        }
    }
}
```
