### ISSUE TITLE
Strange issue with AsyncContext + TweetInvi's Sync.

### ISSUE THREAD

**Issue by JaneSmith** [linvi/tweetinvi#106]
Hello. I'm having a strange issue with my project, and I'm not sure what is to blame - AsyncEx, TweetInvi, or me. :(

Basically, I have a working WPF app that uses TweetInvi and plenty of async - it all works fine. I recently wanted to make a console version, and found AsyncEx with its AsyncContext class, which resolves issues with using async methods with console applications. It sounded perfect. Unfortunately, my application didn't work. I've managed to shrink the issue down to these three scenarios:

**Scenario 1:**
This is what I'm *trying* to do. It doesn't work. I use TweetInvi's Sync.ExecuteTaskAsync method from within AsyncEx's AsyncContext.Run. TweetInvi's Sync.ExecuteTaskAsync never returns - I can set a breakpoint on the following line and it never triggers. This completely stops my application from progressing.
```
private static int Main(string[] args) {
	return AsyncContext.Run(Program.MainAsyc);
}

private static async Task<int> MainAsyc() {
	var twitterCredentials = new TwitterCredentials(blankedOut1, blankedOut2, blankedOut3, blankedOut4);
	Auth.SetCredentials(twitterCredentials);

	var latestTweets = await Sync.ExecuteTaskAsync(() => Timeline.GetUserTimeline(blankedOut5, new UserTimelineParameters {
		MaximumNumberOfTweetsToRetrieve = 20,
		ExcludeReplies = true
	}));

	return 0;
}
```

**Scenario 2:**
In this scenario, I use TweetInvi's Sync.ExecuteTaskAsync on its own in the normal Main method, without using AsyncEx at all. It works fine and returns.
```
private static int Main(string[] args) {
	var twitterCredentials = new TwitterCredentials(blankedOut1, blankedOut2, blankedOut3, blankedOut4);
	Auth.SetCredentials(twitterCredentials);

	Sync.ExecuteTaskAsync(() => Timeline.GetUserTimeline(blankedOut5, new UserTimelineParameters {
		MaximumNumberOfTweetsToRetrieve = 20,
		ExcludeReplies = true
	})).Wait();
	
	return 0;
}
```

**Scenario 3:**
In this scenario, I use AsyncEx's AsyncContext.Run method, without using TweetInvi at all. It works fine and returns.
```
private static int Main(string[] args) {
	AsyncContext.Run(Test);
	return 0;
}

private static async Task Test() {
	await Task.Run(() => Thread.Sleep(5000));
}
```

Why doesn't scenario 1 work? I'd really appreciate any help with this.

**Comment by linvi** [comment]
Hello there,

To help you I would definitely need to know what your `AsyncContext` is.

Are you referring to https://github.com/StephenCleary/AsyncEx?
I do not know this library but I can take a quick look if you want me to.

Linvi

**Comment by JaneSmith** [comment]
Yes, that's correct. I'm referring to the AsyncEx library. Sorry for not making that clear.

I also posted this as an issue on their GitHub page, because I wasn't sure where the problem was: https://github.com/StephenCleary/AsyncEx/issues/43

According to the replies there, and my understanding of it, the issue seems to lie with TweetInvi's TaskFactory implementation, which uses Task.Factory.StartNew without specifying a scheduler.
