### ISSUE TITLE
How to get Tweets from a specific account as soon as they are posted

### ISSUE THREAD

**Issue by HenriqueMarino** [linvi/tweetinvi#1061]
I was reading the documentation, but I didn't find anything related to Tweets events for example. Because I wanted to get an account's tweets and their content

**Comment by linvi** [comment]
Hi there,

I would suggest you checkout the version 5.0 of tweetinvi and the documentation about events:

https://linvi.github.io/tweetinvi/dist/account-activity/account-activity-events.html

Let me know if this answers your question.

Cheers,
Linvi

**Comment by HenriqueMarino** [comment]
Yes, it helped in some parts. This documentation you showed me is much better than the one in READM.md

However, my program crashes when I start. I feel something is missing for the code to work properly, and I don't know what it is. Would you help me?

```csharp
Auth.SetUserCredentials("API_key", "API_secret", "Acces_token", "Acces_token_secret");

string user = "xxxxxxxxxxxxx";

var stream = Stream.CreateAccountActivityStream(user);            
            
Console.WriteLine("Listening to Twitter...");

stream.TweetCreated += (sender, arguments) =>
{
   Console.WriteLine(arguments.Tweet.FullText);
                
};
```

And finally, congratulations on the great job done with tweetinvi

**Comment by linvi** [comment]
Hi there, 

I just wanted to point out that you are sharing code for 4.0 and not 5.0.
Please check all the [documentation of Account Activity](https://linvi.github.io/tweetinvi/dist/account-activity/account-activity.html) because you will first need to request a special account from Twitter.

Cheers,
Linvi

**Comment by HenriqueMarino** [comment]
I updated the version of your library to v5, and followed the examples in the documentation, however the following error is occurring:

`https://api.twitter.com/1.1/account_activity/all/dev/webhooks.json?url=https%3A%2F%2F44bf704bd386.ngrok.io%20 request failed.`

```csharp
static async Task Main(string[] args)
{
    Plugins.Add<AspNetPlugin>();
   
    //user that i will watch
    long USER_ID = 00000000;

    var appClient = new TwitterClient("API_key", "API_secret", "Acces_token", "Acces_token_secret");

    var user = await userClient.Users.GetAuthenticatedUserAsync();
    Console.WriteLine(user); //program crashes after execute this line

    await userClient.AccountActivity.CreateAccountActivityWebhookAsync(":env_name", "https://something.ngrok.io ");

    Console.WriteLine("Listening to Twitter...");

    var accountActivityHandler = userClient.AccountActivity.CreateRequestHandler();

    await RunServer(accountActivityHandler);

    var accountActivityStream = accountActivityHandler.GetAccountActivityStream(USER_ID, ":env_name");

    accountActivityStream.TweetCreated += (sender, arguments) =>
    {
        Console.WriteLine(arguments.Tweet.FullText);
    };
}

static async Task RunServer(Tweetinvi.Models.IAccountActivityRequestHandler accountActivityHandler)
{
    var httpServer = new SimpleHttpServer(8042);

    httpServer.OnRequest += async (sender, context) =>
    {
        var webhookRequest = WebhookRequestFactory.Create(context);

        // check if the request comes from twitter
        if (await accountActivityHandler.IsRequestManagedByTweetinviAsync(webhookRequest))
        {
            // let tweetinvi manage the twitter requests and respond to it
            await accountActivityHandler.TryRouteRequestAsync(webhookRequest);
        }
        else
        {
            // a request not coming from twitter (probably for a user of your website)
            var streamWriter = new StreamWriter(context.Response.OutputStream);
            await streamWriter.WriteAsync("Hello friend, this page does not exists!");
            await streamWriter.FlushAsync();
            context.Response.StatusCode = 404;
            context.Response.Close();
        }
    };

    httpServer.Start();

    await httpServer.WaitUntilDisposed();
}
```

thanks for attention

**Comment by HenriqueMarino** [comment]
I updated the version of your library to v5, and followed the examples in the documentation, however the following error is occurring: `Access is denied.`

```csharp
static async Task Main(string[] args)
{    
    Plugins.Add<AspNetPlugin>();

    var userClient = new TwitterClient("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

    //user that i will watch
    long USER_ID = 000000000;

    var user = await userClient.Users.GetAuthenticatedUserAsync();
    Console.WriteLine(user);


    Console.WriteLine("Listening to Twitter...");

    var accountActivityHandler = userClient.AccountActivity.CreateRequestHandler(); //programa crashes after execute this line

    await RunServer(accountActivityHandler);

    await userClient.AccountActivity.CreateAccountActivityWebhookAsync("dev", "https://something.ngrok.io ");

    var accountActivityStream = accountActivityHandler.GetAccountActivityStream(USER_ID, "dev");

    accountActivityStream.TweetCreated += (sender, arguments) =>
    {
        Console.WriteLine(arguments.Tweet.FullText);
    };
}

static async Task RunServer(Tweetinvi.Models.IAccountActivityRequestHandler accountActivityHandler)
{
    var httpServer = new SimpleHttpServer(8042);
    //i made a class based on SimpleHttpServer.cs at this link https://linvi.github.io/tweetinvi/dist/account-activity/account-activity-with-http-server.html
    httpServer.OnRequest += async (sender, context) =>
    {
        var webhookRequest = WebhookRequestFactory.Create(context);

        // check if the request comes from twitter
        if (await accountActivityHandler.IsRequestManagedByTweetinviAsync(webhookRequest))
        {
            // let tweetinvi manage the twitter requests and respond to it
            await accountActivityHandler.TryRouteRequestAsync(webhookRequest);
        }
        else
        {
            // a request not coming from twitter (probably for a user of your website)
            var streamWriter = new StreamWriter(context.Response.OutputStream);
            await streamWriter.WriteAsync("Hello friend, this page does not exists!");
            await streamWriter.FlushAsync();
            context.Response.StatusCode = 404;
            context.Response.Close();
        }
    };

    httpServer.Start();

    await httpServer.WaitUntilDisposed();
}
```

thanks for attention

**Comment by linvi** [comment]
Did you request a premium account on Twitter?

https://developer.twitter.com/en/apply

**Comment by HenriqueMarino** [comment]
if you talk about it, yes!

![image](https://user-images.githubusercontent.com/38007771/91076334-b692d800-e615-11ea-8f7c-090c08fd7891.png)

**Comment by linvi** [comment]
Could you please share the exception that you are receving?

**Comment by HenriqueMarino** [comment]
Yes, here it is:

` System.Net.HttpListenerException
  HResult=0x80004005
  Message=Access is denied.
  Source=System.Net.HttpListener
  StackTrace:
   at System.Net.HttpListener.AddPrefixCore(String registeredPrefix) in /_/src/System.Net.HttpListener/src/System/Net/Windows/HttpListener.Windows.cs:line 553
   at System.Net.HttpListener.AddAllPrefixes() in /_/src/System.Net.HttpListener/src/System/Net/Windows/HttpListener.Windows.cs:line 532
   at System.Net.HttpListener.Start() in /_/src/System.Net.HttpListener/src/System/Net/Windows/HttpListener.Windows.cs:line 281
   at TwitterWatcher.SimpleHttpServer.Start() in C:\Users\henri\source\repos\TwitterWatcher\TwitterWatcher\SimpleHttpServer.cs:line 23
   at TwitterWatcher.Program.<Main>d__0.MoveNext() in C:\Users\henri\source\repos\TwitterWatcher\TwitterWatcher\Program.cs:line 54
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 107
   at TwitterWatcher.Program.<Main>(String[] args)

  This exception was originally thrown at this call stack:
    System.Net.HttpListener.AddPrefixCore(string) in HttpListener.Windows.cs
    System.Net.HttpListener.AddAllPrefixes() in HttpListener.Windows.cs
    System.Net.HttpListener.Start() in HttpListener.Windows.cs
    TwitterWatcher.SimpleHttpServer.Start() in SimpleHttpServer.cs
    TwitterWatcher.Program.Main(string[]) in Program.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in ExceptionDispatchInfo.cs
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task) in TaskAwaiter.cs
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) in TaskAwaiter.cs
    System.Runtime.CompilerServices.TaskAwaiter.GetResult() in TaskAwaiter.cs
    TwitterWatcher.Program.<Main>(string[])`

**Comment by HenriqueMarino** [comment]
Any update?

**Comment by linvi** [comment]
Sorry, not yet. I will try to reproduce your issue tonight.
I recently tried Account Activity successfully, so it probably comes from something in the solution you have.

**Comment by linvi** [comment]
Here is a full example. Let me know if this works for you. Test and approved

``` c#
// Program.cs
using System;
using System.IO;
using System.Threading.Tasks;
using Tweetinvi;
using Tweetinvi.Models;
using Tweetinvi.AspNet;

namespace tweetinvi_hello_world
{
    class Program
    {
        static async Task Main(string[] args)
        {
            Plugins.Add<AspNetPlugin>();

            var userCreds = new TwitterCredentials("CONSUMER", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

            var appCreds = new TwitterCredentials("CONSUMER", "CONSUMER_SECRET",)
            {
                BearerToken = "BEARER_TOKEN"
            };

            var appClient = new TwitterClient(appCreds);
            var userClient = new TwitterClient(userCreds);

            var environments = await appClient.AccountActivity.GetAccountActivityWebhookEnvironmentsAsync();
            if (environments[0].Webhooks.Length > 0)
            {
                // cleanup is not mandatory but this will works 100% of cases if you change your ngrok url
                await appClient.AccountActivity.DeleteAccountActivityWebhookAsync("sandbox", environments[0].Webhooks[0]);
            }

            var accountActivityHandler = appClient.AccountActivity.CreateRequestHandler();

            var httpServer = new SimpleHttpServer(8080);
            httpServer.OnRequest += async (sender, context) =>
            {
                var webhookRequest = WebhookRequestFactory.Create(context);
                if (await accountActivityHandler.IsRequestManagedByTweetinviAsync(webhookRequest))
                {
                    await accountActivityHandler.TryRouteRequestAsync(webhookRequest);
                }
                else
                {
                    if (context.Request.Url.AbsolutePath == "/close")
                    {
                        httpServer.Dispose();
                    }

                    var streamWriter = new StreamWriter(context.Response.OutputStream);
                    await streamWriter.WriteAsync("Hello friend, this page does not exists!");
                    await streamWriter.FlushAsync();
                    context.Response.StatusCode = 404;
                    context.Response.Close();
                }
            };
            httpServer.Start();

            await userClient.AccountActivity.CreateAccountActivityWebhookAsync("sandbox", "https://bab133e35e69.ngrok.io");

            await userClient.AccountActivity.SubscribeToAccountActivityAsync("sandbox");
            var authenticatedUser = await userClient.Users.GetAuthenticatedUserAsync();
            var accountActivityStream = accountActivityHandler.GetAccountActivityStream(authenticatedUser.Id, "sandbox");
            accountActivityStream.EventReceived += (sender, receivedEvent) =>
            {
                Console.WriteLine(receivedEvent.Json);
            };

            accountActivityStream.TweetCreated += (sender, tweetCreatedEvent) => { Console.WriteLine("A tweet was created by USER_ID or a tweet mentioning USER_ID"); };

            await httpServer.WaitUntilDisposed();

            // Now try performing some events and the handlers will trigger the events.
        }
    }
}
```

``` c#
// SimpleHttpServer.cs
using System;
using System.Net;
using System.Threading.Tasks;

namespace tweetinvi_hello_world
{
    public class SimpleHttpServer : IDisposable
    {
        private readonly HttpListener _server;

        public SimpleHttpServer(int port)
        {
            _server = new HttpListener();
            _server.Prefixes.Add($"http://*:{port}/");
        }

        public EventHandler<HttpListenerContext> OnRequest;

        public void Start()
        {
            _server.Start();
            RunServerAsync();
        }

        private async Task RunServerAsync()
        {
            while (_server.IsListening)
            {
                var context = await _server.GetContextAsync();
                OnRequest?.Invoke(this, context);
            }
        }

        public async Task WaitUntilDisposed()
        {
            while (!_disposed)
            {
                await Task.Delay(200);
            }
        }

        private bool _disposed;
        public void Dispose()
        {
            _disposed = true;
            ((IDisposable) _server)?.Dispose();
        }
    }
} 
```

**Comment by HenriqueMarino** [comment]
I still have the same problem

`
An unhandled exception of type 'System.Net.HttpListenerException' occurred in System.Private.CoreLib.dll
Access is denied.

The program '[18004] TwitterWatcher.exe' has exited with code -1 (0xffffffff).
`

The only thing I changed in your code was the credentials and ngrok URL (my Dev environment label is also called a sandbox)

![image](https://user-images.githubusercontent.com/38007771/94598128-e2345e00-0264-11eb-89a3-7aed75f881eb.png)

**Comment by HenriqueMarino** [comment]
I upgraded to the latest version (beta-1) and restarted visual studio in admin mode, in addition to putting the line ```cs await httpServer.WaitUntilDisposed(); ``` above events, and it worked. However, from what I read in the documentation, the user I intend to assist, needs to be registered before the events will work. How could I do that? (I couldn't find it in the documentation)

**Comment by linvi** [comment]
Hi there.

> in addition to putting the line await httpServer.WaitUntilDisposed(); above events, and it worked

I don't see how this is possible. Would you mind sharing your code?

> from what I read in the documentation, the user I intend to watch (another user, not me), needs to be registered before the events to work. How could I do that? (I couldn't find it in the documentation)

Thanks for sharing this, looks like I need to improve the documentation.
So what you need to do is for every user you wish to listen to, you will need to request get credentials for your app ([Auth documentation](https://linvi.github.io/tweetinvi/dist/authentication/authentication.html)).

When you have the user credentials, create a client with these credentials.
Now you just need to invoke:

``` c#
var otherUserCredentials = ...;
var otherUserClient = new TwitterClient(otherUserCredentials);

// registration
await otherUserClient.AccountActivity.SubscribeToAccountActivityAsync("sandbox");
```

I will add this task to documentation for 5.0 to improve this detail.

I hope this helps out.

**Comment by HenriqueMarino** [comment]
My full code: 

```cs

static async Task Main(string[] args)
        {
            Plugins.Add<AspNetPlugin>();

            var userCreds = new TwitterCredentials("CONSUMER", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

            var appCreds = new TwitterCredentials("CONSUMER", "CONSUMER_SECRET")
            {
                BearerToken = "BEARER_TOKEN"
            };

            var appClient = new TwitterClient(appCreds);
            var userClient = new TwitterClient(userCreds);

            var environments = await appClient.AccountActivity.GetAccountActivityWebhookEnvironmentsAsync();
            if (environments[0].Webhooks.Length > 0)
            {
                // cleanup is not mandatory but this will works 100% of cases if you change your ngrok url
                await appClient.AccountActivity.DeleteAccountActivityWebhookAsync("sandbox", environments[0].Webhooks[0].Id);
            }

            var accountActivityHandler = appClient.AccountActivity.CreateRequestHandler();

            var httpServer = new SimpleHttpServer(8042);
            httpServer.OnRequest += async (sender, context) =>
            {
                var webhookRequest = WebhookRequestFactory.Create(context);
                if (await accountActivityHandler.IsRequestManagedByTweetinviAsync(webhookRequest))
                {
                    await accountActivityHandler.TryRouteRequestAsync(webhookRequest);
                }
                else
                {
                    if (context.Request.Url.AbsolutePath == "/close")
                    {
                        httpServer.Dispose();
                    }

                    var streamWriter = new StreamWriter(context.Response.OutputStream);
                    await streamWriter.WriteAsync("Hello friend, this page does not exists!");
                    await streamWriter.FlushAsync();
                    context.Response.StatusCode = 404;
                    context.Response.Close();
                }
            };
            httpServer.Start();

            await httpServer.WaitUntilDisposed();

            await userClient.AccountActivity.CreateAccountActivityWebhookAsync("sandbox", "https://075b77e22be5.ngrok.io");

            await userClient.AccountActivity.SubscribeToAccountActivityAsync("sandbox");
            var authenticatedUser = await userClient.Users.GetAuthenticatedUserAsync();
            long USER_ID = 000000000000000;
            var accountActivityStream = accountActivityHandler.GetAccountActivityStream(USER_ID, "sandbox");
            accountActivityStream.EventReceived += (sender, receivedEvent) =>
            {
                Console.WriteLine(receivedEvent.Json);
            };

            accountActivityStream.TweetCreated += (sender, tweetCreatedEvent) => { Console.WriteLine(tweetCreatedEvent); };
            // Now try performing some events and the handlers will trigger the events.
        }
```
If I run the code normally, the error I mentioned earlier occurs, and if I run the code without changing anything, but as an admin, this error occurs:
```
Tweetinvi.Exceptions.TwitterException: 'https://api.twitter.com/1.1/account_activity/all/sandbox/webhooks.json?url=https%3A%2F%2F0a7c509ed22e.ngrok.io request failed.'
```
I removed the part of the code that contained the events, just to test the server, and it was working normally
![image](https://user-images.githubusercontent.com/38007771/94712236-95fa2400-031f-11eb-95f8-a15005b13135.png)

and sorry for not having detailed it better, but when I said another user, I meant to login with my credentials and watch another user (a news profile for example), specifying the ID of that profile. And for that it needs to be registered, but I couldn't find it in the documentation

**Comment by linvi** [comment]
Hello there,

I am sorry but I do not understand your question. I think I answered your question regarding how to "register"/subscribe a user to a stream. 

``` c#
await otherUserClient.AccountActivity.SubscribeToAccountActivityAsync("sandbox");
```

Please share more details.

**Comment by HenriqueMarino** [comment]
My first question about assisting users is that i want to assist any user, without needing his credentials. For example: I have the API key for my twitter, but I need to monitor your account activity.

My other problem is that I cannot monitor myself, because the program fails to request, and throws the following error:

```
Tweetinvi.Exceptions.TwitterException: 'https://api.twitter.com/1.1/account_activity/all/sandbox/webhooks.json?url=https%3A%2F%2F0a7c509ed22e.ngrok.io request failed.'
```

**Comment by linvi** [comment]
> My first question about assisting users is that i want to assist any user, without needing his credentials. For example: I have the API key for my twitter, but I need to monitor your account activity.

This is not possible. You need approval from users in order to track them. You get their approval by getting them to accept your app which in returns generates a set of credentials.

Without such a mechanism developers would be able to track everybody without their consent.

> My other problem is that I cannot monitor myself, because the program fails to request, and throws the following error:

Please check the description of the exception. You can use the `e.ToString()` to retrieve all the relevant information.
I guess that the problem is that you already have a registered url. You will need to remove your previous registered webhooks as per the doc.

``` c#
// quick solution to clean your sandbox environment
var webhooks = await appClient.AccountActivity.GetAccountActivityEnvironmentWebhooksAsync("sandbox");
if (webhooks.Length > 0)
{
    await appClient.AccountActivity.DeleteAccountActivityWebhookAsync("sandbox", webhooks[0]);
}
```

**Comment by HenriqueMarino** [comment]
You're right. In addition, I had to contact twitter support to release write access, as I was having the following error:

```
URL : https://api.twitter.com/1.1/account_activity/all/sandbox/webhooks.json?url=https%3A%2F%2F152a8ac9770a.ngrok.io
Code : 403
Error documentation description : Forbidden - The request is understood, but it has been refused or access is not allowed. An accompanying error message will explain why. This code is used when requests are being denied due to update limits.
Error message : https://api.twitter.com/1.1/account_activity/all/sandbox/webhooks.json?url=https%3A%2F%2F152a8ac9770a.ngrok.io request failed.
Application cannot perform write actions. Contact Twitter Platform Operations through https://help.twitter.com/forms/platform. (261)
```

I have another question:

I think the best way to get public tweets is with the filtered stream. And I did it! The only thing I wanted to improve, is the latency when receiving the data, which is currently around 3~4 seconds. Is there anything I can do to reduce this latency?

**Comment by linvi** [comment]
> Is it possible for me to get tweets from my feed in real time with Account Activity?

Yes just subscribe your own user. The credentials provided on apps.twitter.com provide access tokens which you can use to authenticate yourself.

**Comment by HenriqueMarino** [comment]
Sorry, but could you explain better what it would be like to subscribe my own user?

Because according to the [documentation](https://linvi.github.io/tweetinvi/dist/account-activity/account-activity-subscriptions.html#subscribe-a-user), I'm already doing this. But I only receive events that start from my actions, as follows, my tweets, responses, likes...

**Comment by linvi** [comment]
What type of interactions are you looking to subscribe to.

All the available events can be found here : https://linvi.github.io/tweetinvi/dist/account-activity/account-activity-events.html

**Comment by HenriqueMarino** [comment]
>What type of interactions are you looking to subscribe to.

My feed in real time. Because I want to get tweets from a specific account in real time, but in the documentation I couldn't find anything related.

**Comment by linvi** [comment]
I am sorry but I am getting very confused. What about these events?

![image](https://user-images.githubusercontent.com/6107439/95003763-6b87bf80-05da-11eb-97cf-50ec1cebf849.png)

**Comment by HenriqueMarino** [comment]
Remember I said I wanted to get my Twitter timeline in real time? This is what I want...

And with that, I can filter the results, to finally get the tweets from a specific account!

In short: I follow an X user, and his tweets will appear on my timeline as soon as they are posted, and through some filters I can get them.

What I mainly need is to get public tweets in real time, and then I do the filtering part.

I hope I made it clearer.

**Comment by linvi** [comment]
Account Activity allow you to track a specific user who gave his approval to get tracked. You can track almost every interaction this user has on Twitter.

Filtered Streams allow you to track tweets posted on twitter. You can track tweets by content, location and user.
There are multiple filtered streams available.
* [Public filtered Stream 1.1](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/api-reference/post-statuses-filter)
* [Enterprise filtered stream 1.1](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/api-reference/powertrack-stream)
* [Public filtered stream 2](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/api-reference/get-tweets-search-stream)

You can read tweetinvi documentation for filtered streams v1.1 [here](https://linvi.github.io/tweetinvi/dist/streams/filtered-stream.html) and [filters available for filtered stream](https://linvi.github.io/tweetinvi/dist/streams/filtered-stream-filters).

I did not have time yet to create documentation for any of the Twitter API v2 endpoints. So please check the Twitter doc for now.

I hope this answers your question.

**Comment by HenriqueMarino** [comment]
Yes, you helped a lot!

I tried to use Account Activity, because it has a faster update than the stream. So I have one last question: is it possible to reduce the update delay that is currently in the stream (around 3~4 seconds)?

**Comment by linvi** [comment]
No this is not possible this is a limitation from Twitter and I assume that technically it would be extremely complex for them to assure such low SLAs for streams offered to thousands of developer apps.

Twitter offers Enterprise version of their streams, they could offer better SLAs but you will probably have to pay a premium. You can discuss the price and your requirements with their enterprise teams.

I suggest you look into Gnip : https://support.gnip.com/apis/#.

**Comment by HenriqueMarino** [comment]
Understood! I will close this topic, as all doubts have been solved. Thank you very much for all your attention and patience!
