### ISSUE TITLE
Are Twitter's lists endpoints missing?

### ISSUE THREAD

**Issue by AniaBerthelot** [linvi/tweetinvi#1063]
How to get twitter's lists timeline, I browsed Tweetinvi's documentation and nowhere it's mentioned. Thanks!

**Comment by linvi** [comment]
Hello there.

Twitter Lists are supported by Tweetinvi 4.0 and 5.0.
You can find the latest documentation here:

https://linvi.github.io/tweetinvi/dist/twitter-api/lists.html

Cheers,
Linvi

**Comment by AniaBerthelot** [comment]
Hello @linvi and thanks for the reply,
Actually It's good what we can do with lists here (CRUD) but I just want to get Lists TIMELINE and it's not documented. Is it integrated or should I do it manually with a direct call?

**Comment by linvi** [comment]
Hello,

I do not understand which functionality you are talking about.
Tweetinvi exposes all the Timelines and Lists features of the Twitter API v1.1.

Thanks to your message, I realised that the Timeline documentation is missing for Tweetinvi 5.0 and I will work on it tonight.
In the meantime you just need to use intellisense to discover the methods available for the Timeline by typing:

``` c#
var client = new TwitterClient(creds);
client.Timelines.
```

You can also find all the Timelines interface here: https://github.com/linvi/tweetinvi/blob/master/src/Tweetinvi.Core/Public/Client/Clients/ITimelinesClient.cs

**Comment by linvi** [comment]
Hi there,

I have added the documentation to access the Twitter timelines.
You can find the documentation here:

https://linvi.github.io/tweetinvi/dist/twitter-api/timelines.html

Cheers,
Linvi

**Comment by AniaBerthelot** [comment]
Hi @linvi,
Thank you for your investment in time and energy.
I was talking about this endpoint https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/create-manage-lists/api-reference/get-lists-statuses

**Comment by AniaBerthelot** [comment]
> Hi @linvi,
> Thank you for your investment in time and energy.
> I was talking about this endpoint https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/create-manage-lists/api-reference/get-lists-statuses

It is implemented ( GetTweetsFromListAsync( ) ), but not visible in documentation. I was thinking that features presented in documentation are all the available ones in the package. Now I got it, I'm exploring methods from IDE.

**Comment by linvi** [comment]
Thanks for sharing, I will add this into the doc :)

**Comment by AniaBerthelot** [comment]
Hi @linvi,
I'd like to use since_id param with my GetTweetsFromListIterator(long listId) so I'm forced to use the version that accepts parms :       
`ITwitterIterator<ITweet, long?> GetTweetsFromListIterator(IGetTweetsFromListParameters parameters);`
But I'm really strugeling to use IGetTweetsFromListParameters as I have to implement all parents interfaces properties plus the constructure...

Is there a better way to inject since_id? Thks champion

**Comment by linvi** [comment]
I thought it was obvious for me that the implemented parameters were already available without the `I` prefix.
I will think about this to improve the doc. Here you go:

``` c#
var tweets = await client.Lists.GetTweetsFromListAsync(new GetTweetsFromListParameters(153)
{
    SinceId = 42
});
```

**Comment by AniaBerthelot** [comment]
Hi, thanks a lot for the quick answer. 
Actually now it is, it's obvious. I was confused by nested Interfaces and some fields was read only that was the case for sinceID. Now everything's ok thanks to you.
