### ISSUE TITLE
Plans to upgrade to new v2 twitter api ?

### ISSUE THREAD

**Issue by pazdev** [linvi/tweetinvi#1064]
https://developer.twitter.com/en/docs/twitter-api/early-access

**Comment by linvi** [comment]
Hi there,

Yes, I have plan to migrate to v2. Though as you probably noticed, I have very limited amount of time.

At the moment there is minimum level of support. You can find the documentation here:

https://linvi.github.io/tweetinvi/dist/more/twitter-labs.html

Cheers,
Linvi

**Comment by linvi** [comment]
Implementation is currently in progress.

**Comment by linvi** [comment]
The implementation is now completed and will be available in 5.0.

**Comment by andypiper** [comment]
Feel free to announce at the [developer forums](https://twittercommunity.com/c/libraries-and-sdks/63), and to use any [badges](https://t.co/apibadges) you need for the README :-)
