### ISSUE TITLE
I'm not able to get extended tweets with GetUserTimelineAsync method

### ISSUE THREAD

**Issue by nminaya** [linvi/tweetinvi#1065]
I'm getting compact tweets when I call GetUserTimelineAsync even thoug I'm specifying that I want to get Extended tweets, as following:

```cs
var getTimelineParameters = new GetUserTimelineParameters("twitterUser")
{
   TweetMode = TweetMode.Extended,
   PageSize = 5
};
var timeLine = await _twitterClient.Timelines.GetUserTimelineAsync(getTimelineParameters);
```

Even the ITweet object of the returned list says that TweetMode is Extended. But the FullText is cut off at the end with three dots (...).

I'm using 5.0.0-alpha-6.

**Comment by linvi** [comment]
Hello,

Thank you for sharing. I have been able to reproduce the issue and will issue a fix.
In the meantime please use the following:

``` c#
var getTimelineParameters = new GetUserTimelineParameters("BarackObama")
{
    PageSize = 5,
    CustomQueryParameters = { new Tuple<string, string>("tweet_mode", "extended") }
};

var timeLine = await userClient.Timelines.GetUserTimelineAsync(getTimelineParameters);
```

Cheers,
Linvi

**Comment by linvi** [comment]
Hi there

Tweetinvi 5.0.0-alpha-8 has just been released and contains the bug fix.
Also, I wanted to mention that I changed the default `client.Config.TweetMode` to be `TweetMode.Extended`.

It means that by default, you should no longer have to add the `TweetMode = TweetMode.Extended` for request parameters.

I hope this helps and thanks for reporting the bug!
