### ISSUE TITLE
Async Main entry point issue

### ISSUE THREAD

**Issue by msbg93** [linvi/tweetinvi#1069]
I have installed the latest version 5.0.0 beta-1 and using framework 4.6.2. Please assist me resolve the issue.

I am following your documentation for API but still getting error.

**Error: {App} does not contain a static 'Main' method suitable for an entry point.
Warning: {App} has the wrong signature to be an entry point.**

![Code](https://user-images.githubusercontent.com/12820867/95016870-b15c7c00-060a-11eb-8839-3a4157277f5e.jpg)

![Error](https://user-images.githubusercontent.com/12820867/95016829-5d519780-060a-11eb-8789-6cdad077c511.jpg)

**Comment by linvi** [comment]
Having an async on the entrypoint is only available in C# 7.1 and above.

You can learn about the C# versions here : https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version
