### ISSUE TITLE
Filtered stream exception

### ISSUE THREAD

**Issue by msbg93** [linvi/tweetinvi#1070]
While streaming with track word I am facing the below issue, please look into this;

![Error1](https://user-images.githubusercontent.com/12820867/95128242-fcab8300-070d-11eb-96af-bc8a1e66458b.jpg)

**Comment by linvi** [comment]
401 means that the credentials are not authorised.
Could you please share the `exception.ToString()`.

``` c#
try
{
    await stream.StartMatchingAnyConditionAsync();
}
catch (TwitterException e)
{
     // Please send me this
     Console.WriteLine(e.ToString());
}
```

**Comment by msbg93** [comment]
Have a look

```
EduNewsKhi
Reason : <html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; cha
rset=utf-8"/>\n<title>Error 401 Unauthorized</title>
Code : -1
Date : 10/6/2020 8:05:18 AM -07:00
URL : https://stream.twitter.com/1.1/statuses/filter.json?track=rainbox&stall_wa
rnings=true&tweet_mode=extended
Twitter documentation description :
```

![Error2](https://user-images.githubusercontent.com/12820867/95154278-52038680-0746-11eb-9300-d43b7050d566.jpg)

**Comment by linvi** [comment]
Hi there, I am not sure what is happening here.
You seem to be authorised to get your username but seems like you are not allowed to access the stream.

Have you tried to refresh your credentials?

**Comment by msbg93** [comment]
I have not tried with refresh code.

Is there access to be open specifically for streaming?

**Comment by linvi** [comment]
> Is there access to be open specifically for streaming?

No there is not, but 401 means you are unauthorised to access the endpoint.
It is probably something wrong to do with the credentials you are using.

If updating your credentials (both consumer keys and access token) does not solve your issue the next step would be to post on https://twittercommunity.com/ as I have not seen this problem before.

**Comment by msbg93** [comment]
I will try and then inform you about

**Comment by msbg93** [comment]
Hey buddy,

I think you need to update your TweetInvi library for filtered stream. Check the below link about v2:

https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/api-reference/get-tweets-search-stream#requests

**Comment by msbg93** [comment]
Also can you please show me that I am trying to do it. You also try to filtered stream then see it's working at your side or not? It's a request please.

**Comment by msbg93** [comment]
Filtered stream endpoint has been deprecated, snapshot attached. I think now you have to update your library for Twitter API v2

![DeveloperPortal](https://user-images.githubusercontent.com/12820867/95246815-e6fb9380-07c9-11eb-90a3-cc726e53a43c.png)

**Comment by linvi** [comment]
Hello,

> I think you need to update your TweetInvi library for filtered stream. Check the below link about v2:
> https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/api-reference/get-tweets-search-stream#requests

FilteredStream API v2 is supported by Tweetinvi 5.0 (not the beta version) but I did not have time yet to document it.

``` c#
await client.StreamsV2.AddRulesToFilteredStreamAsync(new FilteredStreamRuleConfig("hello", "hello tag rule"));
var fs = client.StreamsV2.CreateFilteredStream();

fs.TweetReceived += (sender, args) =>
{
    System.Console.WriteLine($"Tweet receive : {args.Tweet.Text}");
};

await fs.StartAsync();
```

> Filtered stream endpoint has been deprecated, snapshot attached. I think now you have to update your library for Twitter API v2

What has been deprecated is the "labs" version of filtered stream, which was replaced by the filtered stream of api v2.

**Streams for API v1.1 (which you are trying to use) is still supported. You can find the documentation [here](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/overview/statuses-filter).**

> Also can you please show me that I am trying to do it. You also try to filtered stream then see it's working at your side or not? It's a request please.

Everything works fine on my side.

![image](https://user-images.githubusercontent.com/6107439/95306585-82027500-087f-11eb-8d1f-fdafbb1abcf0.png)

**Comment by msbg93** [comment]
Which ide you are using?

**Comment by linvi** [comment]
This is Jetbains Rider, which for me is the best IDE for C# on MacOS. But the IDE does not change anything, this is a .NETCore Console App.

**Comment by msbg93** [comment]
One more request can you please share code that you have written in a text file... leave the keys & token as empty string, I will place mine.

**Comment by linvi** [comment]
This is very simple code.

``` c#
static async Task Main()
{
    TweetinviEvents.BeforeExecutingRequest += (sender, args) =>
    {
        System.Console.WriteLine(args.Url);
    };

    var credentials = new TwitterCredentials(".", "..", "...", "....");
    var client = new TwitterClient(credentials);

    var fs1 = client.Streams.CreateFilteredStream();
    fs1.AddTrack("rainbow");
    fs1.MatchingTweetReceived += (sender, args) =>
    {
        System.Console.WriteLine($"Tweet Received : {args.Tweet.Text}");
    };

    await fs1.StartMatchingAllConditionsAsync();
}
```

**Comment by msbg93** [comment]
Thanks buddy 👍

**Comment by msbg93** [comment]
It's working now... it's mean that there is some issue in my code. Thanks for the help... :)

**Comment by linvi** [comment]
> TweetinviEvents.BeforeExecutingRequest += (sender, args) =>
>                 {
>                     System.Console.WriteLine(args.Url);
>                 };

You can remove this code ;)
