### ISSUE TITLE
can't get past "Could not retrieve the authentication token" question

### ISSUE THREAD

**Issue by redoc209** [linvi/tweetinvi#1076]
Using the sample code for receiving the oauth token 

          // Extract the information from the redirection url
            var requestParameters = await RequestCredentialsParameters.FromCallbackUrlAsync(Request.QueryString.Value, _myAuthRequestStore);
            // Request Twitter to generate the credentials.
            var userCreds = await appClient.Auth.RequestCredentialsAsync(requestParameters);

            // Congratulations the user is now authenticated!
            var userClient = new TwitterClient(userCreds);
            var user = await userClient.Users.GetAuthenticatedUserAsync();

            ViewBag.User = user;

The URLQuery string being returned by Twitter is:
?tweetinvi_auth_request_id=XXXXXXXXX&oauth_token=XXXXXXXXXXX&oauth_verifier=XXXXXXXX

Why are we getting "Could not retrieve the authentication token" every time? The source code hints that the reason may be that the param is missing or mal-formed?  Can you let me know what the  Request.QueryString.Value should look like?  A sample string so we can try to figure out why it is not letting us past that.  Much appreciated

**Comment by redoc209** [comment]
The issue is coming from GetAuthenticationRequestFromIdAsync always returning null.  the authenticationRequestTokenId is in this format 596becf6-XXXX-4ca4-XXXX-eff1dbb43740    Any ideas? 

public static Task<IAuthenticationRequest> GetAuthenticationRequestFromIdAsync(string authenticationRequestTokenId)
            {
            _store.TryGetValue(authenticationRequestTokenId, out var authenticationRequest);
                return Task.FromResult(authenticationRequest);
            }

**Comment by linvi** [comment]
Hi there,

Sorry for not replying earlier. Could you share more details and how you resolved your issue?

Thanks,
Linvi

**Comment by linvi** [comment]
Is it related with the following post : https://twittercommunity.com/t/connected-app-process-silently-fails-how-to-find-cause/144896

**Comment by redoc209** [comment]
No that was a different issue having to do with Twitter (5 hour delay for connected app to show up in account).  The issue we were having when we opened this turns out wasn't an issue with the code but with passing the _myAuthRequestStore.  We got it figured out.  Thanks though!
