### ISSUE TITLE
MediaV2 entity has PreviewImageUrl but no Url

### ISSUE THREAD

**Issue by iandillon** [linvi/tweetinvi#1078]
Hi is there a reason the MediaV2 model class has no Url property. The field is being requested in the expansions but is not on the response model so it not available. I am finding in a lot of cases the preview image url is not populated and it would be helpful to have the pbs.twimg url available from this property

Thanks

**Comment by linvi** [comment]
I will check this out. Thanks for sharing.

**Comment by linvi** [comment]
Hi there.

Thank you for reporting this issue. This problem actually comes from a lack of documentation [twitter forum post](https://twittercommunity.com/t/doc-twitter-api-v2-media-is-missing-the-url-field/145854).
I will release a fix soon with the new property. Sorry about the inconvenience.

Cheers,
Linvi

**Comment by linvi** [comment]
Tweetinvi 5.0.3 is now available on nuget.
