### ISSUE TITLE
CoordinatesV2 Coordinates property type causes exception

### ISSUE THREAD

**Issue by iandillon** [linvi/tweetinvi#1079]
Hi this might be low priority since comments on here suggest that the coordinates property on tweets is rarely populated, however the int[] type on the Coordinates property in the CoordinatesV2 model causes an exception when deserializing. Changing it to a double[] type seems to resolve the problem.

**Comment by linvi** [comment]
Thank you, I will release a fix soon.

**Comment by linvi** [comment]
Tweetinvi 5.0.3 is now available on nuget.
