### ISSUE TITLE
FilteredStream with no retweets

### ISSUE THREAD

**Issue by Lucas7yoshi** [linvi/tweetinvi#1080]
Im running a Filtered stream for various terms, but these are very high traffic terms and i do not want duplicated tweets from retweets.

I can filter out simply with ignoring tweets where IsRetweet is true, but i'm pretty sure its missing tweets because the stream is so saturated with retweets that are ignored

How can i filter these out with the stream itself so i can get more tweets i want to actually use?

**Comment by linvi** [comment]
> I can filter out simply with ignoring tweets where IsRetweet is true, but i'm pretty sure its missing tweets because the stream is so saturated with retweets that are ignored

Twitter will send an event if a stream gets saturated and will eventually close your stream. So if your streams is not being closed, you should be receiving all the tweets matching your conditions.

> How can i filter these out with the stream itself so i can get more tweets i want to actually use?

I have effectively never tried doing so but you could try adding to your filter the keyword : `-filter:retweets`.
For example "hello -filter:retweets".

Let me know if this works out for you.

If it does not I suggest asking on https://twittercommunity.com/ and posting a request for support on https://twitterdevfeedback.uservoice.com/forums/921790-twitter-developer-labs.
