### ISSUE TITLE
Search limited to 100 tweets

### ISSUE THREAD

**Issue by TheFizz** [linvi/tweetinvi#1091]
In this example searchResult will be a `ITweet[100]` despite PageSize being set to 228. I tried various values and it is always the same. I am trying to get all replies to a certain tweet. Am I doing something wrong?

```
private static void MentionReceived(object sender, MatchedTweetReceivedEventArgs e)
        {
            var statusId = e.Tweet.InReplyToStatusId;
            var user = e.Tweet.InReplyToScreenName;

            SearchTweetsParameters param = new SearchTweetsParameters($"@{user}");
            param.SinceId = statusId;
            param.SearchType = SearchResultType.Mixed;
            param.PageSize = 228;
            param.IncludeEntities = true;

            var t = Task.Run(() => client.Search.SearchTweetsAsync(param));
            t.Wait();
            var searchResult = t.Result;
            var tweets = searchResult.Where(t => t.InReplyToStatusId == statusId).ToList();
        }
```

**Comment by ndsvw** [comment]
Tweetinvi uses the "count" parameter of the Twitter API to request the number of tweets you specify.

Its default value is 15 and its maximum value is 100:

> The number of tweets to return per page, up to a maximum of 100. Defaults to 15. This was formerly the "rpp" parameter in the old Search API.

Source: https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets

But that should not be a problem. You could just iterate from page to page and therefore get more than 100 tweets:
https://linvi.github.io/tweetinvi/dist/twitter-api-v1.1/iterators.html
