### ISSUE TITLE
403 Forbidden Error Search V2

### ISSUE THREAD

**Issue by fightlikeagirl** [linvi/tweetinvi#1098]
Hello , I have two problem both are about search endpoints.
First I tried,
```
 var consumerOnlyCredentials = new ConsumerOnlyCredentials(TwitterCredentialConstants.CONSUMER_KEY, TwitterCredentialConstants.CONSUMER_SECRET_KEY);
var appClientWithoutBearer = new TwitterClient(consumerOnlyCredentials);
 var bearerToken = await appClientWithoutBearer.Auth.CreateBearerTokenAsync();
var appCredentials = new ConsumerOnlyCredentials(TwitterCredentialConstants.CONSUMER_KEY, TwitterCredentialConstants.CONSUMER_SECRET_KEY)
    {
        BearerToken = bearerToken
    };
var appClient = new TwitterClient(appCredentials);
``` 
(Also I tried userClient it gives me the same error)
and I try to search tweets :

```
var searchQuery="Mesut Özdil OR etc OR etc"
 SearchTweetsV2Parameters searchTweetParameters = new SearchTweetsV2Parameters(searchQuery)
    {
   PageSize=100    
   };
 try 
     {
       var tweetDeneme =await appClient.SearchV2.SearchTweetsAsync(searchTweetParameters);
       var ts=tweetDeneme.Tweets;
        int sayi=ts.Length;
     }
     catch(TwitterException e)
     {
        var hata=  e.ToString();
      }
     catch (Exception ev)
       {
         var hata2 = ev.ToString();
      }
```
Even I try to use app/user endpoints I get the same error : 

```
Reason : Forbidden
Code : 403
Date : 6.01.2021 15:40:59 +03:00
URL : https://api.twitter.com/2/tweets/search/recent?query=Mesut%20%C3%96zil%20OR%20%23BogaziciUniversity%20OR%20ONE%20OF%20SEVEN%20OR%20Puma%20OR%20%23carsamba%20OR%20%23LiderinYan%C4%B1nda%20OR%20BANG%20CHAN%20BEST%20PRODUCER%20OR%20LGBT&max_results=100&expansions=attachments.poll_ids%2Cattachments.media_keys%2Cauthor_id%2Centities.mentions.username%2Cgeo.place_id%2Cin_reply_to_user_id%2Creferenced_tweets.id%2Creferenced_tweets.id.author_id&media.fields=duration_ms%2Cheight%2Cmedia_key%2Cpreview_image_url%2Ctype%2Curl%2Cwidth&place.fields=contained_within%2Ccountry%2Ccountry_code%2Cfull_name%2Cgeo%2Cid%2Cname%2Cplace_type&poll.fields=duration_minutes%2Cend_datetime%2Cid%2Coptions%2Cvoting_status&tweet.fields=attachments%2Cauthor_id%2Ccontext_annotations%2Cconversation_id%2Ccreated_at%2Centities%2Cgeo%2Cid%2Cin_reply_to_user_id%2Clang%2Cpossibly_sensitive%2Creferenced_tweets%2Csource%2Ctext%2Cwithheld%2Cpublic_metrics&user.fields=created_at%2Cdescription%2Centities%2Cid%2Clocation%2Cname%2Cpinned_tweet_id%2Cprofile_image_url%2Cprotected%2Curl%2Cusername%2Cverified%2Cwithheld%2Cpublic_metrics
Twitter documentation description : Forbidden - The request is understood, but it has been refused or access is not allowed. An accompanying error message will explain why. This code is used when requests are being denied due to update limits.
```
How can I fix this ?
Second question, 
I try to do same with Tweetinvi 5.0 with Search endpoint with trend hashtags in Turkey:

```
SearchTweetsParameters searchTweetParameters = new SearchTweetsParameters(searchQuery)
 {
 SearchType = SearchResultType.Popular,
 PageSize = 100
  };
var tweetDeneme = await _userClient.Search.SearchTweetsAsync(searchTweetParameters);
```

I get only two tweets  even I search with most popular hashtags as query , and if I request again I get zero tweet. How can I fix that ?

My last question,
When will retire twitter search 1.1 in your opinion ? thanks.(By the way I can get 50 hashtag in Turkey without problem and search the hashtags only have volume/so has really reputation)

**Comment by ikuosaito1989** [comment]
Hi @fightlikeagirl

403 Forbidden Error Search V2 is caused by not having permission to access v2 endpoints, not tweetinvi. 
To resolve this issue, you need to create a new project on the [development site](https://developer.twitter.com/en/apps/).
Once the project is labeled "V2 ACCESS", you should be able to use v2 endpoints.

<img width="197" alt="スクリーンショット 2021-01-16 午前0 02 05" src="https://user-images.githubusercontent.com/48668579/104742880-57815b80-578e-11eb-98eb-20515fbbe62f.png">
<img width="400" alt="スクリーンショット 2021-01-15 午後11 52 37" src="https://user-images.githubusercontent.com/48668579/104742883-58b28880-578e-11eb-83c4-b08269e8ffea.png">

**Comment by fightlikeagirl** [comment]
Thank you so much @ikuosaito1989

**Comment by linvi** [comment]
Thanks @ikuosaito1989 for looking into this.

**Comment by meshugina** [comment]
> Hi @fightlikeagirl
> 
> 403 Forbidden Error Search V2 is caused by not having permission to access v2 endpoints, not tweetinvi. To resolve this issue, you need to create a new project on the [development site](https://developer.twitter.com/en/apps/). Once the project is labeled "V2 ACCESS", you should be able to use v2 endpoints.
___

Dear _ikuosaito1989_ / Everyone -

Via my Free Twitter Developer Account (and the Default Project/App Twitter supplied when setting up my account), I have both LIMITED V1.1 ACCESS ONLY & V2 ACCESS.  

I'm able to successfully Authenticate and can retrieve my UserName via the following: 
var user = await userClient.Users.GetAuthenticatedUserAsync(); 

However, I'm getting a _403 Forbidden Error_ when I then call either of the following:
var friends = await client.Users.GetFriendIdsAsync("MyFriendName");
var friend = await client.UsersV2.GetUserByNameAsync("MyFriendName"); 

Please advise (and many thanks, in advance).
