### ISSUE TITLE
Signed Binaries

### ISSUE THREAD

**Issue by SealSlicer** [linvi/tweetinvi#11]
Hey Linvi,
Is it possible to provide signed binaries?

**Comment by linvi** [comment]
Hello,

I just verified using `sn -vf` and all the libraries published on nuget are signed.
Could you please let me know which dll is causing an issue?

Also please note that the `tweetinvi.snk` file is available in the root of the project.
The reason for making this key public is to let other developers change the code if they need to.

Linvi

**Comment by SealSlicer** [comment]
Hey,
Sn only verifies strong naming not signing afaik. The properties tabs of the
assemblies don't show certificates or signatures.

Cheers,
Matt Clark On Tue, Aug 11, 2015 at 1:28 PM, linvi < notifications@github.com [notifications@github.com] > wrote:
Hello,

I just verified using sn -vf and all the libraries published on nuget are signed.
Could you please let me know which dll is causing an issue?

Also please note that the tweetinvi.snk file is available in the root of the project.
The reason for making this key public is to let other developers change the code
if they need to.

Linvi

—
Reply to this email directly or view it on GitHub
[https://github.com/linvi/tweetinvi/issues/11#issuecomment-130056682] .[https://github.com/notifications/beacon/AJ_KiHkbwgT9RMVOFciG6TYnZK-hB3WEks5omlJrgaJpZM4Fppso.gif]

**Comment by linvi** [comment]
Well, I guess I could sign the binaries but I do not really see the point behind this.

Tweetinvi is distributed by myself on nuget. Considering this, if you get Tweetinvi from nuget you will always have a 'trusted' version of the binaries.

The only scenario I can imagine right now is an evil force taking my nuget account by force and pushing unsigned dlls.

Is there something I am missing/ not considering?

**Comment by SealSlicer** [comment]
The issue is that for the project we are working on at microsoft all binaries in
the server must be signed.

Cheers,
Matt Clark On Wed, Aug 12, 2015 at 2:33 AM, linvi < notifications@github.com [notifications@github.com] > wrote:
Well, I guess I could sign the binaries but I do not really see the point behind
this.

Tweetinvi is distributed by myself on nuget. Considering this, if you get
Tweetinvi from nuget you will always have a 'trusted' version of the binaries.

The only scenario I can imagine right now is an evil force taking my nuget
account by force and pushing unsigned dlls.

Is there something I am missing/ not considering?

—
Reply to this email directly or view it on GitHub
[https://github.com/linvi/tweetinvi/issues/11#issuecomment-130236419] .[https://github.com/notifications/beacon/AJ_KiGwNqKYSgAnl5JsLLt23u5SpW4HFks5omwpogaJpZM4Fppso.gif]

**Comment by linvi** [comment]
Alright. In the future I will issue signed libraries. 

Now as I mentioned [here](https://github.com/linvi/tweetinvi/issues/10) I will not be able to work on the project nor provide support for the next 15 days. And I won't have time to work on the project tonight either.

When I come back, providing you with signed libraries will be my first assignment.
Would you please consider signing the libraries yourself for the time being?

Cheers,
Linvi

**Comment by SealSlicer** [comment]
That should be sufficient ill talk with the lead on the project. Thanks for your help!

Date: Wed, 12 Aug 2015 08:55:50 -0700

**Comment by linvi** [comment]
Hi,

Could you please let me know what you've decided concerning the signing?
Do you want to sign the dll on your side or would you prefer me to do this?

I am going to search for free certificates that are root trusted. If I can't find any I guess having self certificate authorities does not interest you?

Linvi

**Comment by linvi** [comment]
What do you think of?

http://www.cacert.org

Is Microsoft offering free certificates for Open Source projects?

**Comment by SealSlicer** [comment]
Cacert is good iirc, we do not want to sign it ourselves. Thanks.

Cheers,
Matt Clark On Wed, Sep 02, 2015 at 5:04 AM, linvi < notifications@github.com [notifications@github.com] > wrote:
What do you think of?

http://www.cacert.org [http://www.cacert.org]

Is Microsoft offering free certificates for Open Source projects?

—
Reply to this email directly or view it on GitHub
[https://github.com/linvi/tweetinvi/issues/11#issuecomment-137048410] .[https://github.com/notifications/beacon/AJ_KiEtCyG0sCHtLQ4FdEjGDGjBiIP4vks5ott0ygaJpZM4Fppso.gif]

**Comment by haseeb1431** [comment]
We might want to setup a post build script to run the signtool for signing binaries

https://msdn.microsoft.com/en-us/library/ms180786(v=vs.90).aspx

**Comment by linvi** [comment]
Yes I have seen that, I think I have a problem with the certificate that certum sent to me as I cannot get the private keys.

**Comment by linvi** [comment]
`/t http://timestamp.verisign.com/scripts/timstamp.dll`

Source : https://knowledge.symantec.com/uk/support/code-signing-support/index?page=content&id=INFO190&actp=RSS&viewlocale=en_US

**Comment by linvi** [comment]
@SealSlicer note that Tweetinvi 1.0 nuget dll will be signed.
