### ISSUE TITLE
ReplyCount is always null

### ISSUE THREAD

**Issue by matkoch** [linvi/tweetinvi#1107]
Using the v1 API, and if I'm not mistaken, then `ReplyCount` is always `null`. Tried it with a couple of tweets that actually have replies.

**Comment by baumhoto** [comment]
for v1 you need to be in premium or enterprise tier to get that information.

![image](https://user-images.githubusercontent.com/1313206/112943924-6becb780-9132-11eb-9cc1-558216b5c38e.png)

https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet

with v2 you can get this information though.

**Comment by linvi** [comment]
I think @baumhoto answered the question :)
