### ISSUE TITLE
URL encoding in tweet

### ISSUE THREAD

**Issue by jwillmer** [linvi/tweetinvi#1109]
I have the following URL: `var origin = new Uri(https://www.dwd.de/DE/wetter/warnungen_landkreise/warnWetter_node.html?ort=Tübingen)`

That I use like this: 
```
var tweet = new PublishTweetParameters
{
    Text = $".....{origin}...."
};
```

That creates the following tweet: 
![image](https://user-images.githubusercontent.com/1503577/107631575-81cb1980-6c65-11eb-9bcd-5758483c05b2.png)

As you can see the last URL parameter is not completely recognized. I'm not sure if this is a problem of Twitter or the SDK. Someone knows how to fix - if it is a bug?

**Comment by jwillmer** [comment]
I found out that it is Twitter that can't handle it. So this is what fixed it for me: `var url = Uri.EscapeUriString(message.Origin.ToString());`

**Comment by linvi** [comment]
Thanks for sharing your findings with the community :)
