### ISSUE TITLE
User stream not working in 0.9.10.1

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#111]
Hi Linvi,
User streams have stopped working for me when I switch to Tweetinvi 0.9.10.1.
Whenever I start one, the StreamStopped event is fired with a null DisconnectMessage and an IOException (The read operation failed, see inner exception.).

Inner exception on the IOException is a WebException (The request was aborted: The request was canceled.).

This was caught before going into production, so not a massively urgent problem for me, just sticking with 0.9.10.0 for the minute.
Let me know if you need any more info.
Cheers,
Josh

**Comment by linvi** [comment]
Thanks josh I will release a fix as soon as I find the issue.

**Comment by linvi** [comment]
Issue fixed and release 0.9.10.2 available on nuget.

**Comment by linvi** [comment]
Sorry about this, I knew this bug, I fixed it but I must have forgotten to commit/push it before the release.

Thanks for reporting the issue again :)

**Comment by JoshKeegan** [comment]
Brilliant, thanks!
I'll give 0.9.10.2 a try now

**Comment by linvi** [comment]
Any luck?

**Comment by JoshKeegan** [comment]
Yes thanks, streams working perfectly now :)
