### ISSUE TITLE
Filter out replies

### ISSUE THREAD

**Issue by AlexGipp** [linvi/tweetinvi#1110]
Im using 
```cs
                var timeline = await userClient.Timelines.GetUserTimelineAsync(Config.Bot.TwitterUserId);
                var latestTweet = timeline.First(); 
```
Is there a way to filter out replies?

**Comment by linvi** [comment]
The Twitter API does not offer such filter unfortunately. You can check all the query parameters with the `GetUserTimelineParameters`.
