### ISSUE TITLE
Is there no way to validate a username without catching exceptions?

### ISSUE THREAD

**Issue by Brettyoke49** [linvi/tweetinvi#1112]
I've searched high and low for a way to validate whether or not a given username is valid, but the only way to do so seems to be to catch an exception thrown when attempting to create a user object or access a timeline for a user that  doesn't exist...

**Comment by Brettyoke49** [comment]
After reading further from docs, this seems like it might be by design. I guess I'll live with it.

**Comment by linvi** [comment]
Yes this is now by design. This ensures everything in the library works the same way.
When a request fails the users ought to be aware of it. Prior to 5.0 Tweetinvi was doing the analysis on its own by returning null, this was causing confusion between Exceptions and nulls.
