### ISSUE TITLE
Set Credentials

### ISSUE THREAD

**Issue by luis-ramirez** [linvi/tweetinvi#112]
I can't found this method.

TwitterCredentials.***SetCredentials***("Access_Token", "Access_Token_Secret", "Consumer_Key", "Consumer_Secret");

**Comment by linvi** [comment]
It has been changed to `Auth.SetCredentials` but please be careful that **the parameters have changed of order**!!!

I hate doing this kind of changes but they were necessary to improve the clarity and usability of Tweetinvi.

https://github.com/linvi/tweetinvi/wiki/Credentials

**Comment by luis-ramirez** [comment]
Good, but the documentation need changes :).

**Comment by linvi** [comment]
Please let me know if there is anywhere some code that is invalid in the documentation. I like to have an up to date documentation so please point out the errors!

**Comment by linvi** [comment]
If you were referring to the Introduction/Hello World I have just fixed that. 

Thanks!
