### ISSUE TITLE
Question: Is is possible to get latest tweet from someone?

### ISSUE THREAD

**Issue by Diogovski** [linvi/tweetinvi#1121]
Hi, i want to know if it possible to use this library to get a users latest tweet, so i can save it and then retweet it, without needing to manually type the tweet id!

**Comment by Diogovski** [comment]
???

**Comment by Volen99** [comment]
Hey bro, look at this link: https://www.reddit.com/r/csharp/comments/bnnp0e/how_to_check_for_new_tweets_with_tweetinvi/

After you get the tweet(s), you can use its id to retweet it.
