### ISSUE TITLE
How to efficiently determine AddFollow user ID for matched tweet?

### ISSUE THREAD

**Issue by lcichanowicz** [linvi/tweetinvi#113]
Hi.
I use `IFilteredStream.AddTrack` and then use `Core.Events.EventArguments.MatchedTweetReceivedEventArgs.MatchingTracks` to determine which "track(s)" the tweet matched.

How do I do this same thing for `FilteredStream.AddFollow` to get the `userId` of the followed user(s) that the tweet matched?

Thanks,
Lee

**Comment by linvi** [comment]
I don't know if this answer your question but here you go.

``` c#
var userById = new Dictionary<long, IUser>();
// add what you want here

var s = Stream.CreateFilteredStream();
s.MatchingTweetReceived += (sender, args) =>
{
    var userId = args.Tweet.CreatedBy.Id;
    var matchingUser = userById[userId];
};
```

**Comment by lcichanowicz** [comment]
Thanks, but I have a mix of "Tracks" and "Follows" in my stream.  I believe that code would give me the userId of every tweet, even if it matched a track instead of a follow.  Conceivably, a tweet could match both.

**Comment by linvi** [comment]
I am not sure what you are trying to do. If you want to verify if a `Tweet` has not matched any `Track`, then the `MatchingTracks` will be empty and you can just compare the `CreatedBy.Id` to your Follow list.

**Comment by lcichanowicz** [comment]
When a matched tweet is received, I'm trying to definitively and efficiently determine if it was received because it matches one of my FilteredStream.AddFollow users, and which one.

**Comment by lcichanowicz** [comment]
Before posting here, I did try checking for `MatchingTracks.Count = 0`, then inspecting `Tweet.CreatedBy.Id`, but I got lots of false positives.

**Comment by linvi** [comment]
> When a matched tweet is received, I'm trying to definitively and efficiently determine if it was received because it matches one of my FilteredStream.AddFollow users, and which one.

And why is the initial issue not correct?

> Before posting here, I did try checking for MatchingTracks.Count = 0, then inspecting Tweet.CreatedBy.Id, but I got lots of false positives.

Could you give me an example of a false positive?

Also please note that a tweet can obviously be received because of BOTH parameters are matched.

**Comment by lcichanowicz** [comment]
> And why is the initial issue not correct?
Sorry, I do not understand the question.

**Comment by lcichanowicz** [comment]
False positive example: `MatchingTracks.Count` is zero.  I inspect the `Tweet.CreatedBy.Id` and find that it is not a UserId I am following in the stream.

**Comment by linvi** [comment]
> And why is the initial issue not correct?
I meant the answer (not issue) with the dictionary.

Ok, let me investigate this. Can you share the Tracks and UserIds you are trying to follow?
In fact if you could share the code where you configure the stream it would be perfect.

Thanks

**Comment by lcichanowicz** [comment]
I'll be back on this project later today.  I'll pare down the scope and complexity and share it ASAP.  In short, I'm asking for ` Core.Events.EventArguments.MatchedTweetReceivedEventArgs.Matching***Follows***`

**Comment by lcichanowicz** [comment]
As a hack of a solution, I'm thinking of running two streams: One for tracks and one for follows.

**Comment by lcichanowicz** [comment]
I investigated further, and it seems I failed to understand how the Twitter Stream API handles "follows."  It makes sense now, and it probably explains what I thought were false positives.  In other words, I think I was wrong about the methodology I was trying to use to determine the follow user match for a matching tweet.

I failed to account for chains of retweets (retweet of a retweet) where the streamed matching tweet's user ID is not one I'm following, but the tweet is still a match because of a user ID I am following.  It appears that in such cases, I have to request the retweeted tweet, by ID from Twitter, to look for a user ID I am following, repeating the chaining until I match a user ID.

I plan to inspect and log the match if it's in the streamed tweet (level 1).  If not, I'll leave it NULL, for later processing.

As for getting help from the tweetinvi library with this follow user ID matching, this situation may be too complex to justify spending much time on it.  It would be nice if tweetinvi exposed the ID(s) if they are in the streamed matching tweet: `user_mentions`, `in_reply_to_user_id`, or within `retweeted_status`, but since these often will not yield the match, more API calls will be needed.

**Comment by linvi** [comment]
Hello there, I see and to be honest I did not remember these rules. Last time I used stream to follow users was more than 3 years ago.

If any additional call is required to get additional data this will not be done in Tweetinvi, mainly because of the performance and RateLimits complexity.

I associate this issue to 0.9.11.0 in order to review before publishing the next release. If you are not in a hurry I will do this during this weekend. 

If you are in a hurry please let me know and I will work on this tomorrow evening.

Cheers,
Linvi

**Comment by lcichanowicz** [comment]
Thanks, Thomas.  I do not want to rush you.  Foremost, I needed to understand whether I can readily determine the `MatchingFollows` later, versus missing the opportunity to grab it when the match arrives.  I now see that this will be fine, which relieves some pressure.

I will have to start processing the tweets first thing Monday morning (EDT).  I'm confident I can figure it out.  If you want to wait, I'll share my code with you.  Or, if you want to tackle it sooner, I'll honor my bounty offering.  :]

**Comment by lcichanowicz** [comment]
I just stumbled upon this seemingly very same request from just a few months ago.
[https://tweetinvi.codeplex.com/discussions/647970](https://tweetinvi.codeplex.com/discussions/647970)

**Comment by linvi** [comment]
Please try http://www.speedyshare.com/VtFUW/Tweetinvi.dll and let me know if this help you.

DO NOT USE IN PRODUCTION : this is alpha dll.

Thanks

**Comment by lcichanowicz** [comment]
Just downloaded.  About to dig in.  Thanks!  To be clear, at present I'm using it for local tweet processing out of the "raw" tweet JSON persisted to a local db.

**Comment by lcichanowicz** [comment]
Thomas, can please provide sample code for setting credentials for the stream?  I was using `TwitterCredentials.SetCredentials()` but that appears to have changed.

I tried `Auth.SetCredentials` but I get:
> {"The type initializer for 'Tweetinvi.Auth' threw an exception."}
> Could not load file or assembly 'Autofac, Version=3.5.0.0, Culture=neutral, PublicKeyToken=17863af14b0044da' or one of its dependencies. The system cannot find the file specified.

**Comment by lcichanowicz** [comment]
Ah, resolved with `PM> Install-Package Autofac`, which then led to `PM> Install-Package Newtonsoft.Json`.  I think I'm okay now.

**Comment by linvi** [comment]
Sorry. These things are so obvious for me that I sometimes forgot to mention it :s
I hope you are good now.

List of the dependencies : 

``` xml
<dependency id="Autofac" version="3.5.2" />
<dependency id="Microsoft.Bcl.Async" version="1.0.168" />
<dependency id="Microsoft.Bcl.Build" version="1.0.21" />
<dependency id="Microsoft.Net.Http" version="2.2.29" />
<dependency id="Newtonsoft.Json" version="7.0.1" />

```

**Comment by lcichanowicz** [comment]
Thanks, Thomas.  I got it working, but I'm not finding a way to get Matching**Follows**.  `MatchingTracks` is still always zero when my filtered stream has only an `AddFollow`.  If I had the source, I'd diff it with the current release, but I only have the compiled DLL.  Can I get a hint, please?  :]

**Comment by linvi** [comment]
Here is what I have done : https://github.com/linvi/tweetinvi/commit/cb21ea4972757dfd34c8ae57c42cab52e7b3fe51.

Just to be clear, you are receiving a json event but Tweetinvi does not match the tweet correctly?
