### ISSUE TITLE
JsonSerializer the GetUserTimelineAsync

### ISSUE THREAD

**Issue by jrahma** [linvi/tweetinvi#1134]
Hi,

i am new to tweetinvi..

How can I JsonSerializer the content of GetUserTimelineAsync?

Also do you have a sample class of the fields?

Thanks,
Jassim

**Comment by jrahma** [comment]
What i am trying is to put the output of all the tweets of an account e.g. ("Microsoft") inside a ListView like this:

```
List<MicrosoftTweets> data = JsonSerializer.Deserialize<List<MicrosoftTweets>>(result);
ListViewTweets.ItemsSource = data;

```

**Comment by linvi** [comment]
This is documented here: https://linvi.github.io/tweetinvi/dist/twitter-client/json.html

Hope this helps.
