### ISSUE TITLE
Geo coordinates are the other way around

### ISSUE THREAD

**Issue by maxima120** [linvi/tweetinvi#1136]
LAT is LON and LON is LAT.

if you use how the documentation tells you to - you are in wrong location.

this doesnt work (points not to NY):
https://linvi.github.io/tweetinvi/dist/streams-v1.1/filtered-stream-filters.html
```
stream.AddLocation(new Coordinates(-74, 40), new Coordinates(-73, 41));
```

this works
```
stream.AddLocation(new Coordinates(40, -74), new Coordinates(41, -73));
```

if you examine Coordinates object it shows LAT number in LON field and vice versa.

I think we settled this ages ago and it did work in older versions. Please stop changing the core behaviour. I wasted an hour trying to figure whats wrong after upgrade to v5

**Comment by linvi** [comment]
Sorry about this. I unified all the methods across Tweetinvi in 5.0 to use the same order for the parameters.
