### ISSUE TITLE
Check if comment added already

### ISSUE THREAD

**Issue by Gillardo** [linvi/tweetinvi#1143]
If i want to add a comment to a tweet and its a duplicate, i get an error.  Is there a way to check if a comment has already been added?

**Comment by linvi** [comment]
There are currently no such a feature. What you need to know is that Twitter does not allow to publish duplicate tweets from the same account in a relatively long period (at least few days).

As far as I am aware the conversation API is not yet available so I don't think you can get this information apart by using the Search API.

If the comments you want to publish are created by your app, I would suggest keeping track of those in a DB you own and check with that DB if you've recently published this comment.
