### ISSUE TITLE
Donate button not working

### ISSUE THREAD

**Issue by petreturcu** [linvi/tweetinvi#1148]
The donate button giving a _**This organisation is currently ineligible to receive donations.**_  response when pressed.

Please see below a screenshot of incognito Chrome of the button redirecting to: https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=4W8BCYB4FVSN6

![image](https://user-images.githubusercontent.com/20480119/146203482-08c3d92a-6c3f-4a1a-86d4-20e263be15c4.png)

**Comment by rmount** [comment]
Still not working. I'd be happy to donate if it were possible ...

**Comment by petreturcu** [comment]
Looks like it is working now.
