### ISSUE TITLE
Bandwidth usage of follower stream

### ISSUE THREAD

**Issue by dubmartin** [linvi/tweetinvi#115]
Hi, 

Am running into an issue where running a follower stream of 20 accounts (with a total daily new follower notifications of about 100) using 5-10gb.

Are streams just badnwidth heavy due to the constant connection or does that seem unusually large?

**Comment by dubmartin** [comment]
multiple UserStreams

**Comment by linvi** [comment]
`UserStream` can use more bandwidth than `FilteredStream` still the quantity of data you mention is quite high. Do these accounts follow a lot of users?

**Comment by linvi** [comment]
Please provide more information or I will have to close this thread.

**Comment by linvi** [comment]
Please open the thread again if you still experience this problem.
