### ISSUE TITLE
user.GetFavorites with UserTimelineParameters

### ISSUE THREAD

**Issue by musaika** [linvi/tweetinvi#116]
Hi,

IUser interface has GetUserTimeline method with 2 overloads, while twitter api is also providing same structure for GetFavorites (https://dev.twitter.com/rest/reference/get/favorites/list), there is no method for specifying extra api parameters for this method. And its so important for my project.

I want to call something like: GetFavorites(max_id = xxx, max_number_of_tweets = 20)

Please help..

**Comment by linvi** [comment]
Hello there, you are correct, currently Tweetinvi cannot do that for you.
This is something that is currently being improved and you'll be able to do that later.

With the current version of Tweetinvi you'll have to perform a [Custom Query](https://github.com/linvi/tweetinvi/wiki/Custom-Queries).

``` c#
var lu = User.GetLoggedUser();
var maxNumberOfTweets = 5;

// Look at https://dev.twitter.com/rest/reference/get/favorites/list for more parmeters
var query = $"https://api.twitter.com/1.1/favorites/list.json?count={maxNumberOfTweets}&user_id={lu.Id}";

var favoriteDTOs = TwitterAccessor.ExecuteGETQuery<IEnumerable<ITweetDTO>>(query);
var favorites = Tweet.GenerateTweetsFromDTO(favoriteDTOs);
```

Please let me know if this worked.

PS : I have added this feature for the next version of Tweetinvi.

**Comment by musaika** [comment]
You're my personal hero man.. Thank you very much.. This block saves my life :)
