### ISSUE TITLE
Best way to get tweet JSON of MatchingTweetReceived

### ISSUE THREAD

**Issue by lcichanowicz** [linvi/tweetinvi#117]
I see there is a work item for this.  I wonder if it is still "alive."
https://tweetinvi.codeplex.com/workitem/2341

I ended up hooking both `MatchingTweetReceived` and `JsonObjectReceived` to get the "raw" JSON of the streamed tweet.  Is this currently the best way to get the JSON in addition to leveraging the goodness of MatchingTweetReceived?

**Comment by linvi** [comment]
Hi there,

Unfortunately, this is currently the only way to do such operation. It has been requested multiple times but this won't be available before version 1.1.

There already is a work item for this here : https://github.com/linvi/tweetinvi/issues/75

**Comment by linvi** [comment]
Tweetinvi 1.1 is almost going to be released and you will be able to find this feature in this version ;)
