### ISSUE TITLE
tweet.Favourited always returns false.

### ISSUE THREAD

**Issue by Disastercake** [linvi/tweetinvi#118]
If you use code similar to the following, the Favourited value will always be false.

```
if (!tweet.Favourited)
{
     tweet.Favourite();
     return true;
}
```

**Comment by linvi** [comment]
I am not sure I do understand what you want to do but if you follow the next example you'll see that it works.

``` c#
var tweet = Tweet.PublishTweet("my test of favourite");
// tweet.Favourited is false
tweet.Favourite();
// tweet.Favourited is now true
```

**Comment by Disastercake** [comment]
I'd like to know if the tweet has already been favourited before the
search, so it can be removed from the list.

**Comment by linvi** [comment]
I need to have a better context than this if you want me to help you.
I don't know what search you are referring to. I do not know if you already have the tweet objects or the tweet ids or nothing. Nor do I know how you want to retrieve the tweets.

Please provide more details.

**Comment by Disastercake** [comment]
Sure, here are more details:

1. I search for tweets based on criteria and get the array of tweets back.
2. I loop through the array of tweets.
3. Each iteration of the loop I check if the tweet has been liked BEFORE
the search was performed. (my assumption is Favourited should be true if
the tweet has been liked outside the app)
4. I perform actions based on the boolean value returned in step 3.

From my tests, I've noticed that tweets that have been liked before the
most recent search have the Favourited value at false instead of true.
Does this make more sense?

Note: I use the word "liked" to mean "favourited", as to be unambiguous between
the variable and the verb.

**Comment by linvi** [comment]
Favourited means that the currently authenticated user has liked the tweet.
Even if 100 person like a tweet this `Tweet.Favourited` can be false.

This is how the Twitter API behaves.
