### ISSUE TITLE
How can reply other tweet?

### ISSUE THREAD

**Issue by XnCN** [linvi/tweetinvi#12]
my code 

          var tweetToReplyTo = Tweet.GetTweet(631794399131881472);
            var tweet = Tweet.PublishTweet("We love you back!", new PublishTweetOptionalParameters
            {
         
                InReplyToTweetId = tweetToReplyTo.Id
            });

**Comment by linvi** [comment]
This code is correct and is working when I try it.
Could you please let me know what actually happens when you use this code?

**Comment by linvi** [comment]
I am closing this issue as I don't think it is one.
Feel free to come back and leave some comment if needed.
