### ISSUE TITLE
TweetInvi Code stopped working

### ISSUE THREAD

**Issue by sabarimalaiiyyappan** [linvi/tweetinvi#1216]
TweetInvi is failing at method "appClient.Auth.RequestAuthenticationUrlAsync(redirectURL)" while authenticating and below is the response we get:

Reason : Unauthorized
Details : Could not authenticate you. (32)
Code : 401
Date : 6/30/2023 2:09:16 PM +05:30
URL : https://api.twitter.com/oauth/request_token
Twitter documentation description : Unauthorized - Authentication credentials were missing or incorrect.

Request help to identify why it breaks suddenly

**Comment by Gitekkaad** [comment]
This works for me so far
***************************
using Tweetinvi;
using Tweetinvi.Models;

var client = new TwitterClient  ("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");
var user = client.Users.GetAuthenticatedUserAsync().Result;
MessageBox.Show($"You are now authenticated as {user}!");

**Comment by sabarimalaiiyyappan** [comment]
Thanks for your response. Must be an issue with our app then. We will check on it. Thanks.
