### ISSUE TITLE
How would i perform a user sign in?

### ISSUE THREAD

**Issue by SpireHex** [linvi/tweetinvi#123]
I am making a Windows store app what is going to go into competition with TweetDeck and im trying to find how you use a email and password to create a user stream, right now im not having any luck... Can you even do this because it will be helpful?

**Comment by linvi** [comment]
I recently had a discussion with the staff of Twitter regarding the authentication using the username/password. They told me that they are very rarely granting such permissions to companies.

Instead you need to create an app on [apps.twitter.com](https://apps.twitter.com). From there you will receive a `Consumer Key` and `Consumer Secret`.

You can use these 2 information to start a Twitter user authentication process.

For more information please read :

* [Twitter Credentials](https://github.com/linvi/tweetinvi/wiki/Credentials)
* [Authentication](https://github.com/linvi/tweetinvi/wiki/Authentication)

I hope this help you.
