### ISSUE TITLE
[VOTE] LoggedUser vs AuthenticatedUser

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#126]
@JoshKeegan @ON-MX @dubmartin @komBAS @lcichanowicz @rdahan156 @Muchomasquewebs  @gsogol 

Please take some time to vote for your favourite naming convention.
I understand renaming `LoggedUser` to `AuthenticatedUser` will be annoying and boring but I think that it should be done before Tweetinvi version 1.0.

`User.GetLoggedUser()` will be changed by `User.GetAuthenticatedUser()`.

Please DO NOT take into consideration the fact that it is annoying but only choose what is the more natural naming between the 2.

Thanks for your help.
Linvi

**Comment by rdahan156** [comment]
i'm with "AuthenticatedUser".

**Comment by ON-MX** [comment]
I'm also with "AuthenticatedUser" ^_^

**Comment by JoshKeegan** [comment]
Putting aside the breaking change aspect of this, "AuthenticatedUser" gets my vote.
It's gramatically correct, clearer & more consistent with the naming of the "Auth" class that developers will have used to set their credentials.

If it is to stay as "GetLoggedUser", it would be clearer to make it "GetLoggedInUser" just to make it clear that it isn't anything to do with any logging libraries being used.

**Comment by komBAS** [comment]
I vote for "AuthenticatedUser".
I have still work to do with my application, so renaming shouldn't be the problem.

**Comment by linvi** [comment]
With 4 votes + mine I will change all references of `LoggedUser` to `AuthenticatedUser` in the code, documentation, github issues and stackoverflow.

Loads of fun in perspective!

Thanks all of you for taking the time to reply.

**Comment by linvi** [comment]
Update the documentation and StackOverflow.
