### ISSUE TITLE
streaming api and locations

### ISSUE THREAD

**Issue by ghentsch** [linvi/tweetinvi#129]
What is the correct way to filter tweets based on location? Is it just a matter of using stream.AddLocation() or do I need to check location after receiving a tweet?

Also, when i receive a tweet from event MatchingTweetAndLocationReceived, can I assume that the tweet has a location? Is that location supposed to be in Tweet.Coordinates? If so, i'm seeing null coordinates in tweets from that event.

**Comment by linvi** [comment]
It depends on the number of filter you use and how you start the stream. If you take a look at the [All vs Any](https://github.com/linvi/tweetinvi/wiki/Filtered-Streams#tweetinvi-behavior---all-vs-any) in the `FilteredStream` documentation you will understand that there are 2 ways to filter the tweets.

> When using the StartStreamMatchingAnyConditions method to start the stream, Tweetinvi will return the tweets matching EITHER of the filter types.

> When using the StartStreamMatchingAllConditions method to start the stream, Tweetinvi will return the tweets matching ALL of the filter types.

It means that if you add other types of filters and use `StartStreamMatchingAnyConditions` you can receive tweets not matching a location.

In addition please note that issues related with the stream filtering have very recently been updated in the not yet released version of Tweetinvi.

You can get the alpha binaries [here](https://github.com/linvi/tweetinvi/releases/tag/0.9.11.0-alpha).

Let me know if this help you in any way.

**Comment by ghentsch** [comment]
Thanks. That does make sense. What's the purpose of event MatchingTweetAndLocationReceived? That is, how does it differ from MatchingTweetReceived? My interpretation is that we get MatchingTweetAndLocationReceived if the tweet has coordinates (i.e. location). But i'm seeing null coordinates from tweets i get from that.

**Comment by ghentsch** [comment]
Also, I tried using that alpha build of tweetinvi.dll and I get an exception at:

IFilteredStream stream = Stream.CreateFilteredStream(twitterCredentials);

An unhandled exception of type 'System.TypeInitializationException' occurred in Twitter Reader.exe

**Comment by linvi** [comment]
The purpose was to improve the performances. If a user did not want to retrieve the `Coordinates`, tweetinvi is not making the calculations required to return this.

The idea was to improve the performances to a maximum.

In the new version (0.9.11.0), this event does not exist anymore and you will be able to retrieve the information you seek in the `MatchingTweetReceived` event.

Here is a brief code explanation of 0.9.11.0 (no documentation is yet available).

``` c#
var fs = Stream.CreateFilteredStream(); 

// You can reduce the number of analysis performed on the tweet 
// by changing the `MatchType` parameter
// If you do not specify all entities some tweet received 
// by Tweetinvi will not be returned in `MatchingTweetReceived`.
fs.MatchType = StreamMatchType.AllEntities;

fs.MatchingTweetReceived += (sender, args) =>
{
    // matching locations is now directly included in MatchingTweetReceived
    var locations = args.MatchingLocations; 

    var keywords = args.MatchingTracks; 

    var followers = args.MatchingFollowers;
    var tweet = args.Tweet;
    var matchedThanksTo = args.StreamMatchType;
};

// if you want to filter down the result but yet want to receive 
// the tweets that were not matched, use `NonMatchingTweetReceived`
fs.NonMatchingTweetReceived += (sender, args) =>
{
    var tweet = args.Tweet;
    // No other information is available from this event
};
```

**Comment by linvi** [comment]
> Also, I tried using that alpha build of tweetinvi.dll and I get an exception at:
IFilteredStream stream = Stream.CreateFilteredStream(twitterCredentials);
An unhandled exception of type 'System.TypeInitializationException' occurred in Twitter Reader.exe

Oh sorry you need to reference the dependencies. Please get them from nuget:

``` xml
  <package id="Autofac" version="3.5.2" targetFramework="portable-net4+sl5+win8+wp8" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="portable-net4+sl5+win8+wp8" />
  <package id="Microsoft.Bcl.Async" version="1.0.168" targetFramework="portable-net4+sl5+win8+wp8" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="portable-net4+sl5+win8+wp8" />
  <package id="Newtonsoft.Json" version="8.0.2" targetFramework="portable40-net40+sl5+win8+wp8+wpa81" />
```

**Comment by ghentsch** [comment]
thanks.

**Comment by linvi** [comment]
Before you leave, please let me know if this worked!

**Comment by ghentsch** [comment]
Yes, that did the trick. Thanks for the quick response. Regards,

gh

**Comment by ghentsch** [comment]
I tried a StartStreamMatchingAnyConditionAsync() with a couple of tracks. What I'm finding is that all the correct matches (where one or the other track is matched) are coming in NonMatchingTweetReceived instead of MatchingTweetReceived. So, i'm only getting tweets in MatchingTweetReceived when no matches are made.

**Comment by linvi** [comment]
Oh wait I think I was wrong on something.

Please remove this line : `fs.MatchType = StreamMatchType.AllEntities;`

**Comment by ghentsch** [comment]
I wasn't actually using that line of code. I was just calling StartStreamMatchingAnyConditionAsync() after setting up a few (any) tracks.

**Comment by linvi** [comment]
Would you mind sharing your code please.

**Comment by linvi** [comment]
Hi there, it was a bug, which is now fix and uploaded in the [alpha binaries](https://github.com/linvi/tweetinvi/releases/tag/0.9.11.0-alpha).

Thanks for reporting the issue.
