### ISSUE TITLE
PublishTweetWithImage not working when calling from a web site

### ISSUE THREAD

**Issue by kritochin** [linvi/tweetinvi#13]
Hi, 
I've been trying to post a Tweet with an image but it hungs in this line:

Class:HttpClientWebHelper
Method: return await client.PostAsync(twitterQuery.QueryURL, httpContent);

This only happens when I called it from a site. If I used it in a Console application, like in your examples, it sucessfully post the tweet with the media. 

Thanks you in advance.

**Comment by linvi** [comment]
I will have a look into this in the coming days. There are some issues when using async tasks with ASP.NET. This will be released as a fix of 0.9.9.x.

**Comment by rudiv** [comment]
Note that the same fix for #15 fixes this issue as it resolves the context issues within ASP.NET (and UI applications also).

**Comment by linvi** [comment]
Thanks again for your help. As mentioned in rudiv issue, a fix will be released as part of version 0.9.6.x.
