### ISSUE TITLE
StartStreamMatchingAllConditionsAsync not matching all tracks

### ISSUE THREAD

**Issue by ghentsch** [linvi/tweetinvi#131]
I've setup a stream with 2 tracks and ran the stream with StartStreamMatchingAllConditionsAsync. What i'm finding is that not all matching tweets are matching all words (tracks). It's behaving more like StartStreamMatchingAnyConditionAsync. I'm using 0.9.11.0. Bug or am I assuming something I shouldn't?

**Comment by linvi** [comment]
Could you please share your code. I really need to understand the context to help you with this.

**Comment by ghentsch** [comment]
Sure, here's a quick example:

IFilteredStream stream = Stream.CreateFilteredStream(twitterCredentials);
stream.AddTrack("clinton");
stream.AddTrack("sanders");
stream.MatchingTweetReceived += (sender, args) => {
	Console.WriteLine("Matching Tweet: " + args.Tweet.Text);
};
stream.StartStreamMatchingAllConditionsAsync();

So, what i'm finding is i'm getting some successful matches with just "clinton" in the tweet and not "sanders". Whereas I would only expect matches that have both "clinton" and "sanders" since i'm matching on all conditions. instead of StartStreamMatchingAnyConditionAsync().

**Comment by linvi** [comment]
This is not a bug.

If you want to match 2 keywords you need to add both of them in the same Track with a space. `AddTrack` is an OR operation.

``` c#
// Let's get tweets containing 'linvi' 
stream.AddTrack("linvi");

// OR tweets containing both 'tweetinvi' AND 'rocks'.
stream.AddTrack("tweetinvi rocks");
```

I have implemented it this way to copy the Twitter API logic.

Read the documentation for more information : https://github.com/linvi/tweetinvi/wiki/Filtered-Streams#filter-by-track-and-keywords

And the Twitter documentation for more information over the tracks (phrases). https://dev.twitter.com/streaming/overview/request-parameters#track

**Comment by ghentsch** [comment]
Thanks.
