### ISSUE TITLE
Follow, Unfollow, and Like always return false and fail to perform action.

### ISSUE THREAD

**Issue by Disastercake** [linvi/tweetinvi#132]
My code was working before and would unfollow people, but for the past week or so it stopped working.  The Follow, Unfollow, and Like methods just return false.

However I am able to get search results and the list of people I'm following, and also relationship details (except sometimes relationship details gets hung up).

Any idea what could be wrong?

I use this code for unfollow:
```
bool unfollowed = await Auth.ExecuteOperationWithCredentials(creds, async () =>
{
       return await _loggedUser.UnFollowUserAsync(user);
});
```

I then try to use

`var latestException = ExceptionHandler.GetLastException();`

However this always returns a null.  So I have no idea where to get feedback from the package on why it returned false.

The Rate limit always says there are some remaining.

**Comment by linvi** [comment]
Hello there, please try to keep the issue there so that people experiencing the same issue/problem can find the solution thanks to your experience.

I am glad that you've been able to fix it.

If you need any help feel free to ask!
