### ISSUE TITLE
Authenticating in UWP error

### ISSUE THREAD

**Issue by matdestr** [linvi/tweetinvi#133]
I use the method Auth.SetUserCredentials(...); 

When i try to authenticate in a test console app and publish a tweet everything is fine. When i do the same in a uwp app i get this error when trying to authenticate

System.TypeInitializationException: The type initializer for 'Tweetinvi.Auth' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Tweetinvi.Core.TweetinviCoreModule.Initialize()
   at Tweetinvi.Injectinvi.AutofacContainer.InitializeModules()

If you want to see my code: https://github.com/matdestr/TwitterShared.git

**Comment by linvi** [comment]
Hello there, 

This is a known issue of UWP with PCL libraries please use the following package :+1: 

`Install-Package tweetinviapi -version 0.9.10.2-w10-uap -pre`

Thanks

**Comment by matdestr** [comment]
Thanks, do you have full twitter example with tweetinvi ?

On Sun, Feb 21, 2016 at 1:36 AM linvi <notifications@github.com> wrote:

> Hello there,
>
> This is a known issue of UWP with PCL libraries please use the following
> package [image: :+1:]
>
> Install-Package tweetinviapi -version 0.9.10.2-w10-uap -pre
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linvi/tweetinvi/issues/133#issuecomment-186708578>.
>
-- 
Mathisse De Strooper
+32474054598
mathisse.de.strooper@gmail.com

**Comment by linvi** [comment]
I am not sure what you mean but if you download the source code from Github you'll be able to get an example for UWP, ASP.NET and a Console project.
