### ISSUE TITLE
[VOTE] RateLimits naming

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#141]
@JoshKeegan @ON-MX @dubmartin @komBAS @lcichanowicz @rdahan156 @Muchomasquewebs @gsogol

Your vote was quite helpful regarding the LoggedUser vs AuthenticatedUser. As I am struggling with 2 other names please let me know what you think.

Questions : 

1. `TokenRateLimits` vs. `CredentialsRateLimits`
2. `TokenRateLimit` vs. `EndpointRateLimits`
3. Any other comment/idea.

**More details below:**

I would like to change `TokenRateLimits` (it represents all the rate limits available for a token)  into `CredentialsRateLimits`.

I would like to change `TokenRateLimit` (it represents the rate limits applied to a specific url) into `EndpointRateLimit` or `UrlRateLimit`.

Thanks again for your help.

**Comment by rdahan156** [comment]
1. CredentialsRateLimits
2. EndpointRateLimits

**Comment by JoshKeegan** [comment]
CredentialsRateLimits & EndpointRateLimit

**Comment by komBAS** [comment]
CredentialsRateLimits
EndpointRateLimits
