### ISSUE TITLE
ChunkedUploader / UploadVideo / PublishTweetWithVideo all hang on upload

### ISSUE THREAD

**Issue by rudiv** [linvi/tweetinvi#15]
All variations of uploading a video (video size is less than 500kb) appear to hang when calling "Append". This includes:

    // 1
    var media = Upload.UploadVideo(video);
    // 2
    var uploader = Upload.CreateChunkedUploader();
    var initSucceeded = uploader.Init("video/mp4", video.Length);
    var success1 = uploader.Append(video);
    var media = uploader.Complete();
    // 3
    var twit = Tweet.PublishTweetWithVideo(tweet, video);

The line `uploader.Append(video);` hangs, all other methods never return.

Upon inspection by Fiddler, the Twitter API is returning perfectly fine with a HTTP 204 status code, and looking into the code (only on Github, sorry I haven't had the chance to download and debug further) I can't see any obvious reason why this would cause an issue.

**Comment by rudiv** [comment]
Turns out it was a deadlock with regards to usage of `.Result` in WebRequestExecutor.cs. I assume you had the same issue before with a different method as you are using `.ConfigureAwait(false)` just a few lines above the line that I have fixed.

See pull request.

**Comment by linvi** [comment]
Thanks for your help, I will release a new version 0.9.6.x when I have verified all the other logged issues.
