### ISSUE TITLE
TweetinviAPI NuGet package 0.9.10.2 issue in Windows Universal app

### ISSUE THREAD

**Issue by Myfreedom614** [linvi/tweetinvi#150]
The Latest NuGet package 0.9.10.2 will throw “Could not load file or assembly......" exception in **Windows Universal app**, and in Class Library(Universal), also have the same issue, see this StackOverflow question: http://stackoverflow.com/questions/35813839

Downgrade to 0.9.10 will solve it.

**Comment by linvi** [comment]
Hi,

I just replied to you on stackoverflow:

>
In fact it is not an issue with the package but of the UAP. In any case you can now download the latest version (0.9.11.0) of Tweetinvi on nuget should work.
Update-Package TweetinviApi // if already installed
OR
Install-Package TweetinviApi // if not installed
If you want version 0.9.10.2 you can use the following :
Install-Package TweetinviAPI -Version 0.9.10.2-W10-UAP -Pre

Cheers,
Linvi

**Comment by Myfreedom614** [comment]
@linvi Thank you, I'm investigating this issue with your details
