### ISSUE TITLE
What is the best way to query relationship statuses without hitting the 180 limit so quickly?

### ISSUE THREAD

**Issue by Disastercake** [linvi/tweetinvi#151]
I'm trying to create an app that checks the relationship status between all people the user is following and is following them so you can know where mutual relationships are or are not.  Currently what I do is I get a list of all those people, then I iterate through each of them and check their status.  However each relationship check takes up an entire limit, which means iterating through thousands or tens of thousands of people will inevitably take upwards to days of time.  I've seen some apps that seem to get the entire list without hitting the rate limit, so I'm wondering if there's some sort of special query that can be done to get multiple relationship statuses in one rate limit tick instead of 1 per person.

Any ideas?

Here's example code of what I do to check:

`relationship = await _loggedUser.GetRelationshipWithAsync(user);`

**Comment by linvi** [comment]
I think you are looking for :

``` c#
// 1 way relationship
var followers = User.GetFollowerIds(userSourceId);

// 2 way relationship
var friends = User.GetFriendIds(userSourceId);
```

It gets up to 5000 followers in 1 call.

**Comment by Disastercake** [comment]
Thanks linvi, but I'm actually trying to get the relationship to see if someone follows the user back.  How would I check that using var friends = User.GetFriendIds(userSourceId);?

**Comment by linvi** [comment]
Yes, friends means bidirectional relationship.

**Comment by linvi** [comment]
https://dev.twitter.com/rest/reference/get/friends/list

**Comment by linvi** [comment]
Wait I am wrong, but what you can do is get all the friends + all the followers and then do the intersect of the ids of the 2 lists.

Then you can get all the users intersecting from their ids with 

``` c#
var users = User.GetUsersFromIds();
```

**Comment by Disastercake** [comment]
Ah, that's a good idea!  That way it can just be done with 2 calls.  Thanks linvi, I'll check it out.

**Comment by Disastercake** [comment]
Just a heads up to anyone else wondering, just getting the IDs of friends and followers and cross referencing between them (as linvi suggested) does indeed work perfectly without draining the rate limit.

Thanks again, Linvi!
