### ISSUE TITLE
PublishMessageParameters doesn't expose Media Binaries and therefore allow Media to be published

### ISSUE THREAD

**Issue by simonjen1** [linvi/tweetinvi#154]
PublishMessageParameters doesn't expose Media Binaries and therefore allow Media to be published

**Comment by linvi** [comment]
I do not know which version of Tweetinvi you are using but I am sure that in 0.9.10.x and 0.9.11.x you can do the following :

``` c#
var t = Tweet.PublishTweet("salut", new PublishTweetOptionalParameters
{
    MediaBinaries = new List<byte[]>() // You binaries here
});
```

**Comment by simonjen1** [comment]
Version is 0.9.11.1 and it is present in PublishTweetOptionalParameters, but not in PublishMessageParameters. In twitter you can send a direct message with media, but via Tweetinvi you don't have the option to attach media files.

**Comment by linvi** [comment]
Ah sorry, I am pretty sure that it is still not possible to add media in Messages via the the Twitter API.

But I will confirm that with you.

**Comment by linvi** [comment]
You can see this discussion dating of less than a month where they state that this is not yet possible.

https://twittercommunity.com/t/videos-in-direct-messages/61593/3
