### ISSUE TITLE
CredentialsCreator.GetAuthorizationURL side effect

### ISSUE THREAD

**Issue by BelikovSergey** [linvi/tweetinvi#155]
Hi!

I modified your PIN authentification example from here:
https://github.com/linvi/tweetinvi/wiki/Authentication

```
                var appCredentials = new TwitterCredentials("my key", "my secret");

                ExceptionHandler.SwallowWebExceptions = false;

                // Go to the URL so that Twitter authenticates the user and gives him a PIN code
                var url = CredentialsCreator.GetAuthorizationURL(appCredentials);

                var url2 = CredentialsCreator.GetAuthorizationURL(appCredentials);                

                // This line is an example, on how to make the user go on the URL
                Process.Start(url);

                // Ask the user to enter the pin code given by Twitter
                var pinCode = Console.ReadLine();
```
Second call of GetAuthorizationURL throws:
Exception thrown: 'Tweetinvi.Core.Exceptions.TwitterException' in Tweetinvi.dll
Exception thrown: 'Tweetinvi.Core.Exceptions.TwitterException' in Tweetinvi.dll
Exception thrown: 'Tweetinvi.Core.Exceptions.TwitterException' in Tweetinvi.dll
Exception thrown: 'Tweetinvi.Core.Exceptions.TwitterException' in Tweetinvi.dll
--- Date : 16.03.2016 15:23:42
URL : https://api.twitter.com/oauth/request_token
Code : 401
Error documentation description : Unauthorized -  Authentication credentials were missing or incorrect.
Error message : https://api.twitter.com/oauth/request_token web request failed.
Invalid or expired token. (89)

It modifies TwitterCredentials object behind the scenes (setting AuthorizationKey and AuthorizationSecret). And if I try to use same TwitterCredentials object later, it fails. 
If I create new TwitterCredentials each time from key and secret, then
GetCredentialsFromVerifierCode fail, because it seems they need it.

To me, it looks very counterintuitive. Or I am using it wrong?
My app uses 2 twitter accounts (user and admin). Do I need to store separate AppCredentials for each of them because failed user login break AppCredentials and admin will not be able to use them?

**Comment by linvi** [comment]
Hello,

You are correct, Tweetinvi is behind the scenes updating the `AuthorizationKey` and `AuthorizationSecret`.

> To me, it looks very counterintuitive. Or I am using it wrong?

The reason for doing this was to simplify the authentication process. When I took this decision it looked good to me but I will consider finding a new solution for this problem.

I might end up returning an object containing 3 properties 

* URL
* AuthorizationKey
* AuthorizationSecret

In the meantime please use multiple ApplicationCredentials OR do the authentication processes one after another if this is possible in your context.

**Comment by BelikovSergey** [comment]
Thanks for the information. 
I am using separate credentials object right now and nullify them if user cancel or fail login. This seems to work.
But I think it would be better to make this more transparent in further versions. Return URL (or PIN) with AuthorizationKey and AuthorizationSecret, or, at least, set them to Credentials object only on successful login.

**Comment by linvi** [comment]
I have improved the mechanism for the `CredentialsCreator`. I hope you will like it.
