### ISSUE TITLE
Potential bugs in FilteredStream and TwitterTimeZoneGenerator

### ISSUE THREAD

**Issue by drgraduss** [linvi/tweetinvi#158]
I noticed a few places where you potentially loose data.

`FiltredStream`

Line 202:
```
var expandedURLs = tweet.Entities.Urls.Select(x => x.ExpandedURL);
expandedURLs.Union(tweet.Entities.Medias.Select(x => x.ExpandedURL));
```

Line 219:
```
var displayedURLs = tweet.Entities.Urls.Select(x => x.DisplayedURL);
displayedURLs.Union(tweet.Entities.Medias.Select(x => x.DisplayURL));
```

Media entities won't be processed.

`TwitterTimeZoneGenerator`

Line 479:
```
var description = initialDescription.Replace(" ", "_");
description.Replace("'", "_");
description.Replace("-", "_");
```

`'` and `-` charachters won't be replaced in the `description`.

Excuse me if that was intended.

**Comment by linvi** [comment]
I am pretty sure the `Union` ones are intended but I will verify.
I will also take a look into `TwitterTimeZoneGenerator` as soon as I have some free time.

Thanks for reporting this :)

**Comment by linvi** [comment]
Thank you for your comments, they were useful. And I will release a fix right away.
