### ISSUE TITLE
Data Binding noob question

### ISSUE THREAD

**Issue by FrancisBeland27** [linvi/tweetinvi#161]
Hi, 
I'm starting to code and want to use your library to try to code a homemade Twitter client. I'm trying to do the Data Binding in my XAML interface (Windows 10 Universal App) to show the timeline but I can't figure out how to do it. Can you just steer me in the good direction about what to put in the xmlns:data, the GridView ItemSource and the Data Template x:datatype that would be appreciated.

Thank you

Francis

**Comment by linvi** [comment]
This really is not a question about Tweetinvi but about MVVM.

What I think you should do is create a `TweetViewModel` that will act as a proxy for a `Tweetinvi.ITweet` interface.

When you have your `TweetViewModel` ready, you can create your view's `ViewModel` in which you will have an `ObservableCollection<TweetViewModel>` that your `GridView.ItemSource` will bind on.

Then you can simply write a Template for the `TweetViewModel` class.

I do not wish to elaborate more on the subject as I would have to give a lesson about MVVM and this is way beyond the scope of Tweetinvi which is not a UI specific library but a generic library to access Twitter.
