### ISSUE TITLE
Null returned when code runs on server

### ISSUE THREAD

**Issue by calindotgabriel** [linvi/tweetinvi#179]
Hello,

I got into this weird issue when trying to generate a **redirectUrl** on a remote server ( works well on localhost )

```
var manager = new TwitterManager(); //empty ctor
var redirectUrl = manager.GetRedirectURL();
```

```
public string GetRedirectURL()
{
    var appCreds = new ConsumerCredentials(TwitterAuthentification.APP_CONSUMER_KEY, TwitterAuthentification.APP_CONSUMER_SECRET);
    return CredentialsCreator.GetAuthorizationURL(appCreds, CALLBACK_URL);
}
```
###  **local**
![image](https://cloud.githubusercontent.com/assets/6276098/14138637/000d5da4-f677-11e5-9b5d-7c9e39112be3.png)
![image](https://cloud.githubusercontent.com/assets/6276098/14138644/14a98b2a-f677-11e5-8ba0-ec6546cff250.png)
### **live**
![image](https://cloud.githubusercontent.com/assets/6276098/14138666/3416e246-f677-11e5-958f-02ea777ac872.png)
![image](https://cloud.githubusercontent.com/assets/6276098/14138684/4514fb96-f677-11e5-853f-b5b8e355285f.png)

## Question
How can it work on local and not on remote ? Given that the same code runs on both machines. Is this a server configuration problem or a library related one ? An exception message would have been very helpful, I'm feeling lost and this problem persists for 2+ weeks.

Thank you

**Comment by linvi** [comment]
Please disable the automatic `ExceptionHandler` and let me know what the content of the exception is.
`TwitterException.ToString()` would be good to get most of the information needed.

More about [Exception Handling](https://github.com/linvi/tweetinvi/wiki/Exception-Handling#per-request-exception-handling).

**Comment by calindotgabriel** [comment]
Got this:
`https://api.twitter.com/oauth/request_token Code : -1 Error documentation description : Error message : The request was aborted: Could not create SSL/TLS secure channel`

**Comment by calindotgabriel** [comment]
Fixed. Thank you! :+1:

**Comment by linvi** [comment]
How did you fix it?

**Comment by calindotgabriel** [comment]
You should leave a note to enable security protocols before using your library:

```
    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls
        | SecurityProtocolType.Tls11
        | SecurityProtocolType.Tls12
        | SecurityProtocolType.Ssl3;
```

**Comment by linvi** [comment]
I will definitely add this. I did not have to do it for a while but it looks like it depends of the IIS config.

Thanks for sharing.

**Comment by linvi** [comment]
I leave the issue opened until I have added the documentation.

**Comment by calindotgabriel** [comment]
Thanks for your quick reply and commitment to open source. Cheers!

**Comment by linvi** [comment]
Here you go : https://github.com/linvi/tweetinvi/wiki/ASP.NET-consideration

Thanks for your help :)
