### ISSUE TITLE
Get URL of Tweet from stream

### ISSUE THREAD

**Issue by charlotte-murray** [linvi/tweetinvi#180]
Is there a way to get the url of a tweet when using the streaming API? I've looked through the ITweet class and can't see any way of retrieving this.

**Comment by linvi** [comment]
It has been a while that I thought about adding this property. This will be done in the next version of Tweetinvi.

In the meantime please do the following:

``` c#
var tweet = Tweet.GetTweet( ... );
var tweetURL = $"https://twitter.com/{tweet.CreatedBy.ScreenName}/status/{tweet.Id}";
```

Please leave this issue open so that I add it to the `ITweet` interface.

**Comment by charlotte-murray** [comment]
Thank you!
