### ISSUE TITLE
.net 4.6.1 support?

### ISSUE THREAD

**Issue by jrtagams** [linvi/tweetinvi#181]
Hi -

my app is perfectly working until windows update to .net 4.6.1 and not its not working anymore. getting this

Stream Stopped: 3/30/2016 12:44:30 AM

Value cannot be null.
Parameter name: source

   at AsyncExtensions.ReadLineAsync(TextReader source)
   at Tweetinvi.Streams.Helpers.StreamResultGenerator.<StartStreamAsync>d__7.Mov
eNext()

**Comment by jrtagams** [comment]
im on ver 0.9.3.4

**Comment by linvi** [comment]
Please try with the latest version. Tweetinvi 0.9.3.4 is 2 years old.
I cannot support all the versions of Tweetinvi.

**Comment by linvi** [comment]
Feel free to reopen the issue if needed but I am closing it for the moment.
