### ISSUE TITLE
AddFollow and AddLocation not working

### ISSUE THREAD

**Issue by dubielt1** [linvi/tweetinvi#186]
Hello linvi,

I have coded a super basic "hello world" equivalent with your library, that I wanted to "AddFollow" only my account. But when I send out a tweet from my account (using twitter), it does not get picked up by the filtered stream. But I did just test with other accounts and it worked, so this isn't a big deal.

AddLocation also seems to not be working, although I have no prior experience with this portion of the twitter API, and may misunderstand it. I plugged in coordinates that would represent a rectangle around the city of Houston, but no tweets come through. 

I know my credentials are correct, since I am "porting" a similar project from node. And the access tokens link to my account. Furthermore, AddTrack worked when I tested that. 

Let me know if you need me to post my code!

Versions: Tweetinvi: 0.9.11.2
.NET: 4.5.2
using C#

**Comment by linvi** [comment]
Thanks for all these details.
If you don't mind posting your code it would be great.

Thanks

**Comment by dubielt1** [comment]
Certainly! 

           
            class Example
            {
            static void Main(string[] args)
            {
            var credentials = new TwitterCredentials("cred", "info", "placed", "here");`
 
            var stream = Tweetinvi.Stream.CreateFilteredStream(credentials);
            stream.AddTweetLanguageFilter("en");
            stream.StallWarnings = true;
            stream.FilterLevel = StreamFilterLevel.None;

            //Stream Started
            stream.StreamStarted += (sender, re) =>
            {
                Console.WriteLine("Successfully started");
            };
            //Stream Stopped
            stream.StreamStopped += (sender, re) =>
            {
                Console.WriteLine("stopped");
                Console.WriteLine(re.Exception);
                Console.WriteLine(re.DisconnectMessage);
            };
            //Stream Disconnected
            stream.DisconnectMessageReceived += (sender, re) =>
            {
                Console.WriteLine("Disconnected");
                Console.WriteLine(re.DisconnectMessage);
            };
            //Stream Falling Behind
            stream.WarningFallingBehindDetected += (sender, re) =>
            {
                Console.WriteLine(re.WarningMessage);
            };
            //Matched Tweet
            stream.MatchingTweetReceived += (sender, re) =>
            {
                var tweetJson = re.Tweet;
                Console.Write(tweetJson.Text + " ");
                Console.WriteLine(tweetJson.CreatedBy);
            };

            stream.AddFollow(792826160); //My account
            //stream.AddLocation(new Coordinates(29.516988, -95.769393), new Coordinates(30.084227, -95.058028)); Houston
            Console.WriteLine("Starting Stream...");
            stream.StartStreamMatchingAllConditions();
        }
    }`

**Comment by linvi** [comment]
Have you tried removing the language filter?

**Comment by dubielt1** [comment]
My apologies for disappearing, removing the language filter did the trick!
