### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by rdahan156** [linvi/tweetinvi#189]
Is it possible to Add/Remove followers while the stream is active ? if not is it possible while it's Paused or it must be Stopped ?

**Comment by linvi** [comment]
It is not possible when it is paused. It needs to be stopped, because starting a stream after it has been stopped result in the `HttpRequest` to be run again. `Pause` just result in content to not be retrieved while the `HttpRequest` still runs.

**Comment by rdahan156** [comment]
Just as i thought so, thank you. ;]
