### ISSUE TITLE
TwitterAccessor 401 Authorize exception

### ISSUE THREAD

**Issue by EMartirosyan** [linvi/tweetinvi#193]
Tried to use TwitterAccessor, receive 401 Authorize exception with my query, 
Code from example works perfectly, but when I try to execute my query, receive 401.
```
            TwitterGate.Initialize();

			const string getHomeTimelineQuery = "https://api.twitter.com/1.1/statuses/home_timeline.json";

			// Execute Query can either return a json or a DTO interface
			var tweetsDTO = TwitterAccessor.ExecuteGETQuery<IEnumerable<ITweetDTO>>(getHomeTimelineQuery);

			var tweetsDTO1 = TwitterAccessor.ExecuteGETQuery<IEnumerable<ITweetDTO>>("https://api.twitter.com/1.1/statuses/lookup.json?id=20,432656548536401920");

```

So, TwitterAccessor.ExecuteGETQuery with getHomeTimelineQuery works just fine, but query with lookup request throws 401 Authorize exception. Request query is correct, this is an example query from Twitter REST API docs https://dev.twitter.com/rest/reference/get/statuses/lookup

**Comment by linvi** [comment]
The URL is not formatted by the TwitterAccessor. Therefore you will need to replace `,` by `%2C`.

``` c#
var tweetsDTO1 = TwitterAccessor.ExecuteGETQuery<IEnumerable<ITweetDTO>>("https://api.twitter.com/1.1/statuses/lookup.json?id=20%2C432656548536401920");
```

Please note that you can achieve the same result with the following code : 

``` c#
var tweets = Tweet.GetTweets(20, 432656548536401920);
```

**Comment by EMartirosyan** [comment]
Oh, great. Thank you for rapid answer. Sorry for my poor attention to docs.
