### ISSUE TITLE
Document Exceptions

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#195]

**Comment by linvi** [comment]
To reconsider as the work amount is quite big and 95% the endpoints will show the same `ArgumentNullException` + `ArgumentException`.

It might be worth giving this information directly in the documentation.

**Comment by linvi** [comment]
To reconsider for 1.0.

**Comment by linvi** [comment]
Documentation on github instead of code to explain the difference between `ArgumentException`, `ArgumentNullException`, `TwitterException`.

**Comment by linvi** [comment]
https://github.com/linvi/tweetinvi/wiki/Exception-Handling#per-request-exception-handling

``` c#
try
{
    var authenticatedUser = User.GetAuthenticatedUser(null, new GetAuthenticatedUserParameters());
}
catch (ArgumentException)
{
    // something went wrong with the arguments and request was not performed
}
catch (TwitterException)
{
    // information about fail on http request
}
```

**Comment by haseeb1431** [comment]
https://github.com/linvi/tweetinvi/wiki/Exception-Handling/_compare/d90193282cb4ac0d254ff2e9448563bb168821b6...0c117a81133d8da5e05094e9b96355a7f606c95f
