### ISSUE TITLE
Geocoordinates are LAT/LON always

### ISSUE THREAD

**Issue by maxima120** [linvi/tweetinvi#198]
LAT/LON : Its world wide accepted way to code geo-coordinates. Your params are set vice versa. I understand that if you change them now it will create havoc amongst users.. but its better now than later..

also Twitter provides loads of very nice features while calling for a geolocation. Not just box. I, and am sure the others, will appreciate if you could implement more. Like place name and radius.

Thank you

**Comment by linvi** [comment]
I have never been sure in which order to put them. Do you have any documention referencing this LAT/LON? As Tweetinvi is not yet released in 1.0 I will be happy to change the parameters order.

> also Twitter provides loads of very nice features while calling for a geolocation. Not just box. I, and am sure the others, will appreciate if you could implement more. Like place name and radius.

In which context do you think this is missing? All the endpoints do not provide access to radius or place name. Please let me know which endpoint you think are missing these parameters.

**Comment by linvi** [comment]
I have found [ISO 6709](https://en.wikipedia.org/wiki/ISO_6709), I will inverse the order.
Thanks for bringing this to me.

Please let me know regarding the second question.

**Comment by linvi** [comment]
@maxima120 please try to reply to the question I asked 6 days ago.

> also Twitter provides loads of very nice features while calling for a geolocation. Not just box. I, and am sure the others, will appreciate if you could implement more. Like place name and radius.

In which context do you think this is missing? All the endpoints do not provide access to radius or place name. Please let me know which endpoint you think are missing these parameters.

In the meantime I am closing the issue as it is fixed now.

**Comment by maxima120** [comment]
Sorry I had a holiday I'll have to write a proper response next week

**Comment by linvi** [comment]
Ok thanks

**Comment by maxima120** [comment]
Ok. I was referring to the : https://dev.twitter.com/rest/reference/get/geo/search
The accuracy can be radius to search with the coordinates as center (correct me if I am wrong). also granularity seems very useful only I am not sure whether it works with coordinates or with query only.. if it works with both - its very useful.. The query itself is useful thing - instead of digging internet for a city coords - i can just write "NY USA" and granularity "city"...

**Comment by linvi** [comment]
This has been implemented in version 0.9.12.0.

Here is an example (that returns no result) with all the parameters that you can use :

``` c#
var results = Geo.SearchGeo(new GeoSearchParameters()
{
    Query = "Tweetinvi Land",
    Accuracy = 5,
    Granularity = Granularity.City,
    IP = "74.125.19.104",
    Coordinates = new Coordinates(37.7821120598956, -122.400612831116),
    ContainedWithin = "5a110d312052166f",
    Attributes = { { "street_address", "795%20Folsom%20St" } },
    Callback = "myJsonPCallback",
    MaximumNumberOfResults = 100,
});
```

**Comment by linvi** [comment]
Also I realized that the accuracy could be in feet and therefore 0.9.13.0 will include the ability to choose the measure format.

#207

**Comment by JoshKeegan** [comment]
This one definately needs highlighting in the release notes :)

**Comment by JoshKeegan** [comment]
I agree. 
The only downside to switching to lat/lng is that if you ever needed to support other coordinate systems the convention then becomes to use x,y,(z) regardless of the coordinate system in use. However converting between coordinate systems is beyond the scope of Tweetinvi & I can't see Twitter adding support for anything other than WGS84 any time soon!
