### ISSUE TITLE
Assembly doesn't have a Strong Name

### ISSUE THREAD

**Issue by philjt** [linvi/tweetinvi#199]
The assembly doesn't appear to be strong named.
Looking at the previous issues it looks like they used to be strong named as you indicated they were in the signing issue.
Is the strong naming something that has been removed by mistake?

**Comment by linvi** [comment]
If the library is not using a Strong Name it is a mistake. Are you using version 0.9.12.1?

**Comment by philjt** [comment]
Yes, using the latest NGet package 0.9.12.1.

**Comment by linvi** [comment]
Ok I will check this but I cannot do this before tomorrow evening.

Thank you for reporting it.

**Comment by linvi** [comment]
Could you let me know which version you were using before updating to 0.9.12.1?

**Comment by philjt** [comment]
I only had a test project before that was using 0.9.11.? however that didn't require a strong name, so possible it didn't have one then either.

It was only when I was trying to use it in a new project that does have a strong name that I came across the issue.

**Comment by linvi** [comment]
Thanks a new version 0.9.12.2 will be released tonight.

**Comment by philjt** [comment]
Thanks :)

**Comment by linvi** [comment]
Version 0.9.12.2 has been published on nuget.

Thanks for reporting the problem.
