### ISSUE TITLE
Will TweetSearchParameters("filter") still pass the filter string to the Twitter API as-is?

### ISSUE THREAD

**Issue by charlotte-murray** [linvi/tweetinvi#209]
I'm wondering whether 

```
var searchParams = new TweetSearchParameters(filter)
{
    //blah blah blah
    //other parameters not in the filter string here
};
```
will give me different results to if I had just used 
`Search.SearchTweets(filter)`

I guess what I'm asking is if the search parameters object strips out things like 'from:xyz' from the filter string, or if it just adds extra parameters to the query eventually passed to twitter.

**Comment by charlotte-murray** [comment]
I don't feel like my question was very clear, so I'll give an example..
Will
```
            var searchParams = new TweetSearchParameters("from:NASA")
            {
                Filters = TweetSearchFilters.Images
            };
```
give me the same result as
`Search.SearchTweets("from:NASA filter:images")`?

**Comment by linvi** [comment]
That is correct.

**Comment by linvi** [comment]
Also please note that you can check the query executed by Tweetinvi using the `TweetinviEvents` :

``` c#
TweetinviEvents.QueryBeforeExecute += (sender, args) =>
{
    Console.WriteLine(args.QueryURL);
};
```

**Comment by charlotte-murray** [comment]
Brilliant, thank you! That's exactly what I needed :)

**Comment by linvi** [comment]
You are welcome. Have a great day!
