### ISSUE TITLE
stream.AddTrack not working for exact phrase using quotes

### ISSUE THREAD

**Issue by rarcherbythesea** [linvi/tweetinvi#215]
Hi, i have googled and looked around for an answer to this, i cant believe no one else is talking about it so clearly i am missing something simple here?!....i am creating a filtered stream and want to match on an exact phrase with the words in the precise same order. Supposedly i just put quotes around the words but when i do that i stop getting tweets so it clearly doesnt work. If i dont use quotes then i get tweets with the words in any order

stream.AddTrack("i need a holiday");   <---i get results with this
stream.AddTrack("\"i need a holiday\"");    <--i dont with this!

Can anyone please help me out?

**Comment by rarcherbythesea** [comment]
hmm I've been looking around the code and it looks like its not supported.

**Comment by linvi** [comment]
Twitter Public Stream API does not allow to do such thing. I think you will have to pay for their private data streaming service.

For the public streaming, you will be able to do what is specified in the documentation here :

https://dev.twitter.com/streaming/overview/request-parameters#track

**Comment by rarcherbythesea** [comment]
Thanks - i remember reading that now. You can do it with the 'Search' part of their REST API and i was confusing it with streaming sorry.

**Comment by linvi** [comment]
No worries, if you have any additional question please let me know :)
