### ISSUE TITLE
TwitterTimeOutException

### ISSUE THREAD

**Issue by gdiazderadaa** [linvi/tweetinvi#217]
Hi,
I'm trying to authenticate a user with the following code:

`var appCreds = Auth.SetApplicationOnlyCredentials(consumerKey , consumerUser , true);`

but keep getting the same error again and again: 

> "https://api.twitter.com/oauth2/token web request timed out."

I've been reading the documentation, going through the examples in the Cheatsheet.cs but can't figure out either what's the error caused by or how to solve it.

PS: Got the consumerKey and consumerUser from another application which is working properly.

**Comment by linvi** [comment]
Sorry for not replying earlier. I am well overbooked currently.
Have you been able to find a solution to your problem?

**Comment by gdiazderadaa** [comment]
Unfortunately not, still trying to figure out

**Comment by linvi** [comment]
Coud you disable the exception handling so that you can potentially have more information regarding your problem.

https://github.com/linvi/tweetinvi/wiki/Exception-Handling#per-request-exception-handling

In additionn, could you use Fiddler to see if the http request is executed correctly.

**Comment by gdiazderadaa** [comment]
Got this Tweetinvi.Credentials.TwitterAccessor.HandleQueryException:

> https://api.twitter.com/1.1/account/verify_credentials.json?skip_status=true&include_entities=true&include_email=true web request timed out.

and can't see any request going through

**Comment by linvi** [comment]
Ok, can you share your code as well as the type of application you are working on (W10, WPF, Console, ASP, iOS, Android, Mono, IOT...).

**Comment by linvi** [comment]
I need to have more code than the simple line that you sent in your first email. I need to find out if it is invoked from a ui event, a thread... So please give me the context of the function where your line is created.

**Comment by gdiazderadaa** [comment]
It's a webforms application, net 4.0. This is the hole code for the webform:

```
        protected override void Page_Load(object sender, EventArgs e)
        {
            if (!Page.IsPostBack)
            {
                string WidgetApiKey = "a tested consumer key";
                string WidgetApiSecret = "a tested consumer secret";


                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Ssl3;
                TweetinviConfig.ApplicationSettings.ProxyURL = "a tested proxy address";


                ExceptionHandler.SwallowWebExceptions = false;

                try
                {
                    var appCreds = Auth.SetApplicationOnlyCredentials(WidgetApiKey, WidgetApiSecret, true);

                }
                catch (TwitterException exception)
                {
                    Console.WriteLine(exception.TwitterDescription);
                }


                var user = Tweetinvi.User.GetAuthenticatedUser();
                if (user == null)
                {
                    var lastException = ExceptionHandler.GetLastException();
                    Console.WriteLine(lastException.TwitterDescription);
                }
            }
```

Obviously I can't share twitter account details so changed those strings to paste the snippet here

**Comment by linvi** [comment]
Yes that is alright. Before we even continue, have you tried the query without using the proxy?

**Comment by linvi** [comment]
One second, I do not understand your code.

You are setting up an `ApplicationOnly` credentials. and then you are trying to get a user.
Obviously the user will always be null.

**Comment by gdiazderadaa** [comment]
How can I get the timeline then?

**Comment by linvi** [comment]
Well you need have the user credentials, not the application only credentials.

``` c#
// Documentation : https://github.com/linvi/tweetinvi/wiki/Credentials
// Set up your credentials (https://apps.twitter.com)
Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

// Documentation : https://github.com/linvi/tweetinvi/wiki/Timelines
// Get the latest 40 tweets published on your timeline
var tweets = Timeline.GetHomeTimeline();
```

**Comment by gdiazderadaa** [comment]
Oh I see. The problem is we don't have either token or token secret so will need to find out another way. Thanks for your support

**Comment by linvi** [comment]
Well you can create a Token and Token secret directly from your Twitter application.

https://apps.twitter.com/app/<YOUR_APP_ID>/keys and then click on the button `Generate Access Token and Secret`.
