### ISSUE TITLE
Unable to post Tweet with images after updating to 0.9.12.2

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#221]
Hi Linvi,
I haven't been keeping up to date with Tweetinvi for a couple of months and have just gone to update from 0.9.10.2 to 0.9.12.2 before I pick up work on this application again.
Following the update (still in test environment, so issue isn't urgent) I cannot post a tweet with multiple images attached. Posting still works when no image, or only one image is attached.

Error Message:
```
2016-05-25 14:27:50 - libCommsManager.Helpers.TweetInviExceptionHelpers: Warning: Twitter Exception:
--- Date : 25/05/2016 14:27:46
URL : https://api.twitter.com/1.1/statuses/update.json?status=test%20message%20with%20images&media_ids=735462344843628544%2c735462352590512128%2c735462360312205312
Code : 401
Error documentation description : Unauthorized -  Authentication credentials were missing or incorrect.
Error message : https://api.twitter.com/1.1/statuses/update.json?status=test%20message%20with%20images&media_ids=735462344843628544%2c735462352590512128%2c735462360312205312 web request failed.
Could not authenticate you. (32)
```

As I said before, this isn't urgent since the production environment is still running 0.9.10.2 where this isn't happenning.
Cheers,
Josh

**Comment by linvi** [comment]
Hi Josh,

Thanks for the feedback. I will take a look on it as part of 0.9.13.0.

I can reproduce it and you need it before the release of 0.9.13.0 please let me know and I will consider creating a patch for 0.9.12.2.

**Comment by JoshKeegan** [comment]
Thanks Linvi, I can't see why waiting for 0.9.13.0 will cause me any problems here.

p.s. I like the outcome of all of the renaming. The authentication process in particular now just feels "cleaner".

**Comment by linvi** [comment]
> p.s. I like the outcome of all of the renaming. The authentication process in particular now just feels "cleaner".

Thanks, I really appreciate it :)

**Comment by linvi** [comment]
Just as very quick debrief, are the other endpoints working properly?
Are both images working properly if used as a tweet with a single image?
Which device/technology are you targeting? (wpf, asp, w10 uap...)

Thanks

**Comment by JoshKeegan** [comment]
I haven't finished testing all EPs yet. The system is split into several behind the scenes applications and a web frontend (MVC.NET 4). I've covered most of the web part (which I started with as I expected the authentication process to be the most likely to throw up issues).
So I'll let you know if I come accross any other issues, but unless there's anything else obvious it probably won't be until I sift through the logs tomorrow after leaving all the applications to run overnight.

All images work fine individually & can be sent together using Tweetinvi 0.9.10.2. They were from the Sample Pictures that come with Windows 7.

Tech: 
MVC.NET 4. 
.NET 4.5
VS 2015
Windows 7 x64 (but using .NET target platform Any CPU)

There's also a Console Application that tweets, so I'll let you know if it works in that when I check it.

**Comment by JoshKeegan** [comment]
Also happens in Console Applciation.

**Comment by linvi** [comment]
Thank you for all these information. Last thing can I have the few lines of code that actually upload the images and publish the tweet.

**Comment by JoshKeegan** [comment]
Sure. Here's the relevant snippet where `message` is a `string` and `files` is a `byte[][]`
```cs
//Generate any parameters to be included
PublishTweetOptionalParameters publishParams = new PublishTweetOptionalParameters();

//Add any files
if (files != null)
{
	publishParams.MediaBinaries = files.ToList();
}

//Publish the tweet
ITweet tweet = Tweet.PublishTweet(message, publishParams);
```

**Comment by linvi** [comment]
Perfect thanks. I will get back to you when I have time to investigate.

**Comment by linvi** [comment]
I don't remember having fixed it but I am able to reproduce the issue in 0.9.12.2 but 0.9.13.0 works properly.

So this will be available as part of 0.9.13.0.

**Comment by JoshKeegan** [comment]
What a pleasant surprise :)

I don't suppose there's an ETA for 0.9.13.0?

**Comment by linvi** [comment]
ETA should be around 3 weeks from today.

**Comment by JoshKeegan** [comment]
Thanks :)

**Comment by linvi** [comment]
Has the release solved the issue?

**Comment by JoshKeegan** [comment]
Yes, both this and #237 are fixed with the latest release, thanks!
