### ISSUE TITLE
Support new Extended Tweets (when released)

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#222]
Hi Linvi,
I usually wouldn't post a feature request ahead of it being released by Twitter, but this is a biggie!

Twitter announced yesterday their intention to change the way the 140 character limit is enforced (see https://twittercommunity.com/t/upcoming-changes-to-simplify-replies-and-links-in-tweets/67497 which links to relevant blog & api docs) and this will effectively allow for longer messages.

The default behaviour of the REST API will be to return Tweets in a compatibility mode (see https://dev.twitter.com/overview/api/upcoming-changes-to-tweets), and the Streaming API will always return data matching the current format, but with additional information for extended tweets. So it won't be a breaking change (at least until the Streaming API switch over), but any extended Tweets received in compatibility mode will have been truncated. Because of this reason, I consider supporting receiving the new extended Tweets via the REST API to be a very high priority, with the streaming API & sending them being lower but still very much desired.

They're being very vague with dates & are just saying this will happen in the next few months, but it'd be great if Tweetinvi were able to support this (mainly REST API) ASAP following its release, so that I (& others) store as few tweets as possible in their truncated form.

Any general thoughts ahead of this & what will the plan for Tweetinvi be here?
Cheers,
Josh

**Comment by linvi** [comment]
Tweetinvi will support these changes. I do not know how I will do this right now, but we will.

The problem is that I have never been able to reliably based Tweetinvi on the documentation. And the documentation is already too vague. 

> Links that are added to the Tweet in order to link to media attached via the Twitter app or website (aka “native media links”) do not count, but links typed or pasted into the compose box **may do so**.

I will speak with the Twitter team to see if I can have access to an early access of the API, but this might not be possible. 

In any case we will work on this very hard and make sure the transition will be the smoothest for all the developers.

**Comment by linvi** [comment]
There are a lot of things that I need to consider before going into more details so please hold on. I will get back here when I have a plan in mind and I have reviewed all the tasks that needs to be done.

**Comment by linvi** [comment]
All the tasks for the Extended Tweets story have been created. I have not yet decided what I am going to prioritize each of these.

**Comment by JoshKeegan** [comment]
Brilliant! Thanks for getting started breaking this down into sub-tasks already :) 

I appreciate the docs won't be precise enough to get an implementation of this right without having an actual API to test against, so I'm not expecting a Tweetinvi release ahead of Twitter actually making this live, but it's great to know you'll be working to make it happen as soon as possible.

Also, thanks for continuing to maintain this awesome library! Keeping with the beelding-edge of Twitter API functionality like this helps me a lot. Let me know if there are any of the tasks/issues where you need help.

**Comment by linvi** [comment]
Just wanted to say that 0.9.14.0 is going to be released tomorrow or the day after.
This will include a first draft to support the Extended Tweets based on the documentation.

I was not able to get all the information I need to make it perfect but based on the documentation, the developers should be able to publish extended tweet, retrieve them including from streams.

**Comment by JoshKeegan** [comment]
Great news :)

How will it switch to using Extended Tweets when they are launched?
Will the developer using the library have to set a variable for Tweetinvi to switch to use them?
I ask because I'd be concerned that if the switch was automatic, since the API it's working with isn't live yet and its docs are ambiguous, there's a good chance of it having a few issues & I wouldn't want that in production until it had been tested against the live API.

**Comment by linvi** [comment]
I have issued a documentation of release 0.9.14.0.
Let me know if this answer your questions.

https://github.com/linvi/tweetinvi/releases/tag/0.9.14.0

**Comment by JoshKeegan** [comment]
Sorry, I hadn't seen you'd released it, so hadn't read that.
Thanks!

**Comment by linvi** [comment]
I just issued it 15 minutes ago ;)
