### ISSUE TITLE
[Extended Tweets] Add ITweet.Content

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#228]
Might want to rename that. It should contain the content of the tweet. Meaning the part of the tweet from which the size of the tweet is calculated.

> A display text region, which remains a maximum of 140 characters in length.

https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

**Comment by linvi** [comment]
`Classic Tweet Compatibility Mode` vs `Classic Tweet Extended Mode`

![image](https://cloud.githubusercontent.com/assets/6107439/16022527/2a84fbd6-31b0-11e6-9b07-58d417429b19.png)

**Comment by linvi** [comment]
`Classic Tweet, compatibility mode, hidden text` vs `Classic Tweet, extended mode, hidden text`

![image](https://cloud.githubusercontent.com/assets/6107439/16022627/aef5afe6-31b0-11e6-8598-b90c85aa59e2.png)

![image](https://cloud.githubusercontent.com/assets/6107439/16022610/9a3e6200-31b0-11e6-972d-473e6e8e484e.png)

**Comment by linvi** [comment]
`Extended Tweet, compatibility mode` vs `Extended Tweet, compatibility mode (streaming, with extended_tweet)`

![image](https://cloud.githubusercontent.com/assets/6107439/16022839/c07ef474-31b1-11e6-8456-f875eb215f59.png)

New data :
``` json
 "extended_tweet": {
    "full_text": "@jeremycloud It's neat to have owls and raccoons around until you realize that raccoons will eat the eggs from the owl's nest https://t.co/Q0pkaU4ORH",
    "display_text_range": [
      13,
      125
    ],
    "entities": {
      "hashtags": [],
      "symbols": [],
      "user_mentions": [
        {
          "screen_name": "jeremycloud",
          "name": "/dev/cloud/jeremy",
          "id": 15062340,
          "id_str": "15062340",
          "indices": [
            0,
            12
          ]
        }
      ],
      "urls": [
        {
          "url": "https://t.co/Q0pkaU4ORH",
          "expanded_url": "https://twitter.com/jeremycloud/status/704059336788606976",
          "display_url": "twitter.com/jeremycloud/st…",
          "indices": [
            126,
            149
          ]
        }
      ]
    }
  },
```

**Comment by linvi** [comment]
Looking with a bit more details, it currently looks like the information are stored only for the tweet text and quoted tweet.

**Comment by linvi** [comment]
> Replies: @names that auto-populate at the start of a reply Tweet will not count towards the character limit (but new non-reply Tweets starting with a @mention will count, as will @mentions added explicitly by the user in the body of the Tweet). Additionally, new Tweets that begin with a username will no longer have to use the ”.@” convention in order to have those Tweets reach all of their followers.

**Comment by linvi** [comment]
https://twittercommunity.com/t/extended-tweet-and-suffix/68698

**Comment by haseeb1431** [comment]
I am not sure why are we working on regular expression to extract prefix and suffix. As per my understanding we will get the content (text) as display_text_range and anything outside the bounds will be metadata. Please correct me if I am missing something here. 

I am baffled that how can we support both mode, compatibility and extended mode at the same time. I think we can keep existing properties as is and add additional properties for extended tweets.  Once compatibility mode support is over, we can phase out the old properties. or what do you think, Ideas?

**Comment by linvi** [comment]
> I am not sure why are we working on regular expression to extract prefix and suffix. As per my understanding we will get the content (text) as display_text_range and anything outside the bounds will be metadata. Please correct me if I am missing something here.

We want to do that to have the ability to calculate the length of a Tweet before publishing it.

> I am baffled that how can we support both mode, compatibility and extended mode at the same time. I think we can keep existing properties as is and add additional properties for extended tweets. Once compatibility mode support is over, we can phase out the old properties. or what do you think, Ideas?

Yes, I want to add new properties, `FullText`, `Prefix` and `Suffix`.
The `Text` will actually be the value of the `Content` for extended Tweets. The reason for that is the fact that they clearly mentioned that what needs to be displayed is the `Content`.

**Comment by linvi** [comment]
https://twittercommunity.com/t/extended-tweet-and-space-character-before-suffix/69023
