### ISSUE TITLE
Search.SearchUsers

### ISSUE THREAD

**Issue by isghe** [linvi/tweetinvi#23]
Methods Search.SearchUsers, after first call, very often fails, with a System.NullReferenceException.

**Comment by linvi** [comment]
Hello would you please let me know which version of Tweetinvi are you using?
Have you downloaded it from nuget?

Would also please give me more information like a sample of your code and the stack trace.

**Comment by isghe** [comment]
The last got from NuGET: 0.9.9.6.

**Comment by linvi** [comment]
Can you share stack trace please?

This bug is probably related with https://tweetinvi.codeplex.com/workitem/2625
Can you make sure that your credentials are set up correctly.

**Comment by isghe** [comment]
I don't think it can be related to a credential problem, infact sometimes it is working good (always the first time), but very often not. Anyway for my application a found a workaround inside tweetinvi, working perfectly good:
https://github.com/linvi/tweetinvi/wiki/Custom-Queries#json-query
using the query:
https://dev.twitter.com/rest/reference/get/users/search

**Comment by linvi** [comment]
Thank you for letting me know this, but would you please share your stack trace (in the exception details). 
It will be very difficult for me to understand the bug without such information.

Please send it over!

**Comment by isghe** [comment]
I hope it can helps:
```
System.NullReferenceException verificata
  HResult=-2147467261
  Message=Riferimento a un oggetto non impostato su un'istanza di oggetto.
  Source=Tweetinvi
  StackTrace:
       in Tweetinvi.Search.SearchUsers(String query, Int32 maximumNumberOfResults, Int32 page)
       in XYZWebApplication.Controllers.SearchXYController.ResultTw(String name) in C:\Users\isghe\Documents\development\XYZ\XYZWeb\XYZWebApplication\Controllers\SearchXYController.cs:riga 124
  InnerException: 
```

**Comment by linvi** [comment]
Hello,

Would you please try using Tweetinvi with the Source Code of 0.9.10.0 available on github.
The fix might have solved your issue. It is a  bit difficult for me to identify the source of the bug as I cannot locate it with your stack trace.

With the source code, you will get more information when debugging that would greatly help me.

Thank you again for your time.
Cheers,
Linvi

**Comment by linvi** [comment]
Hello,

Please update to version 0.9.9.7 and this problem should be solved.

Cheers,
Linvi

**Comment by linvi** [comment]
Fixed by https://github.com/linvi/tweetinvi/commit/a952319ed4a463f385f7e7597413276ef1c5fa8b
