### ISSUE TITLE
Email Address Missing

### ISSUE THREAD

**Issue by SealSlicer** [linvi/tweetinvi#239]
After whitelisting our app, the verify_credentials call is supposed to return email addresses, however, I am not seeing it in the return object  Is this currently available? Do i need to cal la different method?

**Comment by linvi** [comment]
No you don't. `var authenticatedUser = User.GetAuthenticatedUser();` will return the email address.
But you need to make sure that you have regenerated your credentials.

Twitter will not return the email address until you have regenerated your application credentials and made the users generate new Access Tokens (for which they will accept to share their email).

**Comment by linvi** [comment]
Can I close this issue?
