### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by SealSlicer** [linvi/tweetinvi#240]
I notice that the only way errors are handled is by returning null. Is this because the twitter API only returns null errors? Is there some way I can configure the library to give errors when errors happen?

**Comment by linvi** [comment]
Yes you can. Please follow the wiki : https://github.com/linvi/tweetinvi/wiki/Exception-Handling#per-request-exception-handling.

You will need to call : `ExceptionHandler.SwallowWebExceptions = false;` and use `try/catch`.

**Comment by linvi** [comment]
Can I close this issue?
