### ISSUE TITLE
Fix certificates warnings

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#241]

**Comment by linvi** [comment]
Can be reproduced with Visual Studio 2015.
Perform a rebuild all.

In the `Error List...` tab there are 3 warnings regarding the certificates.

* A certificate with thumbprint '50F4C2160675C0D3785F70AFDFED0D65F2A54B79' that is specified in the project cannot be found in the certificate store. Please specify a valid thumbprint in the project file.	
* Cannot import the key file 'Examplinvi.UniversalApp_TemporaryKey.pfx'. The key file may be password protected. To correct this, try to import the certificate manually into the current user’s personal certificate store.
* For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.		
	
If needed, lets create a new certificate.

**Comment by haseeb1431** [comment]
I didn't have any warnings my machine while building the solution with VS 2015.

May be I didn't have Universal apps installed, let me install that and load UniversalApp project and try it again.

**Comment by linvi** [comment]
All the errors are on the Universal App project.

**Comment by haseeb1431** [comment]
http://stackoverflow.com/questions/37600908/parameter-targetplatformversion-cannot-be-null-visual-studio-2015
