### ISSUE TITLE
Issue with uploading videos.

### ISSUE THREAD

**Issue by Stev3nT** [linvi/tweetinvi#246]
Hello,

I have an issue with uploading videos, the image uploading works like a charm. The videos I tested with are between 1 and 3 MB in size and have a duration of 5 seconds, formatted as MP4. From what I can tell, after the attempt to make the upload, the object that the method returns has the property HasBeenUploaded set to false.

You can check you the code that is generating this issue, I hope you can recreate it. I might me doing it wrong, I started using this library about 2 hours ago. https://gist.github.com/Stev3nT/ba7bcbe90daa3fb0bc31276ad8dd8957

Thank you for your time and your great work. :P

**Comment by linvi** [comment]
Could you share the video you are trying to upload?

**Comment by Stev3nT** [comment]
https://drive.google.com/open?id=0B0Mtnx2s_e4NOVBPZHF6bDVOTUU

There you go, I hope that helps.

**Comment by linvi** [comment]
Thank you, please let me know the version you are using too.

**Comment by linvi** [comment]
I can reproduce the problem with your video. Could you please try this one and let me know if you still have the same problem.

https://github.com/linvi/tweetinvi.issues/blob/master/sample_video.mp4

**Comment by linvi** [comment]
I have never found a perfect explanation for video format (even though it is [documented](https://dev.twitter.com/rest/media/uploading-media#videorecs)).

Below find the difference between the 2 videos.

![image](https://cloud.githubusercontent.com/assets/6107439/15799367/1f768d5a-2a52-11e6-9c11-a5088aec8d96.png)

**Comment by Stev3nT** [comment]
Thank you for the quick response. I am using the latest version available at NuGet. I currently cannot try the video that you have provided because I'm not at work and I don't have access to the source/servers. I will do some testing this Monday and I will inform you of the results. Thanks once again!

**Comment by linvi** [comment]
Ok, I will not be available for help until the 09/06 but feel free to ask any question, @haseeb1431 might be able to help you.

**Comment by Stev3nT** [comment]
@haseeb1431 On a side note, is there a way to validate the stored user credentials? The access token? If so, is there a API call limit to that validation?

**Comment by Stev3nT** [comment]
@haseeb1431 @linvi It works with the video that you have provided. I guess that ones I tested are too "good" for Twitter. This will be interesting to work around. Thanks for the assistance. :+1:

**Comment by linvi** [comment]
You are welcome, if you find any good solution to check videos that are compatible with Twitter please let me know.

I will try to find a good solution at some point but it won't be in a nearby future.
