### ISSUE TITLE
SearchResultType make it as optional search parameter based on twitter 

### ISSUE THREAD

**Issue by stenly311** [linvi/tweetinvi#248]
Hi, 

based on the twitter documentation in here
[https://dev.twitter.com/rest/reference/get/search/tweets]

**result_type** search parameter is optional, so could the library behave similar way? SearchResultType enum type does not have any equivalent of "empty" option.

Thanks.

**Comment by JoshKeegan** [comment]
I don't remember it being necessary to specify the SearchType when performing a search.
If it isn't set, I wouldn't expect it to pass any result_type parameter to Twitter, hence acting as the default.

Linvi will know for sure, but I think he's currently away so you'll have to look in the src if you need a definite answer. 

Also worth noting that unless Twitter changes their default behaviour, it's the Mixed option they use by default.

**Comment by haseeb1431** [comment]
Agree with @JoshKeegan  here. Default result type is Mixed which is in line with the twitter default as per the docs.

Do you have any other related query or are we good to close this?

**Comment by linvi** [comment]
@stenly311 

As you mentioned the `result_type` parameter is optional. In Tweetinvi it is defaulted as Mixed (which is the same as not specifying the parameter).

By doing so Tweetinvi is providing more information about what Twitter is actually doing. So I do not think I will change this behaviour apart if you can think about something I did not.

**Comment by stenly311** [comment]
@linvi all you said is correct. Although I don't think is good idea for a 3rd party library to have a power set a default value for any parameter.

The last call should be made by service itself every time. Regardless if you logic picks up the same value or not.

**Comment by linvi** [comment]
That is a valid point of view.
