### ISSUE TITLE
Want to know if posting to Twitter is success or failed after Tweet.PublishTweetWithImage 

### ISSUE THREAD

**Issue by vslnvapparao** [linvi/tweetinvi#249]
I want to know if posting to Twitter is success or failed after Tweet.PublishTweetWithImage 
after this method call, I want to display error (if posting to Twitter is failed for some reason)

### Reduced support between the 05/06/2016 and the 09/06/2016.

As I might have limited to none access between those dates, please be patient, I will come back!

**Comment by JoshKeegan** [comment]
By default Tweetinvi hides exceptions from you, but you can fetch them with
```cs
ExceptionHandler.GetExceptions()
```
So, if you call that after posting your message you'll be able to see if anything went wrong.

If there are exceptions, you'll want to clear Tweetinvi's record of them after after dealing with them with:
```cs
ExceptionHandler.ClearLoggedExceptions();
```

If you'd prefer the more standard behaviour of throwing exceptions (so you can try/catch), you can disable Tweetinvi's exception swallower. I can't remember the call for this off of the top of my head but I think it's in the wiki.

**Comment by haseeb1431** [comment]
Kindly refer to following and let me know if you still have any queries. 
[https://github.com/linvi/tweetinvi/wiki/Exception-Handling](https://github.com/linvi/tweetinvi/wiki/Exception-Handling)

**Comment by linvi** [comment]
As mentioned above you can check if a `publish` has been a success by checking whether the result is null or not.

If you want to have more information about what exception caused the publish to fail you will have to follow @JoshKeegan and @haseeb1431 explanation.

I am closing the issue but feel free to reopen it if you have any further question.
