### ISSUE TITLE
Unable to create tweet with more than one image, pasted code works fine with 1 image

### ISSUE THREAD

**Issue by Driscollart** [linvi/tweetinvi#250]
if (tweetingEnabled)
            {
                var unsentPosts = bindingSourceTweets.List.Cast<vmScheduledTwitterPost>().Where(x => x.Sent == false);
                bool itemUpdated = false;

                var settings = tweetController.GetSettings();

                var creds = new TwitterCredentials(autotweet.Models.AutotweetCredentials.ConsumerKey, autotweet.Models.AutotweetCredentials.ConsumerSecret, settings.Single(x => x.SettingName == "AccessToken").SettingValue, settings.Single(x => x.SettingName == "AccessSecret").SettingValue);

                foreach (vmScheduledTwitterPost post in unsentPosts)
                {
                    if (post.SendOn.ToString("MM/dd/yyyy hh:mm tt") == DateTime.Now.ToString("MM/dd/yyyy hh:mm tt") || (post.SendOn <= DateTime.Now && post.AllowCatchup))
                    {
                        var postDataItem = tweetController.twitterItemRepo.GetScheduledTwitterPostItems().SingleOrDefault(x => x.ScheduledTwitterPostItemId == post.ScheduledTwitterPostItemId);
                        var postPhotos = this.currentPhotos.Where(x => x.ScheduledTwitterPostItemId == postDataItem.ScheduledTwitterPostItemId).ToList(); // tweetController.twitterItemRepo.GetScheduledTwitterPhotoItems(post.ScheduledTwitterPostItemId);
                        try
                        {
                            //     Auth.SetUserCredentials(autotweet.Models.AutotweetCredentials.ConsumerKey, autotweet.Models.AutotweetCredentials.ConsumerSecret, settings.Single(x => x.SettingName == "AccessToken").SettingValue, settings.Single(x => x.SettingName == "AccessSecret").SettingValue);

                            if (post.Data1 == null && post.Data2 == null && post.Data3 == null)
                            {
                                var tweet = Auth.ExecuteOperationWithCredentials(creds, () =>
                                {
                                    return Tweet.PublishTweet(post.Text);
                                });

                                if (tweet == null)
                                {
                                    var lastProblem = ExceptionHandler.GetLastException();
                                    postDataItem.SendException = lastProblem.ToString();
                                }
                                else
                                {
                                    postDataItem.GeneratedTweetId = tweet.IdStr;
                                    postDataItem.Sent = true;
                                    postDataItem.SentOn = DateTime.Now;
                                }

                            }
                            else
                            {
                                var mediaItems = new List<IMedia>();

                                var tweet = Auth.ExecuteOperationWithCredentials(creds, () =>
                                {
                                    if (post.Data1 != null)
                                    {
                                        var mediaItem = Upload.UploadImage(post.Data1);
                                        mediaItems.Add(mediaItem);
                                    }
                                    if (post.Data2 != null)
                                    {
                                        var mediaItem = Upload.UploadImage(post.Data2);
                                        mediaItems.Add(mediaItem);
                                    }
                                    if (post.Data3 != null)
                                    {
                                        var mediaItem = Upload.UploadImage(post.Data3);
                                        mediaItems.Add(mediaItem);
                                    }

                                    var currentUser = User.GetAuthenticatedUser();

                                    return Tweet.PublishTweet(post.Text, new PublishTweetOptionalParameters
                                   {
                                       Medias = mediaItems
                                   });

                                });

                                if (tweet == null)
                                {
                                    var lastProblem = ExceptionHandler.GetLastException();
                                    postDataItem.SendException = lastProblem.ToString();
                                }
                                else
                                {
                                    postDataItem.GeneratedTweetId = tweet.IdStr;
                                    postDataItem.Sent = true;
                                    postDataItem.SentOn = DateTime.Now;
                                }
                            }

                            itemUpdated = true;
                        }
                        catch (Exception exc)
                        {
                            postDataItem.SendException = exc.ToString();
                            tweetController.LogError(exc);
                            //throw exc;
                        }
                        finally
                        {
                            tweetController.twitterItemRepo.UpdateScheduledTwitterPostItem(postDataItem, postPhotos);
                        }
                    }
                }
                if (itemUpdated)
                {
                    this.BindGrid();
                }

            }

**Comment by haseeb1431** [comment]
Can you share that which version you are using?

**Comment by JoshKeegan** [comment]
If this is an up to date version, see #221

**Comment by Driscollart** [comment]
Thank you for your prompt reply! I'm using 0.9.12.2, from the nuget package. Sounds like you will have a fix soon, per #221 ?

**Comment by JoshKeegan** [comment]
It's fixed in 0.9.13.0.
If you are only using it for testing/some sort of dev environment you could try https://github.com/linvi/tweetinvi/files/290048/Tweetinvi.0.9.13.0.-.Binaries.zip which is an alpha build, but won't be up to date with src as it's about a week old.

If you're using it in a production environment or otherwise need stability, I'd roll back to 0.9.12.2 which doesn't have this problem & then upgrade once 0.9.13.0 is released.

**Comment by Driscollart** [comment]
The alpha build fixed it fine. I also had the issue in 0.9.12.2, though.
