### ISSUE TITLE
How to fetch older tweets.

### ISSUE THREAD

**Issue by Prabh2308** [linvi/tweetinvi#251]
I have been trying to fetch older tweets. Some 3 months older, but i am unable to get them. Can you tell how to get them?

**Comment by JoshKeegan** [comment]
If you're meaning as results from a search, you can't go back that far. I think the limit is 7 days.
If you need older results than that then there are companies with paid for APIs that will be able to return older results (e.g. GNIP).

Other endpoints aren't limited to the past 7 days, let me know if this is what you need help with but I expect it's the search limtation you're running in to.

**Comment by Prabh2308** [comment]
@JoshKeegan Sir, i am searching tweets on basis of specific hashtags. The code works fine if i search till 29th of last month. but when i go beyond that date. It shows nothing.

**Comment by JoshKeegan** [comment]
Interesting to hear that you're managing to get results from that long ago. I checked in the Twitter API docs & the limit is definitely defined as 7 days (https://dev.twitter.com/rest/public/search). Although I know their implementation of this isn't exact as in the forums they always say "approximately 7 days" or similar, so they're probably removing old data in chunks.

I'd be careful relying on getting results from more than 7 days ago as even it's working now, there's no guarantee it will in a few days/weeks/months.

**Comment by haseeb1431** [comment]
Agree with @JoshKeegan here. I am not sure what your requirements are but if you really need to access data, either you can use GNIP (paid endpoint) or storing the historical data is also an option. Fetch fresh tweets, store them in database or whatsoever, then you can use that historical data as per your needs. Beware of the fact that this will represent the fraction of the actual data.

**Comment by linvi** [comment]
Just an additional comment regarding my personal experience with search.

Twitter officially support access to the 7 days history. But in reality this often varies between 7 and 14 days.

I have not been able to get back to 30 days for quite a while but I know this has been possible in the past. 

As suggested by @JoshKeegan you will have to use GNIP to access old tweets, or as suggested by @haseeb1431 start fresh and use the `SampleStream` or `FilteredStream` to store the tweets in your own database. Then you will be able to query it. Be careful of the database scaling as 1% of total tweets represents 5 millions tweets per day.
