### ISSUE TITLE
URL Authentication

### ISSUE THREAD

**Issue by adityosnrost** [linvi/tweetinvi#260]
Hi,

I would like to learn how to get credentials with Redirect URL authentication. Is there any full sample or guide to use it ? I have not mastered MVC yet, So I use basic knowledge to develop WPF apps.

Thanks

**Comment by linvi** [comment]
Please read the documentation for redirect url [here](https://github.com/linvi/tweetinvi/wiki/Authentication#url-redirect-authentication).

Also you can find a real MVC example if you download the source code from github. There is a project [Examplinvi.Web](https://github.com/linvi/tweetinvi/tree/master/Examplinvi.Web). '

And finally you can find a the example [HomeController](https://github.com/linvi/tweetinvi/blob/master/Examplinvi.Web/Controllers/HomeController.cs).

**Comment by linvi** [comment]
Can I close this?

**Comment by adityosnrost** [comment]
Hi,

Sorry for my late reply, thanks for your help. I'm working on it.
