### ISSUE TITLE
Tweetinvi.Core.Interfaces.ITweet MediaType property not enumerated

### ISSUE THREAD

**Issue by nielsvdc** [linvi/tweetinvi#261]
Could you please enumerate the MediaType for a Tweet instead of being a string. Then it easier to distinguish the different types.

**Comment by linvi** [comment]
I initially wanted to do that. The problem is that I have not found any proper specification helping on the subject. 

In order to ensure that new media types (or some that I don't know about) can be used by the developers of Tweetinvi, I decided to put this as a string.

If you find any good documentation regarding the subject please share it with me and I will consider migrate this as an enum.

**Comment by haseeb1431** [comment]
Are we talking about `Media` property here or 
https://github.com/linvi/tweetinvi/blob/master/Tweetinvi.Core/Interfaces/ITweet.cs#L191 ?

**Comment by nielsvdc** [comment]
No, the MediaType property
https://github.com/linvi/tweetinvi/blob/master/Tweetinvi.Core/Interfaces/Models/Entities/IMediaEntity.cs#L50

Maybe it's a good choose. As I read in the document here https://dev.twitter.com/overview/api/entities-in-twitter-objects only "photo" is used for now and is returned as a string. Or you need to keep track of changes and add enumeration when a change happens.

**Comment by linvi** [comment]
> As I read in the document here https://dev.twitter.com/overview/api/entities-in-twitter-objects only "photo" is used for now and is returned as a string.

This is what is explained in the documentation but this is not the case in practice. If you upload a video, the media type will be `video`. 

> Or you need to keep track of changes and add enumeration when a change happens.

I already track all the changes made to the documentation. The biggest problem is that most of the changes are not updated in the documentation.

**Comment by nielsvdc** [comment]
I see your point. Issue may be closed.

**Comment by linvi** [comment]
I will contact the Twitter team regarding the subject before doing that ;)

Don't forget to star Tweetinvi! And feel free to contact us at any time, we will be happy to help.

**Comment by linvi** [comment]
https://twittercommunity.com/t/media-type-enumeration/68618

**Comment by linvi** [comment]
Add media types according to : https://twittercommunity.com/t/media-category-values/64781/7
