### ISSUE TITLE
How to get original tweets only(No Retweets)

### ISSUE THREAD

**Issue by Prabh2308** [linvi/tweetinvi#262]
Hello, i was making an application for fetching tweets using a specific hashtag. i want to add a filter that my search gives me only original tweets and not retweets. Any suggestions how can i achieve that.

**Comment by linvi** [comment]
Just check the value on the tweet returned by the stream.

``` c#
var fs = Stream.CreateFilteredStream();

fs.AddTrack("#your_hashtag");

fs.MatchingTweetReceived += (sender, args) =>
{
    if (!args.Tweet.IsRetweet)
    {
        // Do your logic
    }
};

fs.StartStreamMatchingAllConditions();
```

**Comment by Prabh2308** [comment]
sir i found this on net, will this work?
searchParameter.TweetSearchFilter = Tweetinvi.Core.Interfaces.Models.Parameters.TweetSearchFilter.OriginalTweetsOnly;

**Comment by linvi** [comment]
Oh sorry, I thought you were using `FilteredStream`.

Yes, you want to use the `TweetSearchFilter`.

**Comment by Prabh2308** [comment]
Thanks sir. And what should i use (TweetSearchFilter) to get tweets containing images or videos only.

**Comment by linvi** [comment]
Here is what you want in the latest version of Tweetinvi:

``` c#
var tweets = Search.SearchTweets(new TweetSearchParameters("your_search")
{
    Filters = TweetSearchFilters.Images | TweetSearchFilters.Videos,
    TweetSearchType = TweetSearchType.OriginalTweetsOnly
});
```

**Comment by Prabh2308** [comment]
thanks sir. Kindly provide solution to issue #264

**Comment by Prabh2308** [comment]
Sir it is generating error. This is the code i am using:
      
        var searchParameter = Search.GenerateTweetSearchParameter(hashtag);
        searchParameter.Lang = Language.English;
        searchParameter.SearchType = SearchResultType.Popular;
        searchParameter.MaximumNumberOfResults = 100000;

**Comment by linvi** [comment]
What do you mean by it is generating an error?

I will need the stacktrace and all the details you can provide so that I can help you.

**Comment by linvi** [comment]
Have you upgraded to 0.9.13.0?

**Comment by Prabh2308** [comment]
Sorry Sir, This code is working fine. i wanted to know where and what should i add to the following code to get only tweets containing videos???

    var searchParameter = Search.GenerateTweetSearchParameter(hashtag);
    searchParameter.Lang = Language.English;
    searchParameter.SearchType = SearchResultType.Popular;
    searchParameter.MaximumNumberOfResults = 100000;

**Comment by linvi** [comment]
``` c#
var searchParameter = Search.GenerateTweetSearchParameter(hashtag);
searchParameter.Lang = Language.English;
searchParameter.SearchType = SearchResultType.Popular;
searchParameter.MaximumNumberOfResults = 100000;
searchParameter.Filters = TweetSearchFilters.Images | TweetSearchFilters.Videos;
searchParameter.TweetSearchType = TweetSearchType.OriginalTweetsOnly;
```

**Comment by Prabh2308** [comment]
![capture1](https://cloud.githubusercontent.com/assets/19783982/16043325/bb6791ca-325c-11e6-8547-b3c472835a09.PNG)

This hing is creating the error. Any solution or alternative?

**Comment by linvi** [comment]
You are not using the latest version of Tweetinvi.
Please upgrade, their has been loads of improvements, bug fixes and changes.

One of which is the fact that `Search.GenerateTweetSearchParameter(hashtag)` no longer exist and has been replaced by `new TweetSearchParameters(hashtag)`.

**Comment by linvi** [comment]
Also there should be only 1 `|`.

**Comment by Prabh2308** [comment]
![capture1](https://cloud.githubusercontent.com/assets/19783982/16044089/9f841736-3260-11e6-8c82-f5de3432daea.PNG)
sir i have updated version now. still it is showing error

**Comment by linvi** [comment]
I see there is an error but you need to tell me what the error actually say before I can help you.

**Comment by Prabh2308** [comment]
![1](https://cloud.githubusercontent.com/assets/19783982/16044423/04efcc7c-3262-11e6-8f9e-fd084818621f.png)

this is the error.

**Comment by linvi** [comment]
You need to have a `using Tweetinvi.Core.Parameters` in your using statements.

**Comment by linvi** [comment]
Did it fixed it?

**Comment by Prabh2308** [comment]
Yes sir it worked. Just 2 more things. firstly as i have checked all my library reference are also from older versions. from where can i download the latest version of references.

secondly if i want to get the place(location) from where the tweet was sent. how can i get that?

**Comment by linvi** [comment]
You should use nuget to ensure that your library are up to date.
From visual studio you can do the following :

`Tools > Nuget Package Manager > Package Manager Console`.

In the console, if you type `Install-Package TweetinviAPI`. The latest version of Tweetinvi will automatically been downloaded, its depencies will be downloaded too and installed.

Later on, you can use the `Update-Package` command to automatically upgrade to later versions.

> secondly if i want to get the place(location) from where the tweet was sent. how can i get that?

All the properties are not listed in the documentation but please use intellisense to get this kind of information. The answer is `tweet.Coordinates`. Note that this can be `null`.

**Comment by Prabh2308** [comment]
tweet.coordinates will return coordinates in numeric value. I want to get the name of the place?

**Comment by linvi** [comment]
You can also check the `tweet.Place`.
