### ISSUE TITLE
Want to get tweet of one date only?(Specific Date)

### ISSUE THREAD

**Issue by Prabh2308** [linvi/tweetinvi#264]
I was trying to fetch tweets of one specific date. I am trying this code but every time it return no output(no tweet).

searchParameter.Since = new DateTime(2016, 06, 06, 00, 00, 01);
searchParameter.Until = new DateTime(2016, 06, 06, 23, 59, 59);

**Comment by linvi** [comment]
Unfortunately twitter does not provide this type of precision and you will not be able to search for only one day.

What I would suggest is that you do the following :

``` c#
var date = new DateTime(2016, 06, 13);

var tweets = Search.SearchTweets(new TweetSearchParameters("hello")
{
    Since = date.AddDays(-1),
    Until = date,
    SearchType = SearchResultType.Recent
}).Where(x => x.CreatedAt.DayOfYear == date.DayOfYear).ToArray();
```

**Comment by Prabh2308** [comment]
k thanks sir.

**Comment by linvi** [comment]
Don't forget to star tweetinvi github repository ;)

**Comment by Prabh2308** [comment]
Done Sir :)

**Comment by fightlikeagirl** [comment]
hello i need the  tweets that tweeted last day with a keyword. But this code turns me a null . can you help me please ?
