### ISSUE TITLE
want to update tweet on the base of status id

### ISSUE THREAD

**Issue by meddy138** [linvi/tweetinvi#266]
i have tweet in my database. if i want to update his no. of retweets and no. favorites how can i update that tweet?
is there any mechanism to update specific tweet?

**Comment by linvi** [comment]
This is not related to Tweetinvi is it? Or do you want to get a mechanism from Tweetinvi to track a Tweet?

**Comment by meddy138** [comment]
it is related tweet invi 
for example i have been fetched tweet on the base of some hashtag and stored the results in the database. after one day when i check the same tweet on twitter his no. of retweets are different from database tweet.
so how to update specific tweet base on his status id ?

**Comment by linvi** [comment]
``` c#
// For single tweet
var tweetId = 42; // From database
var refreshedTweet = Tweet.GetTweet(tweetId);

// For multiple tweets
var tweetIds = new long[] {42, 43};
var refreshedTweets = Tweet.GetTweets(tweetIds);
```
