### ISSUE TITLE
can we get Tweet on the base of tweet id like we get tweet on the base of screenName?

### ISSUE THREAD

**Issue by meddy138** [linvi/tweetinvi#267]

**Comment by linvi** [comment]
Is it the same question as #266?

**Comment by meddy138** [comment]
no its different for example if we have tweet id like 738621958863093760 
how i am able to get tweet which contain that status id?

**Comment by linvi** [comment]
Same answer as #266 

``` c#
// For single tweet
var tweet = Tweet.GetTweet(738621958863093760 );
```

**Comment by meddy138** [comment]
ok sir thank you
how can i get all followers of a specific user by using 
var usr = Tweetinvi.User.GetUserFromScreenName(ScreenName);
 var followers = usr.GetFollowers();

**Comment by linvi** [comment]
Tweetinvi cursor queries are not yet easy to use for complex cases related to RateLimits. I would suggest you read the following wiki to get ALL the followers.

https://github.com/linvi/tweetinvi/wiki/Get-All-Followers-Code

**Comment by meddy138** [comment]
sir how to get screenname of those users who retweets the specific tweet?

**Comment by linvi** [comment]
`tweet.CreatedBy.ScreenName`

**Comment by linvi** [comment]
Tweetinvi has been designed to be simple to navigate via intellisense. Please try to use it!

``` c#
var tweetId = 42;
var retweeterIds = Tweet.GetRetweetersIds(tweetId);
var retweeters = User.GetUsersFromIds(retweeterIds);
```

**Comment by meddy138** [comment]
sir how can i get tweet video?

**Comment by linvi** [comment]
Before asking could you please try to use intellisense?

**Comment by meddy138** [comment]
sir actually i am using tweetinvi from past three months and i have write down all questions and i am looking for a plateform where i can get answer and i found you thanks to you.

**Comment by meddy138** [comment]
var tweet = Tweet.GetTweet(tweetId);
var medias = tweet.Entities.Medias[0];
but it will return  image.

**Comment by linvi** [comment]
It will return images or videos. You will have to check the `tweet.MediaType` or `tweet.VideoDetails` properties.

**Comment by meddy138** [comment]
how to get replies against specific tweet?

**Comment by linvi** [comment]
If you could open such questions on stackoverflow it would be great.
It will give some answer easy to access to people looking for the same questions as you do.

**Comment by meddy138** [comment]
i want to get get retweet count and favcount of specific tweet on the base of Tweet id but it will return "Null reference" or "Object reference not set to an instance of an object."                    
long id = Convert.ToInt64(TweetId);
                    var refreshedTweet = Tweet.GetTweet(id);

                    var retweetCount = refreshedTweet.RetweetCount.ToString();
                    var favcount = refreshedTweet.FavouriteCount.ToString();

**Comment by linvi** [comment]
> how to get replies against specific tweet?

Stackoverflow

> i want to get get retweet count and favcount of specific tweet on the base of Tweet id but it will return "Null reference" or "Object reference not set to an instance of an object."

I will need more information regarding your `NullReferenceException`. I think that the `refreshedTweet` received is `null`. This happen when the request to Twitter has failed.
