### ISSUE TITLE
StartStreamMatchingAnyConditionAsync & AddFollow

### ISSUE THREAD

**Issue by jcmag** [linvi/tweetinvi#269]
Hi,
Could I call AddFollow after the stream is started (using StartStreamMatchingAnyConditionAsync)? Or is it mandatory to call AddFollow before?

**Comment by linvi** [comment]
You must call it when the stream is stopped. If the stream is running you can stop it using `stream.Stop()`.

**Comment by jcmag** [comment]
ok!
Are Start/Stop methods fast? My concern is that I could miss tweets when my stream is stopped...

**Comment by linvi** [comment]
You will miss tweets during this stop. The only thing you could do is run 2 streams (you will need multiple credentials). Stop 1 stream, when the one with the new filters has started, stop the other one.

**Comment by linvi** [comment]
Also be aware that we have an unresolved issue that freeze the UI if you try to start/stop a same stream x times in a very short amount of time. I would recommend to wait 3 seconds before start/stop a stream.

**Comment by jcmag** [comment]
I have no UI (using that from a Windows service); will I have some issues?

**Comment by linvi** [comment]
I am not sure I understand. Didn't you said that the library was not working for Windows Phone?
But to answer your question, Tweetinvi can be used in Windows Service.

**Comment by jcmag** [comment]
I didn't speak about windows phone...
You said you recommend to wait 3 seconds before start/stop a stream; but from a windows service, I don't need to do that,do I?

**Comment by linvi** [comment]
Sorry about windows phone, it was my mistake. I got confused with another issue.

> You said you recommend to wait 3 seconds before start/stop a stream; but from a windows service, I don't need to do that,do I?

I suggest that you wait 3 seconds between invoking a `StopStream` and invoking a `StartStream` regardless of the type of project you use (including windows service).

``` c#
stream.StopStream();
stream.AddTrack("my_track");
Thread.Sleep(3000);
stream.StartStream();
```

**Comment by jcmag** [comment]
ok, will do that
thanks!
