### ISSUE TITLE
New Version of Tweetinvi Creating some issues

### ISSUE THREAD

**Issue by meddy138** [linvi/tweetinvi#270]
before update am using tweetinvi 0.9.07 and it works fine when i update it with latest version it will generate several error which are in snapshots

![untitled](https://cloud.githubusercontent.com/assets/19947885/16108710/3cced91e-33be-11e6-8f8f-66633c53cc14.png)
![untitled1](https://cloud.githubusercontent.com/assets/19947885/16108778/b2b156a2-33be-11e6-957c-6868dee4b071.png)

**Comment by linvi** [comment]
I am not against helping on github. But please try to use stackoverflow with the tweetinvi tag.

**Comment by meddy138** [comment]
sir kindly tell me the problem its version issue

**Comment by linvi** [comment]
I will but on stackoverflow. Github is supposed to deal with issues not questions regarding how to make your code work.

I take time to write a documentation (and a lot of time). Most of the questions you ask are on the wiki.
Even though all your questions have an answer, I will be happy to help on http://stackoverflow.com.

The reason for using stackoverflow over github is the fact that people trying to solve this kind of problem go on stackoverflow. So they will search there.and find the appropriate answer.

**Comment by meddy138** [comment]
Okk sure

**Comment by linvi** [comment]
Answered here https://stackoverflow.com/questions/37853281/new-version-of-tweetinvi-creating-some-issues :D

**Comment by linvi** [comment]
Feel free to ask any other question over there and I will reply.
Though if you encounter a BUG, please post on github ;)
