### ISSUE TITLE
Publishing a tweet fails with default publish optional parameters

### ISSUE THREAD

**Issue by Stev3nT** [linvi/tweetinvi#272]
Hello, it's me again.

I notice an odd behavior that I'm not sure if it comes from twitter or it's just not handled in the library. Basically, when you share a tweet with a message and an instance of `PublishTweetOptionalParameters`, if that instance has the default values, like:

`var tweet = Twitter.Tweet.PublishTweet(message, new PublishTweetOptionalParameters());`

The publishing of that tweet fails. I noticed this when I had the following setup: I have a couple of ads and each ad can have video or image medias. When sharing one of those ads, I first create an instance of `PublishTweetOptionalParameters` (or options for short). Then I run a check if that ad has any medias, if it does, it tries to upload the first 3 medias, ordered by upload number. If all 3 attempts fail, the options remain with its default values, aka the `Medias`, `MediaIds` and `MediaBinaries` remain empty, which causes Twitter to go nuts and the publication of the given tweet fails. 

Because I do my credential validation based on the success of that twitter publish (because the credential validation endpoint has a limit of 15 requests, I can do only 15 tweet publishes for 15 minutes, which is not acceptable), it caused be some problems. It's not a big deal, I already worked it around, I just wanted to let you know. 

https://gist.github.com/Stev3nT/6ff4a807314bb35eadac72473bce0e16
Here is the code that has it worked around, if you are interested. It also fixes my previous issue with uploading videos. I just return null instead of an instance of PublishTweetOptionalParameters when there are no medias uploaded. Since PublishTweet() has a second optional parameter that by default is null, this works.

Cheers!

**Comment by linvi** [comment]
Thanks, we will take a look at it in the shortest delays.
Can you confirm that you are using version 0.9.13.0?

**Comment by Stev3nT** [comment]
I am using 0.9.12, I will update now.

**Comment by Stev3nT** [comment]
After some extended testing, that might not actually be the problem. Don't look into it just yet, I will inform you later today or tomorrow what the actual issue was. It might be because a tweet fails to publish if there's already a tweet with the same message down the timeline. Sorry that I opened an issue before being sure of the cause.

**Comment by Stev3nT** [comment]
Is there a way to catch what exactly is the problem when uploading a tweet? Because for now, it just returns null, which isn't very informative.

**Comment by linvi** [comment]
If it can help please note that you cannot republish the exact same text before a certain delay (I have no documented time). 

> Is there a way to catch what exactly is the problem when uploading a tweet? Because for now, it just returns null, which isn't very informative.

This is the default behaviour of Tweetinvi. It returns null for developers who do not care about why it failed, just that it failed.

If you want more information you will have to read the [error handling documentation](https://github.com/linvi/tweetinvi/wiki/Exception-Handling).

**Comment by Stev3nT** [comment]
I totally missed that, thank you and sorry once again. I'm starting to have nightmares with this Twitter implementation thingy.

**Comment by Stev3nT** [comment]
PS. Is `ExceptionHandler.GetLastException();` thread proof? If an exception occurs on another thread at the same time, will I get that exception or the last exception on the currently invoking thread?

**Comment by linvi** [comment]
No, the default `ExceptionHandler` was more supposed to work out as a way to `LogExceptions`.
If you want proper exception handling I would use [per request exception handling](https://github.com/linvi/tweetinvi/wiki/Exception-Handling#per-request-exception-handling).

This set of tools is old and will be improved in later versions, but I need to find time to improve this.

**Comment by Stev3nT** [comment]
Hello again. This is not really a bug, just a result from my negligence. Sorry once again and keep doing the awesome work you do!
