### ISSUE TITLE
Where is the changelog with API changes?

### ISSUE THREAD

**Issue by Disastercake** [linvi/tweetinvi#273]
I'm a little new to GitHub, so I'm not sure exactly where to check for the change logs.  I'm having a problem with upgrading to the latest version using NuGet, and now there seems to be some major API changes since I last updated.  Most notably:

using Tweetinvi.Core.Credentials is missing.
RateLimitTrackerOptions is missing.
RateLimit.RateLimitTrackerOption is missing.

However the documentation in the Wiki hasn't changed.  Is this a problem with NuGet or were these API changes made?

**Comment by linvi** [comment]
Hello thank you for the feedback. Could you please point out where the documentation has not been updated so that I fix this tonight,

In the meantime you can find the changelog in Code -> Releases.
Or here : https://github.com/linvi/tweetinvi/releases.

Tweetinvi is changing a lot before version 1.0 which is coming like winter.
I want version 1.0 to be as good as possible.

**Comment by Disastercake** [comment]
Great to hear that 1.0 is coming soon.  Thank you very much for your dedication to your craft.  I really appreciate it as I'm primarily a C# dev. =)

I believe this is either a bit outdated now or is just not clear enough what namespace to use:
https://github.com/linvi/tweetinvi/wiki/Credentials

I'm having trouble finding where the TwitterCredentials and ILoggedUser class is now.
Also where RateLimit.RateLimitTrackerOption and RateLimitTrackerOptions

Any hints on where those are at now?

**Comment by linvi** [comment]
I will try to improve the namespaces at some point.

* `RateLimitTrackerOption` *->* `Tweetinvi.Core.RateLimitTrackerMode`
* `ILoggedUser` *->* `Tweetinvi.Core.Interfaces.IAuthenticatedUser`
* `TwitterCredentials` *->* `Tweetinvi.Core.Authentication.TwitterCredentials`

**Comment by Disastercake** [comment]
Thank you very much!  Those work now.

Also I'm missing CredentialsCreator.  Do you know where that one went?

**Comment by linvi** [comment]
It does no longer exist, you need to use the `new TwitterCredentials(...)` keyword.

**Comment by Disastercake** [comment]
I was previously using it like this:
`private void GetAuthURL()
        {
            // Create a new set of credentials for the application
            var appCredentials = new TwitterCredentials(CONSUMER_KEY, CONSUMER_SECRET);

            // Go to the URL so that Twitter authenticates the user and gives him a PIN code
            var url = CredentialsCreator.GetAuthorizationURL(appCredentials);

            // This line is an example, on how to make the user go on the URL
            System.Diagnostics.Process.Start(url);
        }`

How would I get the GetAuthorizationURL now?

**Comment by linvi** [comment]
Ah sorry, you want to use the `AuthFlow`. https://github.com/linvi/tweetinvi/wiki/Authentication

**Comment by linvi** [comment]
BTW don't forget to star the library!
