### ISSUE TITLE
Tweetinvi Get All Tweets from a Screenname

### ISSUE THREAD

**Issue by anjana-sharma** [linvi/tweetinvi#275]
I'm trying to use Tweetinvi to retrieve all the tweets made by a particular screen name.

I've tried GetUserTimeLine (see below) but it shows tweets from all the people I follow instead of just mine.
                   var User = Tweetinvi.User.GetUserFromScreenName(ScreenName);
                    var timelineTweets = User .GetUserTimeline();
its provides me only 40 tweets. is their any authentication issue?

**Comment by haseeb1431** [comment]
Have you tried the visual studio intellisense for GetUserTimeline method? Signature of method is as follows
IEnumerable<ITweet> GetUserTimeline(int maximumNumberOfTweets = 40);

user.GetUserTimeline does have an optional parameter for number of tweets which let you specify the count of tweets you want.
