### ISSUE TITLE
Issue with publishing tweets with 0.9.13 C#/.net

### ISSUE THREAD

**Issue by andrewbanks17** [linvi/tweetinvi#276]
I am a bit new to using the library,  so I might be misinformed. I used the nuget project manager to get tweetinvi (v 0.9.13) and when I attempt to publish tweets by using:

Auth.ApplicationCredentials = new TwitterCredentials(cred1,cred2,cred3,cred4);
var myTweet = Tweet.PublishTweet("Apples");

Nothing is tweeted and myTweet stays null. No errors were thrown either. However, when I publish tweets with:

var creds = new TwitterCredentials(cred1,cred2,cred3,cred4);
var tweet = Auth.ExecuteOperationWithCredentials(creds, () =>
            {
                return Tweet.PublishTweet("Apples");
            });

A tweet is published and a value was returned. From my understanding, both of these statements should do the same thing but for some reason they are not.

**Comment by linvi** [comment]
Please use `Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");` instead of `Auth.ApplicationCredentials = new TwitterCredentials(cred1,cred2,cred3,cred4);`
