### ISSUE TITLE
Ensure Tweetinvi is compatible with .NET Core

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#283]

**Comment by linvi** [comment]
https://github.com/aspnet/Home/issues/1381

**Comment by linvi** [comment]
We will have to wait for rtm as RC tends to change a lot.

**Comment by linvi** [comment]
We will investigate the matter as part of versions > 1.0.

I understand the interest and challenge of using .NETCore but Tweetinvi being already compatible to a very wide range of devices, version 1.0 will not be compatible with it.

Thank you for the information though :)

**Comment by KirilRusev** [comment]
Do you have a roadmap for porting to .Net Core 1.0?

**Comment by linvi** [comment]
Not yet. Tweetinvi is already compatible to a very wide range of devices and I need to look how (if it is even possible) to use PCL with .NET Core.

If not I will have to create an entirely new version of the library targeting .NET Core.
So I will need to do more investigation before giving you a proper answer.

This investigation will be done after version 1.0 (which will go out in the coming days).

**Comment by linvi** [comment]
https://github.com/dotnet/core/issues/206

**Comment by ReimuHakurei** [comment]
I needed to use this library on .NET Core on Linux so I made a giant hackjob that does, in fact, seem to function.

https://github.com/ReimuHakurei/tweetinvi

Here's a binary .nupkg of said giant hackjob:

https://github.com/ReimuHakurei/tweetinvi/releases/download/dnxcore50/TweetinviAPI.9.9.9-pre.nupkg

My testing is limited to its' ability to send tweets, and connect to User Streams (which is all I actually need for my application), so YMMV.

**Comment by linvi** [comment]
Thank you for the info. I will take a look at your code.

**Comment by ReimuHakurei** [comment]
From my observations, it seems like it'll require a separate branch for .NET Core applications.

A bunch of those BCL NuGet packages seem completely broken in .NET Core, and using the PCL targets results in a bunch of issues with HTTP clients. I had to make it target .NET Standard 1.5 as one of the main changes to make it work.

**Comment by linvi** [comment]
Would you mind if I open a private discussion with you on gitter so that we discuss the matter?

**Comment by linvi** [comment]
I just created a public channel here for people to discuss this outside of github issues. 

https://gitter.im/linvi/tweetinvi-netcore

**Comment by linvi** [comment]
* Verify that Class Library with Target being ASP.NET Core 1.0 do not actually work with proper ASP.NET Core project
* Use @ReimuHakurei project as a basis to create our own version for .NET Core library.

**Comment by haseeb1431** [comment]
https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries

**Comment by haseeb1431** [comment]
Will be completed with #334

**Comment by linvi** [comment]
Release 1.1 with nuget now supports .NET CORE
