### ISSUE TITLE
AuthFlow.InitAuthentication returning null

### ISSUE THREAD

**Issue by jwokelly** [linvi/tweetinvi#285]
AuthFlow.InitAuthentication is constantly returning null for me. I checked the Consumer Key and Consumer Secret are correct and I am using the Examplinvi.Web sample. 

`var appCreds = new ConsumerCredentials(MyCredentials.CONSUMER_KEY, MyCredentials.CONSUMER_SECRET);
            var redirectURL = "http://" + Request.Url.Authority + "/Home/ValidateTwitterAuth";
            var authenticationContext = AuthFlow.InitAuthentication(appCreds, redirectURL); //returns null`

**Comment by linvi** [comment]
Please check the following and let me know if you still encounter the same issue :

* https://github.com/linvi/tweetinvi/wiki/ASP.NET-consideration
* https://github.com/linvi/tweetinvi/wiki/401-Errors

**Comment by prajjwaldimri** [comment]
I am also getting null response from AuthFlow.CreateCredentialsFromVerifierCode today. I have not change the code any bit and it was working previously. Can you take a look, here are the screenshots:
![2016-07-04](https://cloud.githubusercontent.com/assets/9110203/16558230/c8b66b9e-4201-11e6-9345-b59d5558d66b.png)
![2016-07-04 1](https://cloud.githubusercontent.com/assets/9110203/16558231/c8d22d20-4201-11e6-8faf-91c90b1f7976.png)

You can see the code [here](https://github.com/prajjwaldimri/Friend-App/blob/master/Windows/FriendProject/BeFriendUWP/Views/TwitterAuthenticator.xaml.cs)

Thanks!

**Comment by linvi** [comment]
Have you checked the DateTime on your machine? Have you read the 2 links that I sent?

**Comment by prajjwaldimri** [comment]
Yup, checked everything. It even broke on the release version of my app and also the code was just working two days ago. I even downgraded to 0.9.12 but still the same exception.

**Comment by linvi** [comment]
I will have to take a look tonight. Please visit gitter.im to communicate privately, I might need to have access to your credentials.

**Comment by prajjwaldimri** [comment]
Alright

**Comment by linvi** [comment]
@jwokelly have you fixed the problem? Please keep me up to date. I just want to be sure you do not encounter any problem.

Thanks

**Comment by jak65** [comment]
i have save problem too.
