### ISSUE TITLE
GetAuthenticatedUser failing throws error: web request failed. 

### ISSUE THREAD

**Issue by vslnvapparao** [linvi/tweetinvi#286]
Hi, 
I am using the below code snippet.

 ```
           var userCreds = AuthFlow.CreateCredentialsFromVerifierCode(verifierCode, authKeyFromCookie, authSecretFromCookie, key, secret);
            var user = Tweetinvi.User.GetAuthenticatedUser(userCreds);
            Auth.SetCredentials(userCreds);
            var t = Tweet.PublishTweetWithImage(twitterMessage, GetImage(uri));
```

And I am able to publish messages with images successfully. But, When trying to publish many images continuously, I get an this error. There are no specific steps to reproduce this issue.

The stack trace:   

> Error:https://api.twitter.com/1.1/account/verify_credentials.json?skip_status=true&include_entities=true&include_email=true web request failed. Trace: at Tweetinvi.Credentials.TwitterAccessor.HandleQueryException(TwitterException ex) at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method) at Tweetinvi.Credentials.TwitterAccessor.ExecuteGETQuery[T](String query, JsonConverter[] converters) at Tweetinvi.Credentials.CredentialsAccessor.ExecuteOperationWithCredentials[T](ITwitterCredentials credentials, Func`1 operation) at Tweetinvi.Factories.User.UserFactory.GetAuthenticatedUser(ITwitterCredentials credentials, IGetAuthenticatedUserParameters parameters) at Thomson.Financial.Thomlets.Economics.Web.PublishTwitter.PublishImageToTwitter() at Thomson.Financial.Thomlets.Economics.Web.PublishTwitter.Page_Load(Object sender, EventArgs e)

Captured the URL parameters as below when the request failed:
authorization_id=xxxxxxx
&oauth_token=xxxxxxxx
&oauth_verifier=xxxxxxx

And 
twitterAuthorizationKey : xxxxxxx
AuthorizationSecret : xxxxxx

Can you help in resolving this issue, please?

**Comment by linvi** [comment]
Hello,

First of all, never share publicly your credentials.
Concerning your problem, it is related with the fact that you keep authenticating new users and this is actually Rate limited.

What you need to do is to store the crendentials information somewhere and then reuse them.
Do not process the entire authentication everytime you want to post something. Or at least not with the same account.

**Comment by linvi** [comment]
Any success?

**Comment by vslnvapparao** [comment]
Linvi - 
I am getting the userCredentials using - `AuthFlow.CreateCredentialsFromVerifierCode`

I call this method - `Auth.SetCredentials(userCreds);`  before  `Tweet.PublishTweetWithImage`

You suggest me to avoid this code snippet, right? `Tweetinvi.User.GetAuthenticatedUser(userCreds)`

And this issue is not seen in my local box, this issue was found by our QA in Beta environment. So, I will make the fix ready and get it tested on Beta environment in the next cycle.

**Comment by linvi** [comment]
* `var userCreds = AuthFlow.CreateCredentialsFromVerifierCode(verifierCode, authKeyFromCookie, authSecretFromCookie, key, secret);` is limited but I do not remember by how much.
* `var user = Tweetinvi.User.GetAuthenticatedUser(userCreds);` is limited to 15 requests every 15 minutes.
* `Auth.SetCredentials(userCreds);` is not limited
* `var t = Tweet.PublishTweetWithImage(twitterMessage, GetImage(uri));` is limited to 50 every 30 minutes (but it can vary and Twitter can accept more).

**Comment by vslnvapparao** [comment]
Thanks Linvi, I quickly tested in my local box, and its working as expected. You may close this issue. 

One question regarding `these numbers` you mentioned (limited to xx every yy minutes). 
Is it specific to our hosting server from where we make request to Twitter (so that I can multiply `these numbers` by 3 if I have 3 servers on load balancer)? 
Or Is it specific to the twitter user (in which we are publishing) In that case I can multiply `these numbers` by number of users? 
Or I don't know other possibilities?

**Comment by linvi** [comment]
It is specific based on the Access Token (user credentials) you provide.

I would personally suggest that you store locally in a static variable. If your project will use multiple servers you can store this information in a database and update it every 15 minutes for example.

Tweetinvi `UserDTO` are now serializable : https://github.com/linvi/tweetinvi/wiki/Serialization-and-Deserialization.

Please note that Twitter monitors any abuses of RateLimits and can decide to block your application if you do..
