### ISSUE TITLE
Limitation of string length while using Tweet.PublishTweetWithImage(message, image)

### ISSUE THREAD

**Issue by vslnvapparao** [linvi/tweetinvi#289]
Hi,
While we are posting messages in Twitter, Twitter will count 24 characters for each URL in the message. 
For example: I am able to tweeet the below message (that has more than 360 characters) on Twitter:

> This is for testing -  https://datastreamprod.int.thomsonreuters.com/dscharting/gateway.aspx?guid=a3c4d3a8-857c-43c9-812d-cf1e85b510bc&owner=ZREU029&action=REFRESH - And this is for testing again to see the limitation of chars-  https://datastreamprod.int.thomsonreuters.com/dscharting/gateway.aspx?guid=a3c4d3a8-857c-43c9-812d-cf1e85b510bc&owner=ZREU029&action=REFRESH - 

But, when I tried the above message using Tweet.PublishTweetWithImage(message, image), it did not publish to Twitter. 

Is there a limitation of sending the number of characters? 
Is there any logic/pattern to allow big URLs in the messages?

**Comment by linvi** [comment]
Publishing a tweet with a media is not the same than publishing a simple tweet.
Tweetinvi give the ability to calculate the length of a tweet text.

``` c#
 var text = "This is for testing - https://datastreamprod.int.thomsonreuters.com/dscharting/gateway.aspx?guid=a3c4d3a8-857c-43c9-812d-cf1e85b510bc&owner=ZREU029&action=REFRESH - And this is for testing again to see the limitation of chars- https://datastreamprod.int.thomsonreuters.com/dscharting/gateway.aspx?guid=a3c4d3a8-857c-43c9-812d-cf1e85b510bc&owner=ZREU029&action=REFRESH";
            
var lengthWithoutMedia = text.TweetLength(); // = 133
var lengthWithMedia = text.TweetLength(true); // = 157
```

As per the result, without the media, the tweet can be published. With a media it cant as its length is 157.

**Comment by vslnvapparao** [comment]
Thanks Linvi, 
I understand this function - `var lengthWithoutMedia = text.TweetLength(); // = 133`
Its explained in a great detail in your test cases too.

I am puzzled to understand `var lengthWithMedia = text.TweetLength(true); // = 157`
As the original string has more than 300 characters. I am very much interested to understand how this overloaded function is returning 157? I did not find any test cases for this overloaded function. Can you please explain me about this function?

**Comment by linvi** [comment]
Sure,

Twitter consider that adding a media to a tweet increase the text size by 24.
`TweetLength(bool publishWithMedia)` with the parameter will therefore add this 24 characters and `133 + 24 = 157`.

**Comment by vslnvapparao** [comment]
Is there any javascript (client side) function equivalent to this - ` text.TweetLength(); ` ?
