### ISSUE TITLE
Streaming stopped working

### ISSUE THREAD

**Issue by jcmag** [linvi/tweetinvi#291]
Hi,
I'm using a FilteredStream with more than 900 twitter accounts, and it stopped working yesterday.
Now my MatchingTweetReceived event handler is never called... but I don't have any exceptions (SwallowWebExceptions is set to false).
How can I find what is the problem?

**Comment by linvi** [comment]
Have you verified that the stream is actually running?
Are you listening to the `Stream.StreamStopped` event to check if it is actually invoked.

**Comment by jcmag** [comment]
Thanks! Got an exception in StreamStopped!
[error details](https://stream.twitter.com/1.1/statuses/filter.json?&follow=1666038950%2C1536852836%2C21637092%2C14192174%2C18639640%2C1942851%2C2178230389%2C3351754565%2C346380319%2C2483382086%2C301413580%2C451649471%2C28775291%2C16712223%2C54990262%2C4896452093%2C3356531254%2C326071859%2C415861762%2C3996742041%2C2617422301%2C8527162%2C16403943%2C39534303%2C3384714484%2C438745608%2C707621282779680768%2C17961861%2C948878156%2C2583803186%2C1361348358%2C729634880988942338%2C12412792%2C549180727%2C58468214%2C2512601228%2C260451506%2)

"Malformed escape pair at index 516", do you know what it means?

**Comment by jcmag** [comment]
Strange, now it is working again...

**Comment by linvi** [comment]
Hmmm, has the number of people you follow been reduced?

**Comment by jcmag** [comment]
I did some tests by reducing the number of accounts to follow: 100 (did not work), 10 (dnw), 1 (it worked), then I reverted my code back to before, and it works again with 925 accounts now...

**Comment by linvi** [comment]
I know that there is a limit to the number of accounts you can add because C# HttpRequest length is limited. But I am pretty sure you should be able to ask for up to 1000 without any problem.

Please report back to me if you still encounter this problem. 

Looking at the URL that you sent the problem is obvious and it seems that the query sent is not complete, as you can see it finishes with `%2` which is the beginning of `%2C` which is the separator between the ids.

Please make sure you report here so that I can fix any problem.

**Comment by jcmag** [comment]
My stream stopped working unexpectedly today, with this error in StreamStopped:

> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

What could be the reason?

**Comment by linvi** [comment]
It is an expected issue that should be handled by Tweetinvi and not throw. A `StreamStopped` event should be raised. If bot this is a bug.
