### ISSUE TITLE
IsRetweet / Retweeted propetries are not working

### ISSUE THREAD

**Issue by avnerho** [linvi/tweetinvi#293]
when I follow a user using IFiltertedStream and the action is called after the user re-tweets a tweet, the information that I get in ITweet interface does not indicate that the tweet was retweeted: IsRetweet and Retweeted properties are false and Retweets List is null.

**Comment by linvi** [comment]
I am aware of this. Unfortunately the public stream api does not provide the `IsRetweet` information. The data returned by Twitter are the data that Tweetinvi gives you.

If you want to know if the current user has effectively retweeted this tweet, you will have to authenticate with this user.
