### ISSUE TITLE
can we get DOB of person sending the tweet?

### ISSUE THREAD

**Issue by Prabh2308** [linvi/tweetinvi#294]
can we get DOB of the person?

**Comment by linvi** [comment]
No you cannot. It is not provided by Twitter.

**Comment by haseeb1431** [comment]
@Prabh2308 We can get only that data from API which is available via web user interface normally. You cannot  view other people's DOB on twitter so same holds true here as well.

**Comment by haseeb1431** [comment]
@Prabh2308 We can get only that data from API which is available via web user interface normally. You cannot  view other people's DOB on twitter.com so same holds true here as well.
