### ISSUE TITLE
Quote Tweet missing space before URI

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#295]
Hi Linvi,
When sending a quote tweet, Tweetinvi appears to not be including a space before the URI of the tweet to be quoted.
i.e. If your message is "blah 123", you'd expect it to post "blah 123 https://twitter.com/{ScreenName}/status/{Status ID}", which Twitter will then display as a quote tweet, but instead you get "blah 123https://twitter.com/{ScreenName}/status/{Status ID}" which won't get recognised as a quote tweet.

Easy to workaround by just adding a space before passing the text to Tweetinvi, but it'd be nice if Tweetinvi did this for you.
Cheers,
Josh

**Comment by linvi** [comment]
Thanks Josh, this has been fixed and will be available in next release.

**Comment by JoshKeegan** [comment]
Thanks for making the change :)

I don't think this new behaviour would be right either though, as if the text that was supplied to Tweetinvi ended in whitespace, another space will still be added. 
I think the correct behaviour would be to trim whitespace from the end of the text (could do the beginning as well if easier since Twitter will trim it, but not necessary) and then always add a space before the status URI.

**Comment by linvi** [comment]
I usually don't like to change the content too much but I guess this is a fair fix. What I will do is remove 1 space character if it is located at the very end of the tweet. If there are 2 spaces at the end of the tweet, then 2 spaces will be sent.

**Comment by JoshKeegan** [comment]
That would solve my issue (current behaviour would cause two spaces since I add one & then Tweetinvi would add one too) so I'm happy with that.

I do still think trimming all whitespace from the right would be better though, as it mimics Twitter's behaviour when posting a Quote Tweet. Doesn't bother me that much though ;)
Thanks,
Josh

**Comment by linvi** [comment]
I learn everyday! I never realized Twitter was doing that. I will therefore clear the trailing spaces.

Thanks for the info :)
