### ISSUE TITLE
How do you get all the favorites of a user?

### ISSUE THREAD

**Issue by Disastercake** [linvi/tweetinvi#296]
I'm trying to get all of the favorites a user has made, however it is only returning 20 of them.  My expectation was that using GetFavoritesAsync with the Int32.MaxValue would return all of the favorites, even if it took some time from metering to do so.  Here's the code I have that will only return 20 tweets (even though the user has 10's of thousands).  Any idea what's wrong?

`IEnumerable<ITweet> likedTweetsRaw = await Auth.ExecuteOperationWithCredentials(_creds, async () =>
            {
                IEnumerable<ITweet> likes = await _loggedUser.GetFavoritesAsync(Int32.MaxValue);
                return likes;
            });`

**Comment by linvi** [comment]
I am not sure what is going wrong with your code. I have just verified and it works properly for me.

Please note that Tweetinvi does not provide automatic iteration over non cursored queries. The maximum number of the the `max` parameter is 200 as [documented on twitter](https://dev.twitter.com/rest/reference/get/favorites/list).

> Specifies the number of records to retrieve. Must be less than or equal to 200; defaults to 20. The value of count is best thought of as a limit to the number of tweets to return because suspended or deleted content is removed after the count has been applied.

To get back in history and actually get more than 200 favourite tweets, you will have to use the `GetUserFavoritesParameters` class and specify the earliest tweet you want to get as the `MaxId`.

``` c#
var favourites = authenticatedUser.GetFavorites(new GetUserFavoritesParameters()
{
    MaximumNumberOfTweetsToRetrieve = 200,
    MaxId = // your tweet max id
});
```

Please ensure you are using the latest version of Tweetinvi (1.0).

Thanks

**Comment by Disastercake** [comment]
I just updated to TweetInvi 1.0, however I'm having problems with the supplied code.  What is an example of MaxID, exactly?  I put in 0 to start from the first favorite ever, however it brings back a result of 0 tweets.  I'm using the exact code you specified.

**Comment by linvi** [comment]
Leave `maxId` null the first time you do a query. Then take the oldest tweet id and set it as a `maxId` as followed :

``` c#
var authenticatedUser = User.GetAuthenticatedUser();

var favouritedTweets = authenticatedUser.GetFavorites(200);
var oldestTweetId = favouritedTweets.Min(x => x.Id);

var newFavs = authenticatedUser.GetFavorites(new GetUserFavoritesParameters()
{
    MaximumNumberOfTweetsToRetrieve = 200,
    MaxId = oldestTweetId
});
```

Note that the async version of `GetFavorites` does not seem to be able to take the `GetUserFavoritesParameters` parameter. I will create a new issue and this will be fixed in next release.

**Comment by linvi** [comment]
You can find it here : https://github.com/linvi/tweetinvi/issues/299

**Comment by Disastercake** [comment]
Thank you!  Also, how can I tell what an older tweet ID is?  Does Twitter do the ID's in numerical order so that higher numbers are always newer?

**Comment by Disastercake** [comment]
I just found some Twitter documentation that the Tweet IDs use something called snowflake and are not simply numerical:

[](https://dev.twitter.com/overview/api/twitter-ids-json-and-snowflake)

Any thoughts on how to compare two IDs to see which is older?

**Comment by linvi** [comment]
As explained 

> These IDs are unique 64-bit unsigned integers, which are based on time, instead of being sequential

I personally think they are actually ordered properly but if you want to make sure you can just compare the `CreatedDate` field.
