### ISSUE TITLE
Rate Limits documentation out of date

### ISSUE THREAD

**Issue by Disastercake** [linvi/tweetinvi#297]
The API for the rate limits documentation examples are out of date.

This line here is out of date:
`RateLimit.RateLimitTrackerOption = RateLimitTrackerOptions.TrackAndAwait;`

It should be changed to:
`Tweetinvi.RateLimit.RateLimitTrackerOption = Tweetinvi.RateLimitTrackerMode.TrackAndAwait;`

Also, putting the entire namespaces in the documentation would be more helpful in finding where things are at exactly, as organization seems to change often.

**Comment by linvi** [comment]
I have just changed the documentation. Thank you for pointing it out.
We are starting to work on a new documentation website that should help the developers in the future.

> Also, putting the entire namespaces in the documentation would be more helpful in finding where things are at exactly, as organization seems to change often.

Organization and naming has often changed and I always informed the user that it could be the case before a version 1.0 is released. Version 1.0 had a complete refactor of its namespace and some naming changes (https://github.com/linvi/tweetinvi/releases/tag/1.0 > **Accessibility and consistency**). 

Note that Namespaces are now coherent and have a dedicated documentation pagge : https://github.com/linvi/tweetinvi/wiki/Namespaces.

Please keep reporting any problem in the documentation that you can find. I try my best to keep it up to date but I sometimes miss some of the wiki pages.
