### ISSUE TITLE
Searches documentation is out of date

### ISSUE THREAD

**Issue by Disastercake** [linvi/tweetinvi#298]
The following appears out of date.  I cannot find TweetSearchParameters data structure anywhere anymore.
```
var searchParameter = new TweetSearchParameters("tweetinvi")
{
    GeoCode = new GeoCode(-122.398720, 37.781157, 1, DistanceMeasure.Miles),
    Lang = Language.English,
    SearchType = SearchResultType.Popular,
    MaximumNumberOfResults = 100,
    Until = new DateTime(2015, 06, 02),
    SinceId = 399616835892781056,
    MaxId = 405001488843284480,
    Filters = TweetSearchFilters.Images
};
```
The closest I've found is 
`Tweetinvi.Parameters.ISearchTweetsParameters`

However just switching TweetSearchParamaters to Tweetinvi.Parameters.ISearchTweetsParameters does not allow the code afterwards to work anymore.  Any idea how to properly make a search and and namespaces used exactly?

**Comment by linvi** [comment]
```` c#
var searchParam = new Tweetinvi.Parameters.SearchTweetsParameters("hello");
var tweets = Search.SearchTweets(searchParam);
```

I will update the documentation right away.

**Comment by linvi** [comment]
Doc updated.

Thanks for reporting it :)
