### ISSUE TITLE
Authorization like instagram

### ISSUE THREAD

**Issue by mahdiit** [linvi/tweetinvi#3]
i read your documentation about authorization, but my instagram app does not have nether pin nor url based authentication, i think it should a sample like  this section

Part 3 - Publishing the Statuses
https://www.develop.com/twitternetapps

your lib does not support this method or i do not find it in documentations

**Comment by linvi** [comment]
Hello,

I am not sure I understand your issue. 

Twitter gives various solution to authenticate. At the end of the authentication process, Twitter gives you an OAuth Token that is specific for a user and an application. When you have this information

Tweetinvi does not yet implement all the authentication mechanisms. This is a work in progress that will be completed as Tweetinvi 1.0 will be released.

Here is a list of the different authentication mechanisms as described in the [Twitter documentation](https://dev.twitter.com/web/sign-in/implementing): 

* Sign in with Twitter (Want to offer a “Sign in with Twitter” button on your website) :x:
* 3-legged OAuth (Want to read or post Twitter data on behalf of visitors to your website) :white_check_mark:
* PIN-based OAuth (Have a mobile, desktop, or embedded app which can’t access a browser) :white_check_mark:
* Tokens from dev.twitter.com (Just want to access the API from your own account) :white_check_mark:
* xAuth (NEED to use usernames/passwords AND have been approved for xAuth) :x:
* OAuth Echo (Offer an API where clients send you data on behalf of Twitter users) :x:
* Application-only authentication (Want to issue authenticated requests on behalf of the application itself) :x:

For a mobile application I would currently advise to use the PIN-based OAuth mechanism.

I am now considering implementing the `Sign in with Twitter` mechanism process as part of the next release (0.9.9.x).

Please let me know if that would help?

Cheers,
Linvi

**Comment by mahdiit** [comment]
i found my answer, think that instagram use xAuth  (that approved by Twitter) becuase it take my username and password in app and no other link, pin or other things

and your recommendation is best answer for a mobile app, I must use PIN-based OAuth for my mobile app and Tokens from dev.twitter.com for my website

**Comment by linvi** [comment]
i have created a work item for xAuth authentication. As soon as I have access from Twitter, I will implement it.

https://tweetinvi.codeplex.com/workitem/2615
