### ISSUE TITLE
Tweetinvi.Exceptions.TwitterNullCredentialsException : Exception description outdated.

### ISSUE THREAD

**Issue by Abhith** [linvi/tweetinvi#307]
Exception description says to set credentials using : **TwitterCredentials.SetCredentials("Access_Token", "Access_Token_Secret", "Consumer_Key", "Consumer_Secret")**;

And as in #112 says,  _TwitterCredentials.SetCredentials_ changed to **Auth.SetCredentials**.

**Comment by haseeb1431** [comment]
@Abhith Thanks for reporting. This is fixed and will be available with next release.
