### ISSUE TITLE
Verify that UserStream.MessageReceived works properly

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#309]
> Leif Bloomquist @LeifBloomquist 05:46
Hey @linvi , all. Is there a trick to receiving Direct Messages? I have Direct Messages permissions set in apps.twitter.com for my app. I get Tweets perfectly with stream.TweetCreatedByAnyoneButMe , but the function attached to stream.MessageReceived is never called.

**Comment by JoshKeegan** [comment]
+1
Checked logs & we haven't received a DM over the streaming API since April.
Cheers,
Josh

**Comment by linvi** [comment]
That is quite strange because I do receive the event.
Guys, would you please subscribe to the `JsonObjectReceived` and check if you receive anything,

Thank you

**Comment by LeifBloomquist** [comment]
Yes.   JsonObjectReceived fires correctly, I got  `"{\"friends\":[50503212]}"`  in the Json parameter of Tweetinvi.Events.TweetReceivedEventArgs .

Nothing firing for MessageReceived though.   App permissions are also Read, Write and Access direct messages.

**Comment by linvi** [comment]
Could you please try to generate new consumer credentials for the application and then try to authenticate with it (you can do it on apps.twitter.com).

If it still does not work, could you try to generate new user credentials from Tweetinvi with the following :

``` c#
var auth = AuthFlow.InitAuthentication(new ConsumerCredentials("CONSUMER_KEY", "CONSUMER_SECRET"));
var url = auth.AuthorizationURL;
Console.WriteLine("Go to " + url + ". And then enter authorization");
var code = Console.ReadLine();

var newCreds = AuthFlow.CreateCredentialsFromVerifierCode(code, auth);
```

And the try to use the `newCreds` in Tweetinvi (`Auth.SetCredentials`) and then create your new `UserStream` (`Stream.CreateUserStream`).

**Comment by JoshKeegan** [comment]
Searching the raw JSON logs for "sender_id" (didn't know before searching about "direct_message"), and it stops in April as well.

There has been a long-running problem with streams disconnecting (sometimes without a disconnect message from Twitter) so my issue could just be that no stream has been active when a DM was sent since April. Having said that, it still seems unlikely since we automaigcally reconnect streams once they've been inactive for 120 seconds and we've received over 4000 DMs since the beginning of May (all must have been fetched over the REST API).

At some point I need to look into a bunch of issues with our use of streams, so I'm going to just add this to the list and come back to it later. Whatever the fix is @LeifBloomquist it'd be good to know as it sounds like I could have the same problem.

**Comment by linvi** [comment]
Thanks for the feedback. I personally have no issue at the moment but I will keep trying to reproduce the problem.

**Comment by JoshKeegan** [comment]
That's why I'm leaving it for now; it'll no doubt be something I've done wrong with the stream so I probably won't be adding anything of value here, and receiving DMs over streams really isn't a priority for me :)

**Comment by linvi** [comment]
@LeifBloomquist have you tried updating your credentials (consumer AND access)? 

If yes, would it be possible to book a time for me to debug on your machine?

**Comment by LeifBloomquist** [comment]
Yes, but I might have skipped a step or done something else.  I'll try the method you describe above.

Yes, totally open to having you remote in for debugging help.

**Comment by linvi** [comment]
@LeifBloomquist I know it has been a while but I was on holiday and now we can take some time to look at your issue together.

Would you please go on https://gitter.im/linvi/tweetinvi so that we can privately share our Skype logins.

**Comment by linvi** [comment]
Also I realize that you have never shared your code. Would you please do so to let me have a base to work on.

**Comment by linvi** [comment]
This has been verified and closed for now.
@LeifBloomquist if you still encounter the bug please reopen the bug.

**Comment by JoshKeegan** [comment]
What was the cause of this?

I'd like to check if I'm also doing whatever was causing this problem.

**Comment by linvi** [comment]
This has just been verified (multiple times). I need some feedback if the @LeifBloomquist still cannot use it.

**Comment by LeifBloomquist** [comment]
Still not working for me, but perhaps it is an issue with my
configuration.  I sent you my code.

**Comment by linvi** [comment]
Yes the code is working for me. I guess we will have to meet at some point and do a skype session.

**Comment by LeifBloomquist** [comment]
Gladly.  I am sure it is a simple fix.  When works for you?
