### ISSUE TITLE
Tweet.Media.Variants.ContentType is null

### ISSUE THREAD

**Issue by avnerho** [linvi/tweetinvi#319]
Hi,
When I'm getting tweets containing video media (MediaType = "video") and trying to access the variants array of each MediaEntity - the ContentType property always returns as null for each of the variants.
(i.e. : ITweet.Media[0].VideoDetails.Variants[0].ContentType)

Why is it so? Is this value not parsed from the json returned from twitter API?

**Comment by avnerho** [comment]
using reflector I figured out what the problem is: in class VideoEntityVariant there should be [JsonProperty("content_type")] attribute on top of ContentType property so the json serializer will be able to deserialize the content_type of the json to the ContentType property, otherwise the deserialization will not work. please fix.

**Comment by linvi** [comment]
Thank you for reporting this issue. It has been fixed and will be available as part of our next release.
