### ISSUE TITLE
Getting tweets from users I don't follow

### ISSUE THREAD

**Issue by avnerho** [linvi/tweetinvi#321]
I'm using FilteredStream for 3 twitter accounts I'm following.
I'm using thw following method:

TweeterStream.AddFollow([account_ID], HandleTweet)

however, when I'm getting tweets on my HandleTweet action - I'm also getting tweets from users I don't follow at all. How can it be if I only added 3 accounts to follow to the stream??
do twitter streams bring back trashy tweets as well?

It's a weird question but if I'm using the same credentials every time I start my application - is it possible that somehow the stream still keeps track on user accounts I've added before and does not clean itself from the old users that I used to follow cause I'm using the same credentials??
If I'm doing something wrong or need to force the stream using the same credentials to reset itself somehow, please let me know. 
If it's a bug, please investigate and fix...

Thanks!

**Comment by linvi** [comment]
Hello there, sorry for the long time without giving you any answer, I will look at this during this weekend.

**Comment by linvi** [comment]
When you are using a `FilteredStream` using the `AccountId` it will send you the tweets created by the user you follow as well as the tweets created by people followed by the user.

A good solution for your problem is to implement your own filter as followed : 

``` c#
var peopleToFollow = new long[] { 42, 43 };
var fs = Stream.CreateFilteredStream();
peopleToFollow.ForEach(x => fs.AddFollow(x));

fs.MatchingTweetReceived += (o, args) =>
{
    if (peopleToFollow.Contains(args.Tweet.CreatedBy.Id))
    {
        // The user you follow is the source of the tweet
    }
};

fs.StartStreamMatchingAllConditions();
```
