### ISSUE TITLE
Uploading media on  direct messages

### ISSUE THREAD

**Issue by LSDigitall** [linvi/tweetinvi#322]
Hello,
Is there a `Tweet.PublishTweetWithImage(,);` equivalent for direct messages?
Thank you.

**Comment by JoshKeegan** [comment]
The Twitter REST API doesn't currently support posting images in DMs.
See https://twittercommunity.com/t/uploading-images-in-dms/12317/8

**Comment by LSDigitall** [comment]
Well, that's too bad.
Thank you anyways.
By the way, is there at least a way to upload the profile picture?
Thanks again.

**Comment by JoshKeegan** [comment]
Take a look at `Account.UpdateProfileImage(byte[])`

**Comment by LSDigitall** [comment]
Thank you. Do you know the UWP equivalent? I can't find it anywhere.

**Comment by JoshKeegan** [comment]
I'd assume it'd be the same, but if not then I don't know, sorry.
@linvi will know but you might have to wait a few more days to get a response.

**Comment by linvi** [comment]
Quick hello from Portugal :)

Regarding the `Account.UpdateProfileImage` I understand you want to use the `async` version of it.
In Tweetinvi if such method is implemented (which is the case here, you can use the `Sync.ExecuteTaskAsync` which returns the result of the aync method invoked.

``` c#
Task<bool> task = Sync.ExecuteTaskAsync(() => Account.UpdateProfileImage(binary));
```

I hope this helps!

Going back to by sunbath!

**Comment by LSDigitall** [comment]
Thank you both and greetings from Portugal too :)
The problem here is that VS doesn't recognize the .UpdateProfileImage for UWP (windows 10) apps.
The error message is: "Account does not contain a definition for UpdateProfileImage".

**Comment by JoshKeegan** [comment]
I don't really know much about UWP, but there might be another `Account` class defined (which obviously wouldn't have that method defined).
If so, you might want to try `Tweetinvi.Account.UpdateProfileImage`.

**Comment by LSDigitall** [comment]
Hi,
unfortunately that doesn't work either.

**Comment by linvi** [comment]
Hello there. I am back so I will look into this issue this weekend.

**Comment by LSDigitall** [comment]
Thank you.
But please don't forget to also go outside and enjoy this great summer time :)

**Comment by linvi** [comment]
Hello there,

As a general rule, please open a new issue if the question is not related to the one initially asked (in this case how to publish an image in a DM).

Anyway lets do the same steps together :

1. Start by creating a new Windows Universal Project
2. Choose build 10586 

![image](https://cloud.githubusercontent.com/assets/6107439/18028907/246f1e28-6c81-11e6-9bb1-71d6867dedba.png)
3. Open Nuget Package Manager and install TweetinviAPI (v1.0)
4. Use the following code :

``` c#
private async void OnLoaded(object sender, RoutedEventArgs routedEventArgs)
{
    var binary = File.ReadAllBytes(@"C:\test.jpg");
    var success = await Sync.ExecuteTaskAsync(() => Account.UpdateProfileImage(binary));

    if (success)
    {
        // do whatever you want here
    }
}
```

## Important
Please use the Nuget Package Installer so that it chooses the appropriate DLLs to install.

**Comment by LSDigitall** [comment]
Got it!
Thank you very much. I wasn't using the latest version (it was 0.9.10.2).
