### ISSUE TITLE
Search multiple Hashtags 

### ISSUE THREAD

**Issue by Prabh2308** [linvi/tweetinvi#323]
Hi,

I want to search tweets that contains multiple hashtags. #hashtag1 and #hashtag2. Because if i search them individually, Then i may get duplicate results.

**Comment by JoshKeegan** [comment]
For the REST API (so not as a stream), this is very simple.
Just search for:
```
#hashtag1 #hashtag2
```

Putting more than one word into a search ANDs them. 
See https://dev.twitter.com/rest/public/search for more operators.

For the Streaming API, I believe it's exactly the same, but this isn't a feature I use in streams so I'm not 100%.
See https://dev.twitter.com/streaming/overview/request-parameters#track

Note that the Streaming API won't support the other more advanced operators that I linked to above for the REST API. I think the only other one they will support is OR, which is given as a comma.

**Comment by Prabh2308** [comment]
"," comma works fine. Sir please suggest if i want to us AND i.e. i want if both hashtags are available in the tweets if yes the tweets are displayed.

**Comment by Prabh2308** [comment]
"," comma works as and operation. How to use or operation. Please help.

**Comment by linvi** [comment]
You can refer to the documentation of the Track for FilteredStream [here](https://github.com/linvi/tweetinvi/wiki/Filtered-Streams#filter-by-track-and-keywords),


AND operation can only be done in a same Track 'stream.AddTrack("linvi tweetinvi")` will therefore only track tweets containing both linvi AND tweetinvi.
OR operation is done via adding a new `stream.AddTrack("gg")`

If you invoke these 2 calls, you will therefore have the following :
All the tweets containing both ('linvi' AND 'tweetinvi') OR all the tweets containing 'gg'.
