### ISSUE TITLE
.Result in httphelper causing deadlocks

### ISSUE THREAD

**Issue by pkeuter** [linvi/tweetinvi#325]
Thanks for your library, appreciated. 

I have a problem when using the library outside of the main thread. I use the library for uploading video's to multiple social networks and so uploading to Twitter runs on the TaskScheduler.

But when I do use the TaskScheduler, I'm getting into a deadlock situation. This is because of the HttpClientWebHelper class using an async method which is then being used synchronously by calling .Result. I would say that there are two possible ways to go:

1. Use a synchronous webclient.
2. Make the library asynchronous.

Here is some more information: https://blogs.msdn.microsoft.com/pfxteam/2012/04/13/should-i-expose-synchronous-wrappers-for-asynchronous-methods/

**Comment by linvi** [comment]
I am aware of this post, so you can feel free to use the non async methods on your own to ensure that you do not have deadlock.

I would like to mention that the library has been improved regularly regarding this point.
Could you confirm that you are experiencing this deadlock in version 1.0?

Please note that a fully async version of Tweetinvi is planned but not done yet.

**Comment by pkeuter** [comment]
Yes I am using version 1.0. I really like the library, but this issue is blocking me from using it, I'm trying to find a workaround, but so far I haven't been able to find a way.

Is the fully async version already commited to Github, so I could test it?

**Comment by linvi** [comment]
No the fully async version is not done yet and should not be done for quite a while because it implies many changes in the library.

Have you tried to use the Non-Async methods and call them asynchronously on your own?

**Comment by linvi** [comment]
I would be quite keen on working with you on your problem. If you do have some time one evening would you be open to look into the problem with me over a Skype session?

**Comment by pkeuter** [comment]
Hey @linvi. That's very kind of you. I managed to fix this problem for now by cloning your library and using the preferred methods on the link I've passed earlier.

```
 if (twitterQuery.HttpContent == null)
                {
                    return Task.Factory.StartNew(() => client.SendAsync(new HttpRequestMessage(httpMethod, twitterQuery.QueryURL)).Result).Result;
                }
                else
                {
                    if (httpMethod != HttpMethod.Post)
                    {
                        throw new ArgumentException("Cannot send HttpContent in a WebRequest that is not POST.");
                    }

                    return Task.Factory.StartNew(() => client.PostAsync(twitterQuery.QueryURL, twitterQuery.HttpContent).Result).Result;
                }
```

There are some other issues though. Setting the credentials from another thread than where I'm doing the actual query doesn't work, and Upload.UploadVideo sometimes gives a null result and it seems that the actual exception is being swallowed (which makes it hard to debug what's wrong).

I don't think I should file a PR for this since I think it's better to fix this from the bottom and you're already working on it.

If you still want to add me on Skype, you can easily find my with my first and last name :-)

**Comment by linvi** [comment]
I will take a look at your solution and decide whether or not I want to include it in version 1.1.
Could you explain what you did and why?

> There are some other issues though. Setting the credentials from another thread than where I'm doing the actual query doesn't work

The Tweetinvi library has been made at the core with the idea that each of the Thread in an application will have its own set of credentials (you can now see the complexity of porting it to async). Which mean that you need to set your credentials in the thread in which you want to use it. Otherwise you can use the `Auth.ApplicationCredentials = new TwitterCredentials(...);`. The `ApplicationCredentials` will be duplicated each time a new thread is created. This might sound confusing but I think it helps make the library easier to use for many people.

> Upload.UploadVideo sometimes gives a null result and it seems that the actual exception is being swallowed

You can unswallow any exception with the following line : `ExceptionHandler.SwallowWebExceptions = false;`

> I don't think I should file a PR for this since I think it's better to fix this from the bottom and you're already working on it. 

I don't think so either but I would be happy to have some feedback on what you did and why as mentioned at the beginning of this message.

> If you still want to add me on Skype, you can easily find my with my first and last name :-)

I will probably do that in the future if you do have time to discuss about this. I am planning on version 2.0 (async) of Tweetinvi and your feedback could be very useful.

Cheers,
Linvi

**Comment by linvi** [comment]
@pkeuter I have taken a closer look at the bug and your solution but I would like to discuss it with you.

Let me know if you are available.

**Comment by linvi** [comment]
Hi again. I want to have more insight before applying your change to fix the deadlock.
Therefore I created a stackoverflow question hoping a people with a good understanding on the subject could help.

If you want to add any comment/answer feel free to take a look at it.
http://stackoverflow.com/questions/39441829/encapsulating-async-method-in-task-factory-startnew

**Comment by linvi** [comment]
@pkeuter Could you please provide more information regarding your solution. Is it ASP.NET, .NET Core, WPF, Console, Winform...

I don't think any of the developers on the question do understand the fix that you applied.
I bought a book on the subject to try and understand how your codes solves the problem but it will take me some time to read it and understand it.

In the meantime please provide as many information as you can.
I will be glad if you can talk me through this bug over a Skype session (go on gitter.im to share our accounts).

**Comment by linvi** [comment]
I do not want to disturb you but I need to have answers from you in order to solve this problem.
If you cannot reply tomorrow, the issue will not be fixed as part of version 1.1.

**Comment by linvi** [comment]
As discussed on gitter, we are moving this problem to version 1.2 or for a 1.1 minor release since we have more information regarding the problem.

**Comment by linvi** [comment]
Any news here, or should I close this one?

**Comment by linvi** [comment]
Closed as not receiving any update.
