### ISSUE TITLE
For some reason I am unable to start stream with location filter.

### ISSUE THREAD

**Issue by abdulmbajwa** [linvi/tweetinvi#326]
When I use this code I get stream no problem.

> Auth.SetUserCredentials("consumerKey", "consumerSecret", "accessToken", "accesTokenSecret");
>             var stream = Stream.CreateFilteredStream();
>             stream.AddTrack("twitter");
>             stream.MatchingTweetReceived += (sender, args) =>
>             {
>                 Console.WriteLine(args.Tweet);
>             };
>             stream.StartStreamMatchingAllConditions();
> 

But whenever I add location filter to stream.
            

> Auth.SetUserCredentials("consumerKey", "consumerSecret", "accessToken", "accesTokenSecret");
>             var stream = Stream.CreateFilteredStream();
>             stream.AddTrack("twitter");
>             stream.AddLocation(new Coordinates(-74, 40), new Coordinates(-73, 41));
>             stream.MatchingTweetReceived += (sender, args) =>
>             {
>                 Console.WriteLine(args.Tweet);
>             };
>             stream.StartStreamMatchingAllConditions();
> 

I get no response. No exception or anything.

**Comment by linvi** [comment]
Sorry for not replying earlier. Have you been able to solve your problem?

**Comment by abdulmbajwa** [comment]
Yes problem is resolved. I had fiddler installed on my system it was interfering with traffic. Stream is working fine :)
