### ISSUE TITLE
Tweet.Place/Tweet.Coordinate Always returns a NULL?

### ISSUE THREAD

**Issue by Prabh2308** [linvi/tweetinvi#327]
i was using 
tweet.place
tweet.coordinate

but every time null is returned?

Any solution

**Comment by Prabh2308** [comment]
this time tweet.place returned== 	Tweetinvi.Logic.Model.Place

**Comment by abdulmbajwa** [comment]
Tweet.Place is not null for me. But coordinates depend on if user is GeoEnabled or not. If user is geoenabled you will get coordinates otherwise it will be null.

**Comment by Prabh2308** [comment]
#abdulmbajwa can you guide me how to enable this.

**Comment by linvi** [comment]
@abdulmbajwa is just saying that the places will not be populated if the user who published the Tweet did not active GeoLocation.

You can do that in your account parameters.

**Comment by Prabh2308** [comment]
Sir why i get **_Tweetinvi.Logic.Model.Place_**. How to resolve this.

**Comment by linvi** [comment]
What do you mean? Do you get an object of this type or do you receive this as a string?
Could you share your code please?

**Comment by Prabh2308** [comment]
dr[0] = tweet.Id;
                dr[1] = tweet.Text;
                dr[2] = tweet.CreatedAt;
                string hashtags = "";
                foreach (var tag in tweet.Hashtags)
                {
                    hashtags += tag.Text + ",";
                }
                dr[3] = hashtags;
                dr[4] = tweet.Source;
                dr[5] = tweet.Place;
if place is null it shows blank, as in pic1
![11](https://cloud.githubusercontent.com/assets/19783982/18254220/19514130-73b9-11e6-832a-d76282859d98.PNG)

if place is available i get this message **_Tweetinvi.Logic.Model.Place._**
![12](https://cloud.githubusercontent.com/assets/19783982/18254242/494bad44-73b9-11e6-97b9-ded3dbf9dda0.PNG)

**Comment by linvi** [comment]
What is the type of `dr`?

**Comment by Prabh2308** [comment]
sir i am saving the data in datalist, dr is the object for new row:
 dt.Columns.Add("Id");
        dt.Columns.Add("Text");
        dt.Columns.Add("CreatedAt");
        dt.Columns.Add("HashTags");
        dt.Columns.Add("Source");
        dt.Columns.Add("Place");

DataRow dr = dt.NewRow();

**Comment by linvi** [comment]
`Place` is an object of type Tweetinvi.Logic.Model.Place`. I think what is happening is that you have an implicit cast to string.

What you want to do is use the properties located inside the `place` property.

**Comment by Prabh2308** [comment]
then sir i get the following error message:
![13](https://cloud.githubusercontent.com/assets/19783982/18254399/efc07bae-73ba-11e6-9c6b-60d02894dd99.PNG)

**Comment by Prabh2308** [comment]
@linvi help me sir?

**Comment by linvi** [comment]
`dr[5] = tweet.Place?.FullName`

**Comment by Prabh2308** [comment]
**_dr[5] = tweet.Place?.FullName_**   is generating an error.

**Comment by linvi** [comment]
`dr[5] = tweet.Place != null ? tweet.Place.FullName : null;`
