### ISSUE TITLE
What all thing can i retrieve using tweetinvi?

### ISSUE THREAD

**Issue by Prabh2308** [linvi/tweetinvi#328]
I want to know what all things can i retrieve using tweetinvi?

currently i am getting the following:
1: Name of sender
2: Tweet itself
3: Source from where tweet was send
4: Date and time

**Comment by linvi** [comment]
You can retrieve everything that is available from the public library.
You can easily use intellisense to list the available properties for each Classes/Interfaces.

**Comment by Prabh2308** [comment]
@linvi Sir is there any way of getting Gender or DOB/AGE of the person who is tweeting?

**Comment by linvi** [comment]
No you cannot access this information as far as I am aware.
