### ISSUE TITLE
stream.AddLocation doesn't work by itself

### ISSUE THREAD

**Issue by mumian** [linvi/tweetinvi#330]
My code failed with the last TweetInvi API. To make it work, I have to combine it with a AddTrack.

The following code works only if I uncomment "stream.AddTrack()".

var stream = Stream.CreateFilteredStream();
stream.AddLocation(new Coordinates(-180, 90), new Coordinates(180, -90));
//stream.AddTrack("xbox");

stream.MatchingTweetReceived += (sender, args) =>
{
}

**Comment by linvi** [comment]
You simply inverted you coordinates latitude and longitude.

``` c#
stream.AddLocation(new Coordinates(90, -180), new Coordinates(-90, 180));
```
