### ISSUE TITLE
Help regarding Geo Coordinates while searching?

### ISSUE THREAD

**Issue by Prabh2308** [linvi/tweetinvi#331]
Hello sir, 
i want to search the tweets that are not from the following coordinates.

I know the code for specific coordinate location:
searchParameter.SetGeoCode(Geo.GenerateCoordinates(-95.7129, 37.0902), 1898371, DistanceMeasure.Miles)

what should i do if i do not want to search from the above coordinates?

**Comment by linvi** [comment]
Hello there,

So I looked carefully at the Twitter REST API and there is no way to do what you are looking for.
But a simple solution could be to do it the other way around.

Meaning that you search for all the tweets (no .SetGeoCode) and then when you receive your result you do some Maths to calculate if the coordinates of the Tweet is located within the invalid coordinates.
