### ISSUE TITLE
Have problem to get Ratelimit when change application credentials

### ISSUE THREAD

**Issue by LenroK** [linvi/tweetinvi#335]
Have some app credentials in database, when my app use all queries I need to change that credentials for other where queries are avilable. But when i try to use `Auth.SetApplicationOnlyCredentials(Cred.ConsumerKey, Cred.ConsumerSecret, true);`
it give me wrong limits. I can not find any solution for this problem.
This is how i change credentials
```
public static bool Credentials()
        {
            CredentialDBContext db = new CredentialDBContext();
            TweetinviEvents.QueryBeforeExecute += (sender, args) =>
            {
                var rateLimits = RateLimit.GetQueryRateLimit(args.QueryURL);
                if (rateLimits != null)
                {
                    if (rateLimits.Remaining > 0)
                    {
                        return;
                    }
                    else
                    {
                        foreach (var Cred in db.Credentials)
                        {
                            Auth.SetApplicationOnlyCredentials(Cred.ConsumerKey, Cred.ConsumerSecret, true);
                            rateLimits = RateLimit.GetQueryRateLimit(args.QueryURL);
                            if (rateLimits.Remaining > 0 && rateLimits != null)
                            {
                                break;
                            }
                        }
                    }
                }
            };
            return true;
        }
```
And for this i need to change credentials
```
[HttpPost]
        public ActionResult DownloadFavoriteTweets(FormAskForFavoriteTweets form)
        {
            Auth.SetApplicationOnlyCredentials("VHSTv1EoNnu9U02skD4HjguS4", "BsjkZuyiVmPuzhw4yZft6OjiptAZBZzNKZPgLRd458mO2B2E0U", true);
            RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackOnly;
            AddCredentialsController.Credentials();
            var user = Tweetinvi.User.GetUserFromScreenName(form.userName);
            var favoriteTweets = Tweetinvi.User.GetFavoriteTweets(form.userName);
            bool isDone = false;
            int collectedTweets = 0;
            if (favoriteTweets!=null)
            {
                foreach (var favoriteTweet in favoriteTweets)
                {
                    if (collectedTweets <= form.maxFavoriteTweetsNumber)
                    {
                        collectedTweets++;
                        var tweet = new FavoriteTweet();
                        tweet.ExperimentId = form.experimentId;
                        tweet.UserId = user.Id;
                        tweet.Tweet = favoriteTweet.Text;

                        db.FavoriteTweets.Add(tweet);
                    }
                    else {
                        isDone = false;
                        break;
                    }
                }
                db.SaveChanges();
            }
            while ((favoriteTweets != null) && (isDone==false))
            {
                var oldestTweetId = favoriteTweets.Min(x => x.Id);
                favoriteTweets = Tweetinvi.User.GetFavoriteTweets(form.userName, new GetUserFavoritesParameters()
                {
                    MaxId = oldestTweetId
                });
                bool firsthInFor = true;
                if (favoriteTweets != null)
                {
                    foreach (var favoriteTweet in favoriteTweets)
                    {
                        if (firsthInFor == false && collectedTweets <= form.maxFavoriteTweetsNumber)
                        {
                            collectedTweets++;
                            var tweet = new FavoriteTweet();
                            tweet.ExperimentId = form.experimentId;
                            tweet.UserId = user.Id;
                            tweet.Tweet = favoriteTweet.Text;

                            db.FavoriteTweets.Add(tweet);
                        }
                        else if (collectedTweets > form.maxFavoriteTweetsNumber)
                        {
                            isDone = true;
                            break;
                        }
                        else { firsthInFor = false; }
                    }
                }
                db.SaveChanges();
            }
            
            return View("Index", db.FavoriteTweets.ToList());
            //return RedirectToAction("Index");
        }
```

**Comment by linvi** [comment]
Thank you for reporting this problem.
I will take a look at it but please be patient, I am currently trying to understand a complex asynchronous bug that have been reported.

Give me 2 days before pinging me back.

Cheers

**Comment by linvi** [comment]
Have you tried using `RateLimit.ClearRateLimitCache();` when you switch your credentials?

> hen i try to use Auth.SetApplicationOnlyCredentials(Cred.ConsumerKey, Cred.ConsumerSecret, true);
it give me wrong limits

What do you mean by it give you wrong limits. Are the limits returned the limits of another set of credentials or are they simply outdated, or are they just wrong?

**Comment by LenroK** [comment]
I didn't try `RateLimit.ClearRateLimitCache();`. 
I suggested to your description about ratelimit tracking (https://github.com/linvi/tweetinvi/wiki/Rate-Limits). I am not sure what limits it returns but I think it gives me `Auth.SetApplicationOnlyCredentials`'s limits.

**Comment by linvi** [comment]
Why do you know that the credentials are incorrect then.
Note that you can also pass the credentials that you want to use the `RateLimit.GetQueryRateLimit`.

``` c#
RateLimit.GetQueryRateLimit("", appCredentials);
```

**Comment by LenroK** [comment]
While debuging when `rateLimits.Remaining` should be 0 it was 15 and return from queries(GetFavoriteTweets) was null. Mayby I can't use it correct way or I miss something. I belive it returns credentials to `Auth.SetApplicationOnlyCredentials` because when I use `Credentials()` and go to place where 'Auth.SetApplicationOnlyCredentials' show in foreach it call 'TweetinviEvents.QueryBeforeExecute ' agine.

**Comment by linvi** [comment]
Could we have a skype call? If you can please wisp me on gitter https://gitter.im/linvi/tweetinvi

**Comment by linvi** [comment]
I need to have some feedback from your side otherwise, I won't be able to help.

**Comment by LenroK** [comment]
Hi, sorry for not reply, I had a lot to do recently. This is code when everything is working properly.
`        public static void Credentials()
        {
            CredentialDBContext db = new CredentialDBContext();
            TweetinviEvents.QueryBeforeExecute += (sender, args) =>
            {
                var queryRateLimits = RateLimit.GetQueryRateLimit(args.QueryURL);

                // Some methods are not RateLimited. Invoking such a method will result in the queryRateLimits to be null
                if (queryRateLimits != null)
                {
                    if (queryRateLimits.Remaining > 0)
                    {
                        // We have enough resource to execute the query
                        return;
                    }
                    else
                    {
                        while (queryRateLimits.Remaining < 1)
                        {
                            foreach (var cred in db.Credentials)
                            {
                                var credential = Auth.SetApplicationOnlyCredentials(cred.ConsumerKey, cred.ConsumerSecret, true);
                                queryRateLimits = RateLimit.GetQueryRateLimit(args.QueryURL, credential);
                                if (queryRateLimits.Remaining > 0)
                                {
                                    args.TwitterQuery.TwitterCredentials = Auth.SetApplicationOnlyCredentials(cred.ConsumerKey, cred.ConsumerSecret, true);
                                    break;
                                }
                            }
                        }
                    }
                }
            };`
I spent some time with your library and I undesrtood what was problem.
'Auth.SetApplicationOnlyCredentials(Cred.ConsumerKey, Cred.ConsumerSecret, true);' in 'Credentials()' was only changing credentials in 'Credentials()'. When code go back to 'DownloadFavoriteTweets()' The query credentials remained unchanged. I think problem is this is MVC app and 'Credentials()' and 'DownloadFavoriteTweets()' are in diffrent controllers.

**Comment by linvi** [comment]
`Auth.SetApplicationOnlyCredentials(cred.ConsumerKey, cred.ConsumerSecret, true)` sets the credentials for the current thread as opposed to application wide.

``` c#
var creds = new TwitterCredentials("consumer key", "consumer secret")
{
    ApplicationOnlyBearerToken = "..."
};

Auth.ApplicationCredentials = creds;
```

Also note that you should not use the `true` parameter by default. The true simply get the bearer token by accessing the Twitter API. You should store this information in your database.

**Comment by linvi** [comment]
I think this issue was resolved, if it was not please let me know and we can reopen it.
