### ISSUE TITLE
Application Credentials: Bad Authentication data

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#338]
Hi Linvi,
I don't usually use application credentials for requests, so forgive me if I'm doing something wrong!
Anyway, I thought it made sense to do so for some unit tests but I'm currently having an issue.

The error I'm getting is "Bad Authentication data." when I try and get a Tweet by its ID.
The same code works fine with user credentials.

The failing test is nice & simple:
```cs
[TestMethod]
public void TestConstructPlainTextTweet()
{
	ITweet tweet = Tweet.GetTweet(781137957730254848);
	TweetInviExceptionHelpers.LogTwitterExceptionsAndThrowFriendly();
	TwitterStatus status = new TwitterStatus(tweet);

	Assert.AreEqual("Plain text tweet", status.Text);
}
```
The credentials get set separately in an `[AssemblyInitialize]` method (not relevant to this, but that's why the credentials line is missing from the above snippet).
Cheers,
Josh

**Comment by linvi** [comment]
Will look into it.

Thanks

**Comment by linvi** [comment]
I have just tested and this do work. Just to be sure, you are setting the bearer token for Application Credentials?

If you do not have any bearer token, you can get it very easily by setting the last parameter to `true`:

``` c#
// If you do not have bearer token. 
// Note that this function is rate limited to try to store the bearer token
var creds = Auth.SetApplicationOnlyCredentials("consumerKey", "consumerSecret", true);
var bearerToken = creds.ApplicationOnlyBearerToken;

// If you already have the bearer token
var creds = Auth.SetApplicationOnlyCredentials("consumerKey", "consumerSecret", "bearerToken");
```

Let me know if this helped.

**Comment by JoshKeegan** [comment]
I was just setting the key & secret.
I thought I checked & the default was true for the 3rd parameter though? 
This was on my work machine so I'll try again tomorrow.

**Comment by linvi** [comment]
The default is `false`, because I do not want Tweetinvi to execute a query without the user knowing about it.

**Comment by JoshKeegan** [comment]
Alright, sorry I must have misread earlier!

**Comment by linvi** [comment]
No problem, I am closing the bug for now.
Feel free to reopen it, if you still experience it.

Have a good evening ;)
