### ISSUE TITLE
ApplicationSettings.TweetMode ignored

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#339]
Hi Linvi,
Just trying to test Extended tweets & it looks like `TweetinviConfig.ApplicationSettings.TweetMode` is getting ignored.
It's working as expected when I set it via `TweetinviConfig.CurrentThreadSettings.TweetMode`.

This is for a call to `Tweet.GetTweet(781144364416397313);`.
Cheers,
Josh

**Comment by linvi** [comment]
Just to be sure, you do remember that `TweetinviConfig,ApplicationSettings....` is not setting the `CurrentThreadSettings`. but if you are actually initializing the APP from the main Thread.

**Comment by JoshKeegan** [comment]
Sounds like it's my mistake then!
So ApplicationSettings will be reflected in any new threads spawned, but not the current one?

Is it possible after setting any settings at an application level to copy them all to the current thread, or should best practice be to set both current thread settings and application settings for each individual setting?

Basically, in my scenario I have an `Init` method in a shared library which should be the first thing called by all applications using it. In some of them, requests will only get sent from new threads and in others (Unit Tests in this case) the same thread will be used. So my `Init` method should work in both cases.

**Comment by linvi** [comment]
So the way, it has been designed is that they are both completely separated now because people could not understand it in the past.

So what you want to do is the following :

``` c#
TweetinviConfig.ApplicationSettings.TweetMode = TweetMode.Extended;
TweetinviConfig.ApplicationSettings.ProxyURL = "";
//...

TweetinviConfig.CurrentThreadSettings.InitialiseFrom(TweetinviConfig.ApplicationSettings);
```

**Comment by JoshKeegan** [comment]
Thanks :)
