### ISSUE TITLE
TwitterCredentials: 2 parameters or 0?

### ISSUE THREAD

**Issue by jamessdixon** [linvi/tweetinvi#35]
I am looking at the documentation for TwitterCredentials here:
https://github.com/linvi/tweetinvi/wiki/Authentication
Specifically, this LOC:
var appCredentials = new TwitterCredentials("CONSUMER_KEY", "CONSUMER_SECRET");

The problem is that I only see this in object explorer
Tweetinvi.TwitterCredentials.TwitterCredentials()

And 
Tweetinvi.TwitterCredentials.SetCredentials(string, string, string, string)

Is the documentation out of date?
Thanks

**Comment by linvi** [comment]
Hi,

The authentication mechanism changed at version 0.9.9.x. If you have a prior version please use this documentation.

https://github.com/linvi/tweetinvi/wiki/Authentication-before-0.9.9.x

If you use version 0.9.9.0 and above, the documentation is up to date.

``` c#
var appCreds = new Tweetinvi.Core.Credentials.TwitterCredentials("CONSUMER_KEY", "CONSUMER_SECRET");
var userCreds = new Tweetinvi.Core.Credentials.TwitterCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");
```

To set up the credentials, you will now use the `Auth` static class.

``` c#
Auth.SetCredentials(creds);
```

Cheers,
Linvi

**Comment by linvi** [comment]
I am closing the issue as I think this is not an issue. Please let me know if this helped and if you find a solution for your problem.
