### ISSUE TITLE
Issue: stream.AddFollow(user); 

### ISSUE THREAD

**Issue by AlishbaZ** [linvi/tweetinvi#350]
Hello linvi. Can you please tell me how can I get the tweets of some other user.
I found this would help me
stream.AddFollow(user); 
but i dont know the userID of the user whose tweets I want. So i thought I could go with user parameter. How can I use ths parameter. (Or if yo could tell me how to get the userID of some other user's account)
Thank you in advance.

**Comment by linvi** [comment]
You have different solutions to get the tweets from user.

First you can get a user from his screename : 
``` c#
IUser tweetinviapi = User.GetUserFromScreenName("tweetinviapi");
long tweetiniviapiId = tweetinviapi.Id;
```

Or you can get a user from your list of followers :
``` c#
IUser authenticatedUser = User.GetAuthenticatedUser();
List<IUser> myFollowers = authenticatedUser.GetFollowers().ToList();
```

Or you can even search for them :

``` c#
List<IUser> tweetinviUsers = Search.SearchUsers("tweetinvi").ToList();
```

When you have found the id OR screename of the user that you are interested in, you can then request their tweet using the `Timeline.GetUserTimeline()`.

``` c#
// From screename
var tweets = Timeline.GetUserTimeline("tweetinviapi").ToList();

// From id
var tweets = Timeline.GetUserTimeline(42).ToList();
```

Differently from the `Timeline` which allow you to get all the tweets posted up to now, the `FilteredStream` will allow you to receive the tweets posted by the user in live.

I hope this helps.

**Comment by AlishbaZ** [comment]
okay. thank you. 
Another question I have is: 
What is the maximum number of tweets that I can get from other user's account? 
For example I need to fetch almost 500 latest tweets from other account.  But by using tweetinvi, i am able to collect almost 160-200 tweets.

**Comment by linvi** [comment]
Hello,

I would suggest that you iterate over the user timeline and set the `MaxId` parameter.
Below you will find a sample solution to do what you want but I would suggest that when you receive less than 200 tweets you perform the test a second time because Twitter not always return the number of tweets requested.

``` c#
var authenticatedUser = User.GetAuthenticatedUser();

var timeline = Timeline.GetUserTimeline(authenticatedUser, 200).ToList();
var entireTimeline = timeline.ToList();

while (timeline.Count == 200)
{
    var lowestId = timeline.Min(x => x.Id);

    timeline = Timeline.GetUserTimeline(authenticatedUser, new UserTimelineParameters()
    {
        MaximumNumberOfTweetsToRetrieve = 200,
        MaxId = lowestId
    }).ToList();

    entireTimeline.AddRange(timeline);
}
```

Also note that you have to be vigilant to the rate limits.

**Comment by linvi** [comment]
Please let me know if this helped.

**Comment by AlishbaZ** [comment]
Yes it worked for me :) Thank you so much for your help, seriously.
