### ISSUE TITLE
Getting tweets for language

### ISSUE THREAD

**Issue by rage10** [linvi/tweetinvi#351]
Hello
I'm trying to get tweets for a language(not related to a user or something, just the latest), but i keep getting the stopStream event called.
when i'm using stream.AddTrack("Apple"); i'm getting tons of results.
can someone help me with this please? Thanks!

``` c#
            var stream = Stream.CreateFilteredStream();'
            //not working with this
            stream.AddTweetLanguageFilter(LanguageFilter.English);
            //working with this.
            stream.AddTrack("Apple");
            stream.MatchingTweetReceived += (sender, arg) =>
            {
                Console.WriteLine("tweet received; the tweet is '" + arg.Tweet + "'");
            };

            stream.StreamStopped += (sender, arg) =>
            {
                Console.WriteLine("StreamStopped");
                stream.StartStreamMatchingAnyCondition();
            };

            Console.WriteLine("starting stream");
            stream.StartStreamMatchingAnyCondition();
```

**Comment by linvi** [comment]
This code does work for me.

Could you please provide more information regarding the error that you are receiving.

``` c#
// You can find the exception in args.Exception
fs.StreamStopped += (sender, args) =>
{
    Console.WriteLine(args.Exception);
};
```

**Comment by rage10** [comment]
Thank you very much for your reply.
first, the reason was i had to add a search term ( so code will work with language && search term).

questions:
1) does that mean that i can't get all tweets in English for example ( without regard to a search term)?
2) I want to get tweets for Hebrew language, but I don't get any(just keeps waiting for one), i thought it's related to encoding, so i tried to encode it to UTF8, but still didn't get any result (there are tweets for sure), here's my code:
            var stream = Stream.CreateFilteredStream();
            stream.AddTweetLanguageFilter(LanguageFilter.Hebrew);
            string searchTerm = "שנה טובה";
            byte[] utf8Bytes = System.Text.Encoding.UTF8.GetBytes(searchTerm);
            string searchTermUtf8 = System.Text.Encoding.UTF8.GetString(utf8Bytes);
            stream.AddTrack(searchTermUtf8);
            stream.MatchingTweetReceived += (sender, arg) =>
            {
                Console.WriteLine("tweet received; the tweet is '" + arg.Tweet + "'");
            };

Thank you!

**Comment by linvi** [comment]
I will try to look at it, but I do know that streams work with Russian character set.
I will get back to you when I know more about this.

**Comment by linvi** [comment]
Hello Rage, this is a very busy time and I unfortunately cannot take enough time to look at your issue for the moment.

I will update this post as soon as I have.

**Comment by linvi** [comment]
Created a new discussion on twittercommunity : https://twittercommunity.com/t/filter-stream-and-hebrew-characters/76064

I will update this issue when I learn more from the Twitter team.

**Comment by linvi** [comment]
> 1) does that mean that i can't get all tweets in English for example ( without regard to a search term)?

No you cannot. The closest you can do is to use a `SampleStream` and filter by Language.

``` c#
var s = Stream.CreateSampleStream();

s.AddTweetLanguageFilter(LanguageFilter.English);

s.TweetReceived += (sender, args) =>
{
	Console.WriteLine(args.Tweet);
};

s.StartStream();
```

> 2) I want to get tweets for Hebrew language, but I don't get any(just keeps waiting for one), i thought it's related to encoding, so i tried to encode it to UTF8, but still didn't get any result (there are tweets for sure), here's my code

There seem to be some problem with Twitter stream when you try to use a Hebrew track keyword AND filter by language.

Until I have more information from Twitter, I would suggest that you remove the `Language` filter and just use a `.AddTrack`.

**Comment by linvi** [comment]
It looks like a problem on Twitter side. They are aware of it. I cannot do more than that to solve the problem.

Try to contact them or add some comment to the post I created on twittercommunity if you want to make sure that the topic keeps being taken into consideration.
