### ISSUE TITLE
Problem - Search Tweets

### ISSUE THREAD

**Issue by alex1389** [linvi/tweetinvi#352]
I have a problem using this library, when I try to search all the tweets from some specific **location** it works, but if I add other searchparameter like filter by **popular** then return nothing, no tweets found when I try to get the popular tweets in some location defined.

Anyone know if this is a Twitter limitation or issue of the Tweetinvi?? 

Thanks!!
Alex

**Comment by alex1389** [comment]
@linvi please help on this. Thanks

**Comment by linvi** [comment]
Thank you for reporting this issue.

Could you please share the version of Tweetinvi you are using and also your code that works, and the code that does not work.

**Comment by alex1389** [comment]
Hi,

The version used is 1.1.0.2 from NuGet, I´m working with VS 2015.

Here are the examples of code that return tweets and other that don't. I need the popular tweets from some specific place. 
Always looking for "quito", also that coordenates are from Quito, Ecuador.

Aproach 1

--------------------------------------------------------------------------------------------
Test #1
```
var searchParameter = new SearchTweetsParameters(hashtag);

searchParameter.SearchType = SearchResultType.Popular;
searchParameter.MaximumNumberOfResults = 200;
searchParameter.GeoCode = new GeoCode(-0.220102, -78.5119250, 50, DistanceMeasure.Kilometers);

var tweets = Search.SearchTweets(searchParameter);
```

Return 0 tweets.
--------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------
Test #2

```
var searchParameter = new SearchTweetsParameters(hashtag);

searchParameter.SearchType = SearchResultType.Popular;
searchParameter.MaximumNumberOfResults = 200;

var tweets = Search.SearchTweets(searchParameter);
```

Return 46 tweets.
--------------------------------------------------------------------------------------------

Aproach 2

--------------------------------------------------------------------------------------------
Test #1

```
IEnumerable<ITweet> tweets = Search.SearchTweets(new SearchTweetsParameters(hashtag)
{
        GeoCode = new GeoCode(-0.220102, -78.5119250, 50, DistanceMeasure.Kilometers),
        SearchType = SearchResultType.Popular
});
```

Return 0 tweets.
--------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------
Test #2

```
IEnumerable<ITweet> tweets = Search.SearchTweets(new SearchTweetsParameters(hashtag)
{
        GeoCode = new GeoCode(-0.220102, -78.5119250, 50, DistanceMeasure.Kilometers),
});
```

Return 100 tweets.
--------------------------------------------------------------------------------------------


After all that tests, I'm not sure yet if there is a issue with the library or there is limitation with twitter API, when I try to search tweets for popular keyword from specific location. Or perhaps, I have seen there is a new update of the library, and could be solution.

Thanks you for quick support,

Alex

**Comment by linvi** [comment]
Hello alex1389, this is a very busy time and I unfortunately cannot take enough time to look at your issue for the moment.

I will update this post as soon as I have.

Sorry for any inconvenience.

**Comment by alex1389** [comment]
Hello @linvi 

I understand you don't have so much time for support. 

Only need a functional example of a search of tweets filtered by location and popularity, that is the main problem for me right now, and I need it solve Asap.

Thanks,
Alex

**Comment by alex1389** [comment]
Hello, @linvi 
Any news about the **## requested detail**??

**Comment by linvi** [comment]
Hello,

I had a look into your problem.

> Test #1

Your problem is that you are attempting to get popular tweets only. This type of tweets are quite rare, and in addition to this, you force the tweet to have coordinates, which most tweets don't have.

Your filters are therefore just too restrictive to be able to match any result.

I have personally been able to match 1 result with broader hashtags and the popular attribute.

> Test #2

Works because 46 tweets seems to have been published with your tag but all of them must not have any geo information. 

If you want tweets with only geo information you can filter your search results with the following `.Where` clause.

`var tweetsWithGeoInfo = tweets.Where(x => x.Coordinates != null || x.Place != null);`

Same explanation for the `Approach 2`.

> After all that tests, I'm not sure yet if there is a issue with the library or there is limitation with twitter API, when I try to search tweets for popular keyword from specific location. Or perhaps, I have seen there is a new update of the library, and could be solution.

It is definitely not an issue with the library, just that your search is too restrictive.

Sorry for the long delay before answering. I usually reply the same day but I have been really overbooked recently.

Have a great day.

**Comment by alex1389** [comment]
Hi @linvi 
Thanks for your support, I know this tool/Free Twitter API have some limits, but the paid version have not all the info what I need right now, any way I have solve with this. Thanks.

Let me ask you some question, Do you know any good library like Tweetinvi but dedicated for Facebook API? I need to do the same but now for facebook.

Kind Regards,
Alex

**Comment by linvi** [comment]
> Thanks for your support, I know this tool/Free Twitter API have some limits, but the paid version have not all the info what I need right now, any way I have solve with this. Thanks.

I am not sure I understand. Search in Twitter Public API is only returning Tweets for the past 7 days.
`Popular` tweets are tweets that have been seen/liked/retweet a lot of times. What I said is that popular tweets of the last 7 days have a high chance to not have been published from the location you are trying to track.

> Let me ask you some question, Do you know any good library like Tweetinvi but dedicated for Facebook API? I need to do the same but now for facebook.

I don't know any in C#, I usually use the javascript ones.

**Comment by alex1389** [comment]
Hi,

Thanks for support, so far everything is ok with the library and results, I have two questions:

1- This library have some function to set a new user to follow??, I have been looking the docs but nothing similar.

2- What is the name of tha library in Javascript for Facebook??

Kind Regards,
Alex

**Comment by linvi** [comment]
1. Tweetinvi implements ALL the endpoints of the Twitter REST and Stream API. If you think any is missing please let me know. I know the doc should be improved and we have planned to do a website for the documentation but it takes a lot of time.

As per following a user you can do the following :

``` c#
var userToFollow = User.GetUserFromScreenName("tweetinviapi");
var success = User.FollowUser(userToFollow);

// or shorter
var success = User.FollowUser("tweetinviapi");
```

2. https://developers.facebook.com/docs/javascript

**Comment by ThuytienVo** [comment]
hi everyone
this is my full code: 
public Twitter()
        {
            var credentials = Auth.CreateCredentials(accessToken, accessSecrectToken, comsumerKey, comsumerSecretKey);
            Auth.SetCredentials(credentials);
        }
before I created a new Twitter, and used search tweet with searchparameter, but it always returned 0 result. Please tell me why it didn't work?
            var searchParameter = Search.CreateTweetSearchParameter("#hashtag");
            searchParameter.Lang = LanguageFilter.English;
            searchParameter.MaximumNumberOfResults = 200;
            searchParameter.Since = new DateTime(2010, 12, 1);
            var tweets = Search.SearchTweets(searchParameter);
