### ISSUE TITLE
Tweets and retweets aren't sent

### ISSUE THREAD

**Issue by testaco23** [linvi/tweetinvi#353]
I tried to make a simple app for retweets but it doesn't work. The credentials are correct since GetAuthenticatedUser() returns the user I want, but when it comes to posting tweets and retweets I get an exception. 

This is the code:
```
string consumerKey = "***";
string consumerSecret = "***";
string accessToken = "***";
string accessTokenSecret = "***";

Auth.SetUserCredentials(consumerKey, consumerSecret, accessToken, accessTokenSecret);

var firstTweet = Tweet.PublishTweet("Test");
//or
Tweet.PublishRetweet(782589609213648900);
```

The exception I'm getting for the tweet is:

> An unhandled exception of type 'Tweetinvi.Exceptions.TwitterException' occurred in Tweetinvi.dll
> Additional information: https://api.twitter.com/1.1/statuses/update.json?status=Test web request failed.

And for the retweet:

> An unhandled exception of type 'Tweetinvi.Exceptions.TwitterException' occurred in Tweetinvi.dll
> Additional information: https://api.twitter.com/1.1/statuses/retweet/782589609213648900.json?trim_user=true web request failed.

**Comment by linvi** [comment]
To help you I will need to have more details regarding the exception that is thrown.

Also, could you please verify that you have not already created a tweet 'Text'.
Twitter does not allow to publish the same Tweet twice in a row.

**Comment by testaco23** [comment]
Yes, I haven't made another tweet like this, I haven't managed to tweet or retweet anything so far through the app.

Here's the whole exception:

> Tweetinvi.Exceptions.TwitterException was unhandled
>   HResult=-2146233079
>   Message=https://api.twitter.com/1.1/statuses/retweet/781606127452745728.json?trim_user=true web request failed.
>   Source=Tweetinvi
>   StatusCode=401
>   TwitterDescription=Unauthorized -  Authentication credentials were missing or incorrect.
>   URL=https://api.twitter.com/1.1/statuses/retweet/781606127452745728.json?trim_user=true
>   StackTrace:
>        at Tweetinvi.Credentials.TwitterAccessor.HandleQueryException(TwitterException ex)
>        at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method, HttpContent httpContent, Boolean forceThrow)
>        at Tweetinvi.Credentials.TwitterAccessor.ExecutePOSTQuery[T](String query, JsonConverter[] converters)
>        at Tweetinvi.Controllers.Tweet.TweetQueryExecutor.PublishRetweet(Int64 tweetId)
>        at Tweetinvi.Controllers.Tweet.TweetController.PublishRetweet(Int64 tweetId)
>        at Tweetinvi.Tweet.PublishRetweet(Int64 tweetId)
>        at NEW.Program.Main(String[] args) in C:\Users\tiger\Desktop\NEW\NEW\NEW\Program.cs:line 30
>        at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
>        at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
>        at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
>        at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>        at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>        at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>        at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>        at System.Threading.ThreadHelper.ThreadStart()
>   InnerException: 

Yet I'm pretty sure the credentials are correct, since they're working for the methods for AuthenticatedUser.

**Comment by testaco23** [comment]
Turns out it got solved by regenerating the access and consumer tokens through the app panel. I had the permissions as Read/Write already but it probably didn't update the credentials when I changed the permissions from simple Read.
