### ISSUE TITLE
Filtered Stream Problem

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#354]
Hi Guys 
I am Mike Hobbs 
I am facing Problem in Filtered stream from few days which is not gonna sort out.
Scenario:
i have 10 keywords which i want to stream parallel from filtered stream. but stream return Tweet of one or two keyword(s) only other remain silent/not getting tweet. what is the issue? 

My code Snippet

``` c#
public void Keywords()
        {
            List<string> Keywordlist = new List<string>();
            Keywordlist.Add("Obama");
            Keywordlist.Add("Clinton");
            Keywordlist.Add("Trump");
            Keywordlist.Add("Perry");
            Keywordlist.Add("Messi");
            Keywordlist.Add("Jolie");
            Keywordlist.Add("Kim");
            Keywordlist.Add("Brad");
            foreach (var keys in Keywordlist)
            {
                Task.Factory.StartNew(() => StreamKeywords(keys));
            }

        }
        public void StreamKeywords(string keyword)
        {
             var credentials = Auth.SetUserCredentials("CK", "CSK", "AT", "AST");

             Auth.ExecuteOperationWithCredentials(credentials, () =>
             {
                 var fs = Stream.CreateFilteredStream();
                 fs.AddTrack("");
                 fs.MatchingTweetReceived += (s, a) =>
                 {
                     Console.WriteLine(a.Tweet.Text);
                 };
                 fs.StartStreamMatchingAllConditions();

             });
        }
```

**Comment by linvi** [comment]
Twitter does not allow single account to run multiple `FilteredStream`.
You will have to add multiple tracks to the same stream.

If you want to have a specific way to react to a keyword you can use `AddTrack(string keyword, ITweet => void)` and use the second parameter to react to a Tweet. 
If you don't care about the keyword simply use the `MatchingTweetReceived` event.

``` c#
TweetinviEvents.QueryBeforeExecute += (sender, args) =>
{
    Console.WriteLine(args.QueryURL);
};

var fs = Stream.CreateFilteredStream();

fs.AddTrack("apple", tweet =>
{
    Console.WriteLine("apple tweet received");
});

fs.AddTrack("hello", tweet =>
{
    Console.WriteLine("hello tweet received");
});

fs.StartStreamMatchingAllConditions();
```

**Comment by mike2341** [comment]
You mean say if i have 100 keywords then i have to make 100 tracks? its not suitable solution.

**Comment by mike2341** [comment]
TweetinviEvents.QueryBeforeExecute += (sender, args) =>
{
    Console.WriteLine(args.QueryURL);
};
And why i need these line of code for Stream?

**Comment by mike2341** [comment]
@haseeb1431 @linvi ?

**Comment by linvi** [comment]
> You mean say if i have 100 keywords then i have to make 100 tracks? its not suitable solution.

Twitter does limit intentionally what you can do with streams. So that if you want to do more, you have to pay for GNIP.

You must run 1 stream per account. If you want to run more you will have to use multiple accounts and potentially proxies/vpn to hide your ip from Twitter because they are tracking such behaviour and blocking accounts that try to do such thing,

> And why i need these line of code for Stream?

Sorry this line is not relevant.

**Comment by mike2341** [comment]
Mr. @linvi 
Lets suppose i make 30 tracks which retrieve data from 30 keywords. Are all tracks works fine against one credential account? if not then whats the reason?
Any alternate for this scenario using Rest API.

**Comment by linvi** [comment]
Yes they are all fine. 

You can find the limitations here : https://dev.twitter.com/streaming/reference/post/statuses/filter

> The default access level allows up to 400 track keywords, 5,000 follow userids and 25 0.1-360 degree location boxes. If you need elevated access to the Streaming API, you can contact Gnip.

To get more information about the track filter itself you can see more here : https://dev.twitter.com/streaming/overview/request-parameters#track

**Comment by linvi** [comment]
Also note that if your problem is about performances, I would suggest that you use a queue and add the tweets in this queue.

Then another process/thread can be responsible to process the data.

**Comment by mike2341** [comment]
i am getting your point to add tweet in queue. can you give me some code snippet how to add them?

**Comment by linvi** [comment]
If you are scared about the performances of your machine, I am saying that you can use a queue like RabbitMQ and consumer your tweets with multiple computers accessing your queue.

**Comment by linvi** [comment]
I hope this has made some sense. In the meantime, I am closing this issue.
