### ISSUE TITLE
Getting Issue in Retweet Counts and Likes Count

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#357]
Hi Mr @linvi 

 I am Getting tweet on base of hashtag from filtered stream and save in to my database. after sometime retweet count of my tweets are different from actual tweet which is on twitter. because Twitter is LIVE
the problem is how can i update my database tweets that they can match with twitter results.
MY code.

``` c#
var fs = Stream.CreateFilteredStream();
fs.AddTrack("#hashtag");
fs.MatchingTweetReceived += (s,a) =>
{
    insertintoDB(a.Tweet.Text, a.Tweet.RetweetCount);
};

fs.StartStreamMatchingAllConditions();
 ```

**Comment by JoshKeegan** [comment]
You'll have to fetch newer versions of each Tweet from the REST API.

How that happens is up to you and will depend on your use case. 
If you need your DB to be kept up to date, you'll have to regularly poll for them. If this is something a user would navigate to, then perhaps you make a REST API call when the user view the Tweet(s).

**Comment by mike2341** [comment]
its very hectic solution for example i have 40000 tweet against specific hashtag so for update i have to iterate all my tweets to rest api To Update retweet count and Likes count? Are you serious? its Time consuming too. Mr @linvi Help me out if you have any solution/suggestion?

**Comment by linvi** [comment]
Yes it is a very basic solution but unfortunately only GNIP for which you have to pay provide the tools that would help you to do that. 

Therefore, @JoshKeegan solution is the best solution that you can follow if you do not want to pay and use the Twitter public API.
