### ISSUE TITLE
Request Accept Header

### ISSUE THREAD

**Issue by ssiko** [linvi/tweetinvi#359]
I am trying to access the Ads Api using Tweetinvi. I am using the following: 

`var result = Auth.ExecuteOperationWithCredentials(TwitterCredentials, () => { return  TwitterAccessor.ExecuteGETQueryReturningJson("https://ads-api.twitter.com/1/accounts"); });`

I am getting a 406 response back which seems to indicate there is an issue in content negotiation. I see an `Accept: image/jpeg` header in the request. Is there a way to manipulate the accept header for requests coming out of tweetinvi. I do get a valid response when sending this request through the browser with a different Accept header.

**Comment by linvi** [comment]
Thank you for looking into this issue. I will have to verify your change and I will probably add a new property in `TwitterQuery` and potentially in `TweetinviConfig` that give users the ability to in addition specify their own headers.
