### ISSUE TITLE
Get tweets written inside a tweet

### ISSUE THREAD

**Issue by AlishbaZ** [linvi/tweetinvi#362]
Hello linvi.
I need to get the urls that are written inside a tweet. For example:

Ready to go further? The #HTC10's battery stands out of the crowd in this side-by-side comparison. http://bgr.com/2016/09/29/iphone-7-vs-htc-10-vs-galaxy-s7/  #powerof10

So if this is the tweet posted by an account I need to get the below link
http://bgr.com/2016/09/29/iphone-7-vs-htc-10-vs-galaxy-s7/

Kindly help me. how will I be able to get the URL that is written inside a tweet. Is there a property for getting such URLs ? 
Waiting for reply. Thank you in advance :)

**Comment by haseeb1431** [comment]
I don't one specifically developed inside the library. You can use regular expression to parse the tweets and extract the URLs.

**Comment by AlishbaZ** [comment]
@linvi cant I get it by any property or something? 
Please reply I need it must for my project. Thank you.

**Comment by JoshKeegan** [comment]
If this is a tweet you're receiving, look at the `Urls` property of an `ITweet`.

**Comment by linvi** [comment]
@JoshKeegan is correct. Use the `ITweet.Urls` property to access all the urls displayed in a Tweet.
