### ISSUE TITLE
Target Newtonsoft.Json 8.0.3 

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#364]
Having a lesser dependency might help some developers to enhance their compatibility with their projects.

https://github.com/linvi/tweetinvi/issues/363

**Comment by JoshKeegan** [comment]
Depending on a lower version is fine, but can I check that it will still be tested against the latest version as well?
That's the most important thing for me, as otherwise Tweetinvi will end up causing the same problem for another project!

**Comment by linvi** [comment]
It will be tested on the latest version only ;)

**Comment by linvi** [comment]
I have tought about this and I don't think this is necessary.

Closing...
