### ISSUE TITLE
can't get Retweet limit

### ISSUE THREAD

**Issue by MokaRex** [linvi/tweetinvi#365]
hi i trying to get update for retweet limit , but all time it give me 180 
the code

`Dim rate5 = ratelimit.TweetPromptsShowLimit.ToString
        XylosTextBox12.Text = rate5
        Dim rate6 = ratelimit.StatusesRetweetsOfMeLimit.ToString
        XylosTextBox12.Text = rate6
        Dim rate7 = ratelimit.StatusesRetweetsIdLimit.ToString`

**Comment by linvi** [comment]
The limit for publishing retweets is the same as the limit for publishing tweets which is 2400 tweets per day divided in intervals of 15 minutes (= 25 tweets every 15 minutes).

Though Tweets and Direct Messages RateLimits are different from the other RateLimits as they will be more tolerant. You could therefore be able to post 40 tweets in 15 minutes without Twitter preventing you to do so. But as a general rule, you should not try to publish more than 25 tweets every 15 minutes as you will not be able to predict if Twitter will accept the request.

You can find the official documentation here : https://support.twitter.com/articles/15364
