### ISSUE TITLE
How to Get 1st Tweet against A specific Keyword

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#366]
i am using rest api i want to get the tweet in which first time the Specific hashtag is mentioned.
Any help and suggestion will be appreciated.

**Comment by linvi** [comment]
Sorry I do not understand what you are trying to do.

**Comment by mike2341** [comment]
I mean to say I am getting Tweets of specific Keyword Like my Keyword is #Trump. so How can i get that tweet in which #Trump is mentioned first time.

**Comment by haseeb1431** [comment]
I am not aware of anything such thing provided by twitter public API. 

Also even if we try to develop a mechanism ourselves, public API is only 1% of actual tweets so we cannot guarantee that our identified tweet will be correct. 

You may want to look at this as well.  http://ctrlq.org/first/

**Comment by linvi** [comment]
The public API does not provide such feature.
Please look at the link provided by @haseeb1431.
