### ISSUE TITLE
Ton Api 308 response.

### ISSUE THREAD

**Issue by ssiko** [linvi/tweetinvi#367]
The ton api returns a 308 response during a PUT to their resumable upload, to indicate that they are ready for the next range of bytes:

https://dev.twitter.com/rest/ton/resumable

I had to alter this line to get around the exception due to the definition of `IsSuccessStatusCode`:

https://github.com/linvi/tweetinvi/blob/master/Tweetinvi.WebLogic/WebRequestExecutor.cs#L49

**Comment by linvi** [comment]
Thanks, I will take a look into this before the release of version 1.2.
