### ISSUE TITLE
Xamarin Forms PCL project - Unable to Nuget package install tweetinvi

### ISSUE THREAD

**Issue by ConsentDevelopment** [linvi/tweetinvi#368]
If you create a new Xamarin forms PCL project and try to install tweetinvi through the Nuget package installer then it fails to install with the following error - 

Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

This is not a tweetinvi issue as such but at the moment it is impossible to install it.

Maybe there is another way to install it with selective assemblies pre-installed?

**Comment by linvi** [comment]
Please provide ALL the information regarding your project.
Are you using Xamarin Studio or Visual Studio?
Which version of .NET do you target, and which PCL version are you targeting.

If you can please describe all the different steps allowing you to reproduce this issue,

Thanks

**Comment by ConsentDevelopment** [comment]
Everything is now working.  I am using Visual Studio and I was targeting the default the default Xamarin PCL profile 259.

I got it working by changing the Xamarin PCL project to use the .Net Standard system which is set to version 1.1.  The .Net target version is now 4.6.

The project.json file also has to be updated with the following added to the netstandard1.1 tag :
 
"imports": ["portable-net45"]

**Comment by linvi** [comment]
Hello,

Thanks for the feedback. Please share your experience with Xamarin in this post as I have not worked on it for quite some time now.

Unfortunately I can experience the same issue as you are but I do not need to use the `imports` in order for Tweetinvi to be properly referenced in the project, do you?

Cheers

**Comment by ConsentDevelopment** [comment]
Hello, I should mentioned this above.  The imports is only needed to get the Xamarin PCL to build.  It is not needed for tweetinv to install correctly.

Thanks for the cool twitter library :)

**Comment by linvi** [comment]
Hello there,

Could you please try to use Tweetinvi 1.2-alpha2 and tell me if this works for you (https://www.nuget.org/packages/TweetinviAPI/1.2.0-alpha2).
It should work in theory but I would like to make sure it does for you.

Nuget command : `Install-Package TweetinviAPI -Pre`

Thanks
