### ISSUE TITLE
Restricted from perform write operation

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#369]
Why twitter restrict me always when i want to publish a tweet? what i have to do my application has been blocked.

**Comment by linvi** [comment]
Hello,

Please try to ask this type of question on stackoverflow or twittercommunity as this is not a question about Tweetinvi and I am currently very busy to the point where I cannot answer to everyone.

To answer your question, your problem probably comes from the fact that you are attempting to publish more than 25 tweets every hour.

Twitter has what they call "adaptive rate limits" for publishing tweets and messages. Which means that you are allowed to publish 2400 tweets per day. This 2400 is divided in chunks of 15 minutes (hence 25 tweets), but if you go over 25 they will not block you straight away. They will block you if you attempt to publish more than 25 every 15 minutes too many times.

The Twitter team thinks that this allow them to prevent spam.

I hope this makes sense.

**Comment by linvi** [comment]
Let me know if this helped.
