### ISSUE TITLE
The type initializer for 'Tweetinvi.TwitterCredentials' threw an exception.

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#37]
As reported on codeplex: https://tweetinvi.codeplex.com/workitem/2649

**Comment by SpireHex** [comment]
This has re-appeared! I can no longer use Auth.SetCredentials(); !

**Comment by linvi** [comment]
Does the error happens consistently?

**Comment by prajjwaldimri** [comment]
Happening with my project too. When requesting the Authentication url from twitter using CredentialsCreator it throws three exceptions:

Exception thrown: 'System.IO.FileLoadException' in Tweetinvi.dll
Exception thrown: 'System.TypeInitializationException' in Tweetinvi.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.ni.dll

**Comment by linvi** [comment]
Would you be able to share your project?

**Comment by prajjwaldimri** [comment]
Yup, here's the repo: https://github.com/prajjwaldimri/Friend-App

**Comment by linvi** [comment]
Thanks, I will take a look at this when I am out of work.

**Comment by prajjwaldimri** [comment]
Alright. Thanks

**Comment by linvi** [comment]
Install with the following command in nuget : 

`Install-Package tweetinviapi -version 0.9.10.2-w10-uap -pre`

Let me know if this worked out for you.

Linked to https://github.com/linvi/tweetinvi/issues/105
