### ISSUE TITLE
Search Tweets Problem

### ISSUE THREAD

**Issue by alex1389** [linvi/tweetinvi#370]
Hello Everybody and @linvi 

Anyone can tell or show me an example of a **tweet search by location and filtered by popularity**??

I'm trying a lot to do it, but there seems to be an error. 

`tweets = Search.SearchTweets(new SearchTweetsParameters(hashtag)
{
GeoCode = new GeoCode(-0.220102, -78.5119250, 50, DistanceMeasure.Kilometers),
TweetSearchType = TweetSearchType.OriginalTweetsOnly,
//SearchType = SearchResultType.Popular                            
});`

This is an example of what I'm trying, I had to comment the line for SearchType because then return 0 tweets.

Thanks!
Alex

**Comment by linvi** [comment]
I think I have just replied to your issue here : https://github.com/linvi/tweetinvi/issues/352.
Let me know if you still have any question.
