### ISSUE TITLE
Cannot Differentiate between Tweet and Retweet 

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#371]
Hi @linvi How are you?

I am getting tweet against specific keyword and save into database. but my issue is 

``` c#
var SearchResults = Search.SearchTweets("#Trump");
foreach(var tweet in SearchResults )
{
	if (Tweet.IsRetweet)
	{
		//retweet goes here
		// i am getting retweet like this
		var tweetText=Tweet.retweetedTweet.text;
	}
	else
	{
		//Tweet goes here
		var tweetText=Tweet.text;
	}
}
```

Both gives me original tweet data how can i consider Original Tweet as Tweet and Retweet as retweet

**Comment by linvi** [comment]
Sorry, I do not understand your question. Could you please provide more information as to what is causing your problems?

Please not that the code you provided does not work because of capitalization.

**Comment by mike2341** [comment]
I set TweetId as primary key in my tweet table. when someone tweet on my streaming keyword it comes into my database but when someone retweet (of this previous tweet which are in database) error comes out as primary key violation because tweet and retweet id are same.
so how can i save tweet and retweet in db.
i am getting reTweet Id Like This

var Id= Tweet.RetweetedTweet.Id;

and Tweet Id Like this

var Id=Tweet.Id;

**Comment by linvi** [comment]
Well your code is just wrong and the error seems legitimate as you are intentionally using the id of the retweeted tweet (`var Id= Tweet.RetweetedTweet.Id;`) which mean that if you already inserted the id of the original tweet there will be an error.

This problem has nothing to do with Tweetinvi but is purely a problem in your code logic I would say.

**Comment by mike2341** [comment]
Well thank you for response i sort it out.

but one thing i want to ask that i have more keyword i want to track. by using one AddTrack method i can track only one keywords track. is it possible that when i start my program i count my keywords and make AddTrack dynamically equal to keywords count like this

int count=6;

create dynamically add Track for every keyword. if it is possible then how?

**Comment by linvi** [comment]
Yes you can add up to 400 keywords to track. Keywords can only be added when the stream is not running.

``` c#
var fs = Stream.CreateFilteredStream();

fs.AddTrack("hello");
fs.AddTrack("hello2");

fs.StartStreamMatchingAllConditionsAsync();

// Later on you want to add a new track

fs.StopStream();
fs.AddTrack("hello3");

fs.StartStreamMatchingAllConditionsAsync();
// ...
```
