### ISSUE TITLE
how to check how much people see the trend on twitter

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#372]
i want to get idea how this calculation can be done in this API
like this 
https://twitter.com/manishinsa2485/status/785872304047742976
![capture](https://cloud.githubusercontent.com/assets/22609391/19592748/992e83e4-9796-11e6-83da-2728dd856ac3.JPG)

**Comment by linvi** [comment]
I have no idea how this is possible. You should probably ask this person directly.
