### ISSUE TITLE
MatchingTweetReceived event sometimes not called

### ISSUE THREAD

**Issue by GioviQ** [linvi/tweetinvi#377]
I cannot reproduce this issue, but sometimes when I call              

```
         stream.StartStreamMatchingAllConditionsAsync();
```

stream.MatchingTweetReceived += (sender, data) => is never called.

So I have to stop and restart my twitter bot.

**Comment by linvi** [comment]
Thank you for reporting this problem.

Have you been able to experience the same problem with `stream.StartStreamMatchingAllConditions` (non async).

Second question is, could you please tell me if the `stream.JsonObjectReceived` event is raised.
Same goes for the `stream.StreamStopped` event.

**Comment by GioviQ** [comment]
Ok thanks I'll try.
Have you ever write a twitter bot? At the moment I have to change my retweet and following strategy because Twitter blocked my account because "suspect activity"...

**Comment by linvi** [comment]
Yes you need to be smart about writing a bot.
Twitter has multiple mechanisms to detect them you will have to outsmart them but I think this is not so complicated.

**Comment by GioviQ** [comment]
Sometimes immediately after stream start, I receive StreamStopped event, so I have to start stream again.

**Comment by linvi** [comment]
Closing the problem as no further development for a while. Feel free to reopen it if needed.
