### ISSUE TITLE
cant get Trends ,

### ISSUE THREAD

**Issue by MokaRex** [linvi/tweetinvi#378]
when trying to get trends as shown in documents , i got error 
"An unhandled exception of type 'System.NullReferenceException' occurred in Tweetinvi.dll
Additional information: Object reference not set to an instance of an object."

code `var trendingTopics = Trends.GetTrendsAt(42);`

**Comment by linvi** [comment]
When I write `42` it means any correct value.

So if you try using `var trendingTopics = Trends.GetTrendsAt(1);` (1 being a valid geo id) you will get results.
