### ISSUE TITLE
Crash when no network is available

### ISSUE THREAD

**Issue by ConsentDevelopment** [linvi/tweetinvi#380]
Get the following exception when no network is available - 

Tweetinvi.Exceptions.TwitterException: Error: NameResolutionFailure

Calling the following code causes the exception -

```
var appCreds = Auth.SetApplicationOnlyCredentials("something", "something");
if (appCreds != null)
{
     Auth.InitializeApplicationOnlyCredentials(appCreds);
     _networkReady = true;
}
```

Does this exception also need to be handled by tweetinvi?

**Comment by ConsentDevelopment** [comment]
This is not urgent as I have added networking checking functionality to my app so the tweetinvi module will not be initialized if there is no internet connection.

**Comment by linvi** [comment]
I will consider this. I am not sure whether I want to actually throw an error for this case.

**Comment by linvi** [comment]
Hello. I have changed the signature `bool InitializeApplicationOnlyCredentials`.
The returned value represents the success of the operation.
