### ISSUE TITLE
ratelimit tracking issue

### ISSUE THREAD

**Issue by MokaRex** [linvi/tweetinvi#381]
sorry for annoying you , as a beginner hope to have help from you
i tried to search tweets using ur method to deal with rate limit but there is something wrong
hope u can take a look to the codes

``` c#
private void xylosButton5_Click(object sender, EventArgs e)
        {
            RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackOnly;
            listView1.Items.Clear();
            int i = 0;
            if (xylosTextBox7.Text == "")
            {
                MessageBox.Show("You must Write something to Search.... !!! ", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }
            TweetinviEvents.QueryBeforeExecute += (sender1, args) =>
            {
                MessageBox.Show("1");
                RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackAndAwait;
                MessageBox.Show("2");
                var queryRateLimits = RateLimit.GetQueryRateLimit(args.QueryURL);
                MessageBox.Show("3");
                if (queryRateLimits != null)
                {
                    MessageBox.Show("4");
                    if (queryRateLimits.Remaining > 0)
                    {
                        MessageBox.Show("5");
                        if (xylosCheckBox1.Checked == false)
                        {
                            MessageBox.Show("6");
                            var matchingTweets = Search.SearchTweets(xylosTextBox7.Text);

                            foreach (Tweetinvi.Models.ITweet t in matchingTweets)
                            {
                                string[] Data1 = new string[6];
                                Data1[0] = t.CreatedBy.ScreenName;
                                Data1[1] = t.Text;
                                Data1[2] = t.Retweeted.ToString();
                                Data1[3] = t.Favorited.ToString();
                                Data1[4] = t.Id.ToString();
                                ListViewItem lvi = new ListViewItem(Data1[0]);
                                lvi.SubItems.Add(Data1[1]);
                                lvi.SubItems.Add(Data1[2]);
                                lvi.SubItems.Add(Data1[3]);
                                lvi.SubItems.Add(Data1[5]);
                                listView1.Items.Add(lvi);
                                i = i + 1;

                                label6.Text = i.ToString();
                            }
                        }
                        else
                        {
                            var users = Search.SearchUsers(xylosTextBox7.Text, page: 2);
                        }
                        return;
                    }

                    args.Cancel = true;
                    MessageBox.Show("You are reached The RATELIMIT... Try another Account !", "RateLimit Error", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
            };
        }
```

**Comment by linvi** [comment]
This code is not correct. `TweetinviEvents.QueryBeforeExecute` is invoked when a user executes a query.
But here you never actually execute any query because your search query is actually located inside the event.

`var users = Search.SearchUsers(xylosTextBox7.Text, page: 2);` should be invoked outside of the `QueryBeforeExecute` scope.

**Comment by MokaRex** [comment]
like that ?
`private void xylosButton5_Click(object sender, EventArgs e)
        {
            RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackOnly;
            listView1.Items.Clear();
            int i = 0;
            if (xylosTextBox7.Text == "")
            {
                MessageBox.Show("You must Write something to Search.... !!! ", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }
            TweetinviEvents.QueryBeforeExecute += (sender1, args) =>
            {
                MessageBox.Show("1");
                RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackAndAwait;
                MessageBox.Show("2");
                var queryRateLimits = RateLimit.GetQueryRateLimit(args.QueryURL);
                MessageBox.Show("3");
                if (queryRateLimits != null)
                {
           
                    if (queryRateLimits.Remaining > 0)
                    {
                     
                       
                        return;
                    }

                    args.Cancel = true;
                    MessageBox.Show("You are reached The RATELIMIT... Try another Account !", "RateLimit Error", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
            };
 if (xylosCheckBox1.Checked == fa
MessageBox.Show("5");
                        if (xylosCheckBox1.Checked == false)
                        {
                            MessageBox.Show("6");
                            var matchingTweets = Search.SearchTweets(xylosTextBox7.Text);

                            foreach (Tweetinvi.Models.ITweet t in matchingTweets)
                            {
                                string[] Data1 = new string[6];
                                Data1[0] = t.CreatedBy.ScreenName;
                                Data1[1] = t.Text;
                                Data1[2] = t.Retweeted.ToString();
                                Data1[3] = t.Favorited.ToString();
                                Data1[4] = t.Id.ToString();
                                ListViewItem lvi = new ListViewItem(Data1[0]);
                                lvi.SubItems.Add(Data1[1]);
                                lvi.SubItems.Add(Data1[2]);
                                lvi.SubItems.Add(Data1[3]);
                                lvi.SubItems.Add(Data1[5]);
                                listView1.Items.Add(lvi);
                                i = i + 1;

                                label6.Text = i.ToString();
                            }
                        }
                        else
                        {
                            var users = Search.SearchUsers(xylosTextBox7.Text, page: 2);
                        }
        }`

**Comment by MokaRex** [comment]
what about conflict between Sender parameter in main void and event
