### ISSUE TITLE
winRT file or dependencies not found

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#382]
http://stackoverflow.com/questions/40113439/tweetinvi-and-winrt-file-or-dependencies-not-found/40173115#40173115

**Comment by clem91** [comment]
[Problem.zip](https://github.com/linvi/tweetinvi/files/552711/Problem.zip)
This is the simpliest solution i have wich reproduce the behavior descripted. Be careful, when you run it, you can't make it run on any CPU, you have to chose x86 or x64. Hope it will help

**Comment by linvi** [comment]
I was able to reproduce the issue. I will work on this as a priority.

**Comment by linvi** [comment]
In the meantime you can use the version 1.0 of Tweetinvi which does work properly.

**Comment by clem91** [comment]
Even with the 1.0 version I can't make it work. I will wait for the next version hoping it will solve this issue. Have a good day

**Comment by linvi** [comment]
Your project seems to be corrupted for some reason. When I try to create a new `Windows Runtime Component (Universal Window)` the project can compile properly with alpha 2.

Could you please verify?

**Comment by clem91** [comment]
I tried without success. How have you added the winRT component? Do you call some classes using tweetinvi in WinJS?

**Comment by linvi** [comment]
Sorry for the very late reply. You can download  a working project here :

https://github.com/linvi/tweetinvi.issues/raw/master/Tweetinvi.382.zip
