### ISSUE TITLE
PublishRetweet and MultiThreading

### ISSUE THREAD

**Issue by GioviQ** [linvi/tweetinvi#383]
```
Auth.ExecuteOperationWithCredentials(Auth.Credentials, () =>
{
    tweet.PublishRetweet();
});
```

`PublishRetweet` still using `Auth.ApplicationCredentials` the same with `Auth.SetUserCredentials(config.ConsumerKey, config.ConsumerSecret, config.AccessToken, config.AccessTokenSecret);`

How can I retweet using current thread credentials?

**Comment by linvi** [comment]
Hi please look at the threading and credentials wiki and let me know if it helps : 

* https://github.com/linvi/tweetinvi/wiki/Credentials
* https://github.com/linvi/tweetinvi/wiki/MultiThreading#threads

``` c#
var t = new Thread(() =>
{
    Auth.SetUserCredentials("", "", "", "");
    var user = User.GetAuthenticatedUser();
});

t.Start();
```

**Comment by GioviQ** [comment]
Maybe a silly question... but the empty strings are just placeholders for real parameters, isn't it?
If so I've just done so and retweet goes under application credentials not user credentials.

**Comment by GioviQ** [comment]
This is an extract of the twitter bot code with retweet.

The problem arise when I started 2 of these bots with different credentials


       using System;
       using System.Collections.Concurrent;
       using System.Linq;
       using System.Threading;
       using Tweetinvi;
       using Tweetinvi.Models;
       using Tweetinvi.Streaming;

    namespace SocialBot.Models
    {
        public class TwitterBot
        {
            private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private TwitterConfig config;
        IFilteredStream stream;
        IAuthenticatedUser currentUser;

        private ConcurrentQueue<ITweet> queue;
        private Thread _consumerThread;

        private bool loop = true;

        public TwitterBot(TwitterConfig config)
        {
            this.config = config;

            Auth.SetUserCredentials(config.ConsumerKey, config.ConsumerSecret, config.AccessToken, config.AccessTokenSecret);

            currentUser = User.GetAuthenticatedUser();           

            stream = Stream.CreateFilteredStream();

            string[] wordsToRetweet = config.wordsToRetweet.Split('|');

            string[] wordsNotToRetweet = config.wordsNotToRetweet.Split('|');

            foreach (string word in wordsToRetweet)
                stream.AddTrack(word);

            stream.DisconnectMessageReceived += Stream_DisconnectMessageReceived;
            stream.JsonObjectReceived += Stream_JsonObjectReceived;
            stream.LimitReached += Stream_LimitReached;
            stream.StreamStopped += Stream_StreamStopped;
            stream.StreamPaused += Stream_StreamPaused;
            stream.WarningFallingBehindDetected += Stream_WarningFallingBehindDetected;

            stream.MatchingTweetReceived += (sender, data) =>
            {
                bool contains = false;
                foreach (string word in wordsNotToRetweet)
                    contains |= data.Tweet.FullText.ToLower().Contains(word);

                if (!contains && !data.Tweet.CreatedBy.Equals(currentUser))
                {
                    queue.Enqueue(data.Tweet);

                    log.InfoFormat("New tweet '{0}' for {1} stream", data.Tweet.FullText, currentUser.ScreenName);
                }

            };

            queue = new ConcurrentQueue<ITweet>();
            _consumerThread = new Thread(Consumer) { Name = string.Format("TwitterConsumerThread{0}", currentUser.ScreenName), IsBackground = true };
        }

        private void Stream_WarningFallingBehindDetected(object sender, Tweetinvi.Events.WarningFallingBehindEventArgs e)
        {
            log.DebugFormat("Stream_WarningFallingBehindDetected {0}", e);
        }

        private void Stream_StreamPaused(object sender, System.EventArgs e)
        {
            log.DebugFormat("Stream_StreamPaused {0}", e);
        }

        private void Stream_StreamStopped(object sender, Tweetinvi.Events.StreamExceptionEventArgs e)
        {
            log.DebugFormat("Stream_StreamStopped {0}", e);
        }

        private void Stream_LimitReached(object sender, Tweetinvi.Events.LimitReachedEventArgs e)
        {
            log.DebugFormat("Stream_LimitReached {0}", e);
        }

        private void Stream_JsonObjectReceived(object sender, Tweetinvi.Events.JsonObjectEventArgs e)
        {
            log.DebugFormat("Stream_JsonObjectReceived {0}", e);
        }

        private void Stream_DisconnectMessageReceived(object sender, Tweetinvi.Events.DisconnectedEventArgs e)
        {
            log.DebugFormat("Stream_DisconnectMessageReceived {0}", e);
        }

        public void Start()
        {
            loop = true;

            _consumerThread.Start();

            stream.StartStreamMatchingAllConditionsAsync();

            log.InfoFormat("TwitterBot {0} started.", currentUser.ScreenName);
        }

        public void Stop()
        {
            stream.StopStream();

            loop = false;

            _consumerThread.Join();

            log.InfoFormat("TwitterBot {0} stopped.", currentUser.ScreenName);
        }

        private void Consumer()
        {
            try
            {
                Auth.SetUserCredentials(config.ConsumerKey, config.ConsumerSecret, config.AccessToken, config.AccessTokenSecret);

                while (loop || queue.Count > 0)
                {
                    if (!loop)
                        log.InfoFormat("There are {0} tweets to process.", queue.Count);

                    ITweet tweet = null;

                    queue.TryPeek(out tweet);

                    if (tweet != null)
                    {
                     
                                //if  some social bot logic
                                {
                                        tweet.PublishRetweet();                                 

                                    log.InfoFormat("Retweet completed by {0}.", currentUser.ScreenName);
                                }
                        }

                        queue.TryDequeue(out tweet);
                    }
                }

            }
            catch (ThreadAbortException)
            {
                Thread.ResetAbort();
            }
        }

        ~TwitterBot()
        {
            Stop();
        }
    }
}`

**Comment by linvi** [comment]
Hi, I think you are not aware that stream does not act the same way as REST calls regarding Thread credentials.

Have a look over there :
https://github.com/linvi/tweetinvi/wiki/Streams#stream-and-credentials

``` c#
// Thread1 credentials
Auth.SetUserCredentials(thread1Credentials);

// Create the stream and store the Thread1 credentials in stream.Credentials
stream = Stream.CreateFilteredStream();

// Thread2
var t = new Thread(() =>
{
    // Thread2 credentials
    Auth.SetUserCredentials(thread2Credentials);

    // Uses Thread1 credentials by default
    stream.StartStreamMatchingAllConditions();
});
```

**Comment by GioviQ** [comment]
Anyway my twitter bot does not work correctly because tweet.PublishRetweet();  does not use current thread credential and I do not know how can I set them. Streams work well, I process tweets in consumer thread.

**Comment by GioviQ** [comment]
Maybe I should use Tweet.PublishRetweet(<tweet_identifier>); instead of  tweet.PublishRetweet();  ?

In the wiki I cannot find a clear solution of my issue.

**Comment by linvi** [comment]
Try the following code :

``` c#
var stream = Stream.CreateSampleStream();

var creds = new TwitterCredentials(/* your creds config */);
var t = new Thread(() =>
{
    stream.TweetReceived += (sender, args) =>
    {
        Auth.ExecuteOperationWithCredentials(creds, () =>
        {
            args.Tweet.PublishRetweet();
        });
    };

    stream.StartStream();
});
```

**Comment by linvi** [comment]
`Auth.ExecuteOperationWithCredentials` allow you to execute an operation using a specific set of credentials.

**Comment by GioviQ** [comment]
In my twitter bot code above I use now
Tweet.PublishRetweet(tweet) instead of tweet.PublishRetweet()

2 bots are currently running and they just seems to work as expected, so Tweet.PublishRetweet(tweet) works as I suppose using current thread credentials instead of tweet.PublishRetweet().

Anyway this behavior is not consistent. A fix or wiki explanation is needed.

Auth.ExecuteOperationWithCredentials not works for me, this was the first thing I tried to do.

**Comment by linvi** [comment]
`Tweet.PublishRetweet(tweet)` and `tweet.PublishRetweet()` are using the same code behind the scene.

I still do not understand what is wrong. Are you saying that the ReTweet you are trying to publish, does not publish or that it does not publish with the correct account?

**Comment by GioviQ** [comment]
it publish but with wrong account. Have you tried my code?

**Comment by GioviQ** [comment]
Tweet.PublishRetweet use threadstatic controller, maybe this is the difference

**Comment by GioviQ** [comment]
I have just started 3 TwitterBot class instances and all works as expected like with 2 bots

**Comment by linvi** [comment]
Hello, I am back and ready to provide more help. Sorry for such a long absence.
Could you please let me know what is the current state of this bug please?

**Comment by GioviQ** [comment]
I am still using Tweet.PublishRetweet(tweet) instead of tweet.PublishRetweet(). The former uses the current thread credentials, the latter not.

**Comment by linvi** [comment]
I have just understand why your code does not work. I will work on a fix as part of this release!

**Comment by GioviQ** [comment]
Bravo!

**Comment by linvi** [comment]
Thanks again for being very responsive and taking time to help. 
This bug was not obvious at first sight but when I got the revelation it was so obvious...

Thanks again, and enjoy Tweetinvi!

**Comment by eaba** [comment]
Hello @linvi am experiencing this same issues with multiple UserStream.
Receiving tweets work fine, but when replying it uses the credentials of the FIRST UserStream created (in a loop)......Its a big issue!!!

**Comment by linvi** [comment]
Hello @eaba, are you using `async`?

**Comment by eaba** [comment]
Yes @linvi 
Here #520 
I got it resolved!
