### ISSUE TITLE
search not retweeted tweets problem

### ISSUE THREAD

**Issue by MokaRex** [linvi/tweetinvi#390]
Hi , i have a problem when search not retweeted tweets , the results is mixed retweeted and not 

i used if (!t.retweeted) to add only not retweeted but reuslts as i told mixed

**Comment by linvi** [comment]
The `Retweeted` property is proper to the authenticated account.
I might rename it in the future by `RetweetByAuthenticatedUser`.

Does it help?

**Comment by MokaRex** [comment]
thanks man for ue support , the problem here , that all tweets give me False for retweeted , but when check some results i found many of these tweets already rretweeted by AuthenticatedUser 

i other words checking if tweet retweeted by AuthenticatedUser  always False even if it's true

**Comment by linvi** [comment]
Is the retweeted property that you are using is coming from the stream?

PS : Sorry for the long time I take to reply. I am way more than overbooked recently.

**Comment by MokaRex** [comment]
no , i did it by publishretweet()

**Comment by MokaRex** [comment]
no , i got it by tweet.retweeted as bool

**Comment by linvi** [comment]
My question where did you get the tweet from, `search`, `stream`, `Tweet.GetTweet`, `timeline`...

**Comment by MokaRex** [comment]
searchtweets ... sorry for misunderstand

**Comment by linvi** [comment]
The search api does not contain the information related to the authenticated user (i.e. Retweeted).

You can find this information in the documentation :

> In API v1.1, the response format of the Search API has been improved to return Tweet objects more similar to the objects you’ll find across the REST API and platform. However, perspectival attributes (fields that pertain to the perspective of the authenticating user) are not currently supported on this endpoint.

https://dev.twitter.com/rest/reference/get/search/tweets

What you will have to do is to retrieve the tweet again via their id.

``` c#
var tweetsFromSearch = Search.SearchTweets("keyword");
var tweetsWithPerspectivalAttributes = Tweet.GetTweets(tweetsFromSearch.Select(x => x.Id).ToArray());
```

**Comment by MokaRex** [comment]
very thanks man ,  after i did your advice i worked well and i got retweeted status correctly but adding tweets to listview is very slowly
