### ISSUE TITLE
Followers always empty

### ISSUE THREAD

**Issue by jscoys** [linvi/tweetinvi#391]
Hi,

I'm newbie with Twitinvi! So i think it's not an issue, but a newbie problem here... Anyway you help will be appreciated!

Here's my code :

``` c#
var userCredentials = Auth.CreateCredentials(consumerKey, consumerSecret, userAccessToken, userAccessSecret);
            
this.authenticatedUser = User.GetAuthenticatedUser(userCredentials);

var followers = this.authenticatedUser.GetFollowers();

Weird thing is that I'm always getting a "An unhandled exception of type 'Tweetinvi.Exceptions.TwitterNullCredentialsException' occurred in Tweetinvi.dll". If I use :

var user = User.GetUserFromScreenName(userName);
```

I'm getting the same exception. What I'm doing wrong? My consumerKey, consumerSecret, userAccessToken and userAccessSecret are well passed throught the CreateCredentials, and when I have a look into my userCredentials object in Debug Mode during execution, I have some information like name, TwitterAccount ID... so it is correctly connecting!

Thx for your help!

**Comment by linvi** [comment]
This might be a bug. Let me investigate and get back to you

**Comment by jscoys** [comment]
Thank you very much! Maybe it's my fault! Thx 4 help!

**Comment by jscoys** [comment]
Hello any news?

**Comment by linvi** [comment]
`var user = User.GetUserFromScreenName(userName);` requires you to set the thread credentials context.

`Auth.SetUserCredentials` instead of `Auth.CreateCredentials`.

You can learn more about credentials here : https://github.com/linvi/tweetinvi/wiki/Credentials.

**Comment by jscoys** [comment]
Thx a lot it worked!
