### ISSUE TITLE
How to Create or Reply Private Message with Media?

### ISSUE THREAD

**Issue by SharpStaff** [linvi/tweetinvi#392]
Hi,
How to Create or Reply Private Message with Media?

When publish tweet, PublishTweetOptionalParameters contains IMedia property, but when publish private message, PublishMessageParameters does not contain IMedia.

**Comment by SharpStaff** [comment]
Sorry, I have not seen

https://github.com/linvi/tweetinvi/issues/322

**Comment by linvi** [comment]
Yes. It's not available and I don't think twitter has this feature in mind in the foreseeable future.
