### ISSUE TITLE
web request failed error  , Manual dealing

### ISSUE THREAD

**Issue by MokaRex** [linvi/tweetinvi#393]
when i reach to limit in retweeting i got error "web request faile"

> An unhandled exception of type 'Tweetinvi.Exceptions.TwitterException' occurred in Tweetinvi.dll

Additional information: https://api.twitter.com/1.1/statuses/retweet/793942700739411968.json?trim_user=true web request failed.

how to work with this error manually

**Comment by linvi** [comment]
I am not sure what `how to work with this error manually` means, but if you want to handle it you can either use a `try/catch` or you can rely on Tweetinvi to return null/false when an operation does not work.

If you want to make sure that the you have the required remaining RateLimits you can read the [documentation](https://github.com/linvi/tweetinvi/wiki/Rate-Limits).

Could you show me the code that is causing you problem.

**Comment by MokaRex** [comment]
many thanks man , i did it  
`Try
                        tweets.PublishRetweet()
                    Catch ex As Tweetinvi.Exceptions.TwitterException
                        MsgBox("Can't Retweet Status , You Reached For Retweet Limit", MsgBoxStyle.Critical)
                        Exit Sub
                    End Try`

**Comment by MokaRex** [comment]
thanks , u can close this issue as it solved
