### ISSUE TITLE
How to Save Raw Tweet In to database.

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#396]
How can i save raw tweet which include every info about user and tweet to save into database. later on i will parse that tweet and separate all information and save them to their tables.
like we can save full json object in our cache table.  similarly i want this in tweetinvi. how to do this?

**Comment by linvi** [comment]
Hello, Tweetinvi gives the ability to serialize and deserialize tweets into json.

https://github.com/linvi/tweetinvi/wiki/Serialization-and-Deserialization
