### ISSUE TITLE
Filterd Stream Problems

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#397]
i have 30 keywords which i want to track from filtered stream.
solution one is that i can manually create 30 tracks for 30 keywords like 

``` c#
var fs = Tweetinvi.Stream.CreateFilteredStream();
                        fs.AddTrack("Keyword1");
fs.AddTrack("Keyword2");
so on 30........................
                                              fs.MatchingTweetReceived += (s, a) =>
                        {
                           
                            Console.WriteLine(a.Tweet);
                        }; 
fs.StartStreamMatchingAllConditions();

```
Ok fine this is suitable for constant 30 keywords. but if my keywords change dynamically how can i change my tracks dynamically. or my keywords numbers increased to 40 then how can i add 10 tracks dynamically without stopping my application?

**Comment by linvi** [comment]
You have to stop the stream. You have to understand that we perform an Http request specifying the parameters that need to be passed to.

Every track are part of this parameter. So you will have to stop the stream.
Tweetinvi will throw an error if you try to insert a track whilst the stream is running.
