### ISSUE TITLE
Upload.UploadVideo fails with video larger than 5mb

### ISSUE THREAD

**Issue by tpbraun** [linvi/tweetinvi#399]
Uploading a < 5mb video works fine.  Uploading a larger one fails with:

> URL : https://upload.twitter.com/1.1/media/upload.json?command=FINALIZE&media_id=(censored)
> Code : 400
> Error documentation description : Bad Request - The request was invalid or cannot be otherwise served. An accompanying error message will explain further. In API v1.1, requests without authentication are considered invalid and will yield this response.
> Error message : https://upload.twitter.com/1.1/media/upload.json?command=FINALIZE&media_id=(censored) web request failed.

I am using the following code:

```
var media = Auth.ExecuteOperationWithCredentials(creds, () =>
{
    //also tried: return Upload.ChunkUploadBinary(data, mediaType);
    return Upload.UploadVideo(data, mediaType);
});
```

**Comment by linvi** [comment]
I think the video you are trying to upload is probably not supported by Twitter. 

Please try this video : https://github.com/linvi/tweetinvi.issues/raw/master/1280x720-stereo-14.8%20MB.mp4. This one complies with the formats requested by Twitter.

You can find more about this here : https://dev.twitter.com/rest/media/uploading-media
