### ISSUE TITLE
Unable to install Tweetinvi Nuget Package

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#400]
i have visual studio 2013 professional i want to update my tweetinvi package from tweetinvi 1.0.0 to latest version but it gives me error every time. here is screenshot of error

![Uploading IJ_cIuwZ.jpg…]()

**Comment by linvi** [comment]
The image is not available. Could you reupload the image and also send me the log.

Thanks

**Comment by linvi** [comment]
This has probably been solved by version 1.2
