### ISSUE TITLE
Unhandled exception causing crash

### ISSUE THREAD

**Issue by ConsentDevelopment** [linvi/tweetinvi#402]
My app is getting the following crash - attached log.txt file.
[log.txt](https://github.com/linvi/tweetinvi/files/588059/log.txt)

Not sure if there is anything I can do my side to prevent it?

This is the first time I have seen this crash since using the library for over a month so it is a very, very rare crash,

Using library version 1.1.1

**Comment by linvi** [comment]
Thank you for reporting this bug. Could you please provide more information regarding the type of application that you have been using Tweetinvi with.

I will see what I can do about this, but it does look like an Autofac issue.

**Comment by ConsentDevelopment** [comment]
I am using a Xamarin forms app running on Android 7.0.  

I only use app-authentication and the method SearchAsync.SearchTweets().  I was asking for 520 results for the search query when the exception crash occurred.

**Comment by ConsentDevelopment** [comment]
I have not had the crash repeat but I have update to the latest AutoFac version 4.2.0 just to be safe.
