### ISSUE TITLE
Compile with Visual Studio 2010 and .NET Framework 4.0

### ISSUE THREAD

**Issue by Niko-O** [linvi/tweetinvi#404]
I **really** want to avoid doing my project in Visual Studio 2015.
But I cannot get projects to compile in Visual Studio 2010 when they have a reference to Tweetinvi.dll.

I have downloaded the Tweetinvi.1.1.-.Binaries.zip from https://github.com/linvi/tweetinvi/releases and added a reference to Tweetinvi.dll. Visual Studio gives these warning:
`Der Primärverweis "Tweetinvi" konnte nicht aufgelöst werden, da er eine indirekte Abhängigkeit von der Frameworkassembly "System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" aufweist, die im derzeit als Ziel angegebenen Framework nicht aufgelöst werden konnte. ".NETFramework,Version=v4.0". Zur Beseitigung des Problems muss entweder der Verweis "Tweetinvi" entfernt oder die Anwendung erneut als Ziel für eine Frameworkversion verwendet werden, die "System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" enthält.`
Which roughly translates to: `The direct reference to Tweetinvi could not be resolved because of the indirect reference to System.Net.Httpd which does not exist in the target framework (4.0).`
And the same for `System.Runtime, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` and `System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`

Manually adding references to the assemblies in the binaries directory, which have the same name but apparently not the same version, did not help:
![unbenannt](https://cloud.githubusercontent.com/assets/4943909/20296866/23586c52-ab05-11e6-8b1b-f2d3b8b7b5b0.png)

Referencing the Tweetinvi.dll in the output directory (which I guess has everything merged together) made Visual Studio compile at first but fail again when I tried to debug it.

Unfortunately it is also not possible to load the Tweetinvi.dll at runtime from a Visual Studio 2010 project because any access to it fails at runtime with a FileNotFoundException saying that those indirect references (or one of them) could not be found.

Any ideas?

**Comment by linvi** [comment]
Hello there,

To be totally honest, I have not tried to run Tweetinvi on VS2010 for a long time now.,
The only thing I do test is that it runs properly with the correct .NET Framework version.

This include .NET 4.0. I do understand that VS2015 is not great but I really don't have enough time to support 6 years old IDEs,

VS2017 is coming with great improvements (memory and performances in general), I guess you will be able to use this new version.

https://www.visualstudio.com/vs/visual-studio-2017-rc/

If you cannot make it work on new IDEs, please reopen this issue

Cheers,
Linvi
