### ISSUE TITLE
Coordinates not working?

### ISSUE THREAD

**Issue by holgeramort** [linvi/tweetinvi#405]
tried this:

``` c#
            var searchParameter = new SearchTweetsParameters("some search")
            {
                Lang = LanguageFilter.English,
                SearchType = SearchResultType.Recent,
                MaximumNumberOfResults = 1000,
            };
            var tweets = Search.SearchTweets(searchParameter);
```

But tweet.Coordinates is always null.

**Comment by linvi** [comment]
Most of the tweet do not contain any geo information.
When a tweet does not contain such information or if this information is set as private, Twitter will return a `.Coordinate` with a value `null`.

If you want to get coordinates, I would suggest that you search for tweets with a specific coordinate.

``` c#
var searchParameter = new SearchTweetsParameters("tweetinvi")
{
    GeoCode = new GeoCode(-122.398720, 37.781157, 1, DistanceMeasure.Miles),
// ...
```
