### ISSUE TITLE
User streams not starting.

### ISSUE THREAD

**Issue by ViolentCrumble** [linvi/tweetinvi#406]
Hi i have a filtered stream working fine. Now i copied the code and converted to user stream and it just never starts.

```

public Tweetinvi.Streaming.IUserStream userStream = Tweetinvi.Stream.CreateUserStream();

//check if twitter stream is not already running
if (userStream.StreamState != StreamState.Running)
{

    //setup credentials.
    Auth.SetUserCredentials("same creds i use on filtered stream");

    //setup stream
    userStream = Tweetinvi.Stream.CreateUserStream();

    userStream.StreamStarted += (sender, args) =>
    {
        Console.Add("Sucess: Twitter: User Stream started");
    };

   await userStream.StartStreamAsync();

}
```

never fires.. anything im missing?

If it helps I installed using nuget.. so i think it's 1.2.0-alpha 2

EDIT: Ok it seems to not work when i have another stream already running? Do i need to start the second stream a different way? It works when i remove the first filtered stream.

Thanks heaps.

**Comment by ViolentCrumble** [comment]
ok i got it working by putting it on another thread, however now it fired 6 times :P

**Comment by linvi** [comment]
Is this closed or do you need further help?

**Comment by ViolentCrumble** [comment]
Well i guess my issue might be related to opening extra threads. I ran into issues with my c#.. Could you please offer advice on best way to check if 2 streams are running and start them both?

I have 2 class wide variables for holding my stream. and check them before starting. But i started each on their own thread and ended up cause all my bots other commands to triple.

**Comment by linvi** [comment]
No further development for a while. Feel free to reopen the ticket if required.
