### ISSUE TITLE
Still being rate limited with RateLimitTrackerMode set to TrackAndAwait

### ISSUE THREAD

**Issue by olilittle** [linvi/tweetinvi#407]
Aloha!

I'm finding that my application is being rate limited (specifically for Likes) despite setting the RateLimitTrackerMode to TrackAndAwait. 

My code has it's own threading system, so is using the non-async tweetinvi calls instead of the async ones. My assumption is that the Async functions are only recommended to stop the application from hanging rather than the Synchronous functions ignoring the rate limits, is that correct?

As far as I can tell, I can still post tweets, send messages etc. It's just the Likes which are limited.

Awesome library btw ^_^

**Comment by linvi** [comment]
Hi,

Would you be able to share simple repro project here?

Thanks for reporting this issue

**Comment by olilittle** [comment]
Apologies for the delay, I'm on vacation atm so I'll provide the repro project when I'm back

**Comment by linvi** [comment]
Any update on this please?
