### ISSUE TITLE
How To  Get User All timeline 

### ISSUE THREAD

**Issue by MokaRex** [linvi/tweetinvi#408]
Hey,

i Wanna to Get All timeline for specific user , i searched in twitter dev pages i found that i can get to 3200 in 1 query how to do that using tweetinvi

**Comment by linvi** [comment]
Hello, this is actually not true, the only way to get all the tweets from a user (the 3200 most recent) is to actually run multiple queries.

The easiest way is to use `RateLimitTrackerMode.TrackAndAwait;` but this will take quite a white.

You will be able to do the following :

``` c#
RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackAndAwait;
var allTweets = Timeline.GetUserTimeline(user, 3200).ToArray();
```

**Comment by moody2000** [comment]
didn't work with me still got 191 tweet

**Comment by webdevaman** [comment]
@MokaRex Check out this link -> https://github.com/linvi/tweetinvi/wiki/Get-All-User-Tweets
