### ISSUE TITLE
Autofac hard version dependency on 1.1.1

### ISSUE THREAD

**Issue by terzano** [linvi/tweetinvi#409]
Hi, on v1.0.0. the Autofac dependency is for version >= 3.5.2
However, v1.1.1 takes a hard dependency on v3.5.2 for .NET Framework 4.5.  I use Autofac extensively on all my projects and this prevents me to move to v1.1.1. 
Is there any compatibility reason to stay on the 3.5 release?

**Comment by linvi** [comment]
When I did that I tried to ensure that nuget does not get confused between .NET Core and Portable Class Libraries.

At some point I will deprecate the to focus on .NETCore but at the current time I need 3.5.2.
In the meantime, I will attempt to put back `>= 3.5.2` and run some tests with nuget again.

**Comment by linvi** [comment]
#402

**Comment by linvi** [comment]
Please try the new alpha version of Tweetinvi : https://www.nuget.org/packages/TweetinviAPI/1.2.0-alpha3

Thanks for informing me about this.

**Note** that `3.5.2` is still a fixed version for .NETCore and .NETStandard projects.
