### ISSUE TITLE
Getting User Timeline , Amount of Tweets

### ISSUE THREAD

**Issue by moody2000** [linvi/tweetinvi#413]
Hello Linvi,
 i tried to get User timeline , i put the no of tweets parameter to 3200 as shown in twitter API docs , but i got only 192 tweet , how to get all 3200 tweets

**Comment by linvi** [comment]
Are you sure that this user does have 3200 tweets?
Could you please provide the id of the user for who you are trying to get all these tweets?

**Comment by moody2000** [comment]
i tested with my account which have 17500 tweet

**Comment by linvi** [comment]
Could you give me your id please, so that I can try it out.

**Comment by moody2000** [comment]
159053980

thanks for help

**Comment by moody2000** [comment]
sorry for annoying you but  any way to get 3200 tweets

**Comment by linvi** [comment]
I will work on this today. Stay posted!

**Comment by linvi** [comment]
Here you go. Please note that the number of tweets can be slightly lower than 3200 as Twitter not always provide all of them :

``` c#
RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackAndAwait;

RateLimit.QueryAwaitingForRateLimit += (sender, args) =>
{
    Console.WriteLine($"Query : {args.Query} is awaiting for rate limits to be available!");
};

var userId = 159053980;
var lastTweets = Timeline.GetUserTimeline(userId, 200).ToArray();
            
var allTweets = new List<ITweet>(lastTweets);
var beforeLast = allTweets;

while (lastTweets.Length > 0 && allTweets.Count <= 3200)
{
    var idOfOldestTweet = lastTweets.Select(x => x.Id).Min();
    Console.WriteLine($"Oldest Tweet Id = {idOfOldestTweet}");

    var timelineRequestParameters = new UserTimelineParameters
    {
        // We ensure that we only get tweets that have been posted BEFORE the oldest tweet we received
        MaxId = idOfOldestTweet - 1,
        MaximumNumberOfTweetsToRetrieve = allTweets.Count > 3000 ? (3200 - allTweets.Count - 1): 200
    };

    lastTweets = Timeline.GetUserTimeline(userId, timelineRequestParameters).ToArray();
    allTweets.AddRange(lastTweets);
}

// All Tweets now contains all the tweets that Twitter can return
```

**Comment by linvi** [comment]
I have created a new documentation page to help other developers with this question.

https://github.com/linvi/tweetinvi/wiki/Get-All-User-Tweets

**Comment by moody2000** [comment]
Sorry linvi , 
But new issue happened when work with your code .
It get NULL value error when trying to get time line
Before that it was work perfectly

**Comment by linvi** [comment]
When you receive null it means that twitter is throwing an error. Could you please disable the error handling and let me know which error twitter is returning please.

**Comment by moody2000** [comment]
![capture](https://cloud.githubusercontent.com/assets/14018918/21563136/b7f29e48-ce8f-11e6-9fd9-107c817f2a78.JPG)
 i got this error showed in Pic

**Comment by moody2000** [comment]
Is this message what you need ..

**Comment by linvi** [comment]
Yes but the message seems very clear to me. It looks like your connection was not fast enough to perform the query in 10 seconds.

Try to increase the timeout limit in the `TweetiniviConfig` and try again please!

**Comment by moody2000** [comment]
it's works now , thanks may be issues from twitter api
