### ISSUE TITLE
What is the TweetMode enum?

### ISSUE THREAD

**Issue by Niko-O** [linvi/tweetinvi#414]
I cannot find any documentation regarding the TweetMode enum. In my case I want to publish a tweet:
`Tweetinvi.Tweet.PublishTweet("SomeText", New Tweetinvi.Parameters.PublishTweetOptionalParameters With {.Foo = Bar, .TweetMode = ?})`
What does TweetMode do and what do the options `Extended` and `Compat` mean?
And where/how do I find the documentation? The nuget package does not contain any XML documentation so intellisense is useless in this regard. The repository does not contain a file called TweetMode.cs (which would be the expected file name).
I did find the file containing the PublishTweetOptionalParameters class: https://github.com/linvi/tweetinvi/blob/master/Tweetinvi.Core/Public/Parameters/PublishTweetOptionalParameters.cs
But unfortunately the TweetMode property is not documented. The link to https://dev.twitter.com/rest/reference/post/statuses/update on the class documentation did not contain any information about what TweetMode could mean. The file which contains the CustomRequestParameters class also does not contain any relavant documentation.
The wiki page https://github.com/linvi/tweetinvi/wiki/Tweets#publish-a-simple-tweet does not explain it either.

**Comment by linvi** [comment]
Hello, sorry about forgetting to mention this in the documentation.

You can currently read about it at https://github.com/linvi/tweetinvi/releases/tag/0.9.14.0.
There is an entire section dedicated to Extended Tweets. They are a new type of tweets that Twitter are now using in their API.

For compatibility purposes, they decided to allow 2 modes. `TweetMode.Extended` will ensure that Tweetinvi read and creates this new type of tweets.

This is also available as a global option if you want all your tweets to use the Extended format.

`TweetinviConfig.CurrentThreadSettings.TweetMode = TweetMode.Extended;`

**Comment by Niko-O** [comment]
Thank you for the link. This explains everything I wanted to know and actually even more ;)

**Comment by linvi** [comment]
A documentation is now available at https://github.com/linvi/tweetinvi/wiki/Extended-Tweets-&-TweetMode.
