### ISSUE TITLE
Include Tweetinvi.xml in nuget package

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#420]
To allow developers to get more information about the library.

**Comment by eduherminio** [comment]
@linvi Any plans to address this, or any identified blockers?

**Comment by linvi** [comment]
Hello there,

Tweetinvi 5.0 is on its way as you can see here : 

https://github.com/linvi/tweetinvi/milestone/19

Do you need this specific feature or do you mean, is Tweetinvi generally being updated?

Cheers,
Linvi

**Comment by eduherminio** [comment]
I was asking for this specific feature, it'd be awesome to have it included in v5.0.
I may even give it a try if you're happy with it.

**Comment by linvi** [comment]
I will try to include it.

**Comment by linvi** [comment]
Waiting for feedback on <inheritdoc /> support in Rider.

https://youtrack.jetbrains.com/issue/RIDER-41984

**Comment by linvi** [comment]
Closing this ticket as inherit doc is another issue.
Xml are now added to the nuget packages for 5.0.

https://github.com/linvi/tweetinvi/issues/1044
