### ISSUE TITLE
Tweets resulting from a search don't contain the coordinates

### ISSUE THREAD

**Issue by Stonivor** [linvi/tweetinvi#422]
Hi, 

When doing a search the resulting tweets don't have the tweet's coordinate.

`tweet.Coordinates == null`

**Comment by linvi** [comment]
You have to understand that Tweet coordinates are rarely populated in Twitter. The main reason is that few people accept to share their location publicly.

Therefore any public endpoint like search will most of the time be short of this field.
Though you can filter by coordinate!

``` c#
var tweets = Search.SearchTweets(new SearchTweetsParameters(new Coordinates(...)))
```

Remember that even if you search by coordinates, the tweet that you receive might not even have the coordinates populated even though this is quite a rare case.
