### ISSUE TITLE
Proxy with complex password (for instance with @ or others characters //)

### ISSUE THREAD

**Issue by jvinel** [linvi/tweetinvi#423]
I have an issue with a proxy with authentication using complex password (with @ or // characters).

It seems that tje issue is related to method WebProxyFactory:GetProxy and how the IWebproxy object is created based on proxyUrl provided.

Could you please consider to expose directly through getter/setter IWebProxy object?

It would be more adaptable.

Thanks,
Julien

**Comment by linvi** [comment]
Hello there, sorry for being long to reply to your question.
This will be added in the next release of Tweetinvi!

**Comment by jvinel** [comment]
Thank you, it will be greatly appreciated :)

**Comment by linvi** [comment]
This feature will be available as part of Tweetinvi 1.3.

`TweetinviConfig.CurrentThreadSettings.ProxyConfig = new ProxyConfig("http://228.23.13.21:4287", new NetworkCredential("username", "password"));`
