### ISSUE TITLE
Getting All Tweets Against Hashtags , Amount of Tweets

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#424]
How can we get all tweets against specific Hashtags/ Topics. Like we get 3200 timeline tweets. is there any method to get all tweets through Search (REST METHOD).

**Comment by linvi** [comment]
You can use Search "paging" via the `SinceId` and `MaxId` parameter. Remember that searches are limited to the tweet published during the previous 7 days.

https://github.com/linvi/tweetinvi/wiki/Searches#tweet-searches
