### ISSUE TITLE
How to check my credentials are working?

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#425]
sometimes my application is going to blocked or restricted to upload tweets due to rate limit violation. is there any method in tweetinvi to check whether my app credentials are working or not? now i am checking manually by visiting www.apps.twitter.com.

**Comment by linvi** [comment]
Twitter does not provide any public endpoint allowing you to check if a set of credentials/an application has been blocked.

I would strongly suggest that you actually code your application in a way that prevent you from being blocked.

There are many discussions about the topic on dev.twitter.com and on twittercommunity.com.

Regarding RateLimits, Tweetinvi provide very helpful tools to handle them properly and this can actually be done automatically for you! Take a look here to learn more about it : https://github.com/linvi/tweetinvi/wiki/Rate-Limits
