### ISSUE TITLE
PublishTweetWithImage not working

### ISSUE THREAD

**Issue by Asshen** [linvi/tweetinvi#427]
Tweet.PublishTweetWithImage is not working for me.
I receive no errors, it just doesn't post to Twitter.

Tweetinvi version = 1.2.0 (nuget package)

I'm using it in an asp.net MVC application as follows:

`byte[] imageBytes = webClient.DownloadData( imageUrl );`
`Tweet.PublishTweetWithImage( text, imageBytes );`

The image is fine, example: http://s123.eu/uploads/media/1/b9272763d8e640b1ba16.jpg
I receive the byte data, no issues there.
Tweetinvi just doesn't seem to post it on Twitter.

I also use Tweet.PublishTweet for tweets without image and that is working fine.

Any suggestions?
Thanks.

**Comment by Asshen** [comment]
Also tried this, and also not working:

`var media = Tweetinvi.Upload.UploadImage( imageBytes );`
`Tweet.PublishTweet( text, new PublishTweetOptionalParameters { Medias = { media } } );`

**Comment by linvi** [comment]
Hello, I must have missed your question.
Do you still encounter problems?

**Comment by Asshen** [comment]
Hey.

Did you fix the bug?
Is there a new version available of tweetinvi?
I will test if the problem is solved.

Regards.
K.

**Comment by Asshen** [comment]
I tested it with the newest version 1.2.0.1, but the problem persists.

So I reopened the issue.
