### ISSUE TITLE
How can display an image Profile

### ISSUE THREAD

**Issue by alktab** [linvi/tweetinvi#428]
Hello
I've tried it review images through GetProfileImageStream Next CODE  
pic.Image =  User.GetProfileImageStream(user, ImageSize.bigger);

In the language C# form !! out error 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'System.IO.Stream' to 'System.Drawing.Image'

What is the problem?
Thank

**Comment by linvi** [comment]
Hello, transforming a stream into a Drawing.Image is not a question relevant on this forum.

Take a look here! http://stackoverflow.com/questions/16857325/io-stream-to-image-in-wpf
