### ISSUE TITLE
Upload.UploadMedia () not working

### ISSUE THREAD

**Issue by marsh12th** [linvi/tweetinvi#429]
Hi,
 
I'm using Tweetinvi v1.2 but **Upload.UploadMedia** always returns a system null reference exception.

```c#
Auth.ExecuteOperationWithCredentials ( Program.user, () =>
{
	var binary = System.IO.File.ReadAllBytes ( "img.png" );   // Binary is fine
	var media = Upload.UploadImage ( binary );   // Always returns "System null reference exception"
	Tweet.PublishTweet ( "TEST", new PublishTweetOptionalParameters
	{
		Medias = new List<IMedia> { media }
	} );
} );
```

**Note:** Analog methods to *UploadMedia ()* ( like Upload.UploadBinary ) give all the same error output.

**Comment by linvi** [comment]
Could you please provide the details of the error returned by Twitter.

You can learn more about error handling here : https://github.com/linvi/tweetinvi/wiki/Exception-Handling

**Comment by marsh12th** [comment]
It's the API what's giving the error, not Twitter ( I think ).
Also I've found out it's about the image size.
I can tweet a 100x100px png fine ( ~30KB ), but a 1920x1080px png ( ~MB ) returns a _System.NullReferenceException_ when calling **Upload.UploadMedia ( binaryFile )**

**Comment by linvi** [comment]
Images > 5MB are not supported by the Twitter API.

You can learn more about the restrictions of image upload here : https://dev.twitter.com/rest/media/uploading-media.html in `Image specifications and recommendations`.

> Image files must meet all of the following criteria:

Supported image media types: JPG, PNG, GIF, WEBP
Image size <= 5 MB, animated GIF size <= 5 MB
The filesize limit above is enforced by the media upload endpoint. In addition, there is a separate product entity specific filesize limit which is applied when calling the Tweet creation (or similar) endpoints with media_id. For example, it is possible to upload a 5 MB image, but the Tweet creation requires images to be < 3 MB. The filesize limit and other constraints may vary depending on the media_category parameter.

**Comment by marsh12th** [comment]
Oh, okay thanks.
My fault I guess, sry.

**Comment by linvi** [comment]
No problem! Feel free to come back here if you have any other question!

**Comment by poryadel** [comment]
Hello thanks for your awsome package. I love that. but i have problem with uploading media. Sometimes throw exeption "Exception of type 'Tweetinvi.Exceptions.TwitterNullCredentialsException' was thrown." and it's really don't even try to upload that. i get last version from nuget last night. please help me <3

**Comment by poryadel** [comment]
I forgot to say i used your exeption handler and it says https://api.twitter.com/1.1/account/verify_credentials.json?skip_status=true&include_entities=true&include_email=true web request timed out.
but it dosen't even trying to upload that media. thanks again

**Comment by linvi** [comment]
The problem comes from a different request which is `User.GetAuthenticatedUser`.
For some reason you have a Timeout.

This has nothing to do with Upload.
Please open new issues when you have such problems.

**Comment by poryadel** [comment]
Ok. Sorry thanks. but user has been Authenticated well and user variable Informations are just fine.
This is my code anyway:
`var userCredentials = Tweetinvi.Auth.CreateCredentials(WebConfigurationManager.AppSettings["PublicTwitterAppKey"], WebConfigurationManager.AppSettings["SecretTwitterAppKey"], kookkon.TWT_AccessKey, kookkon.TWT_AccessSecretKey);
                var authenticatedUser = Tweetinvi.User.GetAuthenticatedUser(userCredentials);
                byte[] file1 = System.IO.File.ReadAllBytes(Server.MapPath("~/images/Photo4.jpg"));
                media = Upload.UploadImage(file1);
                var c = authenticatedUser.PublishTweet("Sometext", new PublishTweetOptionalParameters
                {
                    Medias = new List<IMedia> { media, media }
                });`
Is there any problem with that.
some times `ExceptionHandler.GetLastException()` returns null!

**Comment by linvi** [comment]
I created a bug for you @ https://github.com/linvi/tweetinvi/issues/444
