### ISSUE TITLE
Extended Tweet Text and Suffix properties can't handle multi-byte character

### ISSUE THREAD

**Issue by codenjs** [linvi/tweetinvi#430]
I just upgraded to v1.2 and started using extended tweets for the first time
`TweetinviConfig.CurrentThreadSettings.TweetMode = TweetMode.Extended;`

I'm running into a problem with a specific tweet, where the Text and Suffix properties appear to be incorrect. It looks like they've been split right in the middle of a multi-byte emoji character.

Here's an image of the FullText, Text and Suffix properties while debugging
![tweet](https://cloud.githubusercontent.com/assets/24832578/21555800/6fc5f134-cde9-11e6-8a4f-06982f030115.gif)

This is the tweet:
https://twitter.com/TheWJBretheren/status/813152800821678080

**Comment by linvi** [comment]
Thank you very much for reporting this problem. I will release a fix on the next version of Tweetinvi!

**Comment by linvi** [comment]
Done :)

**Comment by codenjs** [comment]
I'm now using v2.1.0 and I'm still having similar problems. I'm testing the same tweet from my previous example. These are the values from the FullText, Text and Suffix properties
![extendedtweet2](https://user-images.githubusercontent.com/24832578/34369906-f0ec1808-ea8d-11e7-877c-0c7066ba655d.gif)

FullText and Suffix both look correct, but the Text value looks like it's still split in the middle of an emoji character.

**Comment by codenjs** [comment]
Here's a different tweet that's causing an exception and it may be related:
https://twitter.com/hockey_ohio/status/944674446324969474

This is a retweet where the original tweet contains multiple emojis. When I try to access the Suffix property, an exception occurs within Tweetinvi.Core.Core.Helpers.UnicodeHelper.UnicodeSubstring()

```
System.ArgumentOutOfRangeException was unhandled by user code
  HResult=-2146233086
  Message=Specified argument was out of the range of valid values.
Parameter name: index
  ParamName=index
  Source=mscorlib
  StackTrace:
       at System.Char.IsSurrogatePair(String s, Int32 index)
       at Tweetinvi.Core.Core.Helpers.UnicodeHelper.UnicodeSubstring(String str, Int32 startIndex)
       at Tweetinvi.Logic.Tweet.get_Suffix()
```

**Comment by codenjs** [comment]
I've investigated the two previously mentioned tweets:

https://twitter.com/TheWJBretheren/status/813152800821678080
This contains the following Unicode sequence:
`\ud83c\udf85\ud83c\udffc\u26c4\ufe0f\ud83c\udf85\ud83c\udffc`
I looked these up online:
`\ud83c\udf85` = Surrogate pair for U+1F385 FATHER CHRISTMAS
`\ud83c\udffc` = Surrogate pair for U+1F3FC INVALID CHARACTER
`\u26c4` = Character U+26C4 SNOWMAN WITHOUT SNOW
`\ufe0f` = Character U+FE0F VARIATION SELECTOR-16
`\ud83c\udf85` = Surrogate pair for U+1F385 FATHER CHRISTMAS
`\ud83c\udffc` = Surrogate pair for U+1F3FC INVALID CHARACTER

https://twitter.com/hockey_ohio/status/944674446324969474
This contains the following Unicode sequence:
`\ud83c\udfb8\u203c\ufe0f`
I looked these up online:
`\ud83c\udfb8` = Surrogate pair for U+1F3B8 GUITAR
`\u203c` = Character U+203C DOUBLE EXCLAMATION MARK
`\ufe0f` = Character U+FE0F VARIATION SELECTOR-16

Both of these tweets contain Character U+FE0F VARIATION SELECTOR-16 and it's not being counted correctly when generating the extended tweet Text and Suffix properties. It should not be counted as a separate character. It modifies the preceding character. Here's one reference:
https://codepoints.net/U+FE0F?lang=en

> This codepoint may change the appearance of the preceding character. If that is a symbol, dingbat or emoji, U+FE0F forces it to be rendered as a colorful image as compared to a monochrome text variant
