### ISSUE TITLE
Question : How to check whether the tweet is deleted or not ?

### ISSUE THREAD

**Issue by Abhith** [linvi/tweetinvi#431]
We are using search api to get tweets by hashtags and storing it on our db, in some cases user may deleted some of the tweets in twitter that we already stored to our system. So how to check whether the tweet that we stored is deleted or not ?

**Comment by linvi** [comment]
You have to try to get the tweet again in the future and test if it is returned.

``` c#
var tweet = Tweet.GetTweet(39829382);
if (tweet == null)
{
    // Tweet has been destroyed!
}
```

If you want to do that for multiple tweets, you can use `Tweet.GetTweets`
