### ISSUE TITLE
Getting Direct Messages Issue

### ISSUE THREAD

**Issue by moody2000** [linvi/tweetinvi#432]
Hello linvi ,
                  i tried to get messages for Auth user but it always return error "Value cannot be Null"

**Comment by linvi** [comment]
Hello, I cannot help without code.

**Comment by moody2000** [comment]
`private void xylosButton16_Click(object sender, EventArgs e)
        {
            var latestMessagesReceived = Tweetinvi.Message.GetLatestMessagesReceived().ToList();
            //Dim latestMessagesReceivedParameters = New Get
            //Dim latestMessagesReceived = Tweetinvi.Message.GetLatestMessagesReceived(latestMessagesReceivedParameters)

            foreach (var msg in latestMessagesReceived)
            {
                
                string[] data = new string[6];
                data[0] = msg.SenderScreenName;
                data[1] = msg.Text;
                textBox1.Text = textBox1.Text + Microsoft.VisualBasic.Constants.vbNewLine + data[0] + "===" + data[1];
            }`

**Comment by linvi** [comment]
Where is the problem occur? Are you sure that the credentials have been initialized?
