### ISSUE TITLE
User.GetAuthenticatedUser() returns null

### ISSUE THREAD

**Issue by PadraigL** [linvi/tweetinvi#434]
Hi, I can do things like send private messages, publish tweets etc but I cannot access the current user nor can I use User.GetUserFromScreenName() as this returns null also.
I am fully authenticated as mentioned above I can do things like publish tweets etc.
Here is my code:
```
Auth.SetUserCredentials("1", "2", "3", "4");
var user = User.GetAuthenticatedUser();`
```

When I attach a breakpoint to the user line it shows that user is null. This also occurs when I use this code:
`var user = User.GetUserFromScreenName("my_screen_name_here");`

**Comment by linvi** [comment]
Hello, sorry for the delay in replying to you.
This is the first time that I heard of such a bug.

Could you please share with me the error that you receive from Twitter.

You can learn more about error handling here : https://github.com/linvi/tweetinvi/wiki/Exception-Handling

**Comment by linvi** [comment]
Let me know if I can close this bug.

Thank you

**Comment by Hudiel** [comment]
Hi is there any fix for this bug?
I'm also experiencing this.

When i catch the error it states 'Twitter is unable to perform your query within the timeout limit of 10000ms'

**Comment by linvi** [comment]
I think the error is self explanatory. You seem to have a problem with the network/firewall/proxy.

**Comment by Hudiel** [comment]
Thanks for the quick reply

**Comment by linvi** [comment]
Hello there, do you still encounter this issue?

**Comment by linvi** [comment]
Closing as the bug is quite old. Please reopen if needed.

**Comment by Marjani** [comment]
I have same problem 

`
            var userCredentials = Auth.CreateCredentials("?????? ", "????", "????", "?????");
            var authenticatedUser = User.GetAuthenticatedUser(userCredentials);

`

I get lib from nuget and run above code in console project.

**Comment by linvi** [comment]
Are you sure the credentials you are passing through are valid?
If you think so please use the `ExceptionHandler` or deactivate it to find out what is going wrong.

Cheers,
Linvi

**Comment by WhiteLionATX** [comment]
Same issu here:
var user = User.GetUserFromScreenName(e.twitterAccountName);
returns null

Maybe this could help: I changed my twitter username before I got this error.
The methode returns the new name but does not work.
