### ISSUE TITLE
Incorrect properties in filtered streams

### ISSUE THREAD

**Issue by sicknote** [linvi/tweetinvi#438]
Have set up up a basic filtered stream with a keyword using AddTrack.

The Tweets are being received correctly, but appear to have incorrect text. The FullText & Text properties are identical, and ended with a hellip (…), whilst the PublishedTweetLength was 130.

I added a listener for JsonObjectReceived. I can see the incoming tweet in that handler without the truncation seen in the tweet, so it seems to suggest the ITweet created is being constructed incorrectly.

Is there something I am missing? I cannot see any properties to allow a change in the way the data is collected.

Thanks.

**Comment by linvi** [comment]
Could you please share the text of the tweet that is truncated please?
Also I would need the filter that you applied to retrieve this tweet.

Finally could you share the version of the library that you used.

Thank you

**Comment by sicknote** [comment]
Hi @linvi. Thanks for looking at this. I am going to have to say mea culpa, as I was wrong ):

I was collecting the JSON of a tweet to provide and realised the horizontal ellipse was in both the JSON AND the Tweet instance. That is, Twitter is performing the truncation, and not the library. Even though, in the example I had, the text was within the accepted length of a tweet. Somewhat weird IMHO.

Really sorry. I will be more careful.

The library is quick lovely to use by the way.
