### ISSUE TITLE
Searching for tweets in a page

### ISSUE THREAD

**Issue by PublicEyeDeveloper** [linvi/tweetinvi#441]
hello, 
please i want to know if there is a way to search for tweets in a specific user.

example: I want to get all tweets on donald trump is cnn page.

**Comment by linvi** [comment]
Search does not allow such an operator. What you can do though is to get all the tweets of CNN and then filter the one manually.

Another solution is to use a `FilteredStream` that will allow you to get in live all the tweets matching those criterion. But with this solution you will not be able to get the tweets published in the past.
