### ISSUE TITLE
Puplishtweet don't work

### ISSUE THREAD

**Issue by moody2000** [linvi/tweetinvi#443]
Hey linvi . 
Sorry to annoying you so much .. my issue i's Puplishtweet it don't work 
Dim tweet1 = tweet.Puplishtweet(mytweet)

**Comment by moody2000** [comment]
I checked the authority data and another quires work propaply

**Comment by linvi** [comment]
Hello,

I am not sure what you mean here. But `PublishTweet` is the most used feature of the library so I am quite confident that it works.

Could you please provide more information as to what is the problem that you are facing please?

**Comment by moody2000** [comment]
Thanks for ur respond . Sorry for annoying you . The issue was with the account of the application
