### ISSUE TITLE
Tweetinvi Authentication

### ISSUE THREAD

**Issue by tfctpa** [linvi/tweetinvi#446]
Trying to follow the code examples, I am having an issue with Auth.SetUserCredentials in .NET.
The error is: The type or namespace 'SetUserCredentials' could not be found.......
Tweet.publishtweet resolves fine.

What am I missing?

``` c#
// Set up your credentials (https://apps.twitter.com)
Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

// Publish the Tweet "Hello World" on your Timeline
Tweet.PublishTweet("Hello World!");
```

**Comment by linvi** [comment]
It looks like a namespace issue. Have your tried `Tweetinvi.Auth.SetUserCredentials`?

**Comment by tfctpa** [comment]
Just tried, that gave me the same results.
The error is: The type or namespace 'SetUserCredentials' could not be found.......

**Comment by linvi** [comment]
Please provide the entire file on gist.
Also let me know which version of Tweetinvi you are using!

**Comment by tfctpa** [comment]
I am currently running TweetinviAPI v1.2.0.1
Auth.ApplicationCredentials =  new Tweetinvi.Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

I found that the new keyword caused the issue. Sorry to bother you.
