### ISSUE TITLE
Receiving Tweets

### ISSUE THREAD

**Issue by oreasedap94** [linvi/tweetinvi#447]
Dear linvi,
Sometimes I cant receive tweet.. I heard about the limit(15 request per 15 min *correct me if I'm wrong). The first time i request, the tweet can be received but when the 2nd times i request, i cant receive the tweets. May I know why?

**Comment by linvi** [comment]
Hello,

I would need more code to analyse the type of requests you are executing so that I can understand what is going wrong!

Cheers!

**Comment by oreasedap94** [comment]
Hi there @linvi ,

below are the code that i try to implement..

`
#region TweetReceive (3000++)
            RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackAndAwait;

            RateLimit.QueryAwaitingForRateLimit += (sender, args) =>
            {
                Console.WriteLine($"Query : {args.Query} is awaiting for rate limits to be available!");
            };

            //var userId = user2.Id;
            var lastTweets = Timeline.GetUserTimeline(userID, 200).ToArray();

            var allTweets = new List<ITweet>(lastTweets);
            var beforeLast = allTweets;

            while (lastTweets.Length > 0 && allTweets.Count <= 3200)
            {
                var idOfOldestTweet = lastTweets.Select(x => x.Id).Min();
                Console.WriteLine($"Oldest Tweet Id = {idOfOldestTweet}");

                var timelineRequestParameters = new Tweetinvi.Parameters.UserTimelineParameters
                {
                    // We ensure that we only get tweets that have been posted BEFORE the oldest tweet we received
                    MaxId = idOfOldestTweet - 1,
                    MaximumNumberOfTweetsToRetrieve = allTweets.Count > 3000 ? (3200 - allTweets.Count) : 200
                };

                lastTweets = Timeline.GetUserTimeline(userID, timelineRequestParameters).ToArray();
                allTweets.AddRange(lastTweets);

                extractedTwitter_dg.Items.Clear();
                foreach (ITweet prime2 in allTweets)
                {
                    extractedTwitter_dg.Items.Add(new { TweetID = prime2.Id.ToString(), Tweet = prime2.Text, CreatedAt = prime2.CreatedAt.ToString() });
                }
            }
            // All Tweets now contains all the tweets that Twitter can return
            #endregion
`

as you can see from the code.. there's nothing much different as the code that i learn from the documentation given for the Library by you except the way I represent the output in XAML.. mind to guide me.. I'm very interested about this library for my project. Thanks in advance.

Notes: I'm still new in programming tho. Eager to learn something new..

**Comment by linvi** [comment]
Your code looks correct. If the data is not returned it means that Twitter is returning an error.
Could you check the Exception returned by Twitter.

You can learn more about ExceptionHandling here : https://github.com/linvi/tweetinvi/wiki/Exception-Handling#per-request-exception-handling

**Comment by oreasedap94** [comment]
I will try your suggestion by using ExceptionHandling later in my coding. I don't know what happen. If I remember correctly its says the userTimelineParam return null. Unfortunately such problem i told you earlier not happen today.. A bit confusing right now @@... BTW, i will post the error here if I encounter it later.

1 more question, in the ExceptionHandling you suggest me,  is there any necessary function should I display despite the exception error message. This is what I understand, 
`
ExceptionHandler.SwallowWebExceptions = false;

// Execute an operation
try
{
    //My tweet request function
}
catch (ArgumentException ex)
{
    //Display error message
}
catch (TwitterException ex)
{
    //Display error message
}
`
correct me if I'm wrong, Thanks in Advance..

**Comment by linvi** [comment]
That is correct. If you recive a `TwitterException` please provide me the `TwitterException.ToString()`.

Thanks
