### ISSUE TITLE
Notification in Tweetinvi?

### ISSUE THREAD

**Issue by zdrob84** [linvi/tweetinvi#448]
Good Day Linvi,

I would like to ask if you have feature to extract notifications of the logged user?

Thank you

**Comment by linvi** [comment]
Unfortunately Twitter Public REST API does not provide such feature.
Though you can use [UserStream](https://github.com/linvi/tweetinvi/wiki/User-Streams) to listen to various events that can be related to anything that happened to the Authenticated user.
