### ISSUE TITLE
Null AuthenticationContext

### ISSUE THREAD

**Issue by eaba** [linvi/tweetinvi#449]
Hi, I just started your library like this:
```
var applicationCredentials = new ConsumerCredentials("uuuu", "bbbb");
                var authenticationContext = AuthFlow.InitAuthentication(applicationCredentials, "...twitter");
                //System.Console.WriteLine(authenticationContext.ToJson());
                return authenticationContext.AuthorizationURL;
```
I am getting null or empty string.
Please how do i fix this?

**Comment by linvi** [comment]
Tweetinvi handle errors from Twitter by returning null. Could you please provide the error.

Could you please provide the `TwitterException.ToString` details so that I can provide more help.

**Comment by eaba** [comment]
I dont see any exception message, it does not throw any error. Is there a way I can get to the error message

**Comment by linvi** [comment]
You can learn more as how to catch exception by reading the following documentation : 

https://github.com/linvi/tweetinvi/wiki/Exception-Handling

**Comment by eaba** [comment]
Thanks @linvi it appeared to be network related
I was testing without internet connection.

Fixed!!

**Comment by linvi** [comment]
Great :) Have a great evening!

**Comment by eaba** [comment]
Hi @linvi please help me with this issue:
```
System.ArgumentException: Identifier could not be matched to any stored AuthenticationContext.\r\n   at Tweetinvi.AuthFlow.CreateCrentialsFromId(String identifier, IAuthenticationToken authToken)\r\n   at Controllers.OAuthController.<TwitterCallBack>d__1.MoveNext()
```

**Comment by linvi** [comment]
This error mean that the `AuthenticationContext` you provided to the `CreateCredentialsFromCallbackURL` is null and `authorization_id` query parameter retrieved by the callback cannot be mapped to any stored `AuthenticationContext`.

If you need a better explanation please read the following documentation : https://github.com/linvi/tweetinvi/wiki/Authentication#web-application-considerations

> If the authorization key are not set in the credentials, Tweetinvi will attempt to use its cache. If the credentials associated with the authorization_id cannot be found Tweetinvi will throw an Exception.

**Comment by eaba** [comment]
Hello @linvi  I did this:
```
var token = await DbTransaction.GetTwitterToken(new Dictionary<string, string> { {"Id", authorizationId}, {"OAuth", oauthToken} });
                    var authorizationToken = JsonConvert.DeserializeObject<AuthenticationToken>(token);
                    var atoken = new Tweetinvi.Credentials.Models.AuthenticationToken
                    {
                        AuthorizationKey = authorizationToken.AuthorizationKey,
                        AuthorizationSecret = authorizationToken.AuthorizationSecret,
                        AuthorizationUniqueIdentifier = authorizationToken.AuthorizationUniqueIdentifier,
                        ConsumerCredentials = authorizationToken.ConsumerCredentials,
                        VerifierCode = authorizationToken.VerifierCode
                    };

                    var newCredentials = AuthFlow.CreateCredentialsFromVerifierCode(verifierCode, atoken);
                    Log.LogContent(JsonConvert.SerializeObject(newCredentials, Formatting.Indented), "NewCredentials");
                    var authenticatedUser = Tweetinvi.User.GetAuthenticatedUser(newCredentials);
                    Log.LogContent(JsonConvert.SerializeObject(authenticatedUser, Formatting.Indented), "User");
                    var tweet = await TweetAsync.PublishTweet("Hello World");
                    
```
AND I get this:
```
"Tweetinvi.Exceptions.TwitterNullCredentialsException: Exception of type 'Tweetinvi.Exceptions.TwitterNullCredentialsException' was thrown.\r\n   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)\r\n   at Tweetinvi.TweetAsync.<PublishTweet>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Controllers.OAuthController.<TwitterCallBack>d__1.MoveNext()"
```
I can confirm that the newcreddential is not null, which would publishtweet throw null exception?

**Comment by eaba** [comment]
Finally got it to work by doing this:
```
var creds = new TwitterCredentials(newCredentials.ConsumerKey, newCredentials.ConsumerSecret, newCredentials.AccessToken, newCredentials.AccessTokenSecret);
                    //var user = Auth.CreateCredentials(newCredentials.ConsumerKey, newCredentials.ConsumerSecret,newCredentials.AccessToken,newCredentials.AccessTokenSecret);
                    var authenticatedUser = Tweetinvi.User.GetAuthenticatedUser(creds);
                    var tweet = Auth.ExecuteOperationWithCredentials(creds, () => Tweet.PublishTweet("We have joined the family."));
                    
```

**Comment by linvi** [comment]
Remember that `var newCredentials = AuthFlow.CreateCredentialsFromVerifierCode(verifierCode, atoken);` only creates a credentials objects.

## Solution using per thread credentials 
You will for example find the following code:

``` c#
// your code
var newCredentials = AuthFlow.CreateCredentialsFromVerifierCode(verifierCode, atoken); 

// and then...
Auth.SetCredentials(newCredentials);
```

By doing so, any operation run in the thread will be using the `newCredentials`.

## Solution using the `Auth.ExecuteOperationWithCredentials`

`Auth.ExecuteOperationWithCredentials` allow you to specify the credentials for 1 and unique lambda.

In your code you recreate the credentials which you do not need to do.

``` c#
// var creds = new TwitterCredentials(newCredentials.ConsumerKey, newCredentials.ConsumerSecret, newCredentials.AccessToken, newCredentials.AccessTokenSecret);

// var user = Auth.CreateCredentials(newCredentials.ConsumerKey, newCredentials.ConsumerSecret,newCredentials.AccessToken,newCredentials.AccessTokenSecret);
var authenticatedUser = Tweetinvi.User.GetAuthenticatedUser(newCredentials);
var tweet = Auth.ExecuteOperationWithCredentials(newCredentials, () => Tweet.PublishTweet("We have joined the family."));
```

## Read more
You will probably be interested by the following parts of the credentials wiki:
* https://github.com/linvi/tweetinvi/wiki/Credentials#credentials-and-multiple-threads
* https://github.com/linvi/tweetinvi/wiki/Credentials#lets-code

**Comment by eaba** [comment]
Thanks!
One more: how can I tweet to a userid not private message!
