### ISSUE TITLE
DM limits on Twitter

### ISSUE THREAD

**Issue by jscoys** [linvi/tweetinvi#452]
Hi,

I wonder what is the limit of DM on Twitter, not in an hour but under? I use TweetInvi libraries to send DM, everything's great but the magical number where DM stopped to be sent is around 10.

I send a DM every 5 seconds, and every 5 DMs I stop the process for 30 seconds before continuing. Should I send DM every 5 minutes??? Thx a lot.

**Comment by linvi** [comment]
You can find the information you are looking for here: https://support.twitter.com/articles/15364

> The current technical limits for accounts are:
> Direct messages (daily): The limit is 1,000 messages sent per day.

`1000/(3600*24) ~= 0.12 dm/s` => `1/0.12 = 8.33s` 

So just to make sure you don't have a problem I would suggest you do not send more than 1 message every 10 seconds from a single account.

Moreover Twitter has bots detecting `abnormal` behaviour`. Sending 1000 dm per day on a long period will might result in your app being blocked. Therefore I would advise that you reduce this number even lower (1/20 or 1/30secs) if you are planning to do so continuously.

**Comment by jscoys** [comment]
Thx a lot will try!
