### ISSUE TITLE
Get Followers Count - Doesn't Seem To Exist. :/

### ISSUE THREAD

**Issue by Unkindjolt** [linvi/tweetinvi#453]
I'm trying to get just the current number of followers for an account, I can't figure It out, If anyone has got this for C# any help would be greatly appreciated.

**Comment by Ganeshcse** [comment]
Hi,
First u need to get your secret token and other details from Twitter developer console by creating a new app and then follow the below code which gives you of what you needed,

Auth.SetUserCredentials(
                    "CONSUMER_KEY",
                    "CONSUMER_SECRET",
                    "USER_ACCESS_TOKEN",
                    "USER_ACCESS_SECRET");

                var user = Tweetinvi.User.GetAuthenticatedUser();

                FollowersCount.Text = user.FollowersCount.ToString(); 
                // FollowersCount is my label in WinForms
                FollowingCount.Text = user.FriendsCount.ToString(); 
               //FollowingCount is my label in Winforms

Try with above code, it works out and if any issues then it might be with your keys generated from twitter app console.

Good luck.

**Comment by Unkindjolt** [comment]
thanks for the help I'l try that shortly thanks :)
