### ISSUE TITLE
Checking If Tweet Is A Reply: Does The Twitter API Support It Yet?

### ISSUE THREAD

**Issue by Unkindjolt** [linvi/tweetinvi#454]
Is there a possibility to check if a tweet is a reply to a tweet yet or is there a way that TweetInvi can handle this?

**Comment by linvi** [comment]
Hello you can simply use the `InReplyToStatusId` :

``` c#
var tweet = Tweet.GetTweet(42);
var isAReply = tweet.InReplyToStatusId != null;
```
