### ISSUE TITLE
GetUserTimeline seems to be delayed in getting new tweets

### ISSUE THREAD

**Issue by dendle** [linvi/tweetinvi#455]
Hello All,

I am using Tweetinvi to periodically (once every minute) check for new tweets on one user in particular.

``` if (sinceId != 0)
{
    result = Tweetinvi.Timeline.GetUserTimeline(userId, new UserTimelineParameters
    {
        SinceId = sinceId,
        MaximumNumberOfTweetsToRetrieve = maxItems.GetValueOrDefault(10)
    });
}
else
{
    result = Tweetinvi.Timeline.GetUserTimeline(userId, maxItems.GetValueOrDefault(10));
}
```

I store the biggest Id from the list of initial 10, and check every minute after that.

However, say I check at 04:00:12, the user tweets at 4:00:50, I dont appear to pick up that new tweet until something like 4:15:02.

I do eventually get the tweets, its just there seems to be a variable delay when I get them.

Is this usual?

Any help would be greatly appreciated.
Cheers,
Matt

**Comment by linvi** [comment]
Hello, no this is unusual, actually I have never experienced such a problem.
Could you please confirm that you keep experiencing this problem?

**Comment by linvi** [comment]
No response. Please reopen the ticket if you still experience the problem.
