### ISSUE TITLE
Unauthorized -  Authentication credentials were missing or incorrect.

### ISSUE THREAD

**Issue by mantecaptus** [linvi/tweetinvi#457]
Hi
I'm trying to setup in desktop application possibility of posting on twitter using Tweetinvi api.  
But I'm getting error 
{"https://api.twitter.com/1.1/statuses/update.json?status=Test web request failed."}
``` c#
public void SendTweet(Post post)
        {
            Auth.SetUserCredentials( TwitterAccountSettings.ConsumerKey, TwitterAccountSettings.ConsumerSecret,
                TwitterAccountSettings.AccessToken, TwitterAccountSettings.AccessTokenSecret );
            
            if (Auth.Credentials == null) throw new System.Exception( "No Twitter credencials" );
            
            var tweet = Tweet.PublishTweet( post.Title );
            if (tweet == null )
            {
                var latestException = ExceptionHandler.GetLastException();
            }
        }
```

StackTrace

>   w Tweetinvi.WebLogic.WebRequestExecutor.<>c__DisplayClass4_0.<ExecuteQuery>b__0()
   w Tweetinvi.WebLogic.WebRequestExecutor.ExecuteTwitterQuerySafely[T](ITwitterQuery twitterQuery, Func`1 action)
   w Tweetinvi.WebLogic.WebRequestExecutor.ExecuteQuery(ITwitterQuery twitterQuery, ITwitterClientHandler handler)
   w Tweetinvi.WebLogic.TwitterRequestHandler.ExecuteQuery(String queryURL, HttpMethod httpMethod, TwitterClientHandler handler, ITwitterCredentials credentials, HttpContent httpContent)
   w Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method, HttpContent httpContent, Boolean forceThrow)`

Could you please give me some advice what can be a reason of this issue?

Thanks

**Comment by linvi** [comment]
Hello, I would need to have the information that you can find in the `latestException.ToString()`.

Please note that you cannot publish a tweet with the exact same text multiple times in a row. So if you already published a Tweet `test`, publishing such a tweet will result in an Exception.

**Comment by mantecaptus** [comment]
Hi

Thank for replay.
Bellow result of latestException.ToString()
"--- Date : 2017-02-06 18:46:25\r\nURL : https://api.twitter.com/1.1/statuses/update.json?status=test_01\r\nCode : 401\r\nError documentation description : Unauthorized -  Authentication credentials were missing or incorrect.\r\nError message : https://api.twitter.com/1.1/statuses/update.json?status=test_01 web request failed.\r\nCould not authenticate you. (32)\r\n"

Credential are copy paste from dev.twitter.com, save in static class and pass to Auth.SetUserCredentials()
`    public static class TwitterAccountSettings
    {
        public static string ConsumerKey = "xxx";
        public static string ConsumerSecret = " xxx";
        public static string AccessToken = "xxx";
        public static string AccessTokenSecret = "xxx";
    }`
 
Thanks

**Comment by linvi** [comment]
Hello, sorry for the very long reply. Obviously I forgot about this issue.
I cannot reproduce your bug, I do not know if you managed to fix it in the end but I will close the bug for now.

Please reopen it if you did not manage to fix this.
