### ISSUE TITLE
GetUserMentionsTimeline getting data from specific time lapse

### ISSUE THREAD

**Issue by Mabrothrax** [linvi/tweetinvi#459]
Hi,

Im trying to implement a mechanism that's fetching specific (authenticated) user mentions from specific (given) time lapse.  Can anyone provide me with a solution? I've beed reading the documentation for quite some time but  I still havent found anything about the matter (even on cheatsheet).  Help needed :)

**Comment by JoshKeegan** [comment]
Take a look at `Timeline.GetMentionsTimeline`

**Comment by Mabrothrax** [comment]
Yeah, maybe i didnt elaborated to much on the issue i had there but i managed to solved it on my own using sinceId :)

**Comment by JoshKeegan** [comment]
Great :)

**Comment by webdevaman** [comment]
@Mabrothrax How did you use sinceId and please help me how can i determine a specific period of time using SinceId and MaxId.
Like i have to get tweets from Date1 to Date2. How can i get them?

**Comment by Mabrothrax** [comment]
I think you should just stick to the CreatedAt attribute of the tweet, because it contains full date information. I used sinceId in a loop in my application to determine last fetched tweet, so my app wont be uploading the same tweets in case of restarted service.

**Comment by webdevaman** [comment]
but i only want to retrieve the tweets for a specific time period.

**Comment by webdevaman** [comment]
I can't think how to implement this :(

**Comment by webdevaman** [comment]
Though i can use CreatedAt, but how come i can get tweets from Date1 to Date2.

**Comment by linvi** [comment]
Twitter does not provide such filter unfortunately.

You can check the filters here : https://dev.twitter.com/rest/reference/get/statuses/mentions_timeline
