### ISSUE TITLE
Full Text Direct Messages

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#46]
Hi Linvi,
Twitter has (relatively) recently upped the limit on the length of Direct Messages from 140 chars to 10,000.
For compatibility, the REST API limits messages to 140 chars unless you specify you want to use the new higher limit by adding "full_text=true" as a query param.
Could this functionality be added to Tweetinvi?
You can see the full details at https://twittercommunity.com/t/removing-the-140-character-limit-from-direct-messages/41348

Apologies if I've missed something and this is already implemented.
Cheers,
Josh

**Comment by linvi** [comment]
Dev Note: Not only this parameter needs to be added but the same way as Tweets, a `PublishMessageParameters` class should be created and used to improve extensibility.
