### ISSUE TITLE
On Visual Studio Mac, with F#: The type initializer for 'Tweetinvi.Auth' threw an exception

### ISSUE THREAD

**Issue by alvivar** [linvi/tweetinvi#460]
Hi!

On Visual Studio Mac, with an F# project: The type initializer for 'Tweetinvi.Auth' threw an exception.

I tried the same code with the Netcore version and it works, but Netcore is currently incompatible with some libraries that I can access from the Visual Studio Mac version.

This is the full dump of the exception test
[exception.txt](https://github.com/linvi/tweetinvi/files/769807/exception.txt)

This is the repository with the code
[Repository](https://github.com/alvivar/river)

Thanks!

**Comment by JoshKeegan** [comment]
Take a look at https://github.com/linvi/tweetinvi/wiki/Xamarin-Android,-iOS-and-Mono
Microsoft having bought Xamarin makes "Visual Studio for Mac" sound like it isn't running your code on mono, but as far as I'm aware it still is, so needs an extra step to work properly :)

**Comment by alvivar** [comment]
Thank you!

**Comment by linvi** [comment]
Thank you @JoshKeegan. @alvivar is this problem solved?

**Comment by alvivar** [comment]
@linvi I just tested it, and yes, it works!

I just moved from  **Packages**/**Microsoft.Net.Http**/**net40** contents in to **Bin**/**Debug**, and it solved the problem.

**Comment by linvi** [comment]
Thank you for the feedback, I will test this before the next release though.

**Comment by linvi** [comment]
Hello, 

Please note that .NET40 won't be supported anymore with version 2.0 but this problem should now have solved this issue.

Cheers,
Linvi
