### ISSUE TITLE
Dot net core httpClient.Timeout set to 10 seconds 

### ISSUE THREAD

**Issue by jovica-krstevski-locm** [linvi/tweetinvi#461]
Hi, 
I am using FilteredStream implementation and discover that 
HttpClient used for socket is stopping if the tracks are not so popular. 
i found that dot net core implementation on this   httpClient.Timeout = TimeSpan.FromMilliseconds(Timeout.Infinite) is is set to 10  seconds.

![default netcore](https://cloud.githubusercontent.com/assets/2655792/22886057/756f4874-f1fc-11e6-9634-679585e6dd4a.JPG)
 and for  regular dot net is working properly 
![default net4 5](https://cloud.githubusercontent.com/assets/2655792/22886072/8c64b852-f1fc-11e6-94e3-2d64e18f8fee.JPG)

Can you change code and set bigger timeout?  example  twitterQuery.Timeout = TimeSpan.FromDays(1) 

Thanks
Jovica

**Comment by JoshKeegan** [comment]
You can change this by setting `TweetinviConfig.ApplicationSettings.HttpRequestTimeout`.
Note that Tweetinvi has application-wide settings and thread-specific settings, and the thread-specific ones override the application-wide ones.
So if you set the above to a higher value, it will still be the default for the current thread, until you either set the current thread value, or use `TweetinviConfig.CurrentThreadSettings.InitialiseFrom(TweetinviConfig.ApplicationSettings)` to copy all settings over to the current thread. Any new threads will spawn with the application-wide settings though.

**Comment by JoshKeegan** [comment]
Deleted my previous comment as looking at the code (the relevant bit was in your screenshot, whoops!) the stream overrides the timeout set on the twitterQuery. So the Tweetinvi timeout settings aren't any use here, it just needs a workaround in the library, sorry :)

**Comment by linvi** [comment]
Done, thank you for reporting the issue. This will be released as part of the next version of the library.
