### ISSUE TITLE
How Do We Handle Multiple Sets Of Credentials?

### ISSUE THREAD

**Issue by Unkindjolt** [linvi/tweetinvi#462]
So say we want to get two or three accounts and get their follower/friends count but we need to use credentials for each account, how do we handle this?

**Comment by JoshKeegan** [comment]
The simplest way is to just set the credentials you want to use before making each request.
So in pseudocode:
```
set credentials user A
make request user A
set credentials user B
make request user B
```
There are other options but that is probably the simplest way to get started.

**Comment by Unkindjolt** [comment]
So it would be possible then to use a for each loop to create credential
variables?

**Comment by eaba** [comment]
Yes! In each loop, create new credential using the current user token a secret. It works!

**Comment by linvi** [comment]
The library provides multiple solutions to handle multiple credentials.

- By Tweetinvi credentials uses a per thread solution (https://github.com/linvi/tweetinvi/wiki/Credentials#credentials-and-multiple-threads). 
- As suggested by @JoshKeegan and @eaba you can simply loop over and use the `SetUserCredentials`.

What I would recommend though is to use the following snippet:

``` c#
// Generate credentials that we want to use
var creds = new TwitterCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

// Use the ExecuteOperationWithCredentials method to invoke an operation with a specific set of credentials
var tweet = Auth.ExecuteOperationWithCredentials(creds, () =>
{
      return Tweet.PublishTweet("Hello World");
});
```

`Auth.ExecuteOperationWithCredentials` allow you to specify the credentials that will be used by Tweetinvi inside your operation.
