### ISSUE TITLE
Tweet Search REST API Problem

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#464]
When i search a topic which have no hash sign (#) like
var matchingTweets = Search.SearchTweets("TRUMP");
it returns those tweets also which does not contain word trump.
How i handle this?

but if i use 
var matchingTweets = Search.SearchTweets("#TRUMP");
it gives me accurate results.

**Comment by linvi** [comment]
It does not really look like a bug of the library but potentially from Twitter.
Have you made sure that the tweets that you received were not tweets in reply to a Tweet containing the "TRUMP" keyword?

I will try it but I don't think this is something for which I will be able to do anything.

**Comment by mike2341** [comment]
for example i search word "ISIS" it returns me this tweets
var matchingTweets = Search.SearchTweets("ISIS");
https://twitter.com/DMV_Drummerboyy/status/832426727343271937
its bug

**Comment by linvi** [comment]
Hello, a quick message to inform you that I have investigated your problem and it clearly is a problem from Twitter.

I opened a bug request on their website: https://twittercommunity.com/t/search-api-returns-invalid-results/86918

Please +1/love it because they are always very hard to reach.

**Comment by linvi** [comment]
So as explained on the twittercommunity forum, the Search is returning this but there isn't always a solution for Tweetinvi to know about it.

They are apparently going to provide some improvements in the future.

I think I will leave this issue out of 1.3 and get back on it later on when more has been done on twitter and that we have for insight of the search behaviour.

If you think of anything that could help you develop in the future please let me know.

**Comment by linvi** [comment]
Closing as the roadmap for such changes will come in 2018 and will probably involve new changes.
