### ISSUE TITLE
TweetLength work incorrect when uri contains '-' character

### ISSUE THREAD

**Issue by ArtuomKazlovski** [linvi/tweetinvi#468]
TweetLength work incorrect when uri contains '-' character
Uris for test:
`tweet-invi.codeplex.com/salut/linvi.plop`
`tweetinvi.codeplex.com/salut/lin-vi.plop`
`tweetinvi.code-plex.com/salut/linvi.plop`

[In addition the hyphen is permitted if it is surrounded by characters](https://en.wikipedia.org/wiki/Domain_name)

**Comment by linvi** [comment]
Thank you for looking into it and for offering a pull request. I will review this and make it available in next release.

**Comment by linvi** [comment]
Fixed from #469 pull request.
