### ISSUE TITLE
Add new field to help/configuration

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#47]
Hi Linvi,
Twitter has added a new "dm_text_character_limit" field to help/configuration (added in the build up to increasing the Direct Message size limit, see #46).
Can this be exposed through Tweetinvi?
Cheers,
Josh

**Comment by linvi** [comment]
Dev Note: Not only this parameter needs to be added but the same way as Tweets, a `PublishMessageParameters` class should be created and used to improve extensibility.
