### ISSUE TITLE
How To get full tweet Text.

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#470]
How can i get full text of tweet.sometimes its returns ...... at last.??

**Comment by RickySan65** [comment]
you can use tweet.FullText

**Comment by kooroshh** [comment]
FullText have ... too

**Comment by linvi** [comment]
To verify

**Comment by mfusiki** [comment]
Any workaround for this at the moment?

**Comment by linvi** [comment]
Hello there have you set up the configuration required to use Twitter Extended Mode.

``` c#
TweetinviConfig.CurrentThreadSettings.TweetMode = TweetMode.Extended;
TweetinviConfig.ApplicationSettings.TweetMode = TweetMode.Extended;
```
