### ISSUE TITLE
Search API unexpected behaviour

### ISSUE THREAD

**Issue by richweb** [linvi/tweetinvi#472]
Hi

I'm doing a filtered search as such:

``` c#
            string keywordQuery = String.Join(" OR ", keywords);

            // perform the search
            var searchParameter = new SearchTweetsParameters(keywordQuery) {
                MaximumNumberOfResults = 1000,
                Lang = Tweetinvi.Models.LanguageFilter.English
            };
            var tweets = Tweetinvi.Search.SearchTweets(searchParameter);
```

where keywords is an array of keywords I want to find. For example, I might want to returns posts that include the words, "stress" or "depression". What seems to be happening is that its returning posts that EITHER contain one or the other term but not both. So it won't return posts that include BOTH "stress" and "depression".

I can't use an AND because the keywords array might contain similies of depression like "sad", "unhappy". I don't want to AND all those together as its unlikely to return any posts at all. But I would expect it to return all posts that contain those words together with any others that have been OR'd

Any thoughts?

Kind Regards

Richard

**Comment by mike2341** [comment]
var searchParameter = new SearchTweetsParameters("Donald Trump") {
            MaximumNumberOfResults = 1000,
            Lang = Tweetinvi.Models.LanguageFilter.English
        };
        var tweets = Tweetinvi.Search.SearchTweets(searchParameter);

It will return those tweets which contain donald and trump in one tweep.
try this hope it helps

**Comment by JoshKeegan** [comment]
Hi Richard,
Twitter's search API will return tweets that match all terms OR'd.
I've just checked myself:
![dashboard - social sense - google chrome_6](https://cloud.githubusercontent.com/assets/1682204/25274016/397f74f6-2686-11e7-8d03-153ed8943490.jpg)

Bear in mind the usual caveats of the search API though: max ~ 1 week & can take a min for a new tweet to get included.
Cheers,
Josh

**Comment by linvi** [comment]
@richweb can you confirm that @JoshKeegan has helped you with the bug and that it can now be closed?

**Comment by richweb** [comment]
Hi

Sorry for the delay in response.

Its fine - all works as expected. 

The "issue" is simply that posts that contain only one keyword are obviously more numerous / popular so they are the ones that get returned. Other posts that contain multiple keywords are less common. On the surface it may seem they aren't getting returned....but they actually are! :)

All good.

Thanks for your time and sorry for my confusion!

Kind Regards


Richard
