### ISSUE TITLE
Question : Why Tweetinvi.Parameters.UserTimelineParameters doesn't have Since and Untill parameters.

### ISSUE THREAD

**Issue by webdevaman** [linvi/tweetinvi#474]
I was retrieving some tweets from `Tweetinvi.Search.SearchTweets();`  `Since` and `Until` parameters are present there when filter tweets through `Tweetinvi.Parameters.SearchTweetsParameters`

But why there are no such parameters in `UserTimelineParameters` when retrieve tweets from `Timeline.GetUserTimeline(user.UserIdentifier, new UserTimelineParameters() {
                //<filtering>
                }));` 
How can i get those tweets lies between `Since` and `Until` date in `Timeline.GetUserTimeline()` when filtered by `UserTimelineParameters`

**Comment by linvi** [comment]
`Since` and `Until` are 2 properties only available for search because the Twitter API does not provide these parameters for the Timeline endpoint.

`UserTimelineParameters` contains 2 similar properties :

- `SinceId`
- `MaxId`
