### ISSUE TITLE
Filtered Streams - Tweet Language value changed from literal to numeric

### ISSUE THREAD

**Issue by Ionut-Cipeliuc** [linvi/tweetinvi#476]
Hello,

In the last couple of months my app started to receive through "Filtered Streams" the tweets json having the lang value changed from literal (e.g.: en, fr, de, es) to numerical (e.g.: 42,23,45) values.

I've tried to search the web about this change and couldn't find (any) real usable information (please share any resource regarding this change if you own any, it would be much appreciated). Obviously this numeric language format is not very friendly for any human user.

I would like to know how reliable are the mappings of Tweetinvi.Models.Language enum (since I've received tweets having a language value and a different content language).

Thank you.

Regards,
Ionut

**Comment by linvi** [comment]
> In the last couple of months my app started to receive through "Filtered Streams" the tweets json having the lang value changed from literal (e.g.: en, fr, de, es) to numerical (e.g.: 42,23,45) values.
>
> I've tried to search the web about this change and couldn't find (any) real usable information (please share any resource regarding this change if you own any, it would be much appreciated). Obviously this numeric language format is not very friendly for any human user.

I will investigate this problem.

> I would like to know how reliable are the mappings of Tweetinvi.Models.Language enum (since I've received tweets having a language value and a different content language).

You are correct. Twitter is not very good to identify the language. I had the same problem in the past.

**Comment by Ionut-Cipeliuc** [comment]
Hello,

I just want to thank you for the interest in the issue. Meanwhile I've converted all the data to use the numerical format.

Regards,
Ionut

**Comment by linvi** [comment]
Hello there,

I looked at your issue today (numerical) but I was not able to reproduce it.
Could you please share your code and the version of Tweetinvi that you are using.

Thank you

**Comment by Ionut-Cipeliuc** [comment]
Hello,

Sorry for the delay. Here is the code used to stream twitter data. I'm
using version 1.2.0.1 ( https://www.nuget.org/packages/TweetinviAPI/1.2.0.1/
)

Thanks for support & interest.

Regards,
Ionut

**Comment by linvi** [comment]
Cannot be reproduced. This probably was a temporary bug from the Twitter API.
