### ISSUE TITLE
Get "everything" of a User

### ISSUE THREAD

**Issue by KalimKaLo** [linvi/tweetinvi#477]
Hello,

I want to create a log - tool which should get triggered, when a special Account (my own Status Account) Tweet a new Status or got a Mention and gives an answer of the mention.

Is there a Solution for this?

**Comment by JoshKeegan** [comment]
I think a User stream is what you're after: https://dev.twitter.com/streaming/userstreams

If you needed it to be 100% robust, you'd also need to poll various REST API endpoints to fill in anything that gets missed from the streaming API (e.g. if it disconects due to a network failure).
