### ISSUE TITLE
Application-Only Credentials and streaming ?

### ISSUE THREAD

**Issue by ddifeo** [linvi/tweetinvi#478]
Is it possible to have Application-Only Credentials and use the stream api at the same time?

**Comment by Meligy** [comment]
Have you managed to figure out a workaround for application only credentials?

**Comment by linvi** [comment]
As explained in the documentation streams cannot be started from Application-Only Credentials.

- https://dev.twitter.com/streaming/reference/post/statuses/filter
- https://dev.twitter.com/streaming/reference/get/statuses/sample
