### ISSUE TITLE
Tweeting with a video returns an error: The tweet cannot be published as some of the medias could not be published

### ISSUE THREAD

**Issue by misterraj7** [linvi/tweetinvi#48]
I am tweeting with the video.

Here is the code:

       public static void Tweet_PublishTweetWithVideo()
         {
            string filePath = @"C:\Downloads\Video\1.mp4";
            byte[] file1 = File.ReadAllBytes(filePath);
            var tweet = Tweet.PublishTweetWithVideo("first tweet with video", file1);
            
             
         }

How ever this gives me an error: on debugging I found this function returns null.
I get an error: " throw new OperationCanceledException("The tweet cannot be published as some of the medias could not be published!");"

      public IMedia ChunkUploadBinary(byte[] binary, string mediaType)
        {
            var uploader = CreateChunkedUploader();

            if (uploader.Init(mediaType, binary.Length))
            {
                if (uploader.Append(binary))
                {
                    return uploader.Complete();
                }
            }

            return null;
        }

Has some one tried and found a solution to this problem? Please help!

**Comment by linvi** [comment]
Hello,

Please have a look on the [upload](https://github.com/linvi/tweetinvi/wiki/Upload) documentation page. 

There are a few items to keep in mind when uploading video:

* The maximum file size is 15MB and is checked during the upload process
* The maximum length is 30 seconds and is checked when Tweeting with a video media_id
* One video (or animated GIF) media_id can be added to a Tweet. Photos are the only media type that can be added up to four times.

Also if the video is bigger than 5MB you will probably have to use [chunked upload](https://github.com/linvi/tweetinvi/wiki/Upload#chunked-uploads).

Please send me some feedback

**Comment by misterraj7** [comment]
The video that i Used was less than 1MB and the video length is less than 13 seconds. Here is the file:

https://scontent.cdninstagram.com/hphotos-xaf1/t50.2886-16/11918383_946519272061077_343736560_s.mp4

You can try.

**Comment by linvi** [comment]
I will try to look at this today and get back to you.

**Comment by rudiv** [comment]
Just to confirm I have this issue intermittently.

Uploading the same video file will fail with a rate of around 15%, the rest of the time it is successful. I haven't had chance to try and pinpoint the issue within tweetinvi yet, but I'm assuming it's a Twitter error more than a library error.

**Comment by linvi** [comment]
Hi,

For some reason the media you are trying to publish are not compatible.
Here is the Twitter Error : `Invalid or unsupported media, Reason: UnsupportedMedia`.

You can easily get the Exception information by using the `ExceptionHandler`:

``` c#
ExceptionHandler.WebExceptionReceived += (sender, args) =>
{
    Console.WriteLine(args.Value);
};
```

I am therefore closing this issue.

@rudiv if you find out the error is coming from Tweetinvi please let me know.

Cheers,
Linvi

**Comment by stormbreakers** [comment]
Hi, even i am facing the same problem, i am not sure what or where the things are going wrong.
i am using codebird library and used the example provided by them, however it did not work.
it would be great if someone can please look into my query

**Comment by linvi** [comment]
I do not understand whether you are using Tweetinvi or Codebird?

**Comment by baslentfert** [comment]
hi linvi,

i am facing also problems
Code : 400
Error documentation description : Bad Request - The request was invalid or cannot be otherwise served. An accompanying error message will explain further. In API v1.1, requests without authentication are considered invalid and will yield this response.
Error message : https://api.twitter.com/1.1/statuses/update.json?status=test%20dan%20dit%20&media_ids=706598439145103360 web request failed.
media parameter is invalid. (44)


            Auth.SetUserCredentials("personal", "personal", "personal", "personal");

            TweetinviEvents.QueryBeforeExecute += (sender2, args) =>
            {
                Console.WriteLine(args.QueryURL);
            };

            ExceptionHandler.WebExceptionReceived += (sender2, args) =>
            {
                Console.WriteLine(args.Value);
            };

            var binary = File.ReadAllBytes(AppDomain.CurrentDomain.BaseDirectory + "/MediaCoder_test12.mp4");
            var tweet = Tweet.PublishTweetWithVideo("test", binary);
            Console.WriteLine(tweet.IsTweetPublished);


the tweet var is null

when i just use this:
            var tweet = Tweet.PublishTweet("ok yes");
            Console.WriteLine(tweet.IsTweetPublished);

everything woks fine.
