### ISSUE TITLE
List id must be set

### ISSUE THREAD

**Issue by markjustin** [linvi/tweetinvi#482]
I am using Tweetinvi to get the tweets from a twitter list.

For some reason, when I try to do so, I get an exception thrown with the message "List id must be set".

I've followed the documentation and I can't see anything wrong with how I'm using it.

This is how my code looks:

Auth.SetUserCredentials({consumerKey},{consumerSecret},{twitterAccessToken},{twitterAccessTokenSecret});
var list = TwitterList.GetExistingList("durham", "NCLairport");

It should return this list: https://twitter.com/NCLairport/lists/durham

Any ideas on how to get this working?

**Comment by JoshKeegan** [comment]
Looks like a bug in Tweetinvi.

In `TwitterListFactoryQueryGenerator.GetListByIdQuery`, it calls `_listsQueryValidator.ThrowIfListIdentifierIsNotValid` which checks an id has been supplied for the list.  
This call to `GetListByIdQuery` comes from `TwitterListFactoryQueryExecutor.GetExistingList`, so maybe that was supposed to call a different method, or maybe `GetListByIdQuery` should work with any `ITwitterListIdentifier` value, I don't know. One for @linvi to decide :)

Until a fix is made, get the ID for your list & use that instead when calling `TwitterList.GetExistingList`.

**Comment by linvi** [comment]
Thank you for reporting the bug.

This will be fixed ;)
