### ISSUE TITLE
CustomQueryParameter

### ISSUE THREAD

**Issue by Bader80** [linvi/tweetinvi#484]
Hi there
When adding "CustomQueryParameter" to my search, sometimes I get the expected results, but sometimes the result is not affected by the parameter.

code example:

``` c#
var searchParameter = Search.CreateTweetSearchParameter("Trump");
searchParameter.MaximumNumberOfResults = 10;
searchParameter.AddCustomQueryParameter("from", "CNN");
var tweets = Search.SearchTweets(searchParameter);
```

Sometimes I get 10 tweets by @CNN containing Trump, other times I get 10 tweets containing Trump but by different Accounts.

Am I missing something, or what?

**Comment by linvi** [comment]
1 month have passed now. Sorry for not replying earlier.

Have you been able to fix your problem?

**Comment by Bader80** [comment]
unfortunately, no ;(

**Comment by linvi** [comment]
I tried to reproduce your problem without any success.

Could you please log the queries executed by Tweetinvi via the following line of code.

``` c#
TweetinviEvents.QueryBeforeExecute += (sender, args) =>
{
    Console.WriteLine(args.QueryURL);
};
```

And let me know any of the query is incorrect. If this is the case then there is a bug in Tweetinvi.
If all the queries are the same, then it means that something is going wrong with the Twitter Search API (this would not be a first).

**Comment by Bader80** [comment]
Well I noticed that when I request few number of results (tweets) the query works perfectly.
but when I request rather a big number, say 300, It doesn't work as expected.

var searchParameter = Search.CreateTweetSearchParameter("Trump");
searchParameter.MaximumNumberOfResults = 300;
searchParameter.AddCustomQueryParameter("from", "CNN");
var tweets = Search.SearchTweets(searchParameter);

**Comment by linvi** [comment]
Thank you I will test that.

**Comment by kalidorweb** [comment]
Your lib is awesome. Please help.

**Comment by linvi** [comment]
@kalidorweb Please let me know how I can help?

Are you having the same issues that @Bader80 is having?

**Comment by linvi** [comment]
@Bader80 The problem came from the query that you were sending to Twitter.

Please use the following code:

``` c#
var searchParameter = Search.CreateTweetSearchParameter("trump from:CNN");
searchParameter.MaximumNumberOfResults = 300;
//searchParameter.AddCustomQueryParameter("from", "CNN");
var tweets = Search.SearchTweets(searchParameter).ToArray();
```

Sorry for the long time to reply.

Cheers,
Linvi

**Comment by Bader80** [comment]
Thank you
