### ISSUE TITLE
Stream API speed and accessing multiple streams at once

### ISSUE THREAD

**Issue by prasadyaji** [linvi/tweetinvi#490]
Hi,

I have started using tweetInvi stream API to get filtered streams, it's working as expected. But, it's taking almost 1 sec to return 1 tweet. Is there any way I can increase this speed..? Also, from arguments we get one tweet at a time, Is there any way I can get a list of tweets available at that given point of time.?

            stream.MatchingTweetReceived += (sender, args) =>
            {
                   .....
                  Console.WriteLine(args.Tweet.Text);
            };

**Comment by linvi** [comment]
Hello there,

From the testing Tweetinvi is capable of handling hundreds of millions tweets per day from a stream.
Are you sure that your stream filters are supposed to return more than 1 tweet per second?

**Comment by prasadyaji** [comment]
Thanks, @linvi , you were right... I changed the stream filter for trending hashtag and its returning lot of tweets as expected. However, I have seen my stream getting stuck(paused) by itself after some time... I am not getting any exceptions, I have only one stream which is currently running and I did not get any stream stopped or stream paused event. Any idea why is this happening..?

**Comment by linvi** [comment]
Not really, if you do not receive any `StreamStopped` event the Stream must be running.

To get more information can you check the `JsonObjectReceived` event that actually returns ALL the events retrieved by the stream, including the non expected events.

Let me know when you have more information about it.
