### ISSUE TITLE
Issue with Video Uploads and Media Category

### ISSUE THREAD

**Issue by vdms-mark** [linvi/tweetinvi#492]
Seemingly randomly, our call to IChunkedUploader.Init(...) started failing.  Getting the last exception yields this:

> "Forbidden - The request is understood, but it has been refused or access is not allowed. An accompanying error message will explain why. This code is used when requests are being denied due to update limits."

Naturally I thought it was something to do with rate limiting, but after significant investigation, that's not the case.  I was explicitly specifying "amplify_video" for the IChunkUploadInitParamters.MediaCategory, and after some trial-and-error code changes, I found that removing that specification (and temporarily the status checks after uploading), I stopped getting any exceptions.
Further, after some digging around, I found another category enum "tweet_video".  I tested this with status checks after the Complete() call, and the status checks work.

So, it sounds like there is some issue with the "amplify_video" category.  Additionally, the "tweet_video" category is also valid for status checks.

**Comment by linvi** [comment]
This will be investigated, thanks for reporting it.

**Comment by linvi** [comment]
I hope this small changes will help people to not use `amplify_video` but `tweet_video`.

Thanks for your feedback.

**Comment by linvi** [comment]
I have also changed the documentation ;)
