### ISSUE TITLE
Can't seem to update account settings

### ISSUE THREAD

**Issue by RickySan65** [linvi/tweetinvi#495]
i can't seem to update the account settings, i set them, then update the settings (account.update etc)
is this a bug or is it me?

**Comment by RickySan65** [comment]
to be clear it wont save the settings..

**Comment by linvi** [comment]
Could you please share the code you are using. Also are you sure that your application uses the `Read, Write` authorization.

Thanks

**Comment by RickySan65** [comment]
Here's what i'm using..

var settings = au.GetAccountSettings();                           
 var r = Account.CreateUpdateAccountSettingsRequestParameters(settings);
 
 switch (cbAllowDirectMessages.SelectedIndex)
 {
     case 0: settings.AccountSettingsDTO.AllowDirectMessagesFrom = AllowDirectMessagesFrom.All; break;
     case 1: settings.AccountSettingsDTO.AllowDirectMessagesFrom = AllowDirectMessagesFrom.Following; break;
 }

 switch (cbprivacymode.SelectedIndex)
 {
     case 0: settings.AccountSettingsDTO.PrivacyMode = PrivacyMode.Private; break;
     case 1: settings.AccountSettingsDTO.PrivacyMode = PrivacyMode.Public; break;
 }
 switch (cbSensitiveMedia.SelectedIndex)
 {
     case 0: settings.AccountSettingsDTO.DisplaySensitiveMedia = true; break;
     case 1: settings.AccountSettingsDTO.DisplaySensitiveMedia = false; break;
 }

 
 r.SleepTimeEnabled = false;

 var res = au.UpdateAccountSettings(r);
 
 // or 
 var newAccountSettings = Account.AccountController.UpdateAuthenticatedUserSettings(r);

Not sure if "AllowDirectMessagesFrom" etc is exposed in the update method though.

**Comment by RickySan65** [comment]
has this been fixed in the current release?

**Comment by linvi** [comment]
I have not looked into it. Release 2.0 had more serious bugs.

This will be taken care in version 2.1.

**Comment by linvi** [comment]
This is actually not a bug. Your code if modifying the `settings` while you should be modifying `r`.

The only settings that Twitter allows to change are the properties exposed by `IAccountSettingsRequestParameters`:

``` c#
/// <summary>
/// The languages which Twitter should use for this user. 
/// </summary>
List<Language> Languages { get; set; }

/// <summary>
/// Must be a Timezone from http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html
/// </summary>
string TimeZone { get; set; }

/// <summary>
/// The Yahoo! Where On Earth ID to use as the user’s default trend location. 
/// Global information is available by using 1 as the WOEID. 
/// </summary>
long? TrendLocationWoeid { get; set; }

/// <summary>
/// When enabled sleep time is the time when push or SMS notifications should not be sent to the user.
/// </summary>
bool? SleepTimeEnabled { get; set; }

/// <summary>
/// The hour that sleep time should begin if it is enabled. 
/// The value for this parameter should be provided in ISO8601 format (i.e. 00-23). 
/// The time is considered to be in the same timezone as the user’s time_zone setting.
/// </summary>
int? StartSleepTime { get; set; }

/// <summary>
/// The hour that sleep time should end if it is enabled.
/// The value for this parameter should be provided in ISO8601 format (i.e. 00-23). 
/// The time is considered to be in the same timezone as the user’s time_zone setting.
/// </summary>
int? EndSleepTime { get; set; }
```

You can read more about it on Twitter API documentation : https://dev.twitter.com/rest/reference/post/account/settings
