### ISSUE TITLE
Tweetinvi.Stream.CreateUserStream with account with more 10k followers

### ISSUE THREAD

**Issue by AndresRGC** [linvi/tweetinvi#501]
Hi, i have been using this method Tweetinvi.Stream.CreateUserStream().

In an account with more of 10k followers, TweetInvi is not firing any event for streaming.

I have tested with normal twitter Userstream request and with the same account is working.

Thank you.

**Comment by linvi** [comment]
Hello Andres,

I have been made aware of problems for users with thousands of followers. The problem is that I do not have such an account.

Do you think you could share your credentials temporarily so that I can find out what is going wrong with this type of account?

Cheers,
Linvi

**Comment by AndresRGC** [comment]
Sorry but this account is of one of my clients, and for privacy questions is not possible to share credentials with you, sorry.

This is the first response of twitter for this type of accounts, hope it helps.
Please note that xxxxxxxx is for privacy questions.
{"warning":{"code":"FOLLOWS_OVER_LIMIT","message":"The requested user follows more accounts than the maximum supported by this streaming endpoint. Only a subset of 10000 followed accounts are included in this stream.","user_id":xxxxxxxxxxx,"timestamp_ms":"1493310098456"}}

is possible that you are considering this type of message as an error??.

**Comment by linvi** [comment]
I will check this out but normally Tweetinvi should be supporting this warning.

**Comment by linvi** [comment]
Hello there, can you please confirm that the `xxxxx` is an `integer/long` please.
If it is, I have found the bug and I could send you a beta of Tweetinvi 1.3 with the fix included.

**Comment by AndresRGC** [comment]
Yes, it is an integer value.

{"warning":{"code":"FOLLOWS_OVER_LIMIT","message":"The requested user follows more accounts than the maximum supported by this streaming endpoint. Only a subset of 10000 followed accounts are included in this stream.","user_id":1435435435346843434354,"timestamp_ms":"1493311733860"}}

**Comment by linvi** [comment]
Thank you. Will you want a beta build or do you want to wait for the next release (2~4 weeks).

**Comment by AndresRGC** [comment]
Please send me a beta version for checking if it is fixed. Many thanks.

**Comment by linvi** [comment]
Please install the Tweetinvi 1.3-alpha from nuget.
Note that this version has not been fully tested specially for Portable Class Libraries and .NETCore.

Let me know if this version fixed your problem.

Cheers,
Linvi

**Comment by AndresRGC** [comment]
I have tested 1.3-alpha and it's working. Thank you very much. :)

**Comment by linvi** [comment]
Great, remember to upgrade to 1.3 when it is released!

Thank you for reporting the issue and the feedback.
