### ISSUE TITLE
Tweetinvi always showing null user.

### ISSUE THREAD

**Issue by Ralphanzel** [linvi/tweetinvi#502]
I'm new at using tweetinvi, so I tried make a simple one. but the same error always showed up: Additional information: Value cannot be null.

here's the code of mine:

``` c#
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Windows.Forms;
using Tweetinvi;
using Tweetinvi.Core.Interfaces;

namespace WindowsFormsApplication13
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        public void Form1_Load(object sender, EventArgs e)
        {
            
        }

        private void button1_Click(object sender, EventArgs e)
        {
            string AccessToken = "myAccessToken";
            string TokenSecret = "myTokenSecret";
            string ConsumerKey = "myConsumerKey";
            string ConsumerSecret = "myConsumerSecret";
            Auth.SetUserCredentials(ConsumerKey, ConsumerSecret, AccessToken, TokenSecret);
            var user = Tweetinvi.User.GetAuthenticatedUser();
            richTextBox1.Text += user;
            var tweet = Tweet.PublishTweet("Hello from c#");
            var timelinetweets = Timeline.GetUserTimeline(user);
            foreach (var timelinetweet in timelinetweets)
            {
                richTextBox1.Text += timelinetweet;
            }
        }
    }
}
```

**Comment by RickySan65** [comment]
richTextBox1.Text += timelinetweet.Text will give the body of the tweet..

**Comment by linvi** [comment]
If `var user = Tweetinvi.User.GetAuthenticatedUser();` is null it means that your credentials are not valid.

**Comment by linvi** [comment]
I am closing the bug as I did not receive any answer for 30 days. Let me know if you still encounter this problem.

**Comment by SachinUnfyd** [comment]
i am facing Same issue, 

 var autuser = Tweetinvi.User.GetAuthenticatedUser();
 var user = Tweetinvi.User.GetUserFromScreenName("@*********"); 

autuser  or  user   get always null  response

**Comment by linvi** [comment]
@SachinUnfyd  When receiving null from Tweetinvi it means that something went wrong.

In this case, the fact that `GetAuthenticatedUser` returns null probably means that the credentials you are providing are invalid.
