### ISSUE TITLE
Stream `JsonObjectReceived` no longer gets raised for keep-alives

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#506]
I've been starting to use the streaming API again (hence the sudden flurry of activity, sorry!). Previously I received the keep-alives for the stream using the `JsonObjectReceived` event and checking if the `JsonObjectEventArgs.Json` was the empty string.

This no longer gets fired for keep-alives & looking in the code that appears to be intentional (snippet from `StreamTask.Start`):
```cs
var json = GetJsonResponseFromReader(_currentStreamReader, _twitterQuery);

var isJsonResponseValid = json.IsMatchingJsonFormat();
if (!isJsonResponseValid)
{
	if (json == string.Empty)
	{
		continue;
	}

	if (json != null)
	{
		throw new WebException(json);
	}

	if (TryHandleInvalidResponse(numberOfRepeatedFailures))
	{
		++numberOfRepeatedFailures;
		continue;
	}

	throw new WebException("Stream cannot be read.");
}

numberOfRepeatedFailures = 0;

if (StreamState == StreamState.Running && !_processObject(json))
{
	SetStreamState(StreamState.Stop);
	break;
}
```

Should/could this me moved to a separate event (or put back onto `JsonObjectReceived` if it was removed by accident)?

**Comment by linvi** [comment]
So you want to be informed when Twitter sends a Keep-Alive message?

**Comment by JoshKeegan** [comment]
That's right :)

**Comment by linvi** [comment]
Do you it ASAP or can it wait for later? I am trying to limit the scope of 1.3 to provide a release as early as possible.

**Comment by JoshKeegan** [comment]
Depends. If any other PRs will be in the next release then I'd like this too. If not though it doesn't matter to me.

I can make the changes & submit another PR if it's easier? I'll just need to know whether you'd rather it had a new event or revert to the previous behaviour of firing JSON Received with string.Empty.

**Comment by JoshKeegan** [comment]
Sorry, that should say "if all my other PRs..."

**Comment by linvi** [comment]
I think it should be a separate event. `KeepAliveReceived`.

**Comment by JoshKeegan** [comment]
Alright :)
