### ISSUE TITLE
Some tweets in timeline do not contain Media

### ISSUE THREAD

**Issue by C-H-F** [linvi/tweetinvi#509]
Some tweets in the timeline do not contain Media although the tweet does contain an image.

The  attached demo console application should simulate a client accessing twitter. I want to display the text and the image of every tweet. Some tweets do not contain an Image in media although twitter display an image.

[DemoProgram.zip](https://github.com/linvi/tweetinvi/files/1000489/DemoProgram.zip)

**Comment by paspy** [comment]
I am also experiencing this issue.
Further more, some tweets missing Media will also missing Hashtag, although the tweet contains both image and Hashtag.

**Comment by linvi** [comment]
Hello there.

Could you please send me the Tweet ID that you consider should contain a Media/Hashtag so that I can test and see if the problem comes from Tweetinvi or from Twitter.

**Comment by paspy** [comment]
864284541057355777
865740426023653376

Both two should contains hashtag and image

**Comment by linvi** [comment]
Your problem is that this is an extended Tweet and I guess you did not configure your application to use extended Tweets.

Please use the following :

``` c#
TweetinviConfig.CurrentThreadSettings.TweetMode = TweetMode.Extended;
TweetinviConfig.ApplicationSettings.TweetMode = TweetMode.Extended;
```
