### ISSUE TITLE
Giphy

### ISSUE THREAD

**Issue by winstanleyjohn** [linvi/tweetinvi#510]
Hello All,

What is the best way for Tweetinvi to use gifs from Giphy within a tweet?

I know its possible to download a gif and them upload it to twitter using 

public static ITweet PublishTweetWithImage(string text, byte[] image);

But is there any other way of doing it? Is that the only way?

Thanks 

John

**Comment by linvi** [comment]
Why is it a problem to send the gif with `PublishTweetWithImage`?

**Comment by RickySan65** [comment]
the way i do it is to get the gif from their public feed, store it locally and then publish it with linvi, i think he wants to do it directly from giphy, and not download it first.

**Comment by linvi** [comment]
Twitter does not provide such an endpoint on its public API.

**Comment by RickySan65** [comment]
i figured as much, not a smart move from a security point of view.  the normal way to do it works just fine, at least it does for me :)

**Comment by linvi** [comment]
@winstanleyjohn Please reopoen this issue if you think we have not provided a proper answer. But as per right now Twitter does not allow to do such a thing.

**Comment by winstanleyjohn** [comment]
Happy to download and publish as RickySan65 suggests. Just thought it was worth asking if Tweetinvi has anything built in to tweet Gifs from Giphy or if Twitter had any tricks that I didn't know about. 

Thanks for the help.
