### ISSUE TITLE
How to get Tweet's Retweeter Ids more than 100?

### ISSUE THREAD

**Issue by mike2341** [linvi/tweetinvi#511]

**Comment by linvi** [comment]
Hello there,

You have to use cursor queries. Tweetinvi already provide some tools for that but `GetRetweeterIds` cursors have not been implemented yet.

Please look at the same request here : https://github.com/linvi/tweetinvi/issues/208

**Comment by FurkanGozukara** [comment]
@linvi hey did this feature get added ? i mean the cursor?
