### ISSUE TITLE
Upload.UploadVideo amplify_video

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#512]
Hi,
When using `Upload.UploadVideo` i hadn't set the `mediaCategory` optional parameter, as the docs said it was set to `amplify_video` by default: https://github.com/linvi/tweetinvi/wiki/Upload.  
  
However, I got an error from Twitter:
```
Upload STATUS can only be invoked on uploads with processing metadata. Set the `media_category` to `amplify_video` to solve this isue.
```
So I set it `mediaCategory` to `amplify_video` and now it works!

Either this is an easy bug, or the docs need updating :)
Cheers,
Josh

**Comment by linvi** [comment]
Changed the documentation. As most developers currently do not use the STATUS endpoint.

**Comment by JoshKeegan** [comment]
Note for anyone that comes accross this in future, the code for the latest version of Tweetinvi is:
```C#
// Upload the video
DefaultLog.Debug("Uploading video to Twitter");
IUploadVideoParameters parameters = new UploadVideoParameters(fileVideo.FileContent)
{
    QueryMediaType = fileVideo.ContentType,
    QueryMediaCategory = "amplify_video"
};
IMedia twitterVideo = Upload.UploadVideo(parameters);
DefaultLog.Debug("Video uploaded to Twitter with Media ID {0}", twitterVideo.MediaId);
```

The fix is the same, but parameter names have changed, so would be kinda hard to figure out from this issue if you hadn't used the old method aswell :)
