### ISSUE TITLE
stream.StartStream() not blocking

### ISSUE THREAD

**Issue by danielghandahari** [linvi/tweetinvi#513]
stream.StartStream() is not blocking. I run the method in a test environment and it works perfectly fine. BUT, in my real program, I am running an extension in Visual Studio, and stream.StartStream() is not blocking, and therefore not working, help!

**Comment by linvi** [comment]
Are you sure that in your production environment the code does work.
I would assume that the stream fails, and therefore exit.

You can listen to the `StreamStopped` event to be informed when a stream stops.
The argument contains any error that could be associated with it.
