### ISSUE TITLE
Unable to filter stream emoji tracks

### ISSUE THREAD

**Issue by Dynogic** [linvi/tweetinvi#515]
Hello,

I'm trying to use Tweetinvi to filter stream emojis.

With Tweepy for Python, the following is giving me a constant stream output (the Fire emoji):
``` c#
from __future__ import absolute_import, print_function

from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream

# Go to http://apps.twitter.com and create an app.
# The consumer key and secret will be generated for you after
consumer_key=""
consumer_secret=""

# After the step above, you will be redirected to your app's page.
# Create an access token under the the "Your access token" section
access_token=""
access_token_secret=""

class StdOutListener(StreamListener):
    """ A listener handles tweets that are received from the stream.
    This is a basic listener that just prints received tweets to stdout.

    """
    def on_data(self, data):
        print(data)
        return True

    def on_error(self, status):
        print(status)

if __name__ == '__main__':
    l = StdOutListener()
    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)

    stream = Stream(auth, l)
    stream.filter(track=[u'\U0001f525'])
```

However, doing the following with Tweetinvi is yielding no solution:

``` c#
            var stream = Stream.CreateFilteredStream();
            stream.AddTrack("\ud83d\udd25");
            stream.MatchingTweetReceived += (sender, argz) =>
            {   
            };
            stream.StartStreamMatchingAllConditions();
```

Inspecting the raw web request made to the Twitter servers using Fiddler:
> POST https://stream.twitter.com/1.1/statuses/filter.json HTTP/1.1
> User-Agent: Tweetinvi/1.2.0.1
> Cache-Control: no-cache
> Authorization: [omitted]
> Accept: image/jpeg, application/json
> Content-Type: application/x-www-form-urlencoded; charset=utf-8
> Host: stream.twitter.com
> Content-Length: 38
> Connection: Keep-Alive
> 
> track=%F0%9F%94%A5&stall_warnings=true

Looks correctly formatted with the utf-8 charset properly specified.

Unsure to exactly what Tweetinvi is not doing properly that Tweepy is.

Please advise on a possible fix, or a possible direction forward.

Cheers,
Jake.

**Comment by Dynogic** [comment]
For reference: http://www.charbase.com/1f525-unicode-fire

**Comment by linvi** [comment]
Fixed in upcoming 2.1 ;)

**Comment by linvi** [comment]
Consider scenario like `hello+emoji`

**Comment by linvi** [comment]
Now every case properly works!
