### ISSUE TITLE
Other hashtags and mentions not being shown when truncated is true

### ISSUE THREAD

**Issue by Hudiel** [linvi/tweetinvi#517]
Hi Guys,

It seems other hashtags and mentions are not being shown if truncated is true.
is this connected to the bug with fulltext?

are there any temporary workarounds for this?

P.S. don't really know if i should have just commented this in the fulltext issue or not.

**Comment by linvi** [comment]
Please use the latest version of Tweetinvi https://github.com/linvi/tweetinvi/releases/tag/1.3.

This should probably solve your problem.
