### ISSUE TITLE
Cannot get it to work, prints done but nothing works! does not send a tweet!

### ISSUE THREAD

**Issue by mabbashm110** [linvi/tweetinvi#52]
using System;
using Tweetinvi;
using Tweetinvi.Core.Credentials;

namespace TweetTry
{
	class Program
	{
		static void Main(string[] args)
		{
			applicationMenu ();
			

		}

		static void applicationMenu()
		{
			ITwitterCredentials credentials = Auth.SetUserCredentials (Consumer Key, ConsumerSecret, AccessToken, AccessTokenSecret);

			Console.WriteLine ("Select an action");
			Console.WriteLine ("1. Tweet\n2. Get Timeline\n3. Get Logged User");
			string input = Console.ReadLine ();
			try
			{ 
			if (input == "1")
			{
                Tweet.PublishTweet ("@1o1reasons Thanks for the info");
				Console.WriteLine ("Done");
			}
				
			else if (input == "2")
			{
				var tweets = Timeline.GetHomeTimeline();
				
					Console.WriteLine (tweets.ToString());
				
			}

			else
			{
				var loggedUser = User.GetLoggedUser(credentials);
				Console.WriteLine (loggedUser.ToString ());
			}
            Console.ReadLine ();
			}
			catch (Exception ex)
			{
				Console.WriteLine (ex.Message);
				Console.ReadLine ();
			}
		}
	}
}

**Comment by mabbashm110** [comment]
I am a newbie at this so I must be doing something wrong! please help!

**Comment by linvi** [comment]
Thank you for your feedback. First of all, we need to verify that you the credentials you provide work.
To do so please do the following at the top of your application.

``` c#
Auth.SetUserCredentials (Consumer Key, ConsumerSecret, AccessToken, AccessTokenSecret);
var lu = User.GetLoggedUser();

if (lu != null)
{
    Console.WriterLine("You are authenticated as " + lu);
}
else 
{
    Console.WriterLine("Authentication failed!");
}
```

Get back to me with the result.

**Comment by mabbashm110** [comment]
Life saver!
it worked! there was an authentication issue!
Thanks a million.

**Comment by mabbashm110** [comment]
May need some help along the way, 
how do I search twitter for a specific hashtag and get all users and tweets?

**Comment by linvi** [comment]
Please read the following documentation to help you understand how to search on twitter with Tweetinvi.

* [Search](https://github.com/linvi/tweetinvi/wiki/Searches)
* [Filtered Stream](https://github.com/linvi/tweetinvi/wiki/Filtered-Streams)

Please let me know if you need more help, but please open new tickets if you have a bug.

Cheers,
Linvi
