### ISSUE TITLE
nuspec for v1.2.0.1 specifies wrong version of Autofac

### ISSUE THREAD

**Issue by jackfoxy** [linvi/tweetinvi#521]
<dependencies>
            <group>
                <dependency id="Autofac" version="3.5.2" />

Decompiling the Tweetinvi.dll, however, shows a reference to Autofac Version=3.5.0.0

**Comment by linvi** [comment]
The `3.5.2` version of Autofac is the expected version.
What is the exact problem you are facing?

**Comment by jackfoxy** [comment]
It's now immaterial to me. Tweetinvi 1.3.0 does not have this issue.
