### ISSUE TITLE
arg.Tweet.Text same as Tweet.fulltext

### ISSUE THREAD

**Issue by wessel1608** [linvi/tweetinvi#524]
Tweet.Text also includes the prefix and suffix aswell. So does the fulltext. How can i get tweet.text to display without the prefix and the suffix

**Comment by linvi** [comment]
For now just remove the `Suffix` and `Prefix` from the `FullText`.

**Comment by wessel1608** [comment]
How can I do that?

**Comment by wessel1608** [comment]
>>>>

**Comment by RickySan65** [comment]
var fulltweettext = tweet.FullText.Replace(tweet.Suffix, "");
etc...

**Comment by linvi** [comment]
Here is a simple example :

``` c#
var tweets = Timeline.GetHomeTimeline();
var tweetsWithSuffix = tweets.Where(x => x.FullText != x.Text).ToArray();
tweetsWithSuffix.ForEach(t =>
{
    t.Text = t.FullText.Substring(t.Prefix.Length);
});
```
