### ISSUE TITLE
Windows Store certification issue

### ISSUE THREAD

**Issue by laszlopaszternak** [linvi/tweetinvi#534]
Hi!

We tried to use your library in our Windows 8.1 project. (when we did the coding only a V0.9something version was available.)
Now we had a request to publish the app in the App Store but the certification process fails with the following error message:
Supported API test
    API System.Collections.Specialized.NameValueCollection in SYSTEM, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. Tweetinvi.dll calls this API.
    API System.Collections.Specialized.NameValueCollection.set_Item(System.String,System.String) in SYSTEM, PUBLICKEYTOKEN=B77A5C561934E089 is not supported for this application type. Tweetinvi.dll calls this API.

Do you happen to know a solution for this problem? (is it related to the nuget package version or it will fail no matter which version we use?)

Thanks!

**Comment by linvi** [comment]
It looks like a problem with PCL target. I have very recently upgraded all the code to .NETCore.
This will remove the PCL target limitations. If you project supports .NET 4.6 please upgrade.

I personally never published any W8.1 with Tweetinvi on the store. I just created them locally and tested them.

**Comment by linvi** [comment]
Closing as the problem comes from PCL which is no longer used after 2.0.
