### ISSUE TITLE
Multiple Assembly 2.0!

### ISSUE THREAD

**Issue by eaba** [linvi/tweetinvi#535]
On Visual Studio 2015 I got Multiple Assemblies issues on build for `System.Runtime.Serialization.Primitives` and `System.Reflection`. I got it to build by removing those two assemblies from the reference.

But then my Jobs didn't fire. I am using Quartz.net which worked with version 1.3.0 down but stopped working with 2.0.

There could be some conflicts.
Regards

**Comment by linvi** [comment]
Could you please share a sample project that can use before Tweetinvi is added as a nuget reference?

**Comment by eaba** [comment]
> Could you please share a sample project that can use before Tweetinvi is added as a nuget reference?

I dont totally get you! If you meant a sample protect for you to test it on, what about https://github.com/quartznet/quartznet? It has samples you could use?

**Comment by linvi** [comment]
I am asking for a project where I can reproduce the problem. I already have a lot of work so I try to ask for sample projects reproducing the issue so that I don't have to lose time on trying to reproduce the problem.

**Comment by eaba** [comment]
https://github.com/quartznet/quartznet/tree/master/src/Quartz.Examples is much faster to use. It will take me a while to create a sample project for this purpose. But you can use the above to reproduce the problem.

**Comment by cblaze22** [comment]
I have same issue.  Is this project explicitly targeting that version?

{"Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}

**Comment by linvi** [comment]
Hello there,

Very sorry for the lack of communication.
Did you check the ASP.NET considerations in here : 

https://github.com/linvi/tweetinvi/releases/tag/2.0

Let me know if this helps.

Cheers,
Linvi

**Comment by linvi** [comment]
Previous post should have answered the question.
