### ISSUE TITLE
Latest release error installing

### ISSUE THREAD

**Issue by sewarts** [linvi/tweetinvi#541]
Trying to install latest release via nuget - has anyone else come across this?

Could not install package 'Nito.AsyncEx.Context 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with 
that framework. For more information, contact the package author.

Thanks

**Comment by RickySan65** [comment]
You have to target 4.6.x it'll install properly then

**Comment by linvi** [comment]
Tweetinvi > 2.0 will not support versions lower than 4.6 as it has dependencies on .NETStandard 1.3.
