### ISSUE TITLE
is there a way to work with tweet parameters to Make it from mobile

### ISSUE THREAD

**Issue by AfaqSoft** [linvi/tweetinvi#544]
I am sorry for my Poor language
I have tweet like flowing code 

``` c#
var K = new Coordinates(5.2710054,24.0628200);
var sanFranciscoPlaceId = "5a110d312052166f";
var t = Tweet.PublishTweet(str, new PublishTweetOptionalParameters
{
    Coordinates = K,
    PlaceId = sanFranciscoPlaceId  ,
    DisplayExactCoordinates = true,
});
```
this code showing tweet place id
I need to Parameter to show this tweet Like it making from mobile 
How can do that .. Thank you

**Comment by linvi** [comment]
Sorry but I am not sure what you mean. Do you mean that you want to send the tweet from a computer/server but in a way that it is sent as if it came from a mobile?
