### ISSUE TITLE
How can i get PlaceId for any country ?

### ISSUE THREAD

**Issue by AfaqSoft** [linvi/tweetinvi#545]
Hello ,
in need to fill combo box of country PlaceId like "5a110d312052166f" that for San Francisco
Thank you

**Comment by Bader80** [comment]
If you are asking about woeid then try this
http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20geo.places%20where%20text=%27**Francisco**%27&format=xml

you can substitute  Francisco  with any other location

**Comment by linvi** [comment]
Yes the best solution is to use the YahooApis.
