### ISSUE TITLE
Error with V2.0.0

### ISSUE THREAD

**Issue by avknaidu** [linvi/tweetinvi#549]
Updated my app from v1.2.0.1 to V2.0.0 and submitted the app for certification and my app certification failed.

Below is what I received as an error from certification team.

![capture1](https://user-images.githubusercontent.com/6171200/27861659-57ee7abe-619f-11e7-918c-7b89386398ff.PNG)

Only workaround for now is by downloading the whole Code and build it myself in release mode ( Already done that. Waiting for Certification process to complete ). However I would love to get this fixed through nuget package.

Thanks

**Comment by linvi** [comment]
Thank you for reporting this. I have recreated an entire script for the build in .NETCore but apparently I have missed something.

This will be fixed in next release.

**Comment by linvi** [comment]
Updated the build process for version 2.1.

https://github.com/linvi/tweetinvi/commit/eedee30732611912cd9dd210f19a39878291b387

**Comment by avknaidu** [comment]
@linvi Thanks I will look for the Latest 2.1 nuget.
