### ISSUE TITLE
DownloadBinary function

### ISSUE THREAD

**Issue by pal5hahnair** [linvi/tweetinvi#550]
Hi ,

I tried DownloadBinary function.

However, when we convert byte to base64, Picture is not displayed properly.

``` c#
byte[] imageData = TwitterAccessor.DownloadBinary("Image URL");
string base64String = Convert.ToBase64String(imageData);
Image1.ImageUrl = "data:image/jpg;base64," + base64String;
```

Please advise. It seems there is some problem in byte array.

**Comment by linvi** [comment]
Are you attempting to get the image from a private message?

**Comment by pal5hahnair** [comment]
Hey

Yes,

I was attempting it.

But i got the solution.

Regards,
Palak

Sent from my iPhone

On Sep 25, 2017, at 10:12 PM, linvi <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you attempting to get the image from a private message?

**Comment by linvi** [comment]
Could you please share your solution here please? I am actually quite interested to know about it.

I was not able to retrieve the proper image binary from private messages and I did not have time to investigate.

If you found a solution it would be great so that I can add it to Tweetinvi :D

**Comment by linvi** [comment]
Is it possible for you to share the code you use to decode the image?

**Comment by pal5hahnair** [comment]
Yes sure, I will send it to you once i am in office.

Sent from my iPhone

On Sep 26, 2017, at 11:09 PM, linvi <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it possible for you to share the code you use to decode the image?

**Comment by linvi** [comment]
Ping ping ping ;)

**Comment by RickySan65** [comment]
Never reached the office from the looks of it ;)

**Comment by linvi** [comment]
@pal5hahnair This feature is very interesting, if you could help me figure it out without investing too much time it would be very much appreciated.

Cheers,
Linvi

**Comment by linvi** [comment]
@pal5hahnair Hello again. Tweetinvi 2.1 will be released as soon as I receive my code signing certificates.

I would be very please to add this feature. Please reply here if you receive this notification.

**Comment by linvi** [comment]
@pal5hahnair any update :( ?

**Comment by pal5hahnair** [comment]
Hey, I will reply you with the code tomorrow without fail.

**Comment by pal5hahnair** [comment]
Here you go!!

*Code :*

   var oauth_token = "oauth_token";
            var oauth_token_secret = "oauth_token_secret";
            var oauth_consumer_key = "oauth_consumer_key";
            var oauth_consumer_secret = "oauth_consumer_secret";



            var oauth_version = "1.0";
            var oauth_signature_method = "HMAC-SHA1";


            var oauth_nonce = Convert.ToBase64String(
                new
ASCIIEncoding().GetBytes(DateTime.Now.Ticks.ToString()));
            var timeSpan = DateTime.UtcNow
                - new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);
            var oauth_timestamp =
Convert.ToInt64(timeSpan.TotalSeconds).ToString();


            var status = "Updating status via REST API if this works";
            var resource_url = URL; // Use Image URL


            var baseFormat =
"oauth_consumer_key={0}&oauth_nonce={1}&oauth_signature_method={2}" +
"&oauth_timestamp={3}&oauth_token={4}&oauth_version={5}";


            var baseString = string.Format(baseFormat,
                                       oauth_consumer_key,
                                       oauth_nonce,
                                       oauth_signature_method,
                                       oauth_timestamp,
                                       oauth_token,
                                       oauth_version
                                       );

            baseString = string.Concat("GET&",
Uri.EscapeDataString(resource_url), "&", Uri.EscapeDataString(baseString));

            var compositeKey =
string.Concat(Uri.EscapeDataString(oauth_consumer_secret),
                                    "&",
Uri.EscapeDataString(oauth_token_secret));

            string oauth_signature;
            using (HMACSHA1 hasher = new
HMACSHA1(ASCIIEncoding.ASCII.GetBytes(compositeKey)))
            {
                oauth_signature = Convert.ToBase64String(

hasher.ComputeHash(ASCIIEncoding.ASCII.GetBytes(baseString)));
            }


            var headerFormat = "OAuth oauth_nonce=\"{0}\",
oauth_signature_method=\"{1}\", " +
                               "oauth_timestamp=\"{2}\",
oauth_consumer_key=\"{3}\", " +
                               "oauth_token=\"{4}\",
oauth_signature=\"{5}\", " +
                               "oauth_version=\"{6}\"";

            var authHeader = string.Format(headerFormat,
                                    Uri.EscapeDataString(oauth_nonce),

Uri.EscapeDataString(oauth_signature_method),
                                    Uri.EscapeDataString(oauth_timestamp),

Uri.EscapeDataString(oauth_consumer_key),
                                    Uri.EscapeDataString(oauth_token),
                                    Uri.EscapeDataString(oauth_signature),
                                    Uri.EscapeDataString(oauth_version)
                            );


            HttpWebRequest request =
(HttpWebRequest)WebRequest.Create(resource_url);
            request.Headers.Add("Authorization", authHeader);
            request.Method = "GET";
            request.ContentType =
"application/x-www-form-urlencoded;charset=UTF-8";
            ServicePointManager.ServerCertificateValidationCallback =
delegate { return true; };
            WebResponse response = request.GetResponse();


            var respStream = response.GetResponseStream();
            var contentLen = response.ContentLength;
            byte[] outData;
            using (var tempMemStream = new MemoryStream())
            {
                byte[] buffer = new byte[128];
                while (true)
                {
                    int read = respStream.Read(buffer, 0, buffer.Length);
                    if (read <= 0)
                    {
                        outData = tempMemStream.ToArray();
                        break;
                    }
                    tempMemStream.Write(buffer, 0, read);
                }
            }


            Bitmap bp = new Bitmap(new MemoryStream(outData));



            bp.Save(Server.MapPath("~/Images/" + ID + ".jpg"),
ImageFormat.Jpeg);

**Comment by linvi** [comment]
Thank you very much I will be looking into this in the coming days

**Comment by linvi** [comment]
Code with formatting.

``` c#
var oauth_token = "oauth_token";
var oauth_token_secret = "oauth_token_secret";
var oauth_consumer_key = "oauth_consumer_key";
var oauth_consumer_secret = "oauth_consumer_secret";
var oauth_version = "1.0";
var oauth_signature_method = "HMAC-SHA1";
var oauth_nonce = Convert.ToBase64String(new ASCIIEncoding().GetBytes(DateTime.Now.Ticks.ToString()));
var timeSpan = DateTime.UtcNow	- new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);
var oauth_timestamp = Convert.ToInt64(timeSpan.TotalSeconds).ToString();

var status = "Updating status via REST API if this works";
var resource_url = URL; // Use Image URL

var baseFormat =
"oauth_consumer_key={0}&oauth_nonce={1}&oauth_signature_method={2}" +
"&oauth_timestamp={3}&oauth_token={4}&oauth_version={5}";

var baseString = string.Format(baseFormat,
						   oauth_consumer_key,
						   oauth_nonce,
						   oauth_signature_method,
						   oauth_timestamp,
						   oauth_token,
						   oauth_version
						   );

baseString = string.Concat("GET&",
Uri.EscapeDataString(resource_url), "&", Uri.EscapeDataString(baseString));

var compositeKey = string.Concat(Uri.EscapeDataString(oauth_consumer_secret), "&", Uri.EscapeDataString(oauth_token_secret));

string oauth_signature;
using (HMACSHA1 hasher = new
HMACSHA1(ASCIIEncoding.ASCII.GetBytes(compositeKey)))
{
	oauth_signature = Convert.ToBase64String(hasher.ComputeHash(ASCIIEncoding.ASCII.GetBytes(baseString)));
}

var headerFormat = "OAuth oauth_nonce=\"{0}\",
oauth_signature_method=\"{1}\", " +
				   "oauth_timestamp=\"{2}\",
oauth_consumer_key=\"{3}\", " +
				   "oauth_token=\"{4}\",
oauth_signature=\"{5}\", " +
				   "oauth_version=\"{6}\"";

var authHeader = string.Format(headerFormat,
						Uri.EscapeDataString(oauth_nonce),

Uri.EscapeDataString(oauth_signature_method),
						Uri.EscapeDataString(oauth_timestamp),

Uri.EscapeDataString(oauth_consumer_key),
						Uri.EscapeDataString(oauth_token),
						Uri.EscapeDataString(oauth_signature),
						Uri.EscapeDataString(oauth_version)
				);

HttpWebRequest request =
(HttpWebRequest)WebRequest.Create(resource_url);
request.Headers.Add("Authorization", authHeader);
request.Method = "GET";
request.ContentType =
"application/x-www-form-urlencoded;charset=UTF-8";
ServicePointManager.ServerCertificateValidationCallback =
delegate { return true; };
WebResponse response = request.GetResponse();

var respStream = response.GetResponseStream();
var contentLen = response.ContentLength;
byte[] outData;
using (var tempMemStream = new MemoryStream())
{
	byte[] buffer = new byte[128];
	while (true)
	{
		int read = respStream.Read(buffer, 0, buffer.Length);
		if (read <= 0)
		{
			outData = tempMemStream.ToArray();
			break;
		}
		tempMemStream.Write(buffer, 0, read);
	}
}

Bitmap bp = new Bitmap(new MemoryStream(outData));

bp.Save(Server.MapPath("~/Images/" + ID + ".jpg"),
ImageFormat.Jpeg);
```

**Comment by linvi** [comment]
Example to save image from Direct Message : 

``` c#
var message = Message.GetLatestMessagesSent().ToArray()[0];

var media = message.Entities.Medias.First();
var imageUrl = media.MediaURLHttps;

var bin = TwitterAccessor.DownloadBinary(imageUrl);

Bitmap binbp = new Bitmap(new MemoryStream(bin));
binbp.Save("image.png");
```
