### ISSUE TITLE
Get lists/memberships implemented?

### ISSUE THREAD

**Issue by chriswill** [linvi/tweetinvi#552]
Is the Twitter api to get the lists that a user is a member of implemented?  https://dev.twitter.com/rest/reference/get/lists/memberships

Normally I search the repo for the api url to find it listed in resources, but lists/memberships.json doesn't appear to be used.

If it is implemented, can someone please point me to the location?  I checked ITwitterList already.

**Comment by linvi** [comment]
It does not look like it is. I will try to add this as soon as I can.

**Comment by linvi** [comment]
To consider for quick add to 2.1
