### ISSUE TITLE
MissingMethodException on User.GetAuthenticatedUser() (ONLY in IOS)

### ISSUE THREAD

**Issue by Xerosge** [linvi/tweetinvi#553]
Hi, im new in Xamarin and i don't really know if this is a problem of tweetinvi or im missing something

I create a project with tweetinvi for list tweets, I instal te tweetinvi nuget (after a lot of problem for instalation) and try with the example give in the wiki (User.GetAuthenticatedUser())

In android work fine, but in ios give me the error System.MissingMethodException (see image  attached)
![errortweetinvi](https://user-images.githubusercontent.com/29948827/28120948-e8f9f342-6719-11e7-98e1-b5ab59e312b4.png)

as say, i had a lot of problem for install the plugin, only can install after I put this in project.json:

`"frameworks": {
    ".NETPortable,Version=v4.5,Profile=Profile111": {
      "imports": [
        "net46
"
      ]
    }
  }`

i don't know if i doing something wrong

**Comment by linvi** [comment]
Should be fixed with 2.1
