### ISSUE TITLE
Filtered Stream AddFollow Returning Mentions

### ISSUE THREAD

**Issue by DEVKWS** [linvi/tweetinvi#554]
Following a user for a filtered stream is returning matched tweets from mentions. Not all mentions though. I was expecting only tweets from the user to be matched.

`var stream = Stream.CreateFilteredStream();`
`stream.AddFollow(14260960);`

`stream.MatchingTweetReceived += (sender, argus) =>`
`{`
`}`
`var task = stream.StartStreamMatchingAnyConditionAsync();`

**Comment by linvi** [comment]
I am not sure what are your expectations but please check the `MatchOn` property :

``` c#
var fs = Stream.CreateFilteredStream();
fs.MatchOn = MatchOn.UserMentionEntities | MatchOn.Follower;; // .... whatever you want 
```

**Comment by linvi** [comment]
Reference : https://github.com/linvi/tweetinvi/issues/530
