### ISSUE TITLE
Verify user handle

### ISSUE THREAD

**Issue by jaydeflix** [linvi/tweetinvi#555]
Is there a built in method to determine if a handle is a valid account before going through the authentication steps? I'm not seeing anything, I'm just looking for a boolean return letting me know that I should tell the user 'Hey, that account doesn't exist.'

ETA: And if there isn't, can I throw that in as a feature request?

**Comment by Ramkarthik** [comment]
Assuming you have provided valid consumer key, consumer secret, user access token and user access secret and called the Auth.SetUserCredentials method...

Make a call to User.GetUserFromScreenName method. If the account doesn't exist, it would return `null`.

For ex:
`var handleWhichExists = Tweetinvi.User.GetUserFromScreenName("Jack");`
 `var handleWhichDoesntExist = Tweetinvi.User.GetUserFromScreenName("RandomNonExistingHandle");`

In the above code, `handleWhichDoesntExist` object would be `null`. I think this is one way you could check if user account exists.

**Comment by linvi** [comment]
I think @Ramkarthik solution is the easiest solution that you could use.

Cheers,
Linvi
