### ISSUE TITLE
Error when trying to get Authenticated user on Raspberry Pi 3 with Mono

### ISSUE THREAD

**Issue by simoneddeland** [linvi/tweetinvi#556]
When calling User.GetAuthenticatedUser() I get the following error on my Raspberry Pi 3 running the latest version of Mono. When I run it on my Windows 10 PC the program runs just fine.

> Unhandled Exception:
> System.AggregateException: One or more errors occurred. ---> System.MissingField                                                                       Exception: Field 'System.Net.ExceptionHelper.WebPermissionUnrestricted' not foun                                                                       d.
>   at Tweetinvi.WebLogic.TwitterClientHandler.set_TwitterQuery (Tweetinvi.Models.                                                                       ITwitterQuery value) [0x00018] in <c5bb7bd6a84b4e0e96487ca4b7d0aa52>:0
>   at Tweetinvi.WebLogic.HttpClientWebHelper.GetHttpClient (Tweetinvi.Models.ITwi                                                                       tterQuery twitterQuery, Tweetinvi.Core.Web.ITwitterClientHandler twitterHandler)                                                                        [0x00011] in <c5bb7bd6a84b4e0e96487ca4b7d0aa52>:0
>   at Tweetinvi.WebLogic.HttpClientWebHelper+<GetHttpResponse>d__0.MoveNext () [0                                                                       x00010] in <c5bb7bd6a84b4e0e96487ca4b7d0aa52>:0
>    --- End of inner exception stack trace ---

I know this might now be an error on TweetInvi's part but I can't find any information on how to solve this anywhere else. Has anyone else successfully ran TweetInvi on the Raspberry Pi 3 using Mono?

**Comment by linvi** [comment]
I will try it out on my Raspberry Pi as soon as I can but I cannot provide any specific date.

Let me know if you have been able to fix it though.

Cheers,
Linvi

**Comment by linvi** [comment]
Hello there,

I did not try with Mono but the Examplinvi.UAP application is properly working on Raspberry Pi 3 with Windows IOT Core.

Please try the sample available in the source code of the repo.

Cheers,
Linvi

**Comment by simoneddeland** [comment]
@linvi I tried running the sample Examplelini.NETFramework on my Pi using mono and got the same error. Runs fine on my Windows 10 PC.

**Comment by linvi** [comment]
When you say mono do you mean using .NETCore libraries?

Tweetinvi is no longer using PCL.

**Comment by simoneddeland** [comment]
No, I have not installed .NET Core, I've installed the Mono runtime http://www.mono-project.com/download/#download-lin-raspbian

**Comment by linvi** [comment]
I will try to check this out at some point. But Tweetinvi is no longer using PCL which is what Mono supports.

At the current time if you want to use Tweetinvi on Raspberry Pi please use Windows 10 IOT as explained here : 

https://developer.microsoft.com/en-us/windows/iot/getstarted

I will get back to you later on regarding mono though.

**Comment by simoneddeland** [comment]
@linvi I installed .NET Core 2.0 on my Pi (still using Raspbian) a few days ago and ported my console app using Tweetinvi to .NET Core, it runs fine now. I don't think that it works with mono yet though.

**Comment by linvi** [comment]
Yes Mono is no longer supported as Tweetinvi is now based on .NET Core.

I will remove this from the compatibility list.
