### ISSUE TITLE
I can't for some reason get DM to retrieve any message.  

### ISSUE THREAD

**Issue by jjziets** [linvi/tweetinvi#557]
I can send Private Messages to followers but for some reason, I can not get any Private Messages read. 
I have a timer that runs every 1s and checks if there are messages. Will reduce this in the future. 
In the main() I have authenticatedUser the account and I can send PM on twitter. But when that follower replys I dont get the PM.

But MSG is always Null. 

       private static void OnTwitterTimedEvent(Object source, System.Timers.ElapsedEventArgs e)
        {
            try
            {
                IEnumerable<IMessage> MSG  = controller.GetLatestMessagesReceived(); ; // Message.GetLatestMessagesReceived(100);
                
                if (MSG != null)
                {
                    Console.WriteLine(MSG.ElementAt(0).SenderScreenName + MSG.ElementAt(0).Text);

                    if ((MSG.ElementAt(0).SenderId == ###MYID### ) & (MSG.ElementAt(0).Text == "?"))
                    {
                        Message.PublishMessage(tweet, ###MYID###);
                        Console.ForegroundColor = ConsoleColor.DarkGreen;
                        Console.WriteLine(MSG.ElementAt(0).SenderScreenName + MSG.ElementAt(0).Text);
                        Console.ResetColor();
                        Message.DestroyMessage(MSG.ElementAt(0));
                    }
                }
            } catch
            {
                }

        }

**Comment by jjziets** [comment]
i have also tried:

       private static void OnTwitterTimedEvent(Object source, System.Timers.ElapsedEventArgs e)
        {

            try
            {
                var latestMessagesSent = Message.GetLatestMessagesSent();
                var latestMessagesSentParameter = new MessagesSentParameters();
                latestMessagesSentParameter.PageNumber = 239823;
                var latestMessagesSentFromParameter = Message.GetLatestMessagesSent(latestMessagesSentParameter);

                if (latestMessagesSentFromParameter != null)
                {
                    Console.WriteLine("Messages Send : ");
                    foreach (var mms in latestMessagesSentFromParameter)
                    {
                        Console.WriteLine("- '{0}'", mms.Text);
                    }

                }
            } catch
            {
            }

        }


I also tried using

IAuthenticatedUser authenticatedUser = User.GetAuthenticatedUser(); authenticatedUser.GetLatestMessagesReceived();

**Comment by jjziets** [comment]
The app does have read, write and DM permissions

**Comment by RickySan65** [comment]
do you get exceptions? if so try it with 
catch (exception ex)
{
console.writeline(ex.message);
}

and see what the message is

**Comment by linvi** [comment]
@jjziets Have you been able to fix this problem?

If not have you tried to regenerate your credentials?

Cheers,
Linvi
