### ISSUE TITLE
var authenticationContext = AuthFlow.InitAuthentication(appCredentials) error

### ISSUE THREAD

**Issue by jaydeflix** [linvi/tweetinvi#558]
When my code hits
`            var appCredentials = new TwitterCredentials(ConsumerKey, ConsumerSecret);
            var authenticationContext = AuthFlow.InitAuthentication(appCredentials);`

I'm getting an exception:

> System.FormatException occurred
  HResult=0x80131537
  Message=String was not recognized as a valid Boolean.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Boolean.Parse(String value)
   at Tweetinvi.Credentials.WebTokenFactory.InitAuthenticationProcess(IConsumerCredentials appCredentials, String callbackURL, String credsIdentifier)
   at Tweetinvi.AuthFlow.InitAuthentication(IConsumerCredentials appCredentials, String callbackURL)
   at MSDevListManager.MainPage.<twitterCheck>d__6.MoveNext() in C:\Users\jayde\Source\Repos\MSDevListManager\MSDevListManager\MainPage.xaml.cs:line 82 

I'd really just love a tip. I'm not even sure where precisely to start.

**Comment by ChrizC** [comment]
Hi @jaydeflix,

This appears to be because of a `bool.Parse(...)` call as opposed to a `bool.TryParse(...)` inside of Tweetinvi. It seems to indicate the authentication failed.

@linvi if you're taking contributions, happy to pick this up.

**Comment by jaydeflix** [comment]
@ChrizC Yay and Boo and Yay. Or some combination. Hurm. That would suggest my ConsumerKey/Secret isn't working right, yeah? I'm just trying to follow https://github.com/linvi/tweetinvi/wiki/Authentication.

**Comment by jaydeflix** [comment]
*fires up Fiddler to figure out what's being sent*
*starts app*
no error.

..... Rargh.

**Comment by linvi** [comment]
Thanks for reporting the bug, I will take a look as soon as possible.

Cheers,
Linvi

**Comment by linvi** [comment]
Hello there,

The fix will be available in 2.1. I have not been able to reproduce it myself but the fix is there anyway ;)

Thank you for the feedback!
Linvi
