### ISSUE TITLE
Issure with User.GetUserFromId when using a dataGridView Control

### ISSUE THREAD

**Issue by edkitch** [linvi/tweetinvi#559]
I am trying to pull a user but their usier ID using the following code:

`if (t == "@"){var user = User.GetUserFromId(term.ToString().Substring(1));}`

When I run this I get the error:

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'DataGridViewTextBoxColumn' does not contain a definition for 'GetUserFromId' and no extension method 'GetUserFromId' accepting a first argument of type 'DataGridViewTextBoxColumn' could be found (are you missing a using directive or an assembly reference?)

Any ideas?

**Comment by edkitch** [comment]
I have realised my mistake and fixed it using:

`var user = Tweetinvi.User.GetUserFromScreenName(term.ToString());`

**Comment by linvi** [comment]
CLosing the issue :)
