### ISSUE TITLE
Universal Windows 10 apps always returning null and not throwing exceptions.

### ISSUE THREAD

**Issue by patrikohlsson** [linvi/tweetinvi#56]
When running/debugging a Universal Windows 10 app built in VS 2015 Express with Tweetinvi 0.9.9.7 (installed via NuGet) all functions for getting tweets, users or search results return null.

A simple example is as follows:
```c#
Auth.SetUserCredentials("", "", "", "");

ExceptionHandler.SwallowWebExceptions = false;

var user = User.GetLoggedUser();
if(user==null)
{
    Debug.WriteLine("Exception:");
    var exception = ExceptionHandler.GetLastException();
    Debug.WriteLine(ex);
}
```

`user` variable is null but no exception is thrown so `var exception` is always null as well. No difference when using a try-catch block.

The tested credentials were valid and the exact same code works as expected in VS 2013 Express.
The network related flags in the manifest are set too. Weirdly, you can still post tweets and access streams.

Same issue when using 0.9.10.

**Comment by patrikohlsson** [comment]
Problem persists in VS 2015 Community edition.

**Comment by patrikohlsson** [comment]
Disabling the firewall service (not good as VS needs it to register release binaries), you get this exception:

```
Exception thrown: 'System.AggregateException' in Tweetinvi.WebLogic.dll
System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Windows.Web.Http.Filters.HttpBaseProtocolFilter.SendRequestAsync(HttpRequestMessage request)
   at System.Net.Http.HttpHandlerToFilter.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.<SendAsync>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Tweetinvi.WebLogic.HttpClientWebHelper.<GetHttpResponse>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Tweetinvi.WebLogic.WebRequestExecutor.<>c__DisplayClass4_0.<ExecuteQuery>b__0()
   at Tweetinvi.WebLogic.WebRequestExecutor.ExecuteTwitterQuerySafely[T](ITwitterQuery twitterQuery, Func`1 action)
   at Tweetinvi.WebLogic.TwitterRequestHandler.ExecuteQuery(String queryURL, HttpMethod httpMethod, TwitterClientHandler handler, ITwitterCredentials credentials)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteGETQuery[T](String query, JsonConverter[] converters)
   at Tweetinvi.Factories.User.UserFactory.GetUserFromScreenName(String userName)
   at Twerker.MainPage.<>c.<.ctor>b__0_0()
   at Tweetinvi.Credentials.CredentialsAccessor.ExecuteOperationWithCredentials(ITwitterCredentials credentials, Action operation)
   at Twerker.MainPage..ctor()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Windows.Web.Http.Filters.HttpBaseProtocolFilter.SendRequestAsync(HttpRequestMessage request)
   at System.Net.Http.HttpHandlerToFilter.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.<SendAsync>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Tweetinvi.WebLogic.HttpClientWebHelper.<GetHttpResponse>d__2.MoveNext()<---
```

The credentials are valid so this error might just be related to the absence of a firewall.

**Comment by linvi** [comment]
I will take a look into this issue as soon as I can. 
I will try to make it happen tonight.

**Comment by linvi** [comment]
Also please provide the `InnerException` details of the `AggregateException` you mentioned in your last message.

**Comment by MrAndrewAu** [comment]
I can confirm the same problem is happening for me. Windows 10 Universal App, using VS 2015.

`Auth.SetUserCredentials(consumerKey, consumerSecret, userAccessToken, userAccessSecret);`
`var tweets = Search.SearchTweets(searchParameter).ToList();`
`ExceptionHandler.SwallowWebExceptions = false;`
`var latestException = ExceptionHandler.GetLastException();`

latestException.Source:
'Tweetinvi.Credentials'

latestException.Message:
'https://api.twitter.com/1.1/statuses/show.json?id=651905838064336896&include_my_retweet=true web request failed.'

latestException.StackTrace:
'   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteGETQuery[T](String query, JsonConverter[] converters)
   at Tweetinvi.Factories.Tweet.TweetFactoryQueryExecutor.GetTweetDTO(Int64 tweetId)
   at Tweetinvi.Factories.Tweet.TweetFactory.GetTweet(Int64 tweetId)
   at Tweetinvi.Tweet.GetTweet(Int64 tweetId)
   at SocialMi2.HelperFunctions.GetTweetsFromIds(String query)'

latestException.TwitterDescription:
`Not Found - The URI requested is invalid or the resource requested, such as a user, does not exists. Also returned when the requested format is not supported by the requested method.`

I was literally pulling my hair out for the past 12 hours trying to figure this out, and then I saw this post. It might be worth mentioning that the same code works flawlessly using TweetInv 0.9.8.1 in a Windows 8 Store App, the only difference is that obviously the authentication part is 'TwitterCredentials.SetCredentials(userAccessToken, userAccessSecret, consumerKey, consumerSecret);'

**Comment by linvi** [comment]
Thanks for the comment, just to check have you tried the Examplinvi.UniversalApp on your machine?
You can find it under the [branch 0.9.10.0](https://github.com/linvi/tweetinvi/tree/Tweetinvi-0.9.10.0).

**Comment by MrAndrewAu** [comment]
Just downloaded Examplinvi.UniversalApp, and entered the four auth keys in MainPage.xaml.cs, and started up the Examplinvi.UniversalApp.

The textblock says "Please enter your credentials in the MainPage.xaml.cs file"

**Comment by linvi** [comment]
I don't have a Windows 10 available, I will investigate tonight with one. In the meantime could you please tell me which condition of the MainPage.xaml.cs is not passing?

* `Auth.Credentials == null`
* `string.IsNullOrEmpty(Auth.Credentials.ConsumerKey)`
* `string.IsNullOrEmpty(Auth.Credentials.ConsumerSecret)`
* `string.IsNullOrEmpty(Auth.Credentials.AccessToken)`
* `string.IsNullOrEmpty(Auth.Credentials.AccessTokenSecret)`
* `Auth.Credentials.AccessToken == "ACCESS_TOKEN"`

**Comment by MrAndrewAu** [comment]
Hi Linvi, thanks for your hard work on this. But please ignore my previous post. I forgot to click the "Deploy" button after setting the credentials, so the app wasn't seeing the updated auth tokens. So the RunSampleStream() function in Examplinvi.UniversalApp actually works, but after I do this instead:

            `//RunSampleStream();`
            `var searchParameter = Search.CreateTweetSearchParameter("#funny");`
            `searchParameter.SearchType = SearchResultType.Recent;`
            `searchParameter.MaximumNumberOfResults = 30;`
            `var tweets = Search.SearchTweets(searchParameter).ToList();`

Then we run into the same problem as the original post, where tweets is null.

**Comment by patrikohlsson** [comment]
I ran the Examplinvi.UniversalApp on 0.9.10 from source set a breakpoint on the `User.GetLoggedUser()` call. When stepping in i found that `jsonResponse` in
```c#
public T ExecuteGETQuery<T>(string query, JsonConverter[] converters = null) where T : class
{
    string jsonResponse = ExecuteQuery(query, HttpMethod.GET);
    return _jsonObjectConverter.DeserializeObject<T>(jsonResponse, converters);
}
```
... looks like gibberish. I stepped into the DeserializeObject-function and it fails to recognize the json formatting and returns a default value:
```c#
if (!StringExtension.IsMatchingJsonFormat(json))
{
    return default(T);
}
```

That is all I got from it, maybe it helps.

**Comment by linvi** [comment]
Yes, I know I have identified the same thing, for some unknown reason, the data receive from the WebRequest stream in a Universal App is not the same as the data received from any other type of project. This is really strange.

**Comment by patrikohlsson** [comment]
That is strange indeed. The request is exactly the same right?

**Comment by linvi** [comment]
Yes, I am using the **exact** same code in both universal and console app and they both received a stream. The console receive a well formatted json while the universal app receive an invalid format of string.

**Comment by linvi** [comment]
Plus I am certain that this was working with version 1.0 of Universal App, unfortunately, I don't think I can rollback to verify this.

**Comment by linvi** [comment]
I have not found a solution for now. I will continue investigating tomorrow.

**Comment by patrikohlsson** [comment]
I think I've found a solution or at least a workaround. `HttpResponseMessage.Version` was "1.1" on a working project and "2.0" on a non-working project. So I changed the `SendAsync` method:
```c#
protected Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken, string authorizationHeader)
{
    request.Headers.Add("User-Agent", "Tweetinvi/0.9.10.0");
    request.Headers.ExpectContinue = false;
    request.Headers.CacheControl = new CacheControlHeaderValue { NoCache = true };
    request.Headers.Add("Authorization", authorizationHeader);
    request.Version = new Version("1.1"); // <-- Explicitly request version 1.1

    return base.SendAsync(request, cancellationToken);
}
```
And it works! 
Linvi, do you know if this is a good solution or if it ends up destroying something else?

**Comment by patrikohlsson** [comment]
Oh yeah, I forgot to mention it is in the TwitterClientHandler.cs file of Tweetinvi.WebLogic.

**Comment by linvi** [comment]
Thank you so much for looking at this issue. To be honest I was not going to look at the HTTP version right away for sure. I though some headers were incorrectly passed through.

**Comment by linvi** [comment]
I have tested it and it works, if you want the credit for this you can create a pull request for branch 0.9.10.0 and I will gladly add your change to the branch.

Otherwise I will add it myself probably tonight and release a new version of Tweetinvi 0.9.9.8.

Thanks again.

**Comment by MrAndrewAu** [comment]
This fixes the issue in my own app, and I do not notice any other problem after a quick test. Thank you guys, really appreciate it.

**Comment by patrikohlsson** [comment]
No credit needed Linvi, it was a collective effort. Thank you for a great library.

**Comment by linvi** [comment]
Version 0.9.9.8 has been pushed to nuget. 

Enjoy Tweetinvi with you Universal App!
