### ISSUE TITLE
Problem with 2.0 install and System.Net.Http, Version=4.1.1.0,

### ISSUE THREAD

**Issue by smartnotify** [linvi/tweetinvi#561]
Hello,
I'm hoping someone has run into the same issue and has some feedback/ideas as I am running out of ideas.
We're on .net 4.6.1 
Decided to update to version 2.0 and when doing the NUGet Install, this is the prompt we got.
![tweetinvi_1](https://user-images.githubusercontent.com/10913974/29161119-46aca6a4-7db5-11e7-898a-0e0bd6828bcf.png)

But then when calling the basic AuthFlow method, we keep getting:
Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

We've tried a bunch of things, including downgrading to 4.1.1.0 for System.Net.Http --> But when we do this it prompts us to downgrade the Tweetinvi version.

or adding the always fun:
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.1" newVersion="4.1.1.1" />
      </dependentAssembly>
In the  config...to no success what so ever!

We'll keep on trying but if you have some suggestions on what to look into, it'd be most welcome!

Thank you!

**Comment by chadwackerman** [comment]
Add a reference to the latest version of Newtonsoft.Json (10.0.3 at the time of this writing) first and it cleared everything up for me.

@karelz has been promising a writeup on this issue for almost six months. Send him my regards.

https://github.com/dotnet/corefx/issues/17522

**Comment by smartnotify** [comment]
You are spot on, it has to be the source of the problem.  I already had the latest Newtonsoft so now I am down to tracking dll by dll where the root of the problem may be.
Painful...

**Comment by jeromechrist** [comment]
@smartnotify try using [Paket ](https://fsprojects.github.io/Paket/getting-started.html), i had the same kind of issue with System.Runtime.Serialization.Primitives, Paket showed it was a the Azure Functions package that had a specific version of Newtonsoft 9.0.1

**Comment by smartnotify** [comment]
Thanks @jeromechrist . Paket looks really useful. Trying to resolve why Microsoft.Bcl.Build  is creating so many problems but at least I'm making some progress in getting closer to the problem child!
Thank you.

**Comment by TelmoNeves** [comment]
Did you fix the issue? I have the same framework version and I'm getting the same error.

**Comment by smartnotify** [comment]
Unfortunately not yet.  We are hoping an older DLL is the culprit but it is one that cannot be easily replaced just yet.
We've put that on our todo list for the coming weeks.  Hopefully it does it.  Will post an update if we make some progress but it's been a really vexing issue so far that has only been triggered in the tweetinvi case so far.

**Comment by TelmoNeves** [comment]
Well, I did fix the issue yesterday :)

What I did was to look for older versions of System.Net.Http.dll and try 1 by 1. Eventually I found 1 that worked (I don't remember which version it was, sorry). But then, the same error popped out but this time for another dll, System.Runtime.Serialization.Primitives.dll and I did the same thing. Now everything is working properly.

**Comment by linvi** [comment]
Hello,

Did you look at https://github.com/linvi/tweetinvi/releases/tag/2.0 section **ASP.NET (.NET Framework) considerations**?

Cheers,
Linvi

**Comment by linvi** [comment]
Closing as previous comment will probably solve it.

Feel free to reopen if needed.

**Comment by PRMan99** [comment]
Please reopen.  I have all kinds of problems with System.Runtime, System.IO, System.Net.Http version conflicts on 4.6.1 and 4.7.1.  This library is unusable in its current form.

**Comment by linvi** [comment]
Could you please describe your problem and even better create a code repo that reproduces these problems?

Are you using Tweetinvi 4.0?

**Comment by hozail** [comment]
I've resolved this issue System.NetHttp Version...by reinstalling these versions:
TweetinviAPI=0.9.12.2
System.Net.Http=2.0.20505
