### ISSUE TITLE
Receive all tweets in English. Possible?

### ISSUE THREAD

**Issue by maxima120** [linvi/tweetinvi#562]
Hi I am doing a small research project. Is it possible to **stream** all the tweets in the system (with English filter).. Not just mine and my followees but all.. Is it possible?

Alternatively - receive **all** users from a geolocation?

Are there daily limits for streaming?

**Comment by ChrizC** [comment]
This seems more suited to ask Twitter directly.

However, reading the docs [here](https://dev.twitter.com/streaming/overview/request-parameters), I've found that you can supply a `language` parameter to your stream request on the public streaming API. You can also provide a `locations` parameter - but this only matches Tweets that have geolocation on the actual Tweet.

You don't appear to be able to get a list of users for a certain geolocation.

There's no daily limits for receiving data from streaming, but Twitter may throttle you if you disconnect and reconnect the stream too often in a short period of time.

This issue should be closed as it's not relevant to the project.

**Comment by maxima120** [comment]
thanks. I used location and it worked. don't need users. cheers

**Comment by linvi** [comment]
You can add a language filter.

Please check this out here in the documentation : https://github.com/linvi/tweetinvi/wiki/Streams#stream-parameters

Cheers,
Linvi
