### ISSUE TITLE
NETFramework,Version=v4.5.2

### ISSUE THREAD

**Issue by andrehortab2u** [linvi/tweetinvi#563]
Package Manager Console Host Version 3.4.4.1321

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package TweetinviAPI
Attempting to gather dependency information for package 'TweetinviAPI.2.0.0' with respect to project 'SocialBot', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'TweetinviAPI.2.0.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'TweetinviAPI.2.0.0'
Resolved actions to install package 'TweetinviAPI.2.0.0'
  GET https://api.nuget.org/v3-flatcontainer/autofac/4.6.0/autofac.4.6.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/autofac/4.6.0/autofac.4.6.0.nupkg 511ms
Installing Autofac 4.6.0.
Adding package 'Autofac.4.6.0' to folder 'c:\users\andre\onedrive\documents\visual studio 2015\Projects\SocialBot\packages'
Added package 'Autofac.4.6.0' to folder 'c:\users\andre\onedrive\documents\visual studio 2015\Projects\SocialBot\packages'
Added package 'Autofac.4.6.0' to 'packages.config'
Successfully installed 'Autofac 4.6.0' to SocialBot
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/10.0.2/newtonsoft.json.10.0.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/10.0.2/newtonsoft.json.10.0.2.nupkg 499ms
Installing Newtonsoft.Json 10.0.2.
Adding package 'Newtonsoft.Json.10.0.2' to folder 'c:\users\andre\onedrive\documents\visual studio 2015\Projects\SocialBot\packages'
Added package 'Newtonsoft.Json.10.0.2' to folder 'c:\users\andre\onedrive\documents\visual studio 2015\Projects\SocialBot\packages'
Added package 'Newtonsoft.Json.10.0.2' to 'packages.config'
Executing script file 'c:\users\andre\onedrive\documents\visual studio 2015\Projects\SocialBot\packages\Newtonsoft.Json.10.0.2\tools\install.ps1'
Successfully installed 'Newtonsoft.Json 10.0.2' to SocialBot
  GET https://api.nuget.org/v3-flatcontainer/nito.asyncex.context/1.1.0/nito.asyncex.context.1.1.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/nito.asyncex.context/1.1.0/nito.asyncex.context.1.1.0.nupkg 499ms
Installing Nito.AsyncEx.Context 1.1.0.
Install failed. Rolling back...
Package 'Nito.AsyncEx.Context.1.1.0' does not exist in project 'SocialBot'
Removed package 'Newtonsoft.Json.10.0.2' from 'packages.config'
Removed package 'Autofac.4.6.0' from 'packages.config'
Package 'Nito.AsyncEx.Context.1.1.0' does not exist in folder 'c:\users\andre\onedrive\documents\visual studio 2015\Projects\SocialBot\packages'
Removing package 'Newtonsoft.Json.10.0.2' from folder 'c:\users\andre\onedrive\documents\visual studio 2015\Projects\SocialBot\packages'
Removed package 'Newtonsoft.Json.10.0.2' from folder 'c:\users\andre\onedrive\documents\visual studio 2015\Projects\SocialBot\packages'
Removing package 'Autofac.4.6.0' from folder 'c:\users\andre\onedrive\documents\visual studio 2015\Projects\SocialBot\packages'
Removed package 'Autofac.4.6.0' from folder 'c:\users\andre\onedrive\documents\visual studio 2015\Projects\SocialBot\packages'
Install-Package : Could not install package 'Nito.AsyncEx.Context 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', 
but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package TweetinviAPI
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM>

**Comment by Abhith** [comment]
please read [this](https://github.com/linvi/tweetinvi/releases)
Tweetinvi 2.0 requires .NETFramework 4.6.

**Comment by linvi** [comment]
Hello,

As written in the documentation, 4.5.2 is no longer supported. The reason is that some project lacks default `SynchronizationContext` which can result in problems with using Tweetinvi and multithreading.

Therefore I decided to use AsyncEx which wraps function inside its custom SynchronizationContext.
The problem is that AsyncEx is only available for .NETStandard 1.3 and therefore I cannot provide the new version of Tweetinvi for frameworks lower than 4.6.

Cheers,
Linvi
