### ISSUE TITLE
ITweet.Text and Suffix returns wrong value when the DisplayTextRange is { 0, 0 }

### ISSUE THREAD

**Issue by pgrho** [linvi/tweetinvi#564]
The ITweet.Text should be "", but Text returns "h" and Suffix is "ttps://...".

https://github.com/linvi/tweetinvi/blob/c6d02c900c0d2a863e96dda559dc8e28a36a439f/Tweetinvi.Logic/Tweet.cs#L121

**Comment by linvi** [comment]
Hello,

Could you share the id of the tweet that is causing this bug please?

Cheers,
Linvi

**Comment by pgrho** [comment]
Try this https://twitter.com/pgrho/status/912490987422748673

**Comment by linvi** [comment]
Thank you for the feedback. This is now fixed :)
