### ISSUE TITLE
TweetInvi Stream API not working

### ISSUE THREAD

**Issue by chethi666** [linvi/tweetinvi#565]
I just tried to do Public and Filtered Stream in TweetInvi today morning which was already working on yesterday.

Streaming started successfully but it didn't return any data.
Using TweetInvi version 2.0 in nuget C#
Please let me know if there is any update on this

**Comment by linvi** [comment]
Hello,

I know this has been a month now but it would be great if you could share some feedback.
Have you been able to fix this problem?

Sorry for the delay, as always I try to find the time when I can.

Cheers,
Linvi

**Comment by chethi666** [comment]
Sorry for the late reply. Streaming works I think on that day it was an issue with Twitter.
All worked fine for me.
Thanks!

**Comment by david-ae** [comment]
Streaming starts and does not return any data. No errors. Wondering whats wrong?

**Comment by istavrit** [comment]
its a Problem???
Streaming does not start at all and does not return any data. No errors. Wondering whats wrong? @linvi

**Comment by linvi** [comment]
@david-ae @istavrit are you still experiencing the problem?
