### ISSUE TITLE
Account Activity API (webhook) / new DM REST endpoints

### ISSUE THREAD

**Issue by geoseb** [linvi/tweetinvi#566]
Hi,

I would like to know if, in the near future, you will integrate the new Account Activity API (webhook) and the new DM REST endpoints ?

Thanks !
Best Regards

**Comment by linvi** [comment]
I will analyze if this can be added to version 2.1 and will let you know.

Cheers,
Linvi

**Comment by linvi** [comment]
Hello @geoseb  @eaba ,

Is it possible for one of you to share your credentials to access the Account Activity API for me to run some tests.

I have made a request to access the api but this might take some time before it is granted.
If you cannot, I think this feature will be part of 2.2.

Cheers,
Linvi

**Comment by geoseb** [comment]
Hello @linvi,
Sadly i can't share the access. They are not mine...

**Comment by linvi** [comment]
Still no account on my side.

Moving for later versions.

**Comment by geoseb** [comment]
Be more simple for you to integrate it when Twitter release the stable version ^^

**Comment by xjose97x** [comment]
really interested on this feature

**Comment by linvi** [comment]
Tweetinvi 3.0 is now live. 

Next version will be only on this new Activity Api.
The one after will be about the Direct Messages.

Cheers,
Linvi

**Comment by linvi** [comment]
Few notes to the global vision of the Webhooks implementation.

* `TweetinviWebhook` : each instance represent a single point where any developer can add, remove, start and stop `WebhookReceivers`. 

* `WebhookReceiver`: will be responsible to retrieve a specific type of event (url). It will be able to register multiple `WebhookHandlers`. The developer will be able to start/stop this event receiver. If the user decides to stop the event receiver, Tweetinvi will send a request to Twitter to unregister the url. The `WebhookReceiver` will have a unique id that will allow Tweetinvi to trace down the request to the proper receiver in a scenario where a user wants to have pre/post logic shared for each of the `WebhookHandlers`. It will also help with logging and deregistering the handlers.

* `WebhookHandler`: will represent a single "event" handler of the `WebhookReceiver`. It can be started/stopped.

* `AccountActivityWebhook`: It will be an extension of the `TweetinviWebhook`. It will be instantiated with the credentials of the user we want listen to and will provide additional features to more easily handle the events related with a Twitter user.
