### ISSUE TITLE
how to count comments of any tweet through tweetid

### ISSUE THREAD

**Issue by alisawani** [linvi/tweetinvi#567]

**Comment by alisawani** [comment]
@linvi pleaase solve my issue i need your help

**Comment by linvi** [comment]
This is not possible. This question has been asked various times and I personally asked the Twitter Developer Team to do something about it over the previous years.

This feature is only available in the private Twitter API which you won't have access to.

The only solution you have is to record the tweets in reply to a user via a Stream endpoint and store it in your own database.

Cheers,
Linvi

**Comment by alisawani** [comment]
thanks Linvi Sir    On Monday, 25 September 2017, 10:44:20 pm GMT+5, linvi <notifications@github.com> wrote:  
 
 
This is not possible. This question has been asked various times and I personally asked the Twitter Developer Team to do something about it over the previous years.

This feature is only available in the private Twitter API which you won't have access to.

The only solution you have is to record the tweets in reply to a user via a Stream endpoint and store it in your own database.

Cheers,
Linvi
