### ISSUE TITLE
Get tweet picture

### ISSUE THREAD

**Issue by romin4you** [linvi/tweetinvi#568]
Hello,

How do you access the tweet pictures? i can access the tweet content but it doesn't include the picture tweeted with it...

Thanks in advance!

**Comment by Bader80** [comment]
you can loop through the tweet.Media collection

foreach (IMediaEntity media in tweet.Media)

then check for pictures

if (media.MediaType == "photo" )

**Comment by linvi** [comment]
Hello,

@Bader80 is right, this is the correct approach for this problem.

Cheers,
Linvi
