### ISSUE TITLE
Limit the number of tweets received from stream?

### ISSUE THREAD

**Issue by PeiErnLim95** [linvi/tweetinvi#569]
Dear Author, 

I have using the tweetinvi for my project and I would like to stream the tweets from Twitter. 
However, I do hope that I can limit the number of tweets received from each track filtered. 
May I know is there any solution to this? For example I want to limit the tweets received from Keyword Filtered "Love", and I need only 10 tweets out of them. 
I couldn't find any method in the documentation to use in this situation. 
Thank you.

**Comment by linvi** [comment]
I know you have closed the issue but for further reference you just need to have a counter and when it reaches 10, you can use `stream.StopStream()`.

Cheers,
Linvi
