### ISSUE TITLE
Get my followers tweets from thier user id 

### ISSUE THREAD

**Issue by muneebrana23** [linvi/tweetinvi#570]
Hello @linvi , i am trying to get the tweets from my followers using their id.
i am using this command .
 `var tweets = Timeline.GetUserTimeline(862720321); `
and to print them on console i am using foreach loop
` foreach ( var twt in tweets)
            {
                Console.WriteLine(twt);
             }`
but it returned the NullRefrenceException. so no tweet stored in var tweets. 
what should i do?

**Comment by Ramkarthik** [comment]
The user whose tweets you are trying to retrieve has their account protected and hence you are not getting any tweets in return.

You could add a condition to check if the user's account is protected before going to the for loop:
`if(!Tweetinvi.User.GetUserFromId(862720321).Protected)`

**Comment by linvi** [comment]
Thanks @Ramkarthik for looking into this.

Closing.
