### ISSUE TITLE
NuGet package wrong content

### ISSUE THREAD

**Issue by PapaMufflon** [linvi/tweetinvi#572]
I'm sure, I'm doing something wrong here. I set up a new dotnet core project with `dotnet new console` and then I wanted to add the tweetinvi NuGet package to it with `dotnet add package TweetinviAPI`. `dotnet restore` works, but when I try to compile it, it cannot find the namespace `Tweetinvi`.

So I looked into the downloaded package and saw that it looks different than the one which I manually downloaded from `nuget.org`. Instead of a `lib` folder, there is a normal project structure with sln file and so on.

Installing other NuGet packages from the command line works for me. Is there a trick with tweetinvi?

**Comment by PapaMufflon** [comment]
Ok, one thing I noticed is that version 8.0.0.2 gets installed!?. When I explicitly state `dotnet add package TweetinviAPI --version 2.0.0`, the correct version gets installed.

But compilation still isn't possible, same error: `The type or namespace name 'TwitterCredentials' could not be found`.

Using dotnet core version 1.1.0 with a netcoreapp1.1 target framework.

**Comment by linvi** [comment]
Hello please do the following:

> dotnet new console
> dotnet add package TweetinviAPI --version 2.0.0
> donet restore

Create your code:

``` c#
Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");
var authenticatedUser = User.GetAuthenticatedUser();
Console.WriteLine(authenticatedUser);
```

> dotnet run

**Comment by PapaMufflon** [comment]
Just to follow up - had no time to have a look into this. It compiles now \o/
Thank you!
