### ISSUE TITLE
Tweet.PublishTweetInReplyTo() Method does't work!

### ISSUE THREAD

**Issue by Sasinda98** [linvi/tweetinvi#573]
Here's the version of the method that I used -: PublishTweetInReplyTo(string text, long tweetToReplyToId);

As you can see I can pass in a string as the reply and can pass in a long for the twitter ID, But when I do so reply just gets posted on to my twitter timeline without the @PersonI'mReplyingTo . So basically PublishTweetInReplyTo tweets in to the timeline, doesn't actually reply...

Sorry if it's me who screwed up, I'm just starting out on C# and wanted to try this out and came across this issue, thought I should let you guys know.

-Thanks!

**Comment by Ramkarthik** [comment]
As mentioned in the below link: In September 2015, Twitter changed the requirements for publishing a tweet in reply to another one. You now have to add "@screenName" (screen name of the author of the tweet you are replying to) to the text of the tweet you want to publish.

[https://github.com/linvi/tweetinvi/wiki/Tweets#publish-in-reply-to](https://github.com/linvi/tweetinvi/wiki/Tweets#publish-in-reply-to)

**Comment by linvi** [comment]
@Ramkarthik is correct.

**Comment by Sasinda98** [comment]
Thanks guys!!
