### ISSUE TITLE
TweetinviEvents.QueryAfterExecute - Determining cause of a failure

### ISSUE THREAD

**Issue by markiemooster** [linvi/tweetinvi#574]
**TweetInvi 2.0.0.0**

If an appropriate event handler is setup, and a query to Twitter is made, then the event handler fires afterwards and passes a QueryAfterExectureEvents args object.

Is there a way to determine what JSON data was returned, or the reason for a failure in the case where args.success == false?

**Comment by linvi** [comment]
Not for now but I will see if I have time to add this to the next release.

**Comment by linvi** [comment]
To quickly improve my answer. 

Please check the `eventArgs.HttpContent` for the content returned by the query.
This can be json or simple text based on the request and the error.

Regarding the error, I will check this out.

**Comment by markiemooster** [comment]
Regarding eventArgs.HttpContent, this is returns nothing for my particular error case.

**Comment by linvi** [comment]
Yes Twitter does not always return content when an error occur.
Also the error could be another error like Timeout.

As mentioned above I will add more information regarding any issue that could have occurred in the eventArgs.

**Comment by linvi** [comment]
This feature will be available in Tweetinvi 2.1.
