### ISSUE TITLE
<title>Error 401 Unauthorized</title>

### ISSUE THREAD

**Issue by jdahan91** [linvi/tweetinvi#575]
> {--- Date : 10/4/2017 3:16:12 PM
> URL : https://stream.twitter.com/1.1/statuses/filter.json?follow=3920730437&stall_warnings=true
> Code : -1
> Error documentation description : 
> Error message : <html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\n<title>Error 401 Unauthorized</title>
> }

i'm developing for xamarin.android app, the MainActivity looks like this:
Note that when the stream starts, it stops immediately due to unauthentication which is odd.
```
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            SetContentView(Resource.Layout.Main);

            loadCredentialsFromFile();

            btnStart = FindViewById<Button>(Resource.Id.btnStart);
            btnStart.Click += BtnStart_Click;

            btnStop = FindViewById<Button>(Resource.Id.btnStop);
            btnStop.Click += BtnStop_Click;

            btnFollowers = FindViewById<Button>(Resource.Id.btnFollowers);
            btnFollowers.Click += btnFollowers_Click;

            btnCredentials = FindViewById<Button>(Resource.Id.btnCredentials);
            btnCredentials.Click += btnCredentials_Click;

            _items = new List<string>();
            _adapter = new ArrayAdapter<string>(this, Android.Resource.Layout.SimpleListItem1, _items);

            lvLog = FindViewById<ListView>(Resource.Id.lvLog);
            lvLog.Adapter = _adapter;

            _stream = Tweetinvi.Stream.CreateFilteredStream();
            _stream.MatchingTweetReceived += _stream_MatchingTweetReceived;
            _stream.StreamStopped += _stream_StreamStopped;

            loadFollowersFromFile();
        }
```

**Comment by linvi** [comment]
Hi please check the following README and let me know if this helped.

https://github.com/linvi/tweetinvi/tree/master/Examplinvi.Xamarin.Android

Cheers,
Linvi

**Comment by jdahan91** [comment]
Well, i'm loading the creds from a local file deserialized in json, does it matter if i enter the creds manually? could you help me livni in real time via teamviewer?

**Comment by jdahan91** [comment]
livni, give me your email so we can discuss this via hangouts.

**Comment by jdahan91** [comment]
g

**Comment by linvi** [comment]
Documentation: Add a documentation page for Android development.

**Comment by linvi** [comment]
Closing as the issue as the project did not have the required permissions (`Internet`).
