### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by Muchomasquewebs** [linvi/tweetinvi#58]
I upload a image and get this exception:

var file = File.ReadAllBytes(imagePath);
var media = Upload.UploadImage(file);

Exception:

Se produjo una excepción de tipo 'System.AggregateException' en Tweetinvi.WebLogic.dll pero no se controló en el código del usuario

Información adicional: Se han producido uno o varios errores.

Thanks
Regards

**Comment by linvi** [comment]
Hi there,

I will need more information concerning your bug as I cannot reproduce it.
Are you sure that you are correctly setting your credentials and at the same time that the file matches the Twitter image restrictions.

Finally would you please share your full stack trace as well as the InnerException of the AggregateException you are currently receiving.

Thanks

**Comment by Muchomasquewebs** [comment]
Hi Livi:

Sorry for the incovenience but the error is the credentials, in older versions I have not to set the credential for image uploading.

Thank you so much and sorry again!
Nice day

**Comment by linvi** [comment]
OK thanks for the feedback :)
