### ISSUE TITLE
Enable enable_dm_commands for status/update?

### ISSUE THREAD

**Issue by cblaze22** [linvi/tweetinvi#587]
Is there a way to enable this settings, enable_dm_commands, when doing a status update?

**Comment by linvi** [comment]
Hi,

It seems that DM commands will no longer be supported by Twitter in 3 days.
So this will not be added to the library.

https://twittercommunity.com/t/retiring-legacy-dm-commands-on-the-standard-tweet-api/86653

Cheers,
Linvi
