### ISSUE TITLE
Get user's email address

### ISSUE THREAD

**Issue by omriX** [linvi/tweetinvi#591]
How can I get Email address using Tweetinvi ?
I have already get the permission "Request email addresses from users" in my app.

Thanks in advance.

**Comment by linvi** [comment]
Be aware that you can only get the email from the `authenticated user`.

``` c#
Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

var user = User.GetAuthenticatedUser();
var email = user.Email;
```

As you mentioned you also need to have the permission.
If you gave the permission and the email is not received you will have to re generate the credentials.

Cheers :)
Linvi

**Comment by omriX** [comment]
First of all, thank you for the fast answer.

Second, the code that you sent is for getting my own email.
I want to get the email of other user, that I doesn't have the customer
keys and the access tokens.

Is it possible ?

BTW, I am very new in tweetinvi, so I am sorry if the question is annoying.

2017-11-02 20:54 GMT+02:00 linvi <notifications@github.com>:

**Comment by linvi** [comment]
Twitter has some security over email for obvious reasons.

Therefore the only way to access the email of user is to request him to approve your app.
When the user has approved your app and you received his credentials (learn more on how to request a user to authenticate here : https://github.com/linvi/tweetinvi/wiki/Authentication), you will be able to invoke `Auth.SetUserCredentials` with this new user credentials.

As soon as you have invoked `Auth.SetUserCredentials`, a request to `User.GetAuthenticatedUser` will return the information about your user and will contain his email.

**Comment by omriX** [comment]
Thank You ! :)
