### ISSUE TITLE
Successful publish but returns an error

### ISSUE THREAD

**Issue by gsogol** [linvi/tweetinvi#6]
I get a lot of successful publishes when calling PublishTweet or PublishTweetWithMedia, but when checking for an exception afterwards like so:
if (ExceptionHandler.GetLastException() != null)
            var exceptionDescription = ExceptionHandler.GetLastException().TwitterDescription;

I get "Bad Request - The request was invalid or cannot be otherwise served. An accompanying error message will explain further. In API v1.1, requests without authentication are considered invalid and will yield this response."

I can see I'm passing the twitter token and secret key and some posts return no error and some do. What would make some posts go through and some not?

**Comment by linvi** [comment]
Hi,

There are 3 main conditions that can make a tweet fail to publish.
* The same tweet was recently published on the same account (exact same text)
* The tweet text is too long (use the `ITweet.Length` property to find out the real size of a text; be aware that this property will cease to exist in Tweetinvi 0.9.9.x)
* You've reached the RateLimits for publishing (unlikely for publish tweet)

Also you can deactivate the ErrorHandling so that you detect when an error occurs and try/catch them:

``` c#
ExceptionHandler.SwallowWebExceptions = false;
```

Linvi

**Comment by gsogol** [comment]
They actually throw 403 when > 140. So that's fine. They also throw 403 when duplicate so I'm good with those. Latest is 400. The tweet actually goes through and seems to happen randomly. Trying the same one again returns 200 but then I see duplicates on timeline. I've noticed that when I get 400, the image on the timeline is not attached as photo but the text and link is there.

**Comment by linvi** [comment]
mmmh, this is a strange behavior. I don't reckon ever having encountered this issue (and I posted thousands of tweets!).

Would you please share some of your code as well as the image/video that you are trying to upload, when this fails?

Also, can you get more details from the TwitterException. I have designed the TwitterException to contain various information that could be useful to debug this type of problem.

**Comment by gsogol** [comment]
The code is pretty simple:
<code>
RateLimit.RateLimitTrackerOption = RateLimitTrackerOptions.TrackAndAwait;<p>
var image = await GetImageAsync(twitterPost.ImageUrl);
Tweetinvi.TwitterCredentials.ExecuteOperationWithCredentials(credentials, async () =>
{
                    await TweetAsync.PublishTweetWithMedia(tweetText, image);
});
</code>

If you go to https://twitter.com/jeffbabblynew, you will see some tweets don't have a photo attached, just text and link. My code attaches an image as well and I could see the image is there (all bytes). Other tweets that were successful, on the timeline, show a photo.

**Comment by linvi** [comment]
So are you saying, that twitter return a 400 exception but still publishes a Tweet?
Are you sure that the image you receive is of a valid format (dimensions, image type, size...)?

**Comment by gsogol** [comment]
Yes and yes it's valid cause doing the same a second later submits the same image correctly. I can look into it but it's never the same image. Only happens when I submit like 10 in a row within 20 secs or so. One of them is bound to return 400

**Comment by linvi** [comment]
Hi,

Sorry for letting you down on this issue. I have been working a lot for releasing Tweetinvi 0.9.9.x and make sure it was compatible with Windows 10.

Would you please share a bit more code? I would like to see how you publish the 10 tweets you are talking about.

Also do you know that when you publish an image, it creates a media that can only be used once?
Finally could you please share with me the information stored in the TwitterException available in the [ExceptionHandler](https://github.com/linvi/tweetinvi/wiki/Exception-Handling).

Thanks

**Comment by linvi** [comment]
Hi could you please get back to me. I will close the issue if I do not have a response before the 12/08/2015.

**Comment by gsogol** [comment]
The code snippet I sent is all I have. Different people send different urls. We crawl the site and get an image from that url based on some algorithm which is meaningless for this issue. However it is possible the images can be the same but very rare. They seem to throttle after the same user posts many in a row.

**Comment by linvi** [comment]
I have added some checks, an exception should now be thrown if a media could not be published.
Please let me know if this helps when the version 0.9,10.0 is released.

In the meantime, I am closing the issue for tracking purpose. Feel free to reopen it later.
