### ISSUE TITLE
Keep Alive?

### ISSUE THREAD

**Issue by luca1010** [linvi/tweetinvi#604]
Hi,

if I open a stream to receive Direct messages (on a very low traffic account) it works for a while but after a few hours it stops raising events.

I have found a KeepAliveReceived event in Tweetinvi, but I do not know hot to use it. By now I set a timer that sends messages to the bot account to "keep alive", I hope it works but it is a bit ugly.

**Comment by linvi** [comment]
Hello,

All the stream already have a keep-alive functionality by default.

The event `KeepAliveReceived` is actually an event sent by Twitter every 30 seconds in case your stream is too restrictive to have receive any Tweet for this duration.

I am not sure why your stream is stopping but if it does please just restart the stream. Something has probably gone wrong with your connection at some point.

You can manage errors as explained here : 

https://github.com/linvi/tweetinvi/wiki/Streams#stop-and-error-handling

Cheers,
Linvi
