### ISSUE TITLE
Transmission protocol of filtered streams

### ISSUE THREAD

**Issue by roterrechen** [linvi/tweetinvi#607]
Hi, 
Im working on a project with twitter in the university and im implementing the filtered stream in my application.
When I try this application at home with the exact same code everything works fine and the tweets which i look for are printed out but when im trying in the University it doesnt work.
I suspect that the Network/Firewall/proxy and the wifi of the university are the root of the problem.
But to solve this I need to know how the streams are transmitted to me from twitter. 
Is there a TCP or UDP connection or how dose it work?
Or has somebody else the same problem and knows what to do with it?
Im a little bit desperate because i cant find similar problems in forums and the documentation also does not say anything to that.

**Comment by linvi** [comment]
Hello,

Before checking the network of your school I would firstly suggest that you check that the TimeZone and the Time are actually correct on the computer.

Not doing so will result in Twitter to refuse the request as the signature requires a Timestamp.

Secondly, if you still encounter this problem you can use the proxy as explained : 

``` c#
TweetinviConfig.CurrentThreadSettings.ProxyConfig = new ProxyConfig("url", new NetworkCredential("username", "password"));
```

I hope this helps :)

**Comment by roterrechen** [comment]
Thank you very much..it was the time in the PC :)
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 25.11.17, 00:42, linvi <notifications@github.com> schrieb:
Hello,
Before checking the network of your school I would firstly suggest that you check that the TimeZone and the Time are actually correct on the computer.
Not doing so will result in Twitter to refuse the request as the signature requires a Timestamp.
Secondly, if you still encounter this problem you can use the proxy as explained :
TweetinviConfig.CurrentThreadSettings.ProxyConfig = new ProxyConfig("url", new NetworkCredential("username", "password"));
I hope this helps :)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linvi/tweetinvi","title":"linvi/tweetinvi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linvi/tweetinvi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@linvi in #607: Hello,\r\n\r\nBefore checking the network of your school I would firstly suggest that you check that the TimeZone and the Time are actually correct on the computer.\r\n\r\nNot doing so will result in Twitter to refuse the request as the signature requires a Timestamp.\r\n\r\nSecondly, if you still encounter this problem you can use the proxy as explained : \r\n\r\n``` c#\r\nTweetinviConfig.CurrentThreadSettings.ProxyConfig = new ProxyConfig(\"url\", new NetworkCredential(\"username\", \"password\"));\r\n```\r\n\r\nI hope this helps :)"}],"action":{"name":"View Issue","url":"https://github.com/linvi/tweetinvi/issues/607#issuecomment-346906785"}}}
