### ISSUE TITLE
Get tweet's full text

### ISSUE THREAD

**Issue by hugonne** [linvi/tweetinvi#608]
When I search tweets, if the text is long, I get just the first part of it with an ellipsis and a link to the tweet. So for instance, if the tweet says:

> To celebrate #BlackFriday we're giving one lucky person the chance to win this Tommy Hilfiger #FreebieFriday bundle! FOLLOW & RT for a chance to win - comp ends at 5pm. Good luck!

All I get is 

> To celebrate #BlackFriday we're giving one lucky person the chance to win this Tommy Hilfiger #FreebieFriday bundle… https://t.co/zkTc3K96MF

Tried with both **Text** and **FullText** properties. Is there a way to get the actual full text of the tweet?﻿

**Comment by hugonne** [comment]
That feature is actually achieved by including a custom query parameter with tweet_mode=extended. `CustomQueryParameters = { new Tuple<string, string>("tweet_mode", "extended")}`

**Comment by linvi** [comment]
Please read the following documentation : https://github.com/linvi/tweetinvi/wiki/Extended-Tweets-%26-TweetMode

Also note that starting at the next release the default `TweetMode` will be set to `Extended`.

**Comment by hugonne** [comment]
Great information. Thanks a lot.
