### ISSUE TITLE
Problem hacking Dm quick reply 

### ISSUE THREAD

**Issue by luca1010** [linvi/tweetinvi#609]
Hi,

I posted this https://stackoverflow.com/q/47489322/3065132
Because I think that it is a general problem with my query, maybe a missing & or something like that.

Here instead I add a more specifico issue. If I use twitterAccessor to post the modified query I have an exception because when Building headers some params of the direct message are treated as headers resulting in a duplicate item exception riservata by the dictionary that holds the headers. Maybe in Dm extra params are not expected and therefore not handled correctly.

**Comment by linvi** [comment]
Associated with https://github.com/linvi/tweetinvi/issues/588

**Comment by linvi** [comment]
DirectMessages are now fully supported as well as dynamic modification of request in 5.0
