### ISSUE TITLE
Rate Limit for a user stream?

### ISSUE THREAD

**Issue by komBAS** [linvi/tweetinvi#61]
Hi,
in my application I use user streams and for testing purpose I let a stream run since yesterday and today this stream stopped working. Restarting the stream does not seem to activate the stream again, at least it seems that no events will be fired anymore.

Linvi, we talked about my app and the background worker threads last week and **my app worked fine for days now**, I am in a "stress test" right now ;-)

Is there any known rate or time limit for a user stream? I tried with and without proxies, no difference.

Or is it something on the twitter side as I see others reporting non working streams too? My App and my credentials in twitter are not blocked, at least I can see no related informations on dev.twitter.com or in my test twitter accounts.

I use 0.9.9.7 and Tweets and Messages still work, but not the streams.

Thanks,
Kay

**Comment by linvi** [comment]
Before conducting any additional tests, would you please verify whether your code works with version 0.9.10.0 which has been released yesterday.

The reason I am asking is that there have been various improvements related with Streams and MultiThreading.

**Comment by komBAS** [comment]
Hi linvi,
as strange as the situation occured, now it is gone and it works with my untouched 0.9.9.7 version and a 0.9.10 version.
That's why I asked if there is a limit to listen to a stream because I was just listening for over a day and I was not able to restart the stream until 30 minutes ago.
I need to make more tests I guess because it is really annoying to run into a Twitter behavior problem every day.

**Comment by linvi** [comment]
I don't think there are `RateLimits` on streams. And you should also be able to run as many User Streams as you want. The only thing that is important is that you do not run the same stream multiple times.

Issue on the REST/STREAM API occurs regularly and Twitter does not always notify the community about it. Unfortunately today I was not able to test the connection to Twitter so I cannot tell you for certain if the issue comes from your end or from Twitter.

Good luck with your awesome project! Keep me up to date, I will be happy to have some news about it.

**Comment by komBAS** [comment]
I just want to tell that I have the same ssue again.

Streams won't fire events after running for several hours. After stopping and waiting for some hours, restart of streams works.

No DisconnectMessageReceived or StreamStopped events are raised.

I don't say that it is a tweetinvi issue, maybe it's a twitter api issue in general.

Problem for me is that I am in the development of a twitter app and I always need to figure out if it is a twitter, tweetinvi or an error of my code issue ;-)

**Comment by linvi** [comment]
Twitter Stream has been experiencing issues and disruptions during the last 3 days as you can see on the Twitter Availability status.

https://dev.twitter.com/overview/status

**Comment by komBAS** [comment]
Ah cool, thanks linvi.

Didn't knew this status page, but now I can match this with my test results.

**Comment by komBAS** [comment]
Remember: Tweetinvi errors must be reconciled with the Twitter status ;-)
