### ISSUE TITLE
Tweet Reply Count

### ISSUE THREAD

**Issue by Bader80** [linvi/tweetinvi#612]
Is there a corresponding property in the tweet object that returns reply_count ?

**Comment by linvi** [comment]
This property has been removed as the Twitter API does not provide consistent values.
But I will check out if this very long lasting bug has been fixed.

**Comment by Bader80** [comment]
is it possible to include it in the next release 2.3??

**Comment by linvi** [comment]
Yes sorry it was a mistake of my part.

**Comment by Jillustre96** [comment]
Any development on the REply_Count feature?

**Comment by linvi** [comment]
As you can see this should be added in the next release but I have not worked on this yet.

**Comment by linvi** [comment]
Hello,

This has now been added and will be available in the coming release.
Note that these fields are only available for accounts with Premium developer accounts.

If you do have one and you could share a token to allow me to work on Enterprise level features it would help me debug such features. You can contact me private on gitter : https://gitter.im/linvi/

Cheers,
Linvi
