### ISSUE TITLE
GetUserTimeLine cuts message length of received tweet down to 140

### ISSUE THREAD

**Issue by ChaoSera** [linvi/tweetinvi#613]
Using the _GetUserTimeLine_ method with the userID and number of tweets gets me the desired tweets but the _FullText_ field cuts the URLs of attached media (pictures in this case) off, if that exceeds 140 characters combined with the tweet text.
I tried modifying it with _UserTimeLineParameter_ but couldn't find an option that related to the Text Length

Edit: Possibly related to #594 ?

**Comment by linvi** [comment]
Please check this out : https://github.com/linvi/tweetinvi/wiki/Extended-Tweets-%26-TweetMode.
And coming update in 2.2 (https://github.com/linvi/tweetinvi/issues/595).

Thanks
