### ISSUE TITLE
Hundreds of tweets missing for a hashtag search

### ISSUE THREAD

**Issue by kunal-lwt** [linvi/tweetinvi#616]
Hi TweetInvi,

There are hundreds of tweets missing for a hashtag search I am conducting for this hashtag:
#MarutiSuzukiComicCon

When I further tried to go into deep analysis, I found out that there are certain users tweetinvi api is skipping. To replicate, I would give you two examples:
Twitter user with twitter handle @AmanGupta130491 has tweeted at least 23 times for the hashtag #MarutiSuzukiComicCon. 
Twitter user with twitter handle @charmingmitu has tweeted at least 23 times for the hashtag #MarutiSuzukiComicCon. 

Many other tools are showing these numbers correctly and my tool is highly relying on your API. 

Please help me with resolving this problem asap.

Sharing my code for the same:

        ```
    string hashtag = "#MarutiSuzukiComicCon";
            int count = int.MaxValue;
            long sinceId = 1;

            Tweetinvi.Auth.SetUserCredentials("my consumer key",
                "my consumer secret",
                "my access token",
                "my access secret");


            var searchParameter = new SearchTweetsParameters(hashtag)
            {
                SearchType = SearchResultType.Recent,
                MaximumNumberOfResults = count,
                SinceId = sinceId,
                TweetSearchType = TweetSearchType.OriginalTweetsOnly
            };

            var tweets = Search.SearchTweets(searchParameter).ToList();
```

**Comment by linvi** [comment]
Twitter search only provide results for the last 7 days in the public API.
This is probably the problem that you were facing.

**Comment by linvi** [comment]
I would like to add that Tweetinvi in itself does not filter results, it provides as returned by Twitter. 

Also note that you specified included a filter with `SearchType = SearchResultType.Recent`.
