### ISSUE TITLE
App user login to the twitter?

### ISSUE THREAD

**Issue by Develop-CharlieLee** [linvi/tweetinvi#619]
I downloaded tweetinvi via nuget packages today and tried to do 

var appCredentials = new TwitterCredentials("CONSUMER_KEY", "CONSUMER_SECRET");

in my code, but Visual studio told me that TwitterCredentials could not be found. What's the problem?

Also, can user (not the developer) login using his or her ID and password and fetch posts in protected accounts?

**Comment by linvi** [comment]
> in my code, but Visual studio told me that TwitterCredentials could not be found. What's the problem?

You need to add the required namespaces like `Tweetinvi` or `Tweetinvi.Models`...

Check the examples for more : 

- https://github.com/linvi/tweetinvi/blob/master/Examplinvi.NETStandard/Program.cs
- https://github.com/linvi/tweetinvi/blob/master/Examplinvi.NETFramework/Program.cs

> Also, can user (not the developer) login using his or her ID and password and fetch posts in protected accounts?

No you cannot login via ID and password as it not provided by Twitter on their public API. You need to follow the authentication process as explained here : 

https://github.com/linvi/tweetinvi/wiki/Authentication
