### ISSUE TITLE
Improve Exception when starting a stream and the user cannot be fetched

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#62]
Hi Linvi,
This is a feature request, not a bug.

Currently, when starting a stream, Tweetinvi will go and fetch the user that we're starting the stream as by making a call to the REST API.
If the call fails for whatever reason then it does:
```
StopStream(new WebException("Could not receive information related with currently logged user."));
```
which will raise the StreamStopped event (which makes this exception accessible).

If I want to check to see if anything has gone wrong before the stream has even been started, I currently need to check that the type of exception is WebException and that the Message field is equal to "Could not receive information related with currently logged user.".
This is a bit messy, but more importantly will break if you were to change the Exception message in a future release.
Would it be possible to change this exception for a specific one that extends WebException to remove the need for checking the Message?
Cheers,
Josh

**Comment by linvi** [comment]
Hi Josh,

This request seems perfectly valid. I will add this to version 0.9.11.0 or potentially to a version 0.9.10.1.
Please let me know if you need this feature within a specific timeline.

Cheers,
Linvi

**Comment by JoshKeegan** [comment]
Brilliant!
No rush for it, as I can still check the Message if needed. It's just a nice-to-have.
Cheers,
Josh
