### ISSUE TITLE
Stream stops after a while with a 401 Unauthorized error

### ISSUE THREAD

**Issue by vaindil** [linvi/tweetinvi#623]
I'm running several streams from the same server but different app credentials for each, in case that's relevant. The streams sometimes stop working after a few hours, they drop with a 401 Unauthorized error. I can restart the program and they connect just fine, then drop after a few more hours. It's triggering the `StreamStopped` event, not `DisconnectMessageReceived`.

Am I supposed to be handling this somehow? Not sure what to do about this.

**Comment by linvi** [comment]
`DisconnectMessageReceived` is an event received from Twitter informing you that they intentionally closed the connection.

`StreamStopped` is an event handling any exception that could have cause the connection/stream to stop.

> Am I supposed to be handling this somehow? Not sure what to do about this.

Yes you are. There are many reasons why a stream can stop. You need to make sure it reconnects if it fails at any point.
