### ISSUE TITLE
entities doesn't include media element for Direct Messages?

### ISSUE THREAD

**Issue by philjt** [linvi/tweetinvi#624]
It used to be possible (version 1.0) with TweetInvi to retrieve the media information with a direct message. As it was included on the messageDTO entities object. It looks like this property has been removed, when the entities object was moved to the main message object.

Twitter is still returning the media element within the direct message response json, so not sure why this has been removed from TweetInvi?

Has this been removed by mistake?

Retrieving the media from the direct message is quite fundamental to our application.

Thanks
Phil

**Comment by linvi** [comment]
To investigate

**Comment by linvi** [comment]
Fixed https://github.com/linvi/tweetinvi/issues/643
