### ISSUE TITLE
Extended tweet is always empty 

### ISSUE THREAD

**Issue by xFahim** [linvi/tweetinvi#625]
Hi, 

I'm using tweetinvi in one of my projects and it's really amazing. But the only issue I'm facing right now is, 
it's showing truncated tweet when the tweet is lengthier. 
so, it's showing some part of the tweet and then providing a link to the full tweet.So is there any way I can get the full extended tweet? 

I've already tried the 'Extended tweet' property but it always returns null. And couldn't find any way to set the tweeter mode either.

Thanks 
Fahim

**Comment by linvi** [comment]
Please check this out https://github.com/linvi/tweetinvi/wiki/Extended-Tweets-%26-TweetMode
And please be aware that ExtendedTweets will be on by default in next version of Tweetinvi (https://github.com/linvi/tweetinvi/issues/595)
