### ISSUE TITLE
DM Media support

### ISSUE THREAD

**Issue by dancojocaru2000** [linvi/tweetinvi#627]
Hello!

Since Twitter now supports Direct Message media through the new [POST direct_messages/events/new](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event), could you please implement it?

**Comment by linvi** [comment]
Direct Messages will come as part of version 2.3. 

- https://github.com/linvi/tweetinvi/issues/588
- https://github.com/linvi/tweetinvi/issues/496
