### ISSUE TITLE
Search.SearchTweets returning null

### ISSUE THREAD

**Issue by nohack12** [linvi/tweetinvi#629]
Hi everyone!

I'm trying to search tweets according to a certain word using the Search.SearchTweets function. This is the exaple code I have

`Auth.SetUserCredentials(consumerKey, consumerSecret, userKey, userSecret);`
` var matchingTweets = Search.SearchTweets("friend");`

I have noticed that if I search tweets containing the word 'tweetinvi' or 'amigo' i get some tweets, but if i try to search tweets containing other words like 'hello' or 'friend' i get 0 results (null)

I have used tweetinvi for 2 years so far and searches always worked great.

I'm using the last version i have installed recently using the nuget packaje manager.

Why is the search not working?
Thank you!

**Comment by linvi** [comment]
Hello,

If some searches return results it probably imply that there is something going wrong on the public api.
But to be sure of this, could you check if Tweetinvi is throwing any exception by deactivating the ExceptionHandler as explained here : https://github.com/linvi/tweetinvi/wiki/Exception-Handling.

Let me know of the result

Thanks

**Comment by nohack12** [comment]
Hi!

Thank you four your quick response!
I checked the last exception and this is what i got:

`The following error occured : 'Twitter was not able to perform your query within the Timeout limit of 10000 ms.`

I have disabled the ExceptionHandler and Tweetinvi threw this exception:

`An unhandled exception of type 'Tweetinvi.Exceptions.TwitterTimeoutException' occurred in Tweetinvi.Credentials.dll`

`Additional information: https://api.twitter.com/1.1/search/tweets.json?q=friend&count=100 web request timed out.`

**Comment by linvi** [comment]
From your comment, it appears that either there is a problem with your connection or a problem with the Twitter search API (which regularly happens).

**Comment by nohack12** [comment]
Ok! thank you very much

It seems like now it is working without making any change, so I will try to check if it is a connection problem the next time It happens again.

**Comment by linvi** [comment]
Perfect. Feel free to reopen the ticket if you have more questions related to this.
