### ISSUE TITLE
Count of filters

### ISSUE THREAD

**Issue by philhaldane** [linvi/tweetinvi#63]
Hi all, first just have to say this lib is excellent. I wrote an app for linking twitter to another system last year and currently rewriting it with tweeting and it has made life so much easier.

I do have an issue I'm trying to solve, i need to create a filtered stream with circa 8 filters and then keep a count of tweets per filter? i can't run more than two streams therefore need to do it all through a single stream and count the separate filters. Filters are hashtag searches, any ideas or suggestions would be appreciated?

thanks, P

**Comment by linvi** [comment]
There already are 2 different solution to get the matching keywords.

**Solution 1**
Use a callback function for each of the keywords. This solution is good if you want to act differently based on the keyword.

``` c#
var fs = Stream.CreateFilteredStream();

fs.AddTrack("hello", tweet =>
{
    // A tweet with the keyword Tweetinvi has been received
});

fs.StartStreamMatchingAllConditions();
```

**Solution 2**
If you simply want to have the list of matching keywords, the information is already passed through in the event args of the event `MatchingTweetReceived`.

``` c#
var fs = Stream.CreateFilteredStream();

fs.MatchingTweetReceived += (sender, args) =>
{
    var matchingKeywords = args.MatchingTracks;
    foreach (var keyword in matchingKeywords)
    {
        // The tweet contains the following keywords
    }
};

fs.StartStreamMatchingAllConditions();
```

I hope this helps.

**Comment by philhaldane** [comment]
Linvi,

Thanks for this, I have tried both methods but cant seem to get either option functioning correctly; take the first my code looks like;

 var fs = Stream.CreateFilteredStream();
                fs.AddTrack(textBox1.Text, tweet =>
                    {
                        fs.MatchingTweetReceived += (sender, args) =>
                         {
                            updateUI(args.Tweet.Text);
                            count(1);
                         };
                    });

                fs.AddTrack(textBox2.Text, tweet =>
                    {
                        fs.MatchingTweetReceived += (sender, args) =>
                       {
                           updateUI(args.Tweet.Text);
                           count(2);
                       };
                    });
                        
            fs.StartStreamMatchingAllConditionsAsync();

When I execute this, the first time I tweet the specific keyword it returns, updates a user interface and count to the correct counter.
The second time I tweet I picks it up but then runs my updateUI and count twice, no matter which keywork is found, and so on in increments, rather than a single occurance of each tweet. Does that make sense?
I tired the second option but could manage to put all the keywords in as tracks and look for and return a single keyword form all the keywords I am looking for.

thanks
in advance,

**Comment by linvi** [comment]
Well the code you are giving here exactly does what you wrote.

``` c#
fs.AddTrack(textBox1.Text, tweet =>
{
    // This code is invoked each time a Tweet containing the textBox1.Text is received
    // Each time you receive a Tweet you ask Tweetinvi to do the following code 
    // As a result the 1st time MatchingTweetReceived is registered once and therefore the code is invoked once.
    // The second time, MatchingTweetReceived is registered twice and therefore the code is invoked twice.
    fs.MatchingTweetReceived += (sender, args) =>
    {
        updateUI(args.Tweet.Text);
        count(1);
    };
});
```

What you want to do is the following:

``` c#
fs.AddTrack(textBox1.Text, tweet =>
{
    updateUI(tweet.Text);
    count(1);
});
```

Cheers.

**Comment by philhaldane** [comment]
Thanks for this linvi, worked a treat,

that is I had it working but suddenly stopped, I wasn't aware of a limit of streams bar the 1% however I have written another very basic bit of code as follows; but still get no return results? (I Have put in correct credentials)

Auth.SetCredentials("Access_Token", "Access_Token_Secret", "Consumer_Key", "Consumer_Secret");
            var fs = Stream.CreateFilteredStream();

            fs.AddTrack("#hello", tweet =>
            {
                Console.WriteLine(tweet.Text); 
                                
            });
            fs.StartStreamMatchingAllConditionsAsync();

**Comment by linvi** [comment]
Hi again, from your comment I am not sure if the code is working or isn't. Could you please try to rephrase :)
