### ISSUE TITLE
multiple streams not working as expected

### ISSUE THREAD

**Issue by rubenbryon** [linvi/tweetinvi#633]
I'm starting multiple streams like this:

```
public void startListening(List<string> users)
{
    foreach (string user in users)
    {
        var t = new Thread(() =>
        {
            userStream(user);
        });
        t.isBackground = true;
        t.Start();
    }
}

private void userStream(string user)
{
    Auth.setUserCredentials(creds);
    var stream = Tweetinvi.Stream.CreateFilteredStream();
    IUser twitterUser = User.GetUserFromScreenName(user);
    long twitterID = twitterUser.Id;

    stream.AddFollow(twitterID);
    stream.MatchingTweetReceived += (sender, args) =>
     {
         if (args.Tweet.CreatedBy.Id == twitterID)
         {
             Tweet.PublishRetweet(args.Tweet);
             Console.WriteLine("retweeted from " + user);
         }
     };
    stream.StartStreamMatchingAllConditionsAsync();
}
```

1 - This works only somewhat, only retweets are made for one of the users it appears.

2 - How would I in this case properly stop and/or restart the streams (for example when the list 'users' is edited?

Thanks!

Edit: Do I understand correctly that only one stream per set of user credentials is possible? I'll proceed to try with multiple .AddFollow's to the stream.

**Comment by linvi** [comment]
You cannot run multiple `FilteredStream` concurrently with the same credentials.

What you are looking for is `UserStream` which requires the users to have approved your application and therefore provided you with their credentials.

You can also use a single `FilteredStream` and `.AddFollow` but you will have to stop the stream everytime you want to add a user.

**Comment by rubenbryon** [comment]
Allright thanks for the fast response, it seems to indeed work like that.
