### ISSUE TITLE
Can we get all followers now?

### ISSUE THREAD

**Issue by MonsterMMORPG** [linvi/tweetinvi#635]
Did you implement it?

https://github.com/linvi/tweetinvi/wiki/Get-All-Followers-Code

Also for friends we use in url friends part?

 var query = string.Format("https://api.twitter.com/1.1/**friends**/ids.json?screen_name={0}", username);

**Comment by linvi** [comment]
Hello, 

> Did you implement it?

This is not yet implemented as I focus on bug fixing and trying to catch up with the latest features of the api.

> Also for friends we use in url friends part?

Correct.

Cheers,
Linvi
