### ISSUE TITLE
How can i print all of the current limits i have?

### ISSUE THREAD

**Issue by MonsterMMORPG** [linvi/tweetinvi#636]
I have found this 

``` c#  
var ggWp = RateLimit.GetCurrentCredentialsRateLimits(false);
```

But does this include all of the current limits?

Also are there any way to print all of the limits into a file? put into a string list etc?

Also what does this do? `ApplicationRateLimitStatusLimit`

When does `ApplicationRateLimitStatusLimit` get refreshed? that is the main limiter of my application

**Comment by linvi** [comment]
> But does this include all of the current limits?

This include all the `RateLimits` available at the time of release 2.1. The collection of RateLimits rarely changes but sometimes do.

Also as Twitter introduced new endpoints not yet supported by Tweetinvi, they will probably be new elements in the RateLimits.

> Also are there any way to print all of the limits into a file? put into a string list etc?

I would suggest transforming it into `json`.

``` c#
var rateLimits = RateLimit.GetCurrentCredentialsRateLimits();
var json = rateLimits.ToJson();
```

> Also what does this do? ApplicationRateLimitStatusLimit

It refers to the remaining number of queries you can perform to check the credentials.
It is the `RateLimit` of the queries to retrieve the `RateLimits` :)

> When does ApplicationRateLimitStatusLimit get refreshed? that is the main limiter of my application

It depends of which RateLimit mode you use in Tweetinvi.

If you use `RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackAndAwait;` or `RateLimitTrackerMode.TrackOnly` Tweetinvi will cache the information and refresh them when needed. In that mode, Tweetinvi will be able to handle multiple apps running with the same credentials and await to execute a query.

If you want to track the RateLimits yourself you can specify when the cache should be used with the function parameter. But you will be responsible to refresh the cache.

Cheers,
Linvi
