### ISSUE TITLE
Calling StartStreamMatchingAllConditionsAsync() will result in immediate Stop. [0.9.10.0]

### ISSUE THREAD

**Issue by rotem156** [linvi/tweetinvi#64]
I have set the StoppedStream event to point to my event handler, when i call StartStreamMatchingAllConditionsAsync() the StoppedStream event handler gets triggered, is this an internal problem ? what's going on ?

**Comment by linvi** [comment]
Hello, which version of Tweetinvi are you using? Can you share your code.
Could you also disable the `ExceptionHandler` and let me know what error you receive (stack trace if possible).

``` c#
ExceptionHandler.SwallowWebExceptions = false;
```

**Comment by rotem156** [comment]
0.9.10.0, the argument "e" inside the StoppedStream event handler seems to be empty.

    private void btnStart_Click(object sender, EventArgs e)
        {
            if (listView1.Items.Count == 0)
            {
                MessageBox.Show("No people to follow, please add atleast 1 name to the follow list.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            switch (isStreamRunning)
            {
                case true:
                    MessageBox.Show("Streaming is already running!, stop it first before starting it again.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    break;
                case false:
                    ExceptionHandler.SwallowWebExceptions = false;
                    filtered_stream.StartStreamMatchingAllConditionsAsync();
                    break;
            }
        }

     private void FilteredStreamStoppedHandler(object sender, StreamExceptionEventArgs e)
        {
            tsLabel1.Text = "Inactive";
            isStreamRunning = false;
        }

        private void filteredStreamStreamStarted(object sender, EventArgs e)
        {
            tsLabel1.Text = "Active";
            isStreamRunning = true;
        }

      private void MatchingTweetReceivedHandler(object sender, MatchedTweetReceivedEventArgs args)
        {
            var tweetInfo = args.Tweet;

            using (StreamWriter sw = new StreamWriter(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "debugoutput.txt"), true))
            {
                sw.WriteLine(String.Format("screen_name:{0} Text: {1} IsRetweet: {2} InReplyToStatusIdStr: {3} created_at: {4}",
                    tweetInfo.CreatedBy.ScreenName, tweetInfo.Text, tweetInfo.IsRetweet, tweetInfo.InReplyToStatusIdStr, tweetInfo.CreatedAt.ToLocalTime().ToString()));
            }

        }

**Comment by rotem156** [comment]
linvi, did you successfully reproduce the problem ?

**Comment by linvi** [comment]
No I haven't, is it possible for you to share your project please?
Do you know if the stream works in a Console project. The reason why I ask is the fact that I have another [similar issue](https://github.com/linvi/tweetinvi/issues/60) opened for a WPF app, but the stream works in Console Application.

What I do not understand is that your stream stops but you do not receive any Exception, is it correct?

**Comment by rotem156** [comment]
Yes, correct, i do not get any exceptions.

How can i send you my project privately ?

**Comment by linvi** [comment]
Please contact me through the codeplex website :

https://www.codeplex.com/site/users/view/linvi, there is a contact link there. Unfortunately Github no longer provide private messaging.

**Comment by rotem156** [comment]
I think this is an internal bug in the latest version, in 0.9.98.0 it didn't happen.

**Comment by linvi** [comment]
Ok thanks for the info. Please share your code it will probably help a lot for debugging this issue.

**Comment by rotem156** [comment]
i'm not going to register a new account on codeplex, i merely hesitated registering an account on here, give me your email.

**Comment by linvi** [comment]
Could you send it to me here : tweetinvi@forward.cat

Thanks for your help.

**Comment by rotem156** [comment]
Do you have another email ? i failed sending it to that address.

**Comment by linvi** [comment]
Can you try this one? tweetinvi@yopmail.com

**Comment by rotem156** [comment]
failed to send to that one too.

**Comment by linvi** [comment]
Can you please go on gitter (with git account) and we will be able to discuss privately.

https://gitter.im/linvi/tweetinvi

**Comment by rotem156** [comment]
Ok, this issue has been resolved, what was done is we passed the creds (TwitterCredentials) directly into the CreateFilteredStream() function.

**Comment by linvi** [comment]
The issue was that Stream breaking change was not understood when migrating from 0.9.9.8 to 0.9.10.0.

Please read the documentation fo 0.9.10.0 concerning Stream breaking changes here: https://github.com/linvi/tweetinvi/releases/tag/0.9.10.0.
