### ISSUE TITLE
args.Tweet.Hashtags.Count - sometimes wrong

### ISSUE THREAD

**Issue by Scobiform** [linvi/tweetinvi#641]
Sometimes the hashtag count is wrong. It gives 0 or another incorrect number. The hashtags are correct in the json data, so I´m guessing there is something wrong with => `args.Tweet.Hashtags.Count`

Or am I misusing the hashtag count?

**=> EDIT**: Okay it seems like it is a problem with extended tweet. The correct count will be there if the tweet is too long. 

So everyone can just check if extended is not null and use the extended hashtag count. :)

**Comment by linvi** [comment]
Improve the logic to show HashTags for extended tweets

**Comment by linvi** [comment]
Could you please share a Tweet Id for which you can reproduce the issue.

Thanks,
Linvi

**Comment by linvi** [comment]
Could not reproduce. If you can provide a Tweet Id please reopen the issue.
