### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by StephenMP** [linvi/tweetinvi#646]
I think with Twitter's extremely confusing implementation of both OAuth 1.0a and Oauth 2.0 access tokens, both of which are used for different things, it would be great to update the Authentication section of the Wiki documentation to reflect that information accordingly.

Below are my proposed updates for the [Authentication Overview](https://github.com/linvi/tweetinvi/wiki/Authentication#overview)

---

## Overview
Twitter allows a developer's application to authenticate any Twitter user and perform actions on behalf of the user. The API gives access to two different mechanisms that we will name URL Redirect Authentication ([3-legged Oauth](https://developer.twitter.com/en/docs/basics/authentication/overview/3-legged-oauth)) and [PIN-based authentication](https://developer.twitter.com/en/docs/basics/authentication/overview/pin-based-oauth). Both the PIN-based Flow and URL Redirect Flow grant Oauth 1.0a access tokens.

Note: Twitter has two types of Oauth Access Tokens.

1. Oauth 1.0a which Twitter uses to perform actions on behalf of the user.
1. Oauth 2.0 which Twitter uses to perform action on behalf of the application. Read about [Application-only Authentication](https://developer.twitter.com/en/docs/basics/authentication/overview/application-only).

---

Here's the Markdown for the above changes:

```
## Overview
Twitter allows a developer's application to authenticate any Twitter user and perform actions on behalf of the user. The API gives access to two different mechanisms that we will name URL Redirect Authentication ([3-legged Oauth](https://developer.twitter.com/en/docs/basics/authentication/overview/3-legged-oauth)) and [PIN-based authentication](https://developer.twitter.com/en/docs/basics/authentication/overview/pin-based-oauth). Both the PIN-based Flow and URL Redirect Flow grant Oauth 1.0a access tokens.

Note: Twitter has two types of Oauth Access Tokens.

1. Oauth 1.0a which Twitter uses to perform actions on behalf of the user.
1. Oauth 2.0 which Twitter uses to perform action on behalf of the application. Read about [Application-only Authentication](https://developer.twitter.com/en/docs/basics/authentication/overview/application-only).
```

**Comment by linvi** [comment]
Thank you for taking the time to write this documentation.
Usually I try to avoid adding "technical" information of how Twitter handles the requests.

But I will add this to "technical" documentation page.
