### ISSUE TITLE
IUser.Friends and IUser.FriendIds null?

### ISSUE THREAD

**Issue by khteh** [linvi/tweetinvi#647]
Hi;
   IUser.GetFriends() and IUser.GetFriendIds() return list of friends but the Friends and FriendIds properties are both null. Are these property implemented at all? Thanks.

**Comment by linvi** [comment]
These properties were intended to be used by developers to associate the result of `GetFriends()` result directly to a `IUser` object.

One would argue that these properties should not be there as they could be associated in a `Dictionary` or from a `Mapped` object extendind `IUser` but I thought they were useful.

Any input on the solution is more than welcome.

Also note that the property's description is the following : 

``` c#
```
