### ISSUE TITLE
Tweetinvi.Tweet.PublishTweet throws NullReferenceException.

### ISSUE THREAD

**Issue by khteh** [linvi/tweetinvi#648]
Image size is 6547396 bytes. The following is the stack trace:

> NullReferenceException: Object reference not set to an instance of an object.
Tweetinvi.Controllers.Upload.UploadQueryExecutor.UploadMedias(IEnumerable<IMedia> medias, bool forceReUpload)
Tweetinvi.Controllers.Upload.UploadQueryExecutor.UploadBinaries(IEnumerable<Byte[]> binaries)
Tweetinvi.Controllers.Tweet.TweetController.UploadMedias(IPublishTweetParameters parameters)
Tweetinvi.Controllers.Tweet.TweetController.InternalPublishTweet(IPublishTweetParameters parameters)
Tweetinvi.Controllers.Tweet.TweetController.PublishTweet(string text, IPublishTweetOptionalParameters optionalParameters)
ASP.NetCoreTwitterOAuth.Pages.Twitter.IndexModel.PublishTweet() in Index.cshtml.cs

``` c#
        private ITweet PublishTweet()
        {
            var fileBytes = GetByteArrayFromFile(Image);
            var publishOptions = new PublishTweetOptionalParameters();
            if (fileBytes != null)
                publishOptions.MediaBinaries.Add(fileBytes);
            return Tweetinvi.Tweet.PublishTweet(TweetString, publishOptions);
        }
```

**Comment by linvi** [comment]
A lot has changed in version 2.2 for Upload. I cannot reproduce the bug with the new version.

**Comment by khteh** [comment]
I used 2.1.0 which is available from NuGet.

**Comment by linvi** [comment]
Thank you, please test version 2.2 when it becomes available.
