### ISSUE TITLE
Json Serialising Media on ITweet breaks with Video

### ISSUE THREAD

**Issue by TomSteer** [linvi/tweetinvi#65]
Hello,

I'm currently serialising the Media property on the ITweet Interface to json, which works fine until the tweet contains a video. When a video is present it throws the following: The method or operation is not implemented. in this code block: Tweetinvi.Logic.JsonConverters.JsonPropertyConverterRepository.WriteJson. From what I can tell this is because of IVideoEntityVariant uses the JsonPropertyConverterRepository to deserialise it but this also gets picked up by Newtonsoft.Json when serialising too and throws the exception because WriteJson is not implemented.

Is there anything I can do to get around this so I can serialise the Media property?

Thanks and awesome work on this project :+1: 

Tom

**Comment by linvi** [comment]
Hi there,

Sorry for taking so long to reply. I am usually prompt but I have been overbooked this week.
As per your question, this is a known "issue". Serialization of Tweetinvi objects will be available as part of version 1.1. So it means it will be available in around 9 months.

In the meantime, please create your custom proxy/adapter object and add the properties you need to deserialize manually.

This feature is sometimes asked but the goal of version 1.0 is to have a library covering 100% of the Twitter API. After doing this I will add some additional features. Serialization will be the first one.

Cheers,
Linvi

**Comment by linvi** [comment]
Link : https://github.com/linvi/tweetinvi/issues/75

**Comment by linvi** [comment]
For the sake of mentioning it, the json object serialization has been improved. Please check it out.

**Comment by linvi** [comment]
Fixed in version 0.9.13.0. Check the serialization wiki for more information.

https://github.com/linvi/tweetinvi/wiki/Serialization-and-Deserialization
