### ISSUE TITLE
Twitter Data Cleaning and arff Weka with Tweetinvi or something like that...

### ISSUE THREAD

**Issue by istavrit** [linvi/tweetinvi#650]
How can we clear the data we collected with tweetinvi using c # code and then convert it to arff file format and weka can be traine...

Thanks your helping

**Comment by linvi** [comment]
Hello,

Sorry but I cannot help you. This is a question that is not related with Tweetinvi itself but more related with the arff file format. 

I think you would be better of asking this question on stackoverflow.

Cheers,
Linvi
