### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by khteh** [linvi/tweetinvi#654]
Hi;
   I am using ASP.Net Core 2.0 with ReactJS template and V2.1.0 of your library. The app bumps into CORS issue when redirecting to twitter. Here is the error message from the Chrome browser console:

localhost/:1 Failed to load https://api.twitter.com/oauth/authorize?oauth_token=<foo>: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:61825' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by linvi** [comment]
I do not understand how a redirect ends up being caught with CORS.
From the contextual information you are providing it looks like you are trying to execute the WebRequest to access api.twitter.com from the frontend.

A redirection is a different thing and can be performed directly from the server side.

**Comment by khteh** [comment]
Here is my Home.tsx code:

`import * as React from 'react';
import { RouteComponentProps } from 'react-router';
import TwitterLogin from 'react-twitter-auth';
import * as Models from '../Models';
interface UserState {
    user: Models.User
}
export class Home extends React.Component<RouteComponentProps<{}>, UserState> {
    constructor() {
        super();
        this.state = {user: null};
        this.onFailed = this.onFailed.bind(this);
        this.onSuccess = this.onSuccess.bind(this);
    }
    onSuccess = (response: any) => {
        const token = response.headers.get('x-auth-token');
        response.json().then((user: any) => {
            if (token)
                this.setState({ user: user});
        });
    }
    onFailed = (error: any) => {
        alert(error);
    }
    handleAuthenticate() {
        fetch('/Home/TwitterAuth', {
                    method: 'GET',
                    mode: "cors", // or without this line
                    redirect: 'follow',
                    headers: {
                        'content-type': 'application/json'
                    }
                })
            .then(response => {
                if (response !== null && response.body !== null) {
                    //console.log("response: " + JSON.stringify(response));
                    //var user = response.json() as Promise<Models.User>;
                    return response.json() as Promise<Models.User>;
                } else
                    return null;
                //return (response.) ? response.json() as Promise<Models.User> : null
            })
            .then(data => {
                this.setState({ user: data });
            }).catch(e => {
                console.log(e);
                return e;
            });
    }
    logout = () => { this.setState({ user: null}); }
    public render() {
        let content = !!this.state.user && !!this.state.user.isAuthenticated ? (
            <div>
                <p>Authenticated</p>
                <div>{this.state.user.Email}</div>
                <div>
                    <button onClick={this.logout} className="button">Log out</button>
                </div>
            </div>
        ) : (
                <div>
                    <button onClick={this.handleAuthenticate.bind(this)} className="button">Log In</button>
                </div>
            );
        return (
            <div className="App">
                <header className="App-header">
                    <h1 className="App-title">Welcome to React Twitter Application</h1>
                </header>
                {content}
            </div>
        );
    }
}`

**Comment by khteh** [comment]
I am not sure how this is going to work with ReactJS. This is what I did:
(1) Home.tsx: Use clicks "Log In" button. The handler "fetch" from /Home/TwitterAuth which will reach the familiar TwitterAuth method in HomeController.cs. The method

(2) TwitterAuth does it's usual stuff and redirects to twitter page.

(3) Execution returns to fetch(). That's where CORS error happens.

Question:
I expect to return a User object from ValidateTwitterAuth method of HomeController to Home.tsx after the redirection but that never happens as it is stuck in the CORS error.

**Comment by linvi** [comment]
It is because you should not `fetch` /Home/TwitterAuth`. You should navigate to it (e.g. with an anchor tag).

**Comment by khteh** [comment]
Thanks. That solves the problem....

**Comment by linvi** [comment]
You do understand why CORS was being raised?

**Comment by khteh** [comment]
Not really.

**Comment by linvi** [comment]
Your application was `fetching` an endpoint that was redirecting to `api.twitter.com`.
Obviously `api.twitter.com` will does not authorize your website domain (or localhost) to access it via CORS.

As a result `api.twitter.com` does not provide the CORS header required by chrome to authorize the `fetch`.

By using a navigation you are then directly accessing the Twitter website and as a result chrome no longer need to check for CORS as it is a simple url navigation.

I hope this helps :)

Have a great day.

**Comment by khteh** [comment]
That really helps. Thanks.

**Comment by khteh** [comment]
Do you have example with .Net Core 2.0 as server and ReactJS as client? I have a tough time getting this to work due to the redirection using anchor element. Specifically, how to pass the authenticated user object back to the view? I have tried the following:

`        public ActionResult ValidateTwitterAuth()
        {
            User user = new NetCoreReactJSTwitter.User();
            if (Request.Query.ContainsKey("oauth_verifier") && Request.Query.ContainsKey("authorization_id"))
            {
                var verifierCode = Request.Query["oauth_verifier"];
                var authorizationId = Request.Query["authorization_id"];
                var userCreds = AuthFlow.CreateCredentialsFromVerifierCode(verifierCode, authorizationId);
                Auth.SetCredentials(userCreds);
                IAuthenticatedUser u = Tweetinvi.User.GetAuthenticatedUser(userCreds);
                user.isAuthenticated = true;
                user.Name = u.Name;
                user.Email = u.Email;
                user.ScreenName = u.ScreenName;
            }
            return LocalRedirect("/?user="+user.ToJson());
        }
`
       This will result in props.location.search having the query string parameter. This is more of a hack and I am not good in ReactJS.

**Comment by linvi** [comment]
Hello,

I do not have an example available for you and at the moment I need to focus on releasing version 2.2 before working on such example.

If you happen to make it work feel free to share the example here, potentially through a Pull Request.

Thanks,
Linvi
