### ISSUE TITLE
Account.UpdateAccountProfile certain inputs cause a null return

### ISSUE THREAD

**Issue by Meow764** [linvi/tweetinvi#655]
So yeah, I'm trying to create a quick little script to update my bio every x hours to match a rank in a game a play.
Here's my code:
```csharp
var credentials = new AuthCredentials();
Auth.SetUserCredentials(credentials.ConsumerKey, credentials.ConsumerSecret, credentials.AccessToken, credentials.AccessTokenSecret);
var parameters = new AccountUpdateProfileParameters
{
    Description = "test test hi hi382"
};
Account.UpdateAccountProfile(parameters);
```
And that would work just fine, **but** if the input includes a comma `,` or a hashtag `#` (and surely some other ones as well, those are just the ones I found) it will return null and not go through.
Example input of what would not work: `"Hi, test43"` or just simply `"#"`.

Why is this? Is there something I'm doing wrong or is this a bug? Is there a fix?
Any help is appreciated, thanks.

**Comment by Meow764** [comment]
I appreciate that this was acknowledged, and will be looked at(?) 
(Sorry, new to github, I just assume that that v2.2 milestone means that the aim is to have this fixed for verson 2.2?)
But is there any chance there could be a workaround for this? I don't really care how inconvenient it would be or whatever.

**Comment by Ramkarthik** [comment]
There is a PR for this issue #656 which I believe will be merged for v2.2.

For now, you can wrap your description text with Uri.EscapeDataString() like below:
`var parameters = new AccountUpdateProfileParameters
{
      Description = Uri.EscapeDataString("This is your description with comma, hash (#) and you can try with other special characters.")
};`

**Comment by Meow764** [comment]
Thanks @Ramkarthik, but that way has an issue though. 
It very easily throws the exception that my description is longer than 100 characters (even tho in reality it's not).

But I just did this instead of wrapping the whole string in `Uri.EscapeDataString()` to solve my problem, thanks a lot! 
`.Replace("#","%23").Replace(",","%2C")`

**Comment by Ramkarthik** [comment]
Yes @Meow764. Since it Uri Encodes at the time of adding to query parameters, it will consider those also as part of length check. So for now, `.Replace` seems to be a good idea till the PR is merged.

**Comment by linvi** [comment]
This is now fixed by https://github.com/linvi/tweetinvi/commit/ac30c6057f608a142cb7aaad63dad7def840d0dd#diff-95c6b1cf132f99eb75fcd0fbf39d0fcfR260
