### ISSUE TITLE
Example with .Net Core and ReactJS?

### ISSUE THREAD

**Issue by khteh** [linvi/tweetinvi#657]
Hi;

Do you have example with .Net Core 2.0 as server and ReactJS as client? I have a tough time getting this to work due to the redirection using anchor element. Specifically, how to pass the authenticated user object back to the view? I have tried the following:

``` c#
public ActionResult ValidateTwitterAuth()
{
	User user = new NetCoreReactJSTwitter.User();
	if (Request.Query.ContainsKey("oauth_verifier") && Request.Query.ContainsKey("authorization_id"))
	{
		var verifierCode = Request.Query["oauth_verifier"];
		var authorizationId = Request.Query["authorization_id"];
		var userCreds = AuthFlow.CreateCredentialsFromVerifierCode(verifierCode, authorizationId);
		IAuthenticatedUser u = Tweetinvi.User.GetAuthenticatedUser(userCreds);
		user.isAuthenticated = true;
		user.Name = u.Name;
		user.Email = u.Email;
		user.ScreenName = u.ScreenName;
	}
	return LocalRedirect("/?user="+user.ToJson());
}
```

This will result in props.location.search having the query string parameter. This is more of a hack and I am not good in ReactJS.

**Comment by linvi** [comment]
As I mentioned I cannot work on this at the moment. Please ask such question on StackOverflow.
I am sure you will fin a lot of help over there.

Thanks,
Linvi

**Comment by khteh** [comment]
This is resolved and there are 2 ways:

(1) As mentioned in my original post, pass the JSON user object to React component and parse the JSON string manually by off-seting into the query string and uri-decode the string.

(2) Make a fetch call from the React component constructor to the ASP.Net Core controller action method.

I use method (2). Here is my solution: https://github.com/khteh/ASP.NetCoreReactJSTwitter
