### ISSUE TITLE
Twitter was not able to perform your query within the Timeout limit of 10000 ms.

### ISSUE THREAD

**Issue by jcmag** [linvi/tweetinvi#663]
Hi,

I've migrated my app on a new server, and now I get many errors (status code=408) from twitter:
"Twitter was not able to perform your query within the Timeout limit of 10000 ms."

I use searches, and retrieve users timelines; I don't know if I have to change my configuration, since I've moved to a new server. For example, maybe I have to change my auth keys?
Or as I have changed my DNS records, maybe it's related to that...
any idea?

**Comment by jcmag** [comment]
it's working now

**Comment by jcmag** [comment]
I still have this error from time to time; what could be the reason?
is there a way to debug it to have more info?

**Comment by linvi** [comment]
This simply mean that Twitter could not be reached or did not provide a reply after a delay of 10 seconds.

As a result I would check the status of the Twitter API and more importantly the status of your network.

**Comment by jcmag** [comment]
No problem from my network, so I'll add some retry feature after a few minutes.
thanks!
