### ISSUE TITLE
How to refresh FollowersCount and FriendsCount

### ISSUE THREAD

**Issue by MonsterMMORPG** [linvi/tweetinvi#665]
I have the following code to get Friends and Followers counts

However, i think it is not refreshing the actual numbers when called and only returns to the very first authentication counts

```
     authenticatedUser = User.GetAuthenticatedUser();
 if (authenticatedUser.FollowersCount * 1.098 > authenticatedUser.FriendsCount)
  {
      //do something                          
  }
```

So i need to get actual followers and friends count whenever i want

How can i do that?

**Comment by linvi** [comment]
The `authenticatedUser` that you retrieve is a fix object.
Either you will need to pull it regularly otherwise you will have to use the `UserStream`.
