### ISSUE TITLE
Is there an `Event` I can use that is being executed as soon as a new Tweet shows up in the Timeline of a user?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [linvi/tweetinvi#666]
Currently I do `var tweets = Timeline.GetUserTimeline("user");`, iterate through that and run it every 9 minutes.

**Comment by luca1010** [comment]
Hi, Probably streams are what you need...
https://github.com/linvi/tweetinvi/wiki/Streams

**Comment by ErfolgreichCharismatisch** [comment]
How are those called that I follow, which don't follow me in streams? IOW, what is the streams equivalent for Timeline.GetUserTimeline("user")?

**Comment by linvi** [comment]
@luca1010 is right you need to use either a `UserStream` if you have the credentials from that user or the `FilteredStream` if you just want to follow a specific list of users.
