### ISSUE TITLE
Send tweet with authenticated user

### ISSUE THREAD

**Issue by mmshahshahani** [linvi/tweetinvi#667]
Hi
I have authenticated a user successfully 

``` c#

var verifierCode = Request.Params.Get("oauth_verifier");
var authorizationId = Request.Params.Get("authorization_id");

if (verifierCode != null)
{
	var userCreds = AuthFlow.CreateCredentialsFromVerifierCode(verifierCode, authorizationId);
	var user = Tweetinvi.User.GetAuthenticatedUser(userCreds);

	int UserID = Convert.ToInt32(Request.Params.Get("id"));

	var isUser = (from u in context.Users where "some code" select u).SingleOrDefault();

	if (isUser != null)
	{
		isUser.UserTweeterAuthorizationId = authorizationId;
		isUser.UserTweeterVerifierCode = verifierCode;

		context.SaveChanges();

		//بفرسته به ... و ادامه ماجرا
	}
	else
	{
		//بفرسته به ... با پیغام خطا
	}
}
```

How can i send a tweet with this user ?

**Comment by linvi** [comment]
Please follow the introduction part from the documentation :

https://github.com/linvi/tweetinvi/wiki/Introduction#hello-world

It mentions that you have to use your credentials with the `Auth.SetUserCredentials`

**Comment by mmshahshahani** [comment]
Thanks for your answer . I have two question from Hello world sample .

1 - What should I use for "ACCESS_TOKEN" and "ACCESS_TOKEN_SECRET" from query string that reply from twitter ?

2 - Should I use my "CONSUMER_KEY" and "CONSUMER_SECRET" ?

**Comment by mmshahshahani** [comment]
Please help me :-)

**Comment by linvi** [comment]
Hello,

The `userCreds` object that you receive will contain all the information that you are looking for.
Just save these information and use the `Auth.SetUserCredentials` with these information.

Cheers,
Linvi

**Comment by mmshahshahani** [comment]
Thanks a lot for answer . It is really helpful . I write this code

`
            var verifierCode = Request.Params.Get("oauth_verifier");
            var authorizationId = Request.Params.Get("authorization_id");

            if (verifierCode != null)
            {
                var userCreds = AuthFlow.CreateCredentialsFromVerifierCode(verifierCode, authorizationId);
                var user = Tweetinvi.User.GetAuthenticatedUser(userCreds);

                int UserID = Convert.ToInt32(Request.Params.Get("id"));

                var isUser = (from u in context.Users where u.UserTelegramID == UserID select u).SingleOrDefault();

                if (isUser != null)
                {
                    isUser.UserTweeterVerifierCode = verifierCode;
                    isUser.UserTweeterAuthorizationId = authorizationId;

                    context.SaveChanges();

                    bot.SendTextMessageAsync(UserID, user.ToString());
                }
                else
                {
                    //بفرسته به ... با پیغام خطا
                }
`

It is ok but when i try to sent tweet an exception thrown . This is my code

`
var verifierCode = isUser.UserTweeterVerifierCode;
                        var authorizationId = isUser.UserTweeterAuthorizationId;

                        var userCreds = AuthFlow.CreateCredentialsFromVerifierCode(verifierCode, authorizationId);
                        var user = Tweetinvi.User.GetAuthenticatedUser(userCreds);

                        Tweet.PublishTweet(s);
`

The Exception 

An exception of type 'System.ArgumentException' occurred in Tweetinvi.dll but was not handled in user code

Additional information: Identifier could not be matched to any stored AuthenticationContext.

**Comment by mmshahshahani** [comment]
Hi again . excuse me if I bothering you
I changed my code 

`var verifierCode = Request.Params.Get("oauth_verifier");
            var authorizationId = Request.Params.Get("authorization_id");
            var oauthtoken = Request.Params.Get("oauth_token");

            if (verifierCode != null)
            {
                var userCreds = AuthFlow.CreateCredentialsFromVerifierCode(verifierCode, authorizationId);
                var user = Tweetinvi.User.GetAuthenticatedUser(userCreds);

                int UserID = Convert.ToInt32(Request.Params.Get("id"));

                var isUser = (from u in context.Users where u.UserTelegramID == UserID select u).SingleOrDefault();

                if (isUser != null)
                {
                    isUser.UserTweeterVerifierCode = verifierCode;
                    isUser.UserTweeterAuthorizationId = authorizationId;
                    isUser.UserTweeteroAuthtoken = oauthtoken;
                    isUser.UserTweeterAccessToken = userCreds.AccessToken;
                    isUser.UserTweeterAccessTokenSecret = userCreds.AccessTokenSecret;

                    context.SaveChanges();

                    Auth.SetCredentials(userCreds);

                    bot.SendTextMessageAsync(UserID, user.ToString());
                }
                else
                {
                    //بفرسته به ... با پیغام خطا
                }` 

and in another web page i changed my code too

`Auth.SetUserCredentials(Classes.MyCredentials.CONSUMER_KEY, Classes.MyCredentials.CONSUMER_SECRET,isUser.UserTweeterAccessToken,isUser.UserTweeterAccessTokenSecret);

                        Tweet.PublishTweet(isUser.UserTelegramFirstName + " " + isUser.UserTelagramLastName + DateTime.Now.ToString());`

But unfortunately nothing append .

**Comment by mmshahshahani** [comment]
Thank you a lot
