### ISSUE TITLE
The type initializer for 'Tweetinvi.Auth' threw an exception.

### ISSUE THREAD

**Issue by rshahrabani** [linvi/tweetinvi#668]
Hi,

We are encountering an error when trying to use the Tweetinvi library to send a tweet.

.NET Console app using C# .NET 4.6.1 - this is a test application to send a tweet.  This works on a development machine but not on the production server.

Trying to authorize the credentials through the Tweetinvi.Auth and got the below exception. We read the article regarding modification of the web.config file, but this is a simple console application.

Any help would be appreciated.

System.TypeInitializationException: The type initializer for 'Tweetinvi.Auth' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Tweetinvi.Credentials.TweetinviCredentialsModule.Initialize()
   at Tweetinvi.Injectinvi.AutofacContainer.InitializeModules()
   at Tweetinvi.Injectinvi.AutofacContainer.Initialize()
   at Tweetinvi.TweetinviContainer.Resolve[T]()
   at Tweetinvi.Auth.Initialize()
   at Tweetinvi.Auth..cctor()
   --- End of inner exception stack trace ---
   at Tweetinvi.Auth.SetUserCredentials(String consumerKey, String consumerSecret, String userAccessToken, String userAccessSecret)
   at ConsoleCS.Program.TestTweetInvi()
   at ConsoleCS.Program.Main(String[] args)

**Comment by linvi** [comment]
Hello,

This is a common issue due to nuget package installation:

Please read the following documentation : https://github.com/linvi/tweetinvi/wiki/System.Net.Http-not-found-exception

Thanks,
Linvi

**Comment by LambHoot** [comment]
@linvi 
Hi, I've been experiencing this issue recently and have been going through the wiki and closed issues looking for a solution to no avail.

Just installed TweetInviAPI version 4.0.0 for the new direct messages features and it started. The Auth.SetCredentials(creds); is throwing the exception. Code looks like this, ripped straight from the examples:
`ITwitterCredentials creds = new TwitterCredentials(customer_key, customer_key_secret, access_token, access_token_secret);
            Auth.SetCredentials(creds);`
The exception is:
`An unhandled exception of type 'System.TypeInitializationException' occurred in myproject.exe

Additional information: The type initializer for 'Tweetinvi.Auth' threw an exception.`

Project is a windows console app targeting . I've already updated my app.config following the instructions on https://github.com/linvi/tweetinvi/wiki/System.Net.Http-not-found-exception , I've also tried uninstalling and reinstalling TweetInviAPI and all of its dependencies.

The project can be found here:
https://github.com/LambHoot/LambHoot_DiscordBot/tree/TwitterBot

Hopefully you'll have a chance to take a look. Thanks!

**Comment by linvi** [comment]
Hello,

Sorry for the long wait, I am currently in the process of writing some documentation and will be looikng at your project right after.

Cheers,
Linvi

**Comment by LambHoot** [comment]
Hey, sorry for the even longer wait for this response lol, but just in case anyone stumbles upon this issue someday in the future. The fix for me was to build a new project in Visual Studio, then manually re-import all of my classes.

Obviously this solution won't be appropriate for the scope of all projects, but it might be worth the time if you're stuck because of it. Figure there must have been something terribly wrong with my config, but it would have taken longer to discover what that was than to just start a fresh project.

Anyways, thanks!
