### ISSUE TITLE
Tweet Entities having duplicates removed, not counting different indices as different entities

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#67]
Tweetinvi removes duplicate entities in a Tweet without considering their entities indices.
So if a tweet mentions the same user twice, that will only show once in Tweetinvi.

Can be seen in action with:
```
var tweetJson = TwitterAccessor.ExecuteJsonGETQuery("https://api.twitter.com/1.1/statuses/show.json?id=656821186014281729");
ITweet tweet = Tweet.GetTweet(656821186014281729);
```

At a glance, it looks like TweetEntities.InitialiseEntities() calls Distinct() against each collection of entities, but the Equals() method for each entity are ignoring indices, e.g. UserMentionEntity.Equals:
```
public bool Equals(IUserMentionEntity other)
{
  if (!this.Id.HasValue)
    return false;
  long? id1 = this.Id;
  long? id2 = other.Id;
  if (id1.GetValueOrDefault() != id2.GetValueOrDefault())
    return false;
  return id1.HasValue == id2.HasValue;
}
```

This is only really an issue for Hashtags & Mentions, where the otherwise same entity could exist at multiple positions in the tweet.

**Comment by linvi** [comment]
Again thanks for reporting it and for investigating the issue. It will be part of Tweetinvi 0.9.10.1.

Cheers,
Linvi

**Comment by JoshKeegan** [comment]
No worries, thanks for being so quick & fixing these little niggles!
Cheers,
Josh
