### ISSUE TITLE
GeoLocation not working properly

### ISSUE THREAD

**Issue by dmaidon** [linvi/tweetinvi#684]
In the Wiki/Documentation the following is shown for Geolocation:

``` c#
var France = new Coordinates(longitude, latitude);
```

It has me showing up in Antarctica in stead of North Carolina.  When the Latitude and Longitude is reversed, everything is OK. 

``` c#
var France = new Coordinates(latitude, longitude);
```

**Comment by linvi** [comment]
Hello,

This is an error in the documentation. Could you please point me to the issue of the doc please?

Thanks,
Linvi

**Comment by linvi** [comment]
Fixed and thanks for the feedback.
