### ISSUE TITLE
Issue on opening the project in 2015

### ISSUE THREAD

**Issue by prasadraja07** [linvi/tweetinvi#685]
Hi,

I am trying to open the project in VS2015.. THe library are not loading properly..
let us know, how can we solve the issue..

Try to install nuget package manager...
Install-Package TweetinviAPI -Version 3.0.0.0

Check the attached image for the reference

![capture1](https://user-images.githubusercontent.com/2306153/38196618-ba6aa560-368c-11e8-967e-1fc79c1a0eb6.JPG)
![capture2](https://user-images.githubusercontent.com/2306153/38196619-ba9379b8-368c-11e8-8284-46100e3aa4c4.JPG)

**Comment by linvi** [comment]
Tweetinvi no longer support version 4.5. You will have to target at least version 4.6.1.
