### ISSUE TITLE
Can't send the simplest tweet

### ISSUE THREAD

**Issue by wbdavis29** [linvi/tweetinvi#687]
I am new to tweetinvi and I'm having trouble getting the simplest example to work. My ultimate goal is to publish tweets from a desktop app on behalf of users. I defined the app in Twitter and have been assigned all the necessary tokens.

I modified Examplinvi.Winforms to use the Pin code method of authentication...

      // Create a new set of credentials for the application.
      var appCredentials = new TwitterCredentials("App's CONSUMER_KEY", "App's CONSUMER_SECRET); 
					// where these strings are replaced with the app's tokens

      // Init the authentication process and store the related `AuthenticationContext`.
      authContext = AuthFlow.InitAuthentication(appCredentials);   // authContext is public to the class

      // Go to the URL so that Twitter authenticates the user and gives him a PIN code.
      Process.Start(authContext.AuthorizationURL);

This part seems to work perfectly. I log in, authorize the app to use my personal twitter account and get a pin code. I added a TextBox to the example code's main form and a button to submit the pin code. Here is that function...

      private void SubmitButton_Click(object sender, EventArgs e)
      {
         // With this pin code it is now possible to get the credentials back from Twitter
         string pinCode = textBox1.Text;
      
         var userCredentials = AuthFlow.CreateCredentialsFromVerifierCode(pinCode, authContext);

         // Use the user credentials in your application
         Auth.SetCredentials(userCredentials);

         var user = User.GetAuthenticatedUser();

         textBox.Text = string.Format("You are now authenticated as {0}!", user);

*******NOTE: Everything seems to work up to this point. An examination of 'user' shows the proper credentials and user name. The problem is in the next line...

         var tweet = Tweet.PublishTweet("This is a test tweet.");
      }

The PublishTweet function returns null and does not result in the tweet being sent.
I can't find anything in the documentation to explain why this isn't working. Can you help??

UPDATE:  I stepped through the code to where the json query is built, and I manually copied it to my browser.   https://api.twitter.com/1.1/statuses/update.json?status=This%20is%20a%20test%20tweet.&tweet_mode=extended
It returned the message "Bad Authentication Data".  But I'm not sure why.

Thanks...

**Comment by StephenMP** [comment]
Instead of using the Tweet static class to publish a tweet, try using the authenticated user instead.

`user.PublishTweet("This is a test tweet.");`

**Comment by tfarrag2000** [comment]
@StephenMP  

I face the same problem and unfortunately, your solution does not work for me.

**Comment by wbdavis29** [comment]
I believe I've found the problem...  I was getting mixed up with two different methods of authentication.

One fix in my code above would be to remove the line "var user = User.GetAuthenticatedUser();"  By having no parameter, null credentials are established, causing an exception. My code works when that line is removed.

As an alternative, you could change the code to this...

                var userCredentials = AuthFlow.CreateCredentialsFromVerifierCode(pinCode, twitterAuthContext);
                var user = User.GetAuthenticatedUser(userCredentials);

                // Use the user credentials in your application
                Auth.SetCredentials(userCredentials);

That establishes the correct credentials in the User class, and then  you can say "user.PublishTweet(...)" and it should work.
