### ISSUE TITLE
Tweets gets truncated?

### ISSUE THREAD

**Issue by Prabh2308** [linvi/tweetinvi#688]
I have an older version of Tweetinvi (0.9.13). When i am performing the tweet fetching operation all the tweets which are more than 140 characters gets truncated. Since i am in middle of a project i do not want to update. Kindly provide some solution.

**Comment by linvi** [comment]
Hello,

You will have to use the `TweetinviEvents` and append the `extended_mode=true` parameter.
This will return the Tweets differently. Unfortunately at this point Tweetinvi will not have the correct schema. You will therefore have to retrieve the json and then transform it to the expected object.

Unfortunately extended tweets is a big chunk of change and I cannot got back to old versions to make them all compatible.

Cheers,
Linvi
