### ISSUE TITLE
"The Read operation failed. see inner exception"

### ISSUE THREAD

**Issue by rotem156** [linvi/tweetinvi#69]
That's the exception i received inside the filteredStreamStoppedHandler event handler.

No idea what caused it, i do not have any more info, sorry.

**Comment by linvi** [comment]
Could you please share the StackTrace here, I cannot see anything in the post.

Cheers,
Linvi

**Comment by rotem156** [comment]
Sorry but i did not trap the exception in the version when this exception hit me, so you can ignore this.
