### ISSUE TITLE
Error when there's no results fetching trends for a place

### ISSUE THREAD

**Issue by JoshKeegan** [linvi/tweetinvi#690]
Hi Linvi,
Long time no see :)

There's a bug in the code for fetching trends for a place when it has no results.
repro:
```cs
int woeid = 20094386;
IPlaceTrends trends = Trends.GetTrendsAt(woeid);
```
Will throw an exception.

I've fixed it at https://github.com/JoshKeegan/tweetinvi/commit/c244b1d2f83223ac38f2458d9dd8a930badcee5f

Sorry it's not a pull request, I haven't been using the up-to-date version of Tweetinvi for a while and haven't had time to make sure I can swap back from my custom version.
Cheers,
Josh

**Comment by linvi** [comment]
Thanks for reporting it. I will have a look at it.
