### ISSUE TITLE
GetAvailableTrendLocations does not have all countries 

### ISSUE THREAD

**Issue by mmshahshahani** [linvi/tweetinvi#692]
Hi
I want to list trends in some countries but GetAvailableTrendLocations does not have all countries . What should I do ?

And when I use GetClosestTrendLocations(35.77,51.42) for Iran,Tehran it returns Kuwait

I used Trends.GetTrendsAt(woeid of tehran) , But it returns null !!!

**Comment by linvi** [comment]
Hello,

Unfortunately I cannot really say what Twitter is supposed to return for such regions.
I would advise that you speak directly with them on twittercommunity.com. 

They will be able to answer your question in more details. Tweetinvi is only returning what the api is sending as a response.

Cheers,
Linvi
