### ISSUE TITLE
Outdated link in the wiki "Upload" page

### ISSUE THREAD

**Issue by matteocontrini** [linvi/tweetinvi#695]
In [this](https://github.com/linvi/tweetinvi/wiki/Upload) wiki page, the "visit Twitter upload documentation" link should probably be updated to this one:

`https://developer.twitter.com/en/docs/media/upload-media/uploading-media/media-best-practices`

The current link redirects to the API index.
This actually applies for all the links at the bottom of that page ("References").

**Comment by linvi** [comment]
Hello,

Thank you for reporting this. The wiki is open for anyone to improve.
I am currently working to make sure that the new version of the `Activity Stream` is released by Tweetinvi before the 19th of June. 

So if you can take the time to improve it, I would be very grateful.

Thanks,
Linvi

**Comment by matteocontrini** [comment]
>The wiki is open for anyone to improve.

I'm not seeing the edit link on the wiki pages. I guess you should [adjust permissions](https://help.github.com/articles/changing-access-permissions-for-wikis/).

**Comment by marknoble** [comment]
Can confirm there is no edit link and only user @linvi has ever [revised this page](https://github.com/linvi/tweetinvi/wiki/Upload/_history).

**Comment by linvi** [comment]
Thank you both for getting back on the doc. I have updated the links accordingly :)

**Comment by marknoble** [comment]
@linvi Were you able to resolve the permissions issues so others can submit Wiki changes?

**Comment by linvi** [comment]
No. The new documentation should be done via pull requests as Tweetinvi doc is now generated via sphinx and exposed here:  https://linvi.github.io/tweetinvi/dist/index.html.

I don't want to encourage users modifying the old doc.
