### ISSUE TITLE
 User.GetUsersFromIds is not working anymore

### ISSUE THREAD

**Issue by MonsterMMORPG** [linvi/tweetinvi#696]
I have created a new project
Installed tweetinvi as a nuget package

Here a very simple application code
And ` User.GetUsersFromIds` returns nothing

But this one works `User.GetUserFromId`

```
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            authUser();
            RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackAndAwait;
            var authenticatedUser = User.GetAuthenticatedUser();

            var friendIds = User.GetFriendIds(authenticatedUser.ScreenName, 99).ToList();

            var vrFr = User.GetUsersFromIds(friendIds.GetRange(0, 99));//does not work
            var cc = User.GetUserFromId(friendIds.First());//works
        }
```

![image](https://user-images.githubusercontent.com/4149474/39082897-3a0abba4-4563-11e8-8c9b-36751fb49c90.png)

**Comment by linvi** [comment]
Thanks for reporting this. It definitely looks like a bug that I will investigate.

Cheers,
Linvi

**Comment by linvi** [comment]
Hello,

I have tested it and everything works as expected. I do not know what you `.GetRange()` function is doing exactly but if you use `.Take(100)` from Linq everything works as expected.

Cheers,
Linvi
