### ISSUE TITLE
Ensuring isolation across multiple  accounts when performing queries on them?

### ISSUE THREAD

**Issue by svncsvr** [linvi/tweetinvi#698]
I am using tweetinvi to authorize and performs some queries on various accounts of our customers.
Naturally I have to take great care to make sure someone's tweets will never appear in another user's timeline.
I want to briefly explain our development stack and login flow so and hopefully get your thoughts on the security concerns of the design.
Application is being developed using aspnet core mvc 2.0, endpoint methods are defined as async methods in the controllers, loggedin users account is persisted locally, We didn't want to authenticate current thread using

> Auth.SetCredentials();

or the application using 

> Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

because pools threads are shared and we were looking ways to keep the authentication context/scope as narrow as possible so instead, authenticated user is created every time It is needed as 

>  User.GetAuthenticatedUser(new TwitterCredentials(token.AppKey, token.AppSecret, token.Token, token.TokenSecret));

to be able to reduce the number of calls to twitter from tweetinvi internally I also cache the IAuthenticatedUser in a dictionary with profile id set as key.This dictionary is growing in size when new users are authenticating.

Since there are async controller methods and the application deals with numerous accounts concurrently we chose this approach.
If you could share your thoughts and ideas for making sure the accounts isolation on multi-threaded environments I would greatly appreciate.

**Comment by linvi** [comment]
Hello,

As you have probably noticed, I think this concept of 1 authentication per thread is quite problematic and it would probably be one of the design decision that I would consider to change if I had to redo the library from scratch.

As per your question, there are multiple strategies to achieve what you are trying to do.
I assume that at the moment you are then using the `authenticatedUser.ExecuteAuthenticatedUserOperation`?

I think the solution of using a cache for the `AuthenticatedUser` is a good idea in itself specially in an `async` environment like yours.

Another solution could also be to use the `Auth.ExecuteOperationWithCredentials`.

Cheers,
Linvi
