### ISSUE TITLE
Unable to publish with image if tweet contains a URL

### ISSUE THREAD

**Issue by tbduggan** [linvi/tweetinvi#7]
I have an image to tweet and the tweet text contains a URL.  
I shorten the url using google url shortener before I add it to the tweet text.  
The total length of the tweet text with the shortened URL in it is 131.  
Tried both PublishTweetWithImage and publish with optional paramters  (Medias) both fail to publish.

If I simply remove the URL from the tweet text, the tweet succeeds and the image is published.
If I remove the image and publish just the text with the URL, the tweet succeeds.

It is only when a URL exists in the text of the tweet AND you try to publish with image that the tweet fails.

Note: failure is always indicated in the returned ITweet by:
'((Tweetinvi.Logic.Tweet)response).PublishedTweetLength' threw an exception of type 'System.InvalidOperationException'

Note also that I use TweetLength to verify that the tweet text is 131 just prior to the publish operation.  IOW: the url has already been shortened and the total text including the shortened URL is 131

**Comment by linvi** [comment]
Hi.

Thanks for reporting this issue. 
Could you share your code please. 

Also let me know which version of tweetinvi you are using.

Linvi

**Comment by tbduggan** [comment]
Version 0.9.9.1

Did a little more investigation - it actually works if the tweet text length is under 118.

            // test
            byte[] image = System.IO.File.ReadAllBytes(@"C:\temp\testTweetImage.jpg");
            string text = "abcdefghijklmnopqrstuvwxy abcdefghijklmnopqrstuvwxy abcdefghijklmnopqrstuvwxy abcdefghijklmop" + "http://bit.ly/tinyurlwiki";
            int tl = text.TweetLength();
            var tweet = Tweet.PublishTweetWithImage(text, image);


play around by adding/subtracting characters to the last set of alphabet chars to see this succeed and fail.

**Comment by linvi** [comment]
Hi this is not the correct way to calculate the size with media. Please do the following:

``` c#
byte[] image = System.IO.File.ReadAllBytes(@"C:\temp\testTweetImage.jpg");
string text = "abcdefghijklmnopqrstuvwxy abcdefghijklmnopqrstuvwxy abcdefghijklmnopqrstuvwxy abcdefghijklmop" + "http://bit.ly/tinyurlwiki";

var publishParameter = new PublishTweetParameters(text)
{
    MediaBinaries = { image }
};

var tl = Tweet.Length(publishParameter); // returns 141
```

I will try to improve this in future releases.

**Comment by linvi** [comment]
You can find the work item [here](https://tweetinvi.codeplex.com/workitem/2633).
