### ISSUE TITLE
Urls and how to show on web as thumbnail

### ISSUE THREAD

**Issue by dyardyGIT** [linvi/tweetinvi#701]
1) If I use the standard twitter widget, it nicely shows links or urls as thumbnails of the referenced site in my timeline.  I believe these are twitter cards.  Is there any way to show these?

2) extended data is not available

I am using the following - 
```
            TweetinviConfig.CurrentThreadSettings.TweetMode = TweetMode.Extended;
            TweetinviConfig.ApplicationSettings.TweetMode = TweetMode.Extended;

            var userIdentifier = new UserIdentifier("<redacted>");
            var params1 = new UserTimelineParameters();
            params1.IncludeEntities = true;                       
            params1.MaximumNumberOfTweetsToRetrieve = numberToShow;

            var tweets = Timeline.GetUserTimeline(userIdentifier, params1)
                            .OrderByDescending(x => x.CreatedAt)
                            .ToList();
```
I get 8 tweets back from above however...
tweets[0].ExtendedTweet = null

I am not getting any extended tweet information (using latest Nuget v3 release)

thx

**Comment by linvi** [comment]
1. You can use `Tweet.GetOEmbedTweet(tweetid)`

2.

`ExtendedTweet` is used only for streaming purposes.
You should have access to all the information you need without using the `ExtendedTweet`

Cheers,
Linvi
