### ISSUE TITLE
Tweet Fulltext

### ISSUE THREAD

**Issue by robin1607** [linvi/tweetinvi#703]
Hi,

tweet.Text and tweet.Fulltext is showing the exactly same string. I found solutions with prefix and suffix wich doesnt worked for me.
I jut want to display the full tweettext in a textblock.
My function:

```
private void settweettoform()
        {
            tweet.Text = tweet.FullText.Substring(tweet.Prefix.Length);
            if (tweet.Text.Contains("https://"))
            {
                foreach (Match item in Regex.Matches(tweet.Text, @"(http|ftp|https):\/\/([\w\-_]+(?:(?:\.[\w\-_]+)+))([\w\-\.,@?^=%&amp;:/~\+#]*[\w\-\@?^=%&amp;/~\+#])?"))
                {
                    listBox.Items.Add(item);
                }
                textBlock.Text = tweet.Text;     
                
            } else
            {
                textBlock.Text = tweet.Text;
            }

            if(tweet.Entities.Medias.Count > 0)
            {
                image.Source = new BitmapImage(new Uri(tweet.Entities.Medias[0].MediaURL));
                actualimage = 0;
            }
            lblfavs.Content = tweet.FavoriteCount;
            lbluser.Content = "Nutzer: " + tweet.CreatedBy.Name;
        }
```

**Comment by linvi** [comment]
Hello,

FullText and Text can be different in some scenario. The logic behind the scene of Twitter is changing so, this decision are  not being performed by Tweetinvi but by Twitter as per the json they return to the application.

Now I am not sure what you are trying to do but `FullText` is in theory what you would like to show in your textblock.

Cheers,
Linvi

**Comment by robin1607** [comment]
The retweets often end up with '...' and the fulltext is here exactly the same as text.

**Comment by linvi** [comment]
I will verify that as soon as I have time. In the meantime could you share the id of a tweet that allow you to reproduce this problem. 

Thanks
Linvi

**Comment by robin1607** [comment]
Here is a example ID: 995980604016611329
But you can use almost all tweets from this account.

**Comment by linvi** [comment]
Hello,

Thank you for the feedback and I looked into the tweet 995980604016611329 and everything looks good to me.

FullText and Text have the same value because they do not need to be different in this scenario.
FullText is different than Text in various scenarios where the Text is longer than 140 characters.

Let me know if this answers your question.
