### ISSUE TITLE
Exclude retweets and replies

### ISSUE THREAD

**Issue by basslagter** [linvi/tweetinvi#709]
I am using `Search.SearchTweets` and want to exclude retweets and replies from the results. Tried using several option with the SearchTweetsParameters object but can't seem to get it working. Also tried adding "-filter:replies" or "exclude:retweets" in the query itself but no luck either. That results in an empty set which seems like a bug to me. Any help appreciated.

**Comment by Scobiform** [comment]
Just check for args.Tweet.IsRetweet == false and do something with it...

**Comment by basslagter** [comment]
@Scobiform thanks for the response. This is what I ended up doing but I thought there might be some kind of option to leave the filtering to the lib itself. But I guess not.

**Comment by linvi** [comment]
Hello,

Unfortunately, only the [premium](https://developer.twitter.com/en/docs/tweets/search/overview/premium) search api allow you to do that. You will need to pay to access this api and the you can use the CustomRequestParameters to use reach the API via Tweetinvi.

Cheers,
Linvi
