### ISSUE TITLE
GetUserTimeline Stopped on 5/24

### ISSUE THREAD

**Issue by carlor12** [linvi/tweetinvi#716]
I have some legacy code that stopped pulling new tweets older than 5/24. I'm using tweetinvi 1.0. do I need to upgrade? What's the issue?

Thanks,

Carey

**Comment by linvi** [comment]
Hello,

I am not sure what is the problem but I am no longer supporting 1.0.
There are too many changes happening with the Twitter API that I cannot support versions that are that old.

I would suggest that you upgrade to the latest. This will involve a lot of changes but Twitter will again make breaking changes in August 2018. Tweetinvi 4.0 and 5.0 will support these breaking changes so you will have to upgrade in the future.

Cheers,
Linvi

**Comment by carlor12** [comment]
Actually, the problem was different than  I thought. The Tweet about Id was
coming through as text on some items. I'll upgrade, but any Idea what that
is?

**Comment by linvi** [comment]
Could you be more precise. Could you share the `json` that you are receiving?
