### ISSUE TITLE
GetCredentialsRateLimits not effect with fuction FollowUser

### ISSUE THREAD

**Issue by khang0001** [linvi/tweetinvi#719]
I use GetCredentialsRateLimits to get limit my account, when I use function FollowUser, but I check my result of GetCredentialsRateLimits, not anything say I use FollowUser

This is my code

var cer = Auth.SetUserCredentials("111", "222", "3333", "444");
Tweetinvi.User.FollowUser("abc");
var rateLimits = RateLimit.GetCredentialsRateLimits(cer);

This is my all result of rateLimits 
![untitled](https://user-images.githubusercontent.com/20863676/41447658-71f36988-7080-11e8-84e4-c4c4aa923b32.png)

**Comment by MayakoLyyn** [comment]
Hi @khang0001 

Following an user is restricted by special rules that you can find here: https://help.twitter.com/en/rules-and-policies/twitter-limits. e.g.: you have to limit your app to a maximum of 1000 followings per day. 

For reference:

![image](https://user-images.githubusercontent.com/3751959/41770795-80d6873a-7613-11e8-8267-0c25eb9a0ba9.png)

**Comment by linvi** [comment]
@MayakoLyyn is correct, some endpoints do not use the same rate limit logic. 
Twitter does not provide any endpoint to access these information so you will have to handle them on your own to respect the rules specified in their documentation.

Cheers,
Linvi
