### ISSUE TITLE
V2.2 tweet information not correct

### ISSUE THREAD

**Issue by ronaldod** [linvi/tweetinvi#723]
I had to downgrade from v3.0.0.0 to v2.2.0.0. I noticed there is a problem in the tweet information. Most tweets are not showing the media info (tweet.Media.Count from the timeline) (v2.1.0.0) Checked 100 and just one had 1 media. In v3.0.0.0 it showed and successful  indexed 80. Same goes for the hashtag info.
A way to fix this ?

**Comment by linvi** [comment]
Hello,

Thank you (again ;) for your report. 

I am not sure I do understand the problem. Is there a problem in version 2.1 or version 3.0?

- Could you please share your code?
- Could you give me the user id for which you can reproduce the issue?

Thanks,
Linvi

**Comment by linvi** [comment]
Hello, please again share the information that I have requested.

Thanks
