### ISSUE TITLE
use emoji in tweet

### ISSUE THREAD

**Issue by khang0001** [linvi/tweetinvi#725]
Hi, I use tweetinvi very well, But I want public my comment with emoji, how can I do that. I already search in google but not seen any topic about this.

**Comment by ronaldod** [comment]
Take a look here: [http://www.unicode.org/Public/emoji/11.0/](url)

**Comment by khang0001** [comment]
When I use unicode to add reply, as : \U0001F697 \U0001F695 but not convert to emoji. It show string. How can I fix it?
