### ISSUE TITLE
Reading feed frm #tag

### ISSUE THREAD

**Issue by pkhussain** [linvi/tweetinvi#734]
Hi,
 This is my first try, can any one please tell me if it is possible to read any given hashtag using this library.
  hashtags can be in English or Chinese or Arabic languages.
 Will there be any restrictions to access all the tweets from any hashtags (public or private security)?

Thanks

**Comment by JoshKeegan** [comment]
You can use searches to find Tweets containing a hashtag. See https://github.com/linvi/tweetinvi/wiki/Searches  

The public search API is limited to approximately 7 days of results. Tweet privacy is respected by the API so you won't get private Tweets in the results unless the account you're running the search from can see them.
