### ISSUE TITLE
Image doesn't get uploaded with Upload.UploadBinary

### ISSUE THREAD

**Issue by mooningnow** [linvi/tweetinvi#736]
![mediatweetdoesn tgetpublished](https://user-images.githubusercontent.com/38512190/42979225-23bbeeb8-8b9f-11e8-8ef4-6bbae6e82add.PNG)

Please find attached. The media properties remains null after the upload and the below error is thrown when tried to publish the tweet.

The tweet cannot be published as some of the medias could not be published!

I would highly appreciate any quick guidance. thank you!

**Comment by ronaldod** [comment]
I use the next for uploading media. Just remember only one picture is working at the moment (bug).

```
`                            var image = File.ReadAllBytes(Location + FileName);
                            var media = Upload.UploadBinary(image); //is for 3.0.0.0 Removed the if statement as this version only can post one picture (bug).
                                                                    //var media = Upload.UploadImage(image); //is for 2.1.0.0
                            if (media == null || media.MediaId == null || !media.HasBeenUploaded)
                            {
                                throw new OperationCanceledException("The tweet cannot be published as some of the medias could not be published!");
                            }

                            var tweet = Tweet.PublishTweet(TweetText, new PublishTweetOptionalParameters
                            {
                                Medias = { media }//MediaList
                            });`
```

**Comment by mooningnow** [comment]
Thank you for the response. It worked for one image.

**Comment by CraigMuckleston** [comment]
I'm getting the same error (still) using v4.0.2

  var media = Upload.UploadBinary(File.ReadAllBytes(filePath));

media.HasBeenUploaded is always false. I have checked my file and I can see the bytes[] are there
