### ISSUE TITLE
tweetinvi 4.0 upload video and waitformedia is giving a exception

### ISSUE THREAD

**Issue by ronaldod** [linvi/tweetinvi#738]
Upload.WaitForMEdiaToBecomeAvailable(media); Gives the next exception : 

System.InvalidOperationException
  HResult=0x80131509
  Message=Upload STATUS can only be invoked on uploads with processing metadata. Set the `media_category` to `tweet_video` to solve this isue.
  Source=Tweetinvi.Controllers

using : tweetinvi 4.0

The problem is that this error is not constant. it happens once in the 10 posts.

**Comment by ronaldod** [comment]
Problem found. Twitter was causing it.

**Comment by linvi** [comment]
Hi @ronaldod,

Could you share more information so that I can answer questions of other developers if they encounter the same issue?

Thanks,
Linvi

**Comment by ronaldod** [comment]
pve :)  Found out one of the accounts needed a phone verification.
