### ISSUE TITLE
Tweets longer than ~140 characters have a truncated FullText value.

### ISSUE THREAD

**Issue by NibblyPig** [linvi/tweetinvi#740]
When performing a search, `Search.SearchTweets("xxx");`, both Text and FullText are the same if the tweet is longer than ~140 characters (both have a length of 148). They are truncated and end in '...'

The default TweetMode is Extended, I have checked it is set, but either the twitter API isn't behaving, or the flag is not being set correctly. The flag ismentioned here https://developer.twitter.com/en/docs/tweets/tweet-updates

**Comment by linvi** [comment]
Please provide the Tweet id so that I can further assist with this issue.
Tweets of length > 140 have been tested regularly and have been working properly for a while.

Thanks,

**Comment by NibblyPig** [comment]
Looks like it might be an issue with retweets

Search.SearchTweets("Deal with Mexico is coming along nicely. Autoworkers");

```
matchingTweets.First().FullText
"RT @realDonaldTrump: Deal with Mexico is coming along nicely. Autoworkers and farmers must be taken care of or there will be no deal. New P…"
```

**Comment by JoshKeegan** [comment]
In short:
Twitter returns the truncated text for retweets. If the retweet is also returned in the API call (off the top of my head, I think all REST calls do this but the streaming API doesn't), you can access the non-truncated version via the attached `RetweetedTweet` object.

Long version:

Finding a truncated retweet:
```cs
var searchParameter = Search.CreateTweetSearchParameter("b");
searchParameter.TweetSearchType = TweetSearchType.RetweetsOnly;

var tweets = Search.SearchTweets(searchParameter);
foreach (ITweet t in tweets)
{
	Console.WriteLine(t.Text);

	if (t.Truncated || t.FullText != t.Text || t.FullText.EndsWith("…"))
	{
		Console.WriteLine("boo!");
	}
}
```
Example Tweet ID 1054056220246466560

Viewing its raw JSON from Twitter:
![image](https://user-images.githubusercontent.com/1682204/47270092-82a08480-d55e-11e8-8f48-80894898f354.png)

You can still access the non-truncated text in the `retweeted_status` property:
![image](https://user-images.githubusercontent.com/1682204/47270100-a1068000-d55e-11e8-86b0-d265758641a1.png)
In Tweetinvi, this is available as the `RetweetedTweet` property on an `ITweet`.

**Comment by linvi** [comment]
Verified, this is what Twitter REST API and there is nothing we can do about this.
