### ISSUE TITLE
dotnet add package installs version 8.0.0.2 of Tweetinvi?

### ISSUE THREAD

**Issue by rgwood** [linvi/tweetinvi#741]
Hi,

I noticed something odd when migrating a .NET Framework project to .NET Core. If I install Tweetinvi without specifying the version (using `dotnet add package TweetinviAPI`) I end up with this in my project file:

`<PackageReference Include="TweetinviAPI" Version="8.0.0.2" />`

That 8.0.0.2 version is way beyond [the 3.0.0 version listed on Nuget](https://www.nuget.org/packages/TweetinviAPI/), and it doesn't work. Very mysterious! Attempts to import it with `using Tweetinvi;` fail:

`error CS0246: The type or namespace name 'Tweetinvi' could not be found (are you missing a using directive or an assembly reference?)`

## Workaround

Just specify the version: `dotnet add package TweetinviAPI -v 3.0.0`

## Steps to reproduce

```
dotnet new console -n TweetinviRepro
cd TweetinviRepro
dotnet add package TweetinviAPI
```

I'm using .NET Core version 2.1.302 on MacOS 10.13.6.

Thanks for maintaining Tweetinvi! It's a great project.

**Comment by linvi** [comment]
Hello,

Thank you for your feedback. I have been able to reproduce the issue and contacted the nuget team to help me solve this issue.

Thanks,
Linvi

**Comment by rgwood** [comment]
Looks like this has been resolved, thanks.
