### ISSUE TITLE
Message.GetLatestMessages is returning Null suddenly???

### ISSUE THREAD

**Issue by ahmad-atallah** [linvi/tweetinvi#746]
I'm doing a very simple testing on the new Tweetinvi, and it was working just fine, then suddenly `Message.GetLatestMessages` kept returning null!!!

Okay, so after I started to write this question I said let me try it one more time and it worked??? without changing anything in the code?

Any idea what's causing this behavior??

The code I was trying:
```
Auth.SetUserCredentials("111", "222",
            "333", "444");

        var authenticatedUser = Tweetinvi.User.GetAuthenticatedUser();

        var latestMessage = Message.GetLatestMessages(3, out cursor);
        List<Tweetinvi.Models.IMessage> AllDMS = latestMessage.ToList();

        while (cursor != null)
        {
            var latestMessagesParameters = new GetMessagesParameters()
            {
                Count = 3,
                Cursor = cursor
            };

            AllDMS.AddRange(Message.GetLatestMessages(latestMessagesParameters, out cursor).ToList());
        }
        Response.Write(JsonConvert.SerializeObject(AllDMS, Formatting.None));

```

**Comment by linvi** [comment]
Could it be because of the rate limits?

**Comment by ahmad-atallah** [comment]
@linvi oh you're right, it's definitely the rate limits..
I just saw it now, it's 

> Requests / 15-min window (user auth): 15/user

Does that mean every 15 minutes I can make 15 requests each request is maximum 50 DM??

**Comment by linvi** [comment]
I have to look more into it but this might be the new limit yes.

But this also mean that it supports 750 messages every 15 minutes which should be enough for most cases.
