### ISSUE TITLE
Webhooks Guide for .net 4.6.1

### ISSUE THREAD

**Issue by MattC-IPayYou** [linvi/tweetinvi#747]
Hello Tweetinvi!
I see your webhook guide for aspnetcore, but I do not see a corresponding guide for aspnet for the .net framework (specifically we are using 4.6+.) The method used for aspnetcore will not work for regular aspnet. Any advice?

**Comment by MattC-IPayYou** [comment]
@eaba We have a series of services all on webapi on .net 4.6.1.  I don't see any appbuilder in the startup pipeline for this. Am I missing something?

**Comment by linvi** [comment]
I am coming back from holiday this week I will send you more info soon.

**Comment by awisey** [comment]
is there a update on the support for 4.6.1 with regard to webhooks? A example would be great.
