### ISSUE TITLE
Can I receive tweet's replies by stream?

### ISSUE THREAD

**Issue by mastfreaky** [linvi/tweetinvi#748]

**Comment by linvi** [comment]
I am not sure I will verify.

**Comment by JoshKeegan** [comment]
This option appears to have been deprecated by Twitter: https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters.html

**Comment by linvi** [comment]
Yes looks like all of this has been deprecated unfortunately.
