### ISSUE TITLE
URGENT:: Auth.SetUserCredentials is throwing an exception??!

### ISSUE THREAD

**Issue by ahmad-atallah** [linvi/tweetinvi#749]
I have an application that is working as a Windows Service every few minutes to check Twitter DMs.
Anyway, everything is working if I called the function through the ASP .Net **web application** but when I call the functions in the scheduler app (windows service) its throwing the exception as the following:

```

        private static Tweetinvi.Models.IAuthenticatedUser InitializeTweetinvi()
        {
//This line is throwing the exception:
            Auth.SetUserCredentials(consumerKey, consumerSecret, accessToken, accessTokenSecret); 
            var authenticatedUser = Tweetinvi.User.GetAuthenticatedUser();

            return authenticatedUser;
        }
        
```
The error is: _The type initializer for 'Tweetinvi.Auth' threw an exception._

**Comment by ahmad-atallah** [comment]
I realized, when I run the functions using the local mode it works fine, when I publish the website online it wont work :/

@linvi is it known error? any idea?

**Comment by linvi** [comment]
Verify the timezone and time of the machine where the webserver is running.

**Comment by ahmad-atallah** [comment]
@linvi I checked it, it's the same settings as the local machine im working on, also I turned off auto set time zone, but same result?

What else I could do?!

**Comment by ahmad-atallah** [comment]
@linvi  I think I'm the stupidest person in the world..
All this time I was copying the files from my local machine and excluding the .config files :/

So sorry for the hustle..
