### ISSUE TITLE
Enabled Models to be Serializable

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#75]
Users should be able to call a `.ToJson()`  method that will retrieve a json string containing all the information of a specific model

**Comment by linvi** [comment]
List of serializable objects at the current time : 

* Tweet
* User
* Message
* TwitterList
* PlaceTrends

**Comment by linvi** [comment]
List of serializable objects at the current time : 

* Tweet
* User
* Message
* TwitterList
* PlaceTrends
* SavedSearch
* OEmbedTweet

**Comment by linvi** [comment]
! Need to make sure we provide detailed error message if something goes wrong.

**Comment by linvi** [comment]
Added documentation.

**Comment by haseeb1431** [comment]
We need to keep it in consideration that how we write new code in the repository because we want to support both version at the same time. 

http://stackoverflow.com/questions/39169231/isgenerictype-missing-from-net-core
