### ISSUE TITLE
Webhook MessageReceived event throws null reference exception

### ISSUE THREAD

**Issue by bakycar** [linvi/tweetinvi#751]
When registering the Activity stream all events work fine except the MessageReceived event 
![untitled](https://user-images.githubusercontent.com/19710542/44337264-5d1dce80-a47a-11e8-8577-1a31a048d666.png) which throws such an exception at all times.

**Comment by haroonis** [comment]
Hi @bakycar - I was unable to get the code working to evne this level using the tutorial - is there a simple sample code to get the http server set up and to subscribe to the tweets from one user for example?

**Comment by linvi** [comment]
I am coming back from holiday this week i will look into this and définirait l'opprobre the incomplete tutorial.

**Comment by bakycar** [comment]
I don't think there is a problem with the tutorial, as I said I've gotten everything up and running except for receiving the received messages, its actually throwing an exception and I can try fixing it if You'd accept my merge request. 

Regarding the tutorial all that might be missing is which library API to use to send messages or are the old Tweet.PublishTweet/Message.PublishMessage code which used to work and just update the library to the latest version? I had two separate systems for the replying so I didn't try updating the replying one yet.

**Comment by haroonis** [comment]
Thanks linvi that would be great. I tried modifying the Startup.cs example file however am not clear on what the BEARER_TOKEN should be? The other credentials work and I'm able to send / make my own tweets (the simple Hello World test).

**Comment by haroonis** [comment]
> I am coming back from holiday this week i will look into this and définirait l'opprobre the incomplete tutorial.

Hi linvi - do you have a chance to look at this - I'm unable to follow the guide at hthe moment, e.g. not sure BEARER_TOKEN value :(

**Comment by linvi** [comment]
The following PR is solving the problem https://github.com/linvi/tweetinvi/pull/804.

@haroonis the bearerToken can be retrieved automatically by Tweetinvi.

``` c#
Auth.SetApplicationOnlyCredentials(consumerOnlyCredentials);
```

In Tweetinvi, a new method will be available that will only retrieve the bearerToken.

``` c#
// Tweetinvi 5.0
if (consumerOnlyCredentials.ApplicationOnlyBearerToken == null)
{
    Auth.InitializeApplicationOnlyCredentials(consumerOnlyCredentials);
}
```
