### ISSUE TITLE
UserStream not work...

### ISSUE THREAD

**Issue by DeaDCaTsSociety** [linvi/tweetinvi#752]
After changing the Twitter API, the FilteredStream works fine.
but the UserStream close immediately after opening the stream. 
If we can not use the function, it seems to be removed from the wiki and code.

Log: 
userStream StreamStarted
userStream StreamResumed
userStream Stoped
userStream StreamStarted
userStream StreamResumed
userStream Stoped
.....

**Comment by DeaDCaTsSociety** [comment]
Code: 
``
private void StartUserStream()
        {
            var credential = Authentication.Instance.credential;
            userStream = Stream.CreateUserStream(credential);
            userStream.TweetCreatedByAnyoneButMe += UserStream_TweetCreatedByAnyoneButMe;
            userStream.UnmanagedEventReceived += Stream_UnmanagedEventReceived;
            userStream.DisconnectMessageReceived += Stream_DisconnectMessageReceived;
            userStream.WarningFallingBehindDetected += (s, e) => Print("userStream WarningFallingBehindDetected", s, e);
            userStream.AccessRevoked += (s, e) => Print("userStream AccessRevoked", s, e);
            userStream.StreamPaused += (s, e) => Print("userStream StreamPaused", s, e);
            userStream.StreamResumed += (s, e) => Print("userStream StreamResumed", s, e);
            userStream.StreamStarted += (s, e) => Print("userStream StreamStarted", s, e);
            userStream.StreamStopped += UserStream_StreamStopped;
            userStream.LimitReached += (s, e) => Print("userStream LimitReached", s, e);
            userStream.StartStreamAsync();
        }

private void UserStream_StreamStopped(object sender, Tweetinvi.Events.StreamExceptionEventArgs e)
        {
            Console.WriteLine("User Stream Stoped");
            StartUserStream();
        }

private void Print(string eventName, object sender, EventArgs e)
        {
            Console.WriteLine(eventName);
        }
``

**Comment by JoshKeegan** [comment]
The User stream has been retired by Twitter: https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html  

Take a look at the release notes for Tweetinvi v4: https://github.com/linvi/tweetinvi/releases/tag/4.0
The section "Twitter Webhooks, Account Activity and UserStream" should help you migrate to the Webhooks new replacement.

**Comment by DeaDCaTsSociety** [comment]
Yes yes I know that API has been retired. but wiki page and code are still exist https://github.com/linvi/tweetinvi/wiki/User-Streams
https://github.com/linvi/tweetinvi/blob/master/Tweetinvi.Streams/UserStream.cs
I think it should be deleted .

**Comment by JoshKeegan** [comment]
Ok. At the time of the last release, the user stream was still live so it still needed to be in there. It should be deleted from the code in the next release.

**Comment by linvi** [comment]
Correct the `UserStream` code will be retired

**Comment by linvi** [comment]
Removed in next release.
