### ISSUE TITLE
Is Live Stream supported?

### ISSUE THREAD

**Issue by ahmad-atallah** [linvi/tweetinvi#753]
Is live stream supported in Tweetinvi? and by live stream I mean Live Video Stream?
As I understood, the new Twitter API have this feature.

Any help or explaining would be so much appreciated, as I couldn't find any real help even on Twitter Documentation.

**Comment by linvi** [comment]
Hello,

I am not sure where you heard of this, but I have not, neither have I found anything in the documentation.

Could you please link a reference to what you have found please.
At the moment there is no such support in Tweetinvi.

Additionally could you precise what you mean by `Live Video Stream`.

Thanks,
Linvi

**Comment by ahmad-atallah** [comment]
I got confused between Stream APIs with **Live video streaming**..
I found out there's no Twitter APIs available for this, so the answer for my question is no, at least not through twitter directly, it must be done through something called "_Periscope_"

 And, what I meant by Live Video Stream is stream a live video (either using a video file or from user cam).
Anyway, thank you @linvi for all the help!
