### ISSUE TITLE
no Cursor in authenticatedUser.GetLatestMessages ?

### ISSUE THREAD

**Issue by ahmad-atallah** [linvi/tweetinvi#754]
@linvi I noticed that I can't use "cursor" option when I do the following:

```
var authenticatedUser = Tweetinvi.User.GetAuthenticatedUser(appCreds);
authenticatedUser.GetLatestMessages(50, out cursor);  //Obviously, GetLatestMessages accepts only one parameter which is count

```
So, how I can use the cursor feature??

**Comment by linvi** [comment]
I have updated the documentation to include this example : 

https://github.com/linvi/tweetinvi/wiki/Messages#get-messages-with-cursor

Cheers,
Linvi

**Comment by ahmad-atallah** [comment]
@linvi  Something just show up yesterday, this line is causing an error!! any ideas??

`var latestDMs = Message.GetLatestMessages(50, out cursor).Where(x => x.SenderId != UserID);`
