### ISSUE TITLE
30 day | full archive search not working...

### ISSUE THREAD

**Issue by leonpotgieter** [linvi/tweetinvi#755]
Hi, my understanding from the Twitter documentation is that 30 and Full Archive endpoints are available for Premium Accounts...

I have a Premium/Paid Twitter account and am using the Premium tokens but can still only search back 7 days with Tweetinvi? Any advice?

**Comment by linvi** [comment]
I do not have access to paid account, so I have unfortunately never been able to try this api with premium. If you wish to share access I could do some tests and let you know.

Cheers,
Linvi

**Comment by leonpotgieter** [comment]
Thanks, I will do that...  could you pls let me have an email address so I could share the details privately?

**Comment by linvi** [comment]
Hi, you can contact me here : https://gitter.im/linvi

**Comment by JoshKeegan** [comment]
@leonpotgieter Were you trying to access the premium search via a [custom query](https://github.com/linvi/tweetinvi/wiki/Custom-Queries) or were you using the Search functionality built into Tweetinvi?

**Comment by leonpotgieter** [comment]
Hi, I was using the search functionality built into Tweetinvi.  My understanding is that a different endpoint is used for Premium/Full archive which it seems isn’t supported by Tweetinvi.

**Comment by JoshKeegan** [comment]
That's right. You should still be able to make use of Tweetinvi with the premium endpoints by using custom queries, as the format of the Tweet objects that get returned are the same(ish) as the standard API.

**Comment by linvi** [comment]
To close this question. Tweetinvi does not support premium api endpoints at the moment because I do not myself have access so such account.

Though as @JoshKeegan was mentioning you can use custom queries and DTO models to execute your queries via the [custom queries](https://github.com/linvi/tweetinvi/wiki/Custom-Queries).

**Comment by linvi** [comment]
Actually reopening as it can be a future feature of the library.
