### ISSUE TITLE
Using FilteredStream get 420 error constantly

### ISSUE THREAD

**Issue by MattC-IPayYou** [linvi/tweetinvi#759]
Hello Tweetinvi,
We are using FilteredStream to read tweets targetted to a given user since Twitter is dragging their feet on giving us the webhooks access.  We are interested in only a single user.  
We get a 420 error after the stream has been running for a while, and no amount of waiting will allow the stream to recover. We have tried the following:

1.) Long waits (in excess of 5 minutes between connection attempts)
2.) Keep using the same stream object when disconnections occur
3.) Use a different stream object for each connection attempt.

Additional Data:
We notice that we can make this happen pretty consistently when we make a change to our project and do a rebuild (~2 minutes), then refresh the page to start our service in the browser.  However, if we build then run iisreset, we do not have the issue.  We could live with this solution if we never experienced the degradation to 420 while we were running.

**Comment by linvi** [comment]
From Twitter documentation :

```
420 | Enhance Your Calm | Returned when an app is being rate limited for making too many requests.
```

I am not sure exactly what your app is doing but be aware of this one.

Cheers,
Linvi
