### ISSUE TITLE
How to get tweets with the twitter screen names?

### ISSUE THREAD

**Issue by mabbashm110** [linvi/tweetinvi#76]
Sorry am a newbie I know I am not doing something right here, need help

I have a textbox for searches **txtHash** it gets the tweets in the **lstTweets** but I also want the users to be returned for each tweet in a different list box **lstUsers**

At the moment it is returning the same name of users searched, I want the users of the tweets searched instead

This is my code

```javascript
private void btnGetTwtsUsers_Click(object sender, EventArgs e)
        {
            if (!string.IsNullOrEmpty(txtHash.Text.Trim()))
            {
                //List for Tweets using the txtHash Search box
                lstTweets.DataSource = Search.SearchTweets(txtHash.Text).ToList();
                //List for user screen names of each tweet in the lstTweets List box
                lstUsers.DataSource = Search.SearchUsers (txtHash.Text).ToList ();
            }
        }
```

**Comment by linvi** [comment]
Hi sorry for not replying earlier.
Please reopen if you still need help.

Linvi
