### ISSUE TITLE
.Net Stream Developing

### ISSUE THREAD

**Issue by fightlikeagirl** [linvi/tweetinvi#765]
Hello, you wrote that you are gonna develope Twitter Stream for .net in [here.](https://stackoverflow.com/questions/41453431/real-time-tweetinvi-streaming-in-web-api?rq=1) I was looking for it but couldn't find it Tweetinvi examples . I wonder if I miss a detail or page in Tweetinvi ? Did you develope, so where it is ? thank you very much

**Comment by sneiderV** [comment]
Hi, this can help you. It's [a tutorial](https://www.youtube.com/watch?v=e-lJm-bqyI0) that show, how to make an application using streaming.

**Comment by linvi** [comment]
Hello,

To be more precise please be aware that now there are FilteredStreams and User Webhooks.
Both have documentation.

Please read there :

* https://github.com/linvi/tweetinvi/wiki/Filtered-Streams
* https://github.com/linvi/tweetinvi/wiki/Webhooks

Cheers,
Linvi
