### ISSUE TITLE
Compatibility issue with .Net 4.6 

### ISSUE THREAD

**Issue by Nadeem-Saif** [linvi/tweetinvi#766]
I am working on .net 4.6 version project and I am unable to use Tweetiniv in project.
When I tried to install tweetiniv it gave me following error.
![image](https://user-images.githubusercontent.com/25687717/47284992-f4340d80-d606-11e8-8a34-c968d5ffc720.png)

**Comment by JoshKeegan** [comment]
Hi,
Tweetinvi is built targeting .NET Standard 1.4, which for .NET Framework projects means the minimum supported version is 4.6.1.

**Comment by Nadeem-Saif** [comment]
@JoshKeegan 
I am unable to install Tweetinvi can you tell me What needs to be done in order to get it installed.

**Comment by JoshKeegan** [comment]
Upgrade your project to .NET Framework 4.6.1 and reinstall the Tweetinvi nuget package.

**Comment by linvi** [comment]
As @JoshKeegan mentioned you need to upgrade to 4.6.1.
There are various reasons that do not allow the project to run on a lower version than 1.4.

I usually try to keep the project dependencies to the .NET Framework as low as possible.
