### ISSUE TITLE
TweetinviAPI.WebhooksPlugin

### ISSUE THREAD

**Issue by sewarts** [linvi/tweetinvi#773]
I am upgrading TweetInvi to the latest version in my ASP.NET webforms project that targets 4.6.2.

All has gone well however when I install TweetinviAPI.WebhooksPlugin via nuget I get the following error:

Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I can see no reference to System.Runtime, Version=4.2.0.0.

**Comment by remy-burney** [comment]
I'm also having lots of conflicts when trying to use Tweetinvi.
Is there aversion for 4.6 framework maybe ?

![image](https://user-images.githubusercontent.com/43974431/48321080-dd1b9500-e673-11e8-8e93-63a212549d42.png)

**Comment by awisey** [comment]
Hi got the same error a couple of days ago, all i did was do a binding redirect in the web.config like:
<dependentAssembly>
				<assemblyIdentity name="System.Runtime.Extensions" publicKeyToken="B03F5F7F11D50A3A" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.1.2.0" />
      </dependentAssembly>
			<dependentAssembly>
				<assemblyIdentity name="System.Runtime" publicKeyToken="B03F5F7F11D50A3A" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.1.2.0" />
			</dependentAssembly>

**Comment by JoshKeegan** [comment]
One for @linvi
The nuget package is for .NET Standard, but the Tweetinvi.Webhooks project targets .NET Core, so I'm confused :)

**Comment by JoshKeegan** [comment]
@awisey The .NET standard nuget package should work on both .NET Core & .NET Framework, so that's already done.

Sorry if I wasn't clear in my last comment, I just can't see the code for the nuget package as the code I looked at in master targets .NET Core.

**Comment by linvi** [comment]
@JoshKeegan The reason why this project is using .NET Core as opposed to .NET Standard, is because it has dependencies on `Microsoft.AspNetCore.All`.

This is also the reason why "plugins" were created in version 4.0.
Plugins allow developers to add features to Tweetinvi without having to have dependencies on some libraries that they do not want (in that case ASP.NET).

**Comment by linvi** [comment]
@remy-burney 

> I'm also having lots of conflicts when trying to use Tweetinvi.
> Is there aversion for 4.6 framework maybe ?

Tweetinvi 4.0 only supports .NET Framework 4.6.1 and above as it targets .NET Standards 1.4.
