### ISSUE TITLE
Empty Message returns error

### ISSUE THREAD

**Issue by kreativmaschine** [linvi/tweetinvi#774]
Hi *,

I get an exception "The text message of a tweet cannot be null or empty" by calling

`await TweetAsync.PublishTweet(Message, new PublishTweetOptionalParameters
                {
                    Medias = new List<IMedia> { media }
                });`

with an Message == null or string.empty and an eg Image as attachment. So, the exception is quite clear ;-) But i'm wondering because twitter itself allows tweeting images without message text.

I'm i wrong?

thanks.

**Comment by JoshKeegan** [comment]
Thanks.
I have confirmed that this is possible to do via the Twitter API, so we should make it possible via Tweetinvi :)

**Comment by kreativmaschine** [comment]
Cool!

BTW: Thank you for the good work. Really helped.

**Comment by linvi** [comment]
This is now merged into 5.0.
