### ISSUE TITLE
Add Image Description

### ISSUE THREAD

**Issue by awisey** [linvi/tweetinvi#775]
Is there a way to post a description at the bottom of the image using tweetinvi if the user has enabled it?

**Comment by JoshKeegan** [comment]
Hi,
I can't see anything in the Twitter docs on uploading media ([chunked](https://developer.twitter.com/en/docs/media/upload-media/uploading-media/chunked-media-upload) or [simple](https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-upload.html)) mentioning a description attribute, so it doesn't look like the media can have a description.

I think that anything in the Tweet would be above the image, so I don't think it's possible.

Do you have an example of a Tweet that does this?
Cheers,
Josh

**Comment by linvi** [comment]
Closing as no feedback.
