### ISSUE TITLE
Webhooks namespace/class collision

### ISSUE THREAD

**Issue by mitchcapper** [linvi/tweetinvi#778]
There is:
https://github.com/linvi/tweetinvi/blob/master/Tweetinvi/Webhooks.cs#L19
and 
https://github.com/linvi/tweetinvi/blob/master/Tweetinvi.Controllers/Webhooks/WebhookController.cs

Both of them are Tweetinvi.Webhooks.WebhookController.   While referencing Webhooks isn't an issue trying to extend or do reference the class  WebhookController is near impossible.

**Comment by linvi** [comment]
Thanks for the feedback, I will be thinking about it.
Picking the right namespaces actually take me a lot of thinking usually but I agree and this will be improved.

**Comment by linvi** [comment]
Done :)
