### ISSUE TITLE
Add note to User Stream wiki page that it is deprecated

### ISSUE THREAD

**Issue by mitchcapper** [linvi/tweetinvi#779]
Does it make sense to remove that class from the library as well? Users may try to use it and find nothing happens any more.
Wiki is not publicly editable so could not edit myself.

**Comment by JoshKeegan** [comment]
Removing this now ready for the next release would make sense. 
As of the last release, the User Stream was still active on Twitter so it needed to be in the code.

**Comment by linvi** [comment]
Marked UserStream wiki page as deprecated, removed it from direct quick access panel.

It can now be found at : https://github.com/linvi/tweetinvi/wiki/%5BDEPRECATED%5D-User-Streams
