### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by Muchomasquewebs** [linvi/tweetinvi#78]
Hi Linvi:

I have a c# applicattion that uses your library for sending massive tweets and three months ago my clients are experimenting 403 errors.

This is the error message:
"Error: 403, Forbidden - The request is understood, but it has been refused or access is not allowed. An accompanying error message will explain why. This code is used when requests are being denied due to update limits"

They have published tweets with random intervals of 15 to 30 minutes and not for all the day so the Twitter limits should not be consumed, right?

Thanks for your help
Best Regards!

**Comment by linvi** [comment]
Hi there,

The `TwitterException` class that you received should contain more information than simply this message. Would you please share the different information available in the `TwitterException`.

The Twitter limits are for sure not consumed, you can publish a loads of Tweets in a single day.
Get back to me with the info and I will probably be able to be of more help.

Cheers,
Linvi

**Comment by Muchomasquewebs** [comment]
Hi Linvi:

Thanks for the feedback.

The Twitter app is Restricted from performing write actions when I published I few tweets.

This is my timeline:
https://twitter.com/SorpresSorpres

Best Regards

**Comment by linvi** [comment]
Sorry for such late reply. Are you still experiencing this issue?
