### ISSUE TITLE
UserActivityStream unfollow event calls UserFollowed event without specifying it is unfollow

### ISSUE THREAD

**Issue by mitchcapper** [linvi/tweetinvi#780]
so an event like
```
  "follow_events": [
    {
      "type": "unfollow",
```
calls the UserFollowed event on the stream.  No problem there but there is no "type" option on the event args so one cannot tell a follow from an unfollow.   I can submit a PR adding a param to the event, I assume this is the best option? Otherwise to be more like the old user stream could add an unfollow event.

**Comment by linvi** [comment]
I think Twitter no longer provides the ability to listen to unfollow, but I will verify.

**Comment by linvi** [comment]
Sorry for my initial response, it was me not reading properly your comment.
I agree that this is a bug and it will be resolved in next release.

Thanks

**Comment by linvi** [comment]
This is now fixed.

Please note that I had to rename the event for the convention but you will now find the following 3 events ;

``` cs
/// <summary>
/// Current user is now following another user
/// </summary>
EventHandler<UserFollowedEventArgs> FollowedUser { get; set; }

/// <summary>
/// Current user has stopped following another user
/// </summary>
EventHandler<UserUnFollowedEventArgs> UnfollowedUser { get; set; }

/// <summary>
/// Current user has been followed by another user.
/// </summary>
EventHandler<UserFollowedEventArgs> FollowedByUser { get; set; }
```
