### ISSUE TITLE
Any way to log why Twitter follow fails? User.FollowUser

### ISSUE THREAD

**Issue by FurkanGozukara** [linvi/tweetinvi#782]
The function just returns false `User.FollowUser`

When i try from browser it works for the same failed user

So i would like to learn the reason

Authentication is properly made

**Comment by FurkanGozukara** [comment]
I have modified code to log myself

The application doesnt show this error at all

```
Forbidden - The request is understood, but it has been refused or access is not allowed. An accompanying error message will explain why. This code is used when requests are being denied due to update limits.
You are unable to follow more people at this time. Learn more <a href='http://support.twitter.com/articles/66885-i-can-t-follow-people-follow-limits'>here</a>.
```

**Comment by JoshKeegan** [comment]
This was resolved in gitter.

For anyone coming across this, see [Exception Handling](https://github.com/linvi/tweetinvi/wiki/Exception-Handling) in the wiki.
