### ISSUE TITLE
I have started getting Authentication credentials errors in V4

### ISSUE THREAD

**Issue by FurkanGozukara** [linvi/tweetinvi#783]
I have no idea why but seems like authentication is getting lost after some time running (last time application run 1 hour without any error. I didnt have any such problem in V3 and i didnt change any code)

The twitter response

`Unauthorized -  Authentication credentials were missing or incorrect.`

The uncaught error

![image](https://user-images.githubusercontent.com/19240467/49186073-9f598480-f374-11e8-8821-c5270bacaa2b.png)

**Comment by FurkanGozukara** [comment]
now i have more details

![image](https://user-images.githubusercontent.com/19240467/49245498-95db2580-f423-11e8-8bd1-45c73f55e4c4.png)

**Comment by FurkanGozukara** [comment]
Further debug

You can test yourself as well

![image](https://user-images.githubusercontent.com/19240467/49245957-cd969d00-f424-11e8-95e2-4335e0c7eec0.png)

**Comment by FurkanGozukara** [comment]
here test code to reproduce the error 

`var gg = User.GetUserFromId(136657696);`

**Comment by JoshKeegan** [comment]
Your second screenshot shows the requested user as having been suspended on Twitter. I've checked for user ID `136657696` and that appears to be correct.  
Can you post a repro for the original issue/your first screenshot?

**Comment by FurkanGozukara** [comment]
@JoshKeegan i am constantly getting errors i think some checks are broken in v4

i belive they are related to suspended accounts

i dont know how to reproduce first error i am catching uncaught errors application wide

here another one

```
11/29/2018 11:29:48 PM  Object reference not set to an instance of an object.

StackTrace:    at Tweetinvi.Credentials.TwitterAccessor.ExecuteQueryReturningContent(String query, HttpMethod method, HttpContent httpContent, Boolean forceThrow)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteGETQuery[T](String query, JsonConverter[] converters)
   at Tweetinvi.Controllers.Timeline.TimelineQueryExecutor.GetUserTimeline(IUserTimelineQueryParameters timelineParameters)
   at Tweetinvi.Controllers.Timeline.TimelineController.GetUserTimeline(IUserTimelineQueryParameters queryParameters)
   at Tweetinvi.Controllers.Timeline.TimelineController.GetUserTimeline(IUserIdentifier user, IUserTimelineParameters parameters)
   at Tweetinvi.Controllers.Timeline.TimelineController.GetUserTimeline(IUserIdentifier user, Int32 maximumNumberOfTweets)
   at Tweetinvi.Controllers.Timeline.TimelineController.GetUserTimeline(Int64 userId, Int32 maximumNumberOfTweets)
   at Tweetinvi.Timeline.GetUserTimeline(Int64 userId, Int32 maximumTweets)
   at ProjectTwitterV2.MainWindow.followAllFollowers(String srSomeoneElse, Boolean blSelfFollow) in C:\ProjectTwitterV2\ProjectTwitterV2\MainWindow.xaml.cs:line 873\r\n
```

**Comment by FurkanGozukara** [comment]
as far as i see this function causes error

@JoshKeegan 


```
        public string ExecuteQueryReturningContent(string query, HttpMethod method, HttpContent httpContent = null, bool forceThrow = false)
        {
            try
            {
                return ExecuteQuery(query, method, (ITwitterCredentials) null, httpContent).Text;
            }
            catch (TwitterException ex)
            {
                if (forceThrow)
                {
                    throw;
                }

                HandleQueryException(ex);
                return null;
            }
        }
```

**Comment by JoshKeegan** [comment]
I’ll try and reproduce it when I get a moment :)
Is this with Swallow Web Exceptions true or false?
Also, is this just from the latest NuGet package or a custom build?

**Comment by FurkanGozukara** [comment]
@JoshKeegan 

I didnt change this option how do i change?
`Is this with Swallow Web Exceptions true or false?`

This is nuget build. I just changed these parts
`Also, is this just from the latest NuGet package or a custom build?`


I will remove that custom error logging tomorrow as i have learned `ExceptionHandler.GetLastException();`

![image](https://user-images.githubusercontent.com/19240467/49255665-c6c85400-f43d-11e8-8487-f0e408a8323d.png)


![image](https://user-images.githubusercontent.com/19240467/49255683-d051bc00-f43d-11e8-8aee-af21d294b723.png)

![image](https://user-images.githubusercontent.com/19240467/49255720-e65f7c80-f43d-11e8-9828-6209c6686bbf.png)

**Comment by FurkanGozukara** [comment]
@JoshKeegan 

if an error happens it returns empty list or null as an object?
for example

`var friendIds = User.GetFriendIds(authenticatedUser.ScreenName, irHowMany);`

if an error happens inside GetFriendIds what would it return? it would return an `empty list` or `null `?

**Comment by JoshKeegan** [comment]
According to the [wiki](https://github.com/linvi/tweetinvi/wiki/Exception-Handling) the result will be `null` or `false` if the request failed, so an empty list should mean it ran successfully, but there were no results.
