### ISSUE TITLE
Duplicate URL Encoding - Breaking search function

### ISSUE THREAD

**Issue by roachadam** [linvi/tweetinvi#787]
I think I found a bug. When searching for a tweet via text, the url seems to be encoded twice, and thus is not finding results.

Fiddler:
![fiddler](https://i.imgur.com/SKfLddK.png)

As you can see the url encoding is '%2520' when it should be just '%20' %25 is the encoded version of '%' if I recall correctly.

Code:
![code](https://i.imgur.com/Q9QPyHP.png)

Attempting to search for this tweet here: https://twitter.com/Ebony_QT/status/1069590763401592832

Upon putting the same search in twitter directly, the result is fine. However code returns no tweets.

If I can I'll try to check the code to see where this is coming from, but maybe someone else that knows the project better can figure it out.

**Comment by roachadam** [comment]
This is a pretty huge bug, I have confirmed several times that this is the issue. If someone can point me in the direction of the web handling location (not the interfaces, I looked), I can take a deeper look at the issue.
Thanks

**Comment by JoshKeegan** [comment]
What version of Tweetinvi are you using? I thought this had been fixed.

**Comment by roachadam** [comment]
@JoshKeegan Version 4.0.0.0 installed from Nuget.

**Comment by JoshKeegan** [comment]
Thanks, i’ll look into it

**Comment by linvi** [comment]
@JoshKeegan did you look into it?

**Comment by JoshKeegan** [comment]
@linvi No, not yet.
