### ISSUE TITLE
New API request

### ISSUE THREAD

**Issue by jdahan91** [linvi/tweetinvi#789]
It would be appreciated to see in the Account class the [verify_credentials](https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials.html) api.

Edit: I just realised that _CreateCredentialsFromVerifierCodeAsync_ returns null if the pin code is invalid, so adding this api is optional.

**Comment by JoshKeegan** [comment]
I think this is the `User.GetAuthenticatedUser` function in Tweetinvi. It's just been named differently :)

**Comment by linvi** [comment]
Yes @JoshKeegan is correct on this one.

Closing
