### ISSUE TITLE
Backfill or Recover Data for Stream

### ISSUE THREAD

**Issue by fightlikeagirl** [linvi/tweetinvi#792]
Hello, I read the docs but I could not understand that Is there a way If I can get the datas I missed while filter stream has quit or stopped ?

**Comment by linvi** [comment]
No there is no such feature.
The only thing that Twitter provides is that if your stream is connected and you are not processing the messages fast enough it will keep some of them for you on the server up to a certain limit.

**Comment by fightlikeagirl** [comment]
Thank you so much @linvi
