### ISSUE TITLE
Tweets longer than 280 characters fail silently.

### ISSUE THREAD

**Issue by RiotInferno** [linvi/tweetinvi#793]
If you call Tweet.PublishTweet(...) with a string longer than 280 characters, the return value is null and no tweet appears on the timeline. The library fails silently and provides no feedback or exceptions on why the tweet wasn't sent.

**Comment by linvi** [comment]
Please read more about exception handling here : 

https://github.com/linvi/tweetinvi/wiki/Exception-Handling
