### ISSUE TITLE
Wrong casing serializing tweet

### ISSUE THREAD

**Issue by osmay88** [linvi/tweetinvi#795]
I found a small problem serializing a tweet. When I call `args.Tweet.ToJson()` the `user.id` is serialized as `user.Id`. 

Example: 

    "user": {
        "name": "Pepe Lopez",
        "status": null,
       ...
        "Id": 23710757,
        "id_str": "23710757",
        "screen_name": "doufous"
    },

**Comment by linvi** [comment]
Will be available in next release.
