### ISSUE TITLE
Unable to install Tweetinvi on VS 2012

### ISSUE THREAD

**Issue by sourabhsriom** [linvi/tweetinvi#797]
Hi,

I am using VS 2012 and am trying to install the tweetinvi package through the package manager. I get an error citing issue with version of Newtonsoft.json saying : 

*'Newtonsoft.Json' already has a dependency defined for 'NETStandard.Library'.*

Is this a known issue or is there a way to resolve this?

**Comment by Anu6is** [comment]
https://stackoverflow.com/questions/44532170/newtonsoft-json-already-has-a-dependency-defined-for-microsoft-csharp

**Comment by linvi** [comment]
@sourabhsriom did it help you solve your problem?

**Comment by sourabhsriom** [comment]
Thank you for your response @linvi . Is there anything I can do to get it working with .NET 4.0?

**Comment by linvi** [comment]
@sourabhsriom There is no plan to migrate back to 4.0. The library always references the lowest .NET Standard / .NET Framework version possible based on what features of the Framework are used in the library.

In addition please note that version 5.0 of Tweetinvi will probably target .NET Standard 2.0 which will be compatible with 4.6.1.

This upgrade of .NET Standard version will be required for the usage of `AsyncLocal`.
