### ISSUE TITLE
NitoAsyncEx.Context.StrongName is not working for .NET 4.6 projects

### ISSUE THREAD

**Issue by linvi** [linvi/tweetinvi#798]
Hi @linvi 
I tried to install tweetinvi packages and I got an error as my project is of version 4.6 and some of the dependencies in tweetinivi are not compatible with this version. I have attached a screenshot.

![image](https://user-images.githubusercontent.com/25687717/47282157-cbf2e180-d5fb-11e8-92dc-fccd7a368c1b.png)

_Originally posted by @Nadeem-Saif in https://github.com/linvi/tweetinvi/issues/363#issuecomment-431762627_

**Comment by linvi** [comment]
@Nadeem-Saif could you please provide more information regarding your project as to what type of project it is (WPF, Console, ASP.NET...).

Thanks

**Comment by fgroen** [comment]
The package is unlisted, see also: https://www.nuget.org/packages/NitoAsyncEx.Context.StrongName/1.1.0

Best regards,
Freddy

**Comment by linvi** [comment]
The issue is related with .NET 4.6 which is not supported.
Currently only .NET 4.6.1 is supported as we are targeting .NET Standard 1.4.
