### ISSUE TITLE
Exception Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by osmay88** [linvi/tweetinvi#799]
I'm using the streaming Api + keyword tracking. Every some time I receive this Exception on my `StreamStopped` handler. The error occurs randomly not all the time. 

`Exception Index was outside the bounds of the array.`
Example of code 

    public async Task Run(IEnumerable<string> keywords)
        {
            var userCredentials = Auth.CreateCredentials(
                this._config["Twitter:ConsumerKey"],
                this._config["Twitter:ConsumerSecret"],
                this._config["Twitter:AccessTokenKey"],
                this._config["Twitter:AccessTokenSecret"]);

            var stream = Stream.CreateFilteredStream(userCredentials);
            keywords.ForEach(k => stream.AddTrack(k));
            
            stream.MatchingTweetReceived += async (sender, args) =>
            {
                 Console.WriteLine($"RECEIVED {args.Tweet.Id} Matching {tracks} ");
                 await _rabbit.Send(args.Tweet.ToJson());    
            };

            stream.StreamStopped += (sender, args) =>
            {
                Console.WriteLine(args.Exception.Message);
            };

            Console.WriteLine("Listening for tweets..");
            stream.StartStreamMatchingAllConditions();  
        }
        
    }

Stacktrace 

     at System.String.get_Chars(Int32 index)
     at Tweetinvi.Streams.Helpers.StreamTrackManager`1._matchingTracks(String input)
     at Tweetinvi.Streams.Helpers.StreamTrackManager`1.GetMatchingTracksAndActions(String input)
     at Tweetinvi.Streams.FilterStreamTweetMatcher.UpdateMatchesBasedOnTweetText(ITweet tweet, 
     MatchOn matchOn, Dictionary`2 matchingTrackAndActions, MatchedTweetReceivedEventArgs matchingTracksEventArgs, Dictionary`2 matchingQuotedTrackAndActions)
    at Tweetinvi.Streams.FilterStreamTweetMatcher.GetMatchingTweetEventArgsAndRaiseMatchingElements(ITweet tweet, String json, MatchOn matchOn)
    at Tweetinvi.Streams.FilteredStream.<StartStreamMatchingAllConditionsAsync>b__20_1(String json)
    at Tweetinvi.Streams.Helpers.StreamResultGenerator.<>c__DisplayClass23_0.<StartStreamAsync>b__0(String json)
    at Tweetinvi.Streams.StreamTask.Start()

Screenshot of tracked keywords:
![image](https://user-images.githubusercontent.com/11883026/51331553-abafb300-1a82-11e9-91c8-9533750c6451.png)

**Comment by osmay88** [comment]
Any comments or workaround this issue, it's a show stopper for me at the moment.

**Comment by linvi** [comment]
I will continue to investigate but you could make this faster.

Could you add the following :

``` c#
stream.JsonObjectReceived+= (sender, args) =>
{
    Console.WriteLine(args.Json);
};
```

And send me the json that you received just before you receive the error.

Thank you.

**Comment by linvi** [comment]
Will be available in next release.

**Comment by razvan-panda** [comment]
@linvi I am getting the same error message occasionally. Using Tweetinvi v.4.0.0 NuGet
Should I open a new ticket?

**Comment by osmay88** [comment]
Hei @razvan-panda I'm the guy who created this ticked. They have already the fix in their master branch. I'm my case I got this error when adding empty strings as tracked keywords. Maybe this could help you.

**Comment by razvan-panda** [comment]
@osmay88 I checked the fix and that is not the issue we are having. Our tracks are never null or empty.

**Comment by osmay88** [comment]
@razvan-panda I see. Well you should open a new bug probably.

**Comment by linvi** [comment]
@razvan-panda please open another issue with all the details necessary for investigation. 

I need context and code to understand the problem. 

Cheers
