### ISSUE TITLE
Tweet not push with coordinates

### ISSUE THREAD

**Issue by tagplus5** [linvi/tweetinvi#8]
If i use coordinates
```C#
var France = new Coordinates(48.869702, 2.342528);
var tweet = Tweet.PublishTweet("Some love from France!", new PublishTweetOptionalParameters
{
    Coordinates = France
});
```
tweet = null

without coordinates all works

**Comment by linvi** [comment]
Hello,

This is working perfectly well for me . Would you please have a look into the [ExceptionHandler](https://github.com/linvi/tweetinvi/wiki/Exception-Handling) and give me the details of the last exception you receive please.

Thanks

**Comment by tagplus5** [comment]
```C#
var France = new Coordinates(48.869702, 2.342528);
var tweet = Tweet.PublishTweet("Some love from France!", new PublishTweetOptionalParameters
{
    Coordinates = France
});
```
The following error occured : 'Unauthorized -  Authentication credentials were missing or incorrect.'
```C#
var France = new Coordinates(48.869702, 2.342528);
var tweet = Tweet.PublishTweet("Some love from France!", new PublishTweetOptionalParameters
{
    
});
```
tweet without errors

**Comment by linvi** [comment]
Could you please share a bit more context of your code. For example is it run in an async task.
Also could you please share a bit more information from the TwitterException.

Thanks

**Comment by tagplus5** [comment]
i deleted only keys
all my code:
simple console app
```C#
using System;
using Tweetinvi;
using Tweetinvi.Core.Parameters;

namespace TwitterTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var CONSUMER_KEY = "******";
            var CONSUMER_SECRET = "********";
            var ACCESS_TOKEN = "************";
            var ACCESS_TOKEN_SECRET = "**************";
            
            Auth.SetUserCredentials(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);

            var France = new Coordinates(48.869702, 2.342528);

            var tweet = Tweet.PublishTweet("Some love from France!", new PublishTweetOptionalParameters
            {
                Coordinates = France
            });
            
            if (tweet == null) // Something went wrong but we don't know what
            {
                // We can get the latest exception received by Tweetinvi
                var latestException = ExceptionHandler.GetLastException();
                Console.WriteLine("The following error occured : '{0}'", latestException.TwitterDescription);
            }

            Console.ReadLine();
        }        
    }
}
```
.NET Framework 4.6 or .NET Framework 4.5.2 without difference

**Comment by linvi** [comment]
Thanks the code perfectly correct. Please print the TwitterException.ToString() and send it to me.

**Comment by tagplus5** [comment]
TwitterException

Message:
```C#
https://api.twitter.com/1.1/statuses/update.json?status=Some%20love%20from%20France%21&lat=2,342528&long=48,869702 web request failed.
```
StackTrace
```C#
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method)
   at Tweetinvi.Credentials.TwitterAccessor.ExecutePOSTQuery[T](String query, JsonConverter[] converters)
   at Tweetinvi.Controllers.Tweet.TweetQueryExecutor.PublishTweet(IPublishTweetParameters publishParameters)
   at Tweetinvi.Controllers.Tweet.TweetController.InternalPublishTweet(IPublishTweetParameters parameters)
   at Tweetinvi.Controllers.Tweet.TweetController.PublishTweet(String text, IPublishTweetOptionalParameters optionalParameters)
   at Tweetinvi.Tweet.PublishTweet(String text, IPublishTweetOptionalParameters publishTweetOptionalParameters)
   at TwitterTest.Program.Tweetinvi() in D:\GoogleDrive\coding\VSProjects\TwitterTest\TwitterTest\Program.cs:line 20
```

**Comment by tagplus5** [comment]
TwitterException.ToString()

--- Date : 07.08.2015 2:00:34
URL : https://api.twitter.com/1.1/statuses/update.json?status=Some%20love%20from%20France%21&lat=2,342528&long=48,869702
Code : 401
Error documentation description : Unauthorized -  Authentication credentials were missing or incorrect.
Could not authenticate you. (32)

**Comment by linvi** [comment]
Would you please let me know what is the language configured on your machine?

**Comment by tagplus5** [comment]
Interface Language: English
Format: Russian

Error in comma in &long=48,869702 right?

**Comment by linvi** [comment]
Yep, I will have fix this tomorrow cause it is very late right now.
A 0.9.9.3 release will be published tomorrow to fix this bug.

**Comment by tagplus5** [comment]
Thanks.

**Comment by linvi** [comment]
Thank you for reporting it ;)

You can find the work item on codeplex [here](https://tweetinvi.codeplex.com/workitem/2635).

**Comment by linvi** [comment]
Tweetinvi 0.9.9.3 has been released on nuget.org.
The git repository will be updated tonight.

Let me know if this fixes your issue.

**Comment by tagplus5** [comment]
I update to 0.9.9.3, use same code.
Tweet with no errors but coordinates not deliwer.

**Comment by linvi** [comment]
Can you let me know what information are stored in the Tweet.Coordinates.

``` c#
var France = new Coordinates(48.869702, 2.342528);
var tweet = Tweet.PublishTweet("Some love from France!", new PublishTweetOptionalParameters
{
    Coordinates = France
});

Console.WriteLine(tweet.Coordinates);
```

Thanks

**Comment by tagplus5** [comment]
with comma 
```C#
2,342528 - 48,869702
```

**Comment by linvi** [comment]
Yep, it means that the Tweet has the coordinates set up on Twitter.
It shows the coma because of your region settings, this is alright.

**Comment by tagplus5** [comment]
```C#
Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US");

var France = new Coordinates(48.869702, 2.342528);

var tweet = Tweet.PublishTweet("zzz", new PublishTweetOptionalParameters
{
         Coordinates = France
});

Console.WriteLine(tweet.Coordinates.Latitude + " - " + tweet.Coordinates.Longitude);
```
I got
```C#
2.342528 - 48.869702
```
But tweet is still without coordinates.

**Comment by linvi** [comment]
Hi there tweet HAS coordinates on Twitter as the `var tweet` is created from the information received from Twitter (not from what is specified in the parameters).

If you create a tweet with no coordinates this setting will be returned by Twitter as null.

``` c#
// tweet.Coordinates is null
var tweet = Tweet.PublishTweet("Some love from France2 !");
```

If the `Coordinates` property is not null it means that it has been set on Twitter.

**Comment by tagplus5** [comment]
Оk, but
![2015-08-07_21-21-51-zluk9p](https://cloud.githubusercontent.com/assets/2699260/9142802/bc781ac4-3d4a-11e5-9c36-ebe42413268d.png)
Twitter settings
![2015-08-07_21-22-43-d11x6n](https://cloud.githubusercontent.com/assets/2699260/9142812/c7521346-3d4a-11e5-8f0b-1486a9043ff8.png)

Still without coord's

**Comment by linvi** [comment]
With the release 0.9.9.3 you no longer need to set your region to US.
Now I do not understand what the bug is about. The tweet cannot be send or the tweet is sent but the Tweet.Coordinates is null?

**Comment by tagplus5** [comment]
I understand about new version. Just trying different ways. Now tweet
always send but without coordinates.
7 авг. 2015 г. 9:50 PM пользователь "linvi" <notifications@github.com>
написал:

**Comment by tagplus5** [comment]
Tweet.Coordinates is not null. But on twitter they are missing.

**Comment by linvi** [comment]
The fact that Twitter does not show the tweet location is different from the tweet coordinates not set.
Would you please share the link of your tweet or the tweet id you are publishing?

**Comment by tagplus5** [comment]
OK. I tomorrow I send all data.
