### ISSUE TITLE
Tweets with multiple images only returned first image

### ISSUE THREAD

**Issue by jagiles** [linvi/tweetinvi#80]
When searching for tweets by a hashtag, tweets that have multiple images in the extended_entities field in the JSON response only returns a single item in the ITweet.Entities.Medias property.

**Comment by linvi** [comment]
Would you please give the id of the tweet you are referring to please.

Cheers,
Linvi

**Comment by jagiles** [comment]
The id is 661379703102676992.  It came up in a search for #WeAreND but it only contained a single media item in the extended entities property.  When looking at it using the API Console on twitter it shows two media objects.

**Comment by jagiles** [comment]
After doing some more searching it appears as though there is some inconsistency in the Twitter documentation.  Even though they state that the extended_entities property is returned for Tweets, it is not returned in the search/tweets endpoint.  I apologize for raising this as an issue.  There has been some discussion on the [Twitter developer forums](https://twittercommunity.com/t/search-tweets-endpoint-and-extended-entities/31655) discussing its omission from this endpoint.

**Comment by linvi** [comment]
I am reopening the issue as I want to track it in order to log the changes against it.

**Comment by linvi** [comment]
Sorry my bad, I got confused with the issue numbers.
Thank you for your investigation.

I hope you'll love using Tweetinvi :)
