### ISSUE TITLE
Activity API - direct message sent events erroring

### ISSUE THREAD

**Issue by nick-wamba** [linvi/tweetinvi#802]
[Twitter's documentation](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/guides/account-activity-data-objects#direct_message_events) is invalid for these event payloads.  

They document the payload like this:
```
{
  	"for_user_id": 123,
	"direct_message_events": [],
	"apps": {
		"123": {
		},
		"users": {},
```

If you setup a test scenario and look at actual payloads for sent messages and received messages, they are as follows:

Message Sent:
```
{
    "for_user_id": "123",
    "direct_message_events": [
        {
            "type": "message_create",
            "id": "1",
            "created_timestamp": "1548173249424",
            "message_create": {
                "target": {
                    "recipient_id": "456"
                },
                "sender_id": "123",
                "source_app_id": "123",
                "message_data": {}
            }
        }
    ],
    "apps": {
        "123": {}
    },
    "users": {
        "123": {},
        "456": {}
```

Message Received:
```
{
    "for_user_id": "456",
    "direct_message_events": [
        {
            "type": "message_create",
            "id": "1",
            "created_timestamp": "1548173249424",
            "message_create": {
                "target": {
                    "recipient_id": "456"
                },
                "sender_id": "123",
                "message_data": {}
            }
        }
    ],
    "users": {
        "123": {},
        "456": {}
    }
}
```

Note: 
- the user object is a sibling of apps, not a child as the documentation indicates.  
- the received event has the app object and source_app_id in the message
- the sent event does not have the app object and source_app_id in the message

Received messages result in a NullReferenceException in the current codebase at [line 231 of AccountActivityStream](https://github.com/linvi/tweetinvi/blob/d80a84e67c66d63869f6fc7c5051c257a8e2f237/Tweetinvi.Streams/AccountActivityStream.cs#L231):
```
var apps = jsonObjectEvent["apps"].ToObject<Dictionary<string, App>>();
```

**Comment by linvi** [comment]
Thanks again, this has been merged for next release.
