### ISSUE TITLE
Add support for user email.

### ISSUE THREAD

**Issue by francnuec** [linvi/tweetinvi#81]
It is now possible to get user email from twitter API. This however requires this URL query parameter to be added to the URL: "include_email=true".

Please push a fix that adds support for this.

P.S. If the following where added to the project, I would have been able to do this myself:

1. Mark the 'Resources' code file as public, instead of internal (I would guess this was done automatically by the c# compiler). This way, I can modify the query URLs.
2. Make available the raw json string received from the api in a property on each model. This way I would have been able to look up the extra fields not available on the concrete c# object.

**Comment by linvi** [comment]
I will try to add the field to version 0.9.10.1. 

**Mark the 'Resources' code file as public, instead of internal. This way, I can modify the query URLs.**

This will be done.

**Make available the raw json string received from the api in a property on each model. This way I would have been able to look up the extra fields not available on the concrete c# object.**

This won't be done for 0.9.10.1 for sure. I will consider doing this before version 1.0 but I cannot guarantee this to you. The reason I have been reluctant on doing this is mostly a question of memory; this is particularly relevant when using Streams. 

Obviously I can add a configuration setting in order to add the json directly to the objects but this is not something I wanted to do before the release of version 1.0. 

Version 1.1 will also include the deserialization of Tweetinvi objects into json. And [custom objects](https://github.com/linvi/tweetinvi/wiki/Custom-Objects-and-Dependency-Injection) should also help to have improved extensibility.

**Comment by francnuec** [comment]
Alright. Lovely. I look forward to the update.

**Comment by linvi** [comment]
Hello there, do you have a verified account that you could share with me for few hours in order that I make sure the Email field is working properly. I have asked Twitter to verify my app more than 10 times without any answer from them. If you do and you can share your credentials I will invite you in a private channel on [gitter](https://gitter.im/home).

**Comment by francnuec** [comment]
Hey,
Uhmm, yeah, I do. Problem is that app is live, sensitive, and I frankly do not have the authority to share those credentials.
However, I did figure out a way to get emails working with Tweetinvi by extending the ```UserDTO``` class and adding the following property:

```c#
        [JsonProperty("email")]
        public string Email { get; set; }
```

Then I use the following code to access/verify the current user's credentials on Twitter (as against using Tweetinvi.User.GetLoggedUser())

```c#
         TweetinviUserDTO twitterUser = null;
         if (!Tweetinvi.TwitterAccessor.TryExecuteGETQuery<TweetinviUserDTO>(Defaults.TwitterGetCurrentUser, out twitterUser))
         {
             //error
         }
```

Where <code>TweetinviUserDTO</code> is my derived class from ```UserDTO```.
```Defaults.TwitterGetCurrentUser``` points to a const string with value of "https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true". This is the same as available in the Tweetinvi code (and ultimately the Twitter api) but with the addition of <code>?include_email=true</code>

Well, I'm sure you know all these things. I'm just trying to say that if you applied these changes, they would work perfect, as I have already tested it in my own app.

But if you still need it tested, I would be happy to test it out for you from here.

**Comment by linvi** [comment]
Issue has been fixed if I gave you the new Tweetinvi dll would you be able to test?

**Comment by francnuec** [comment]
Yeah, sure. I would.

**Comment by linvi** [comment]
Please find the Tweetinvi.dll here : https://github.com/linvi/tweetinvi/releases/tag/0.9.11.0.
Please note that with the new release 0.9.10.1, Tweetinvi only has 1 dll.

Thanks for your help

**Comment by francnuec** [comment]
You're welcome.

But it didn't work though. I got <code>null</code> for Email field.

Here's the code I used:

```c#
var twitterUser2 = Auth.ExecuteOperationWithCredentials(
                Auth.CreateCredentials(Defaults.TwitterConsumerKey, Defaults.TwitterConsumerSecret,
                    access_token.value, access_token.secret), () =>
                    {
                        return Tweetinvi.User.GetLoggedUser(parameters: new Tweetinvi.Core.Parameters.GetLoggedUserParameters()
                        {
                            IncludeEmail = true
                        });
                    });
```

I hope that's the right code to use.

One problem I had though was finding where the IGetLoggedUserParameters was. But I eventually did anyway.

If I get some time, I'd try go through the source code.

**Comment by linvi** [comment]
Could you add the following before your code :

``` c#
TweetinviEvents.QueryAfterExecute += (sender, args) =>
{
    if (args.QueryURL.Contains("verify"))
    {
        var jsonToSendLinvi = args.JsonResult;
        Debug.WriteLine(jsonToSendLinvi);
    }
};
```

And send me the json structure you receive.
I am sending you an invite on gitter.im for private chat.

**Comment by vishal7862** [comment]
Is this support completed because I am not able to find it working , can anybody help me, I am in urgent need of it

**Comment by linvi** [comment]
This has been completed in version 0.9.11.0 and Tweetinvi is now in version 1.0.
If your app has Twitter Authorizations and you have updated your Twitter Consumer AND Access keys then you should be able to simply call `User.GetAuthenticatedUser()`.

Remember that each user of your app has to reauthorize your app with the new Consumer Key.

**Comment by vishal7862** [comment]
![twitteremail](https://cloud.githubusercontent.com/assets/8035048/17510549/07bc6bf2-5e3d-11e6-8ae6-62ac44a339bb.png)

In this you can see that I am getting null in the Email parameter, Is it because my application is not white listed?

**Comment by grahammccann** [comment]
Like the image above i'm also getting null for the email, i can't seem to find the reason why, is this a bug?

**Comment by linvi** [comment]
@grahammccann

Did you configure your app to have access to the email address?

**Comment by grahammccann** [comment]
Hey linvi,

Do you mean in my C# app or when i created the Twitter app? i figured it was something i was doing wrong as i couldn't see any reports when Googling :)

I'm sure from reading i never checked a box when creating the Twitter app, would that be about right?

cheers mate

**Comment by linvi** [comment]
@grahammccann 

You will need to go in your apps.twitter.com and tick `Request email address from users`

![image](https://user-images.githubusercontent.com/6107439/83260249-5bd21780-a1b1-11ea-8bd6-9e959b60ff77.png)

I hope this helps you :)

Cheeers,
Linvi

**Comment by grahammccann** [comment]
Ah that will be why :) thank you for the help mate :)
