### ISSUE TITLE
Questions about version 1.3

### ISSUE THREAD

**Issue by daz1761** [linvi/tweetinvi#810]
We have been using the latest version 4.0.0 to carry out some basic stuff on a module on a web page i.e. pull the latest tweets and images and display them in a slick slider.  So far, everything has worked really well.  

However, when we came to incorporating in our project, we had a conflict between HttpClient (System.Net.Http) versions.  Sadly we cannot update any higher than v4.0.0, and the latest Tweetinvi uses v4.3.2, so we had to downgrade to Tweetinvi v1.3.0, that uses Microsoft.Net.Http v2.2.29.

One thing we immediately noticed that a particular tweet that had quite a lot of text (nearly max chars) caused the image to come back null.  We thought it might be a one off with that particular image, but I created another tweet with the same amount of chars with a different image, and the same happened again.  Also, both particular tweets were truncated (...) (although this was set to false when debugged) and it was giving us "FullText" though we were calling `tweet.Text` in our loop, meaning we were getting the link for that particular tweet at the end of the tweet.  This can always be deleted with some string trickery, but our main concern is the image and truncation.  Images with shorter tweets were ok.

Is there anything that can be done about this, or is it just because we are using a lower version?  It would be great if we could still use Tweetinvi but on v1.3.0.  As mentioned, v4.0.0 worked brilliantly, but sadly we cannot use that version :-(

**Comment by linvi** [comment]
Hello,

This version is really old and not supported (I do not have time to support so many versions).

What I would suggest is that if you encounter a problem you use the `TweetinviAccessor` (https://github.com/linvi/tweetinvi/blob/1.3/Tweetinvi/TwitterAccessor.cs) and build the request on your own.

Then you will have to handle the json returned from there.

I am currently taking a lot of time working on 5.0 so I will not be able to prioritize this investigation but feel free to download the code from git repo and check what is wrong.

If you open a pull request that fixes the issue, I will create a new minor version for 1.3.

Also in regard to the version of Tweetinvi, if your devices do not support .NET Framework > 4.0.0, you should consider using Docker.

**Comment by daz1761** [comment]
Appreciate the response..  Also appreciate its a really old version.  I will report back to the team I'm liaising with and discuss your response.  I know Docker isn't an option but I'll mention this too.
