### ISSUE TITLE
Question: I can't find the "length" property

### ISSUE THREAD

**Issue by Mega1210** [linvi/tweetinvi#811]
As indicated in your wiki by using "Tweetinvi.Core.Extensions'" I should have access to the string method TweetLength() or anyway be able to use Tweet.Length(). 

None of them is actually available for me. What am I doing wrong? Thank you.

**Comment by linvi** [comment]
Hello,

Twitter changed their algorithm to calculate the length.
When they did, the change was too big to be able to be supported without a significant time investment.

As a result, I decided to remove this feature until this is done.

You can find the 2 following tasks :

* https://github.com/linvi/tweetinvi/issues/224
* https://github.com/linvi/tweetinvi/issues/794

The official Twitter implementation is not available in C# but can be found here :

https://github.com/twitter/twitter-text

If you wish to port this logic, I will more than welcome a Pull Request as my time is currently focused on improving webhooks and async support of the library.

Cheers,
Linvi

**Comment by linvi** [comment]
Note that the old logic is still available in the TweetController under `EstimateTweetLength`.

It can be accessed via the following :

```c#
Tweet.TweetController.EstimateTweetLength();
```

Again, this is using the old algorithm which will work in **MOST** cases but not all.

For example tweets with urls containing top domain names with less than 2 characters (e.g. **.fr**) can result in a different result than when using the official algorithm.
