### ISSUE TITLE
Using multiple filters with search parameters

### ISSUE THREAD

**Issue by sourabhsriom** [linvi/tweetinvi#812]
Hello,

I am using search Parameters to configure how I want my data to be pulled. In my case I am looking for tweets matching the search term, which have a photo or video in them. Right now my search parameters look like this : 

```
 var searchParameter = new SearchTweetsParameters("#sgg2e")
            {
               Lang = LanguageFilter.English,
                MaximumNumberOfResults = 100,
                Filters = TweetSearchFilters.Images 
            };
```

Could you please tell me how I can add another filter for TweetSearchFilters.Video ? I did not find anything in the documentation.

**Comment by sourabhsriom** [comment]
@linvi could you please point me to the documentation for search parameters so I can use multiple media filters?

**Comment by linvi** [comment]
Here you go :

``` c#
Filters = TweetSearchFilters.Images | TweetSearchFilters.NativeVideo | TweetSearchFilters.Verified
```

**Comment by linvi** [comment]
Requires documentation

**Comment by sourabhsriom** [comment]
Thank you so much!

**Comment by linvi** [comment]
Updated documentation
