### ISSUE TITLE
Stream works after an error throwed

### ISSUE THREAD

**Issue by fightlikeagirl** [linvi/tweetinvi#813]
Hello,

I want excellent working stream. First I want it work infinitive, and want to know if there is an error about stream or has stream reached limit ? more important if error occured over and over , I think twitter can block my Ip. Should I use a timer to wait to reconnect again ? or what to do (Should I use while(true) to make stream connection to infinitive? )  I am really confused . 

Thanks for your helps. 

My code :

``` c#
while (true)
    {
    IHubContext _context = GlobalHost.ConnectionManager.GetHubContext<TwiHub>();
    Auth.SetUserCredentials("", "", "", "");
    filteredStream.AddTrack(word);            
    
    filteredStream.MatchingTweetReceived += (sender, args) =>
    {
        _context.Clients.All.broadcastMessage(args.Tweet.FullText);
    }; `

    filteredStream.StreamStopped += (sender, args) =>
    {
        var exceptionThatCausedTheStreamToStop = args.Exception;
        var twitterDisconnectMessage = args.DisconnectMessage;
        _context.Clients.All.broadcastMessage("Error occured :" + exceptionThatCausedTheStreamToStop);
        _context.Clients.All.broadcastMessage(twitterDisconnectMessage);
        // I dont know how to reconnect , which frequency , should I use timer ?
    };

    filteredStream.Limitreached
    {
        // I dont know how to reconnect , which frequency , should I use timer ?
    }

    filteredStream.StartStreamMatchingAllConditions();
}
```

**Comment by linvi** [comment]
I suggest you read some official documentation about the streams :

https://developer.twitter.com/en/docs/tutorials/consuming-streaming-data

You will probably be interested by this part :

> **Step 4**: When disconnected, reconnect to the API
Inevitably, at some point the connection to the stream will close – a disconnection. With realtime streams, it is important to understand that you may be missing data any time you are disconnected from the stream. Whenever a disconnection occurs, your client app must restart the process by establishing a new connection.
>
> Additionally, to ensure that you do not miss any data, you may need to utilize a Redundant Connection, Backfill, or a Replay stream to mitigate or recover data from disconnections from the stream.

**Comment by linvi** [comment]
In addition to this, I would strongly suggest that you use buffering of messages to handle the charge

``` c#
 filteredStream.MatchingTweetReceived += (sender, args) =>
    {
      // For 1 million tweets, you will send 1 million broadcast message, this won't scale.
      // Instead create batches and process these batches in separates processes / threads
        _context.Clients.All.broadcastMessage(args.Tweet.FullText);
    };
```

**Comment by fightlikeagirl** [comment]
Thank You
