### ISSUE TITLE
Upload.CreateChunkedUploader gives error in VS2017

### ISSUE THREAD

**Issue by francescoBLT** [linvi/tweetinvi#814]
I'm writing a  form application that upload mp4 files.. When files are small all is ok. When files are large I can't setup the chunked uploading.  That is when I insert the line:

 var uploader = Upload.CreateChunkedUploader();

the compiler result is:

Error CS0117	: 'Upload' does not contain a definition for 'CreateChunkedUploader'	TwitterTest	C:\Projects\TestCodeVS\VS2017\TwitterTest\TwitterTest\Form1.cs	

How can I overcome ?
Regards

**Comment by linvi** [comment]
Hello,

`Upload` had a major refactoring in version 3.0 (https://github.com/linvi/tweetinvi/releases/tag/3.0).
Developers no longer have to handle chunks on their own, Tweetinvi will do that for them. Though you can control the size of each chunks.

``` c#
var binary = new byte[] { };
Upload.UploadBinary(binary, new UploadOptionalParameters()
{
    MaxChunkSize = 1024 * 1024
});
```
