### ISSUE TITLE
Restart Stream After Stopped

### ISSUE THREAD

**Issue by fightlikeagirl** [linvi/tweetinvi#820]
Hello ,
I have a problem about restarting sample stream after stream.stopped event.
When stream stop event occur, should I use `Stream.Start` function and after this  `StartStreamMatchingAllTweets`  ? what is the right way to make continue/restart stream after stream has stop ? Thank yo so much linvi

**Comment by linvi** [comment]
Hello,

The right way is to re-execute the same method everywhere.
So if you used `StartStreamMatchingAllTweets ` you need to reuse it in your `StreamStopped` event.

Cheers,
Linvi
