### ISSUE TITLE
Streaming filtering using `and`

### ISSUE THREAD

**Issue by razvan-panda** [linvi/tweetinvi#821]
Is it possible to perform the following kind of streaming filter (pseudocode)?

    (track = "shooter" and location = "Miami") or (track = "flood" and location="Los Angeles") or ...

I think it might not be possible because of the following ([quoted from the documentation](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter.html)):

> The track, follow, and locations fields should be considered to be
> combined with an OR operator.

SO: https://stackoverflow.com/q/54982018/750216

**Comment by linvi** [comment]
Please check this section of Tweetinvi's documentation :

https://github.com/linvi/tweetinvi/wiki/Filtered-Streams#filter-by-track-and-keywords

**Comment by razvan-panda** [comment]
That is for `and` between AddTrack terms though. What I was asking is whether it is possible to use and between AddTrack and AddLocation.

**Comment by linvi** [comment]
This is not possible.
The response on StackOverflow is from actual Twitter team.

This is a limitation of the public api stream.
