### ISSUE TITLE
Cannot convert from 'Xamarin.Forms.Entry' to 'Tweetinvi.Models.IUserIdentifier'

### ISSUE THREAD

**Issue by sdalwani1** [linvi/tweetinvi#822]
Hi, I have been trying to access tweets of a user from his/her username provided in the Entry tag. But, I'm unable to solve this issue: cannot convert from 'Xamarin.Forms.Entry' to 'Tweetinvi.Models.IUserIdentifier'.

Can you help?

**Comment by linvi** [comment]
Hello,

I am not expert on Xamarin and unfortunately I am very busy working on the next version of Tweetinvi.
It looks like a question to ask on StackOverflow.

Sorry for not helping here, but I am way too short on time.

Cheers,
Linvi

**Comment by linvi** [comment]
Hello,

I am not expert on Xamarin and unfortunately I am very busy working on the next version of Tweetinvi.
It looks like a question to ask on StackOverflow.

Sorry for not helping here, but I am way too short on time.

Cheers,
Linvi
