### ISSUE TITLE
Not Found - The URI requested is invalid...

### ISSUE THREAD

**Issue by joshuasan** [linvi/tweetinvi#829]
Hi!

I'm testing Tweetinvi 4.0.0 in an .Net Core Console Application.  I'm trying to stream with CreateUserStream().

I get authenticated and the stream starts. But unfortunately the stream is stopped with an error message within 1 second. Is there a problem with Tweetinvi or is it just me who has not understood how to code?

The code I use is (I have ofc changed the credentials and they work since I have tested to print my screen name, location etc):

**************
`static void Main(string[] args)
        {
            Auth.ApplicationCredentials = new TwitterCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

            var user = Tweetinvi.User.GetAuthenticatedUser();

            //setup stream
            var userStream = Tweetinvi.Stream.CreateUserStream();

            Console.WriteLine("Location: {0}", user.Location);

            userStream.StreamStarted += (sender, arguments) =>
            {
                Console.WriteLine("Sucess: Twitter: User Stream started");
            };

            userStream.StreamStopped += (sender, arguments) =>
            {
                Console.WriteLine("STOPPED!");

                if (arguments.Exception != null)
                {
                    Console.WriteLine(arguments.Exception);
                }
            };

            userStream.StartStream();

            Console.ReadLine();
        }`
**************

I then get the following response from my program:
-------------------------------
Location: Stockholm
Sucess: Twitter: User Stream started
STOPPED!
--- Date : 2019-03-13 19:48:00
URL : https://userstream.twitter.com/1.1/user.json?stall_warnings=true&tweet_mode=extended&replies=all&with=followings
Code : 404
Error documentation description : Not Found - The URI requested is invalid or the resource requested, such as a user, does not exists. Also returned when the requested format is not supported by the requested method.
Error message : Stream cannot be read.
-------------------------------

**Comment by linvi** [comment]
Twitter stopped supporting the UserStream after I released Tweetinvi 4.0.

You will now have to use the AccountActivity stream. 

They are fundamentally different as the second uses Webhooks as opposed constantly open socket.

This repo provides a sample Webhooks project but remember that you will have to host this on a server reachable via a DNS as well as offering the https protocol. 

Finally I would like to say that one the emphasis of version 5.0 is on AccountActivity. There will be changes and improvements over the 4.0 implementation. Also the sample will be simpler to understand and use. You can check branch 5.0 if you wish to check the changes. 

Thanks
Linvi

**Comment by joshuasan** [comment]
Thank you for a quick response!

Best regards

**Comment by joshuasan** [comment]
Sorry to disturb again. But I googled a bit and I do not think AccountActivity stream will satisfy my needs.

My aim is to get the tweets of a guy that I follow. I could usually use CreateFilteredStream(). But this guy has protected tweets so it's not possible then. Therefore I tried to use CreateUserStream() since he has allowed me access to his tweets.

But UserStreams are as you said now deprecated and the AccountActivity stream will problably not help me. Any other suggestion how to use either your version 4.0 or maybe something that will work in 5.0 for this? And is it possible 5.0 will be released before summer?

Hopefully there is a solution so I can start building a program that I might have a lot of use with.

**Comment by linvi** [comment]
If you are trying to get live feed of when a user publishes a tweet the AccountActivity fits your purpose. 

You can use the TweetCreated event.

**Comment by joshuasan** [comment]
Ah interesting! Thanks a lot both for your quick and good answers and for your library! :)

**Comment by linvi** [comment]
Regarding your question about timeline, at the moment I am looking for a release of version 5.0 within a month.

**Comment by joshuasan** [comment]
Great! Looking forward to it :)

Cheers!
