### ISSUE TITLE
Getting an exception for random tweets with statuscode -1

### ISSUE THREAD

**Issue by gsogol** [linvi/tweetinvi#83]
Sometimes the user gets a statuscode from twitterexception of -1 with description being empty but it seems sometimes the tweet still goes through but because we receive an exception we retry and sometimes we get duplicates. From searching on twitter community, statuscode of -1 means possible that the library is not using full SSL/TLS. Has anyone seen anything similar?

**Comment by linvi** [comment]
The `TwitterException` contains `.URL` property, could you please share it.

**Comment by gsogol** [comment]
I cannot reproduce this but get 1% of all tweets with this message. Second time works and then when I look at twitter, I see 2 posts after retrying once.

**Comment by gsogol** [comment]
I do not catch with TwitterException, I use
<code>
            if (ExceptionHandler.GetLastException() != null)

            {

                var exceptionDescription = ExceptionHandler.GetLastException().TwitterDescription;

                var statusCode = ExceptionHandler.GetLastException().StatusCode;

                stringBuilder.AppendLine(string.Format("{0} twitter error for post {1} description:{2};statusCode:{3}", userId, tweetText, exceptionDescription, statusCode));

                if (ExceptionHandler.GetLastException().TwitterExceptionInfos != null && ExceptionHandler.GetLastException().TwitterExceptionInfos.Any())

                {

                    ExceptionHandler.GetLastException().TwitterExceptionInfos.ForEach(te =>

                    {
                        
                        stringBuilder.AppendLine(string.Format("Code:{0};Message:{1}", te.Code, te.Message));

                }
</code>

**Comment by linvi** [comment]
The exception you receive from the `ExceptionHandler` is a TwitterException and contains the URL.
This will probably allow me to detect what could go wrong.

**Comment by gsogol** [comment]
just added it and will monitor for exceptions as it should log now

**Comment by gsogol** [comment]
Here is what I log and I just got another one in production. Looks to be something with rate limit but I also log rate limit. The user who used our system just did one tweet so not sure here. Here is the full log:

Text tweeted: "What kills us and what makes us eternal? - I Live Rouge http://bit.ly/1QbI2Gs" 
description:
statusCode:-1
url:https://api.twitter.com/1.1/application/rate_limit_status.json
TwitterExceptionInfos.Any():False
RateLimit:
{"CreatedAt":"2015-11-17T10:36:58.1042816+00:00","AccessToken":"162630139-rr6xmRQiHSMRKsgh7glnXaw2MajMDaXX7pB21Hdb","AccountLoginVerificationEnrollmentLimit":{"remaining":15,"reset":1447757517,"limit":15},"AccountSettingsLimit":{"remaining":15,"reset":1447757517,"limit":15},"AccountUpdateProfileLimit":{"remaining":15,"reset":1447757517,"limit":15},"AccountVerifyCredentialsLimit":{"remaining":15,"reset":1447757517,"limit":15},"ApplicationRateLimitStatusLimit":{"remaining":179,"reset":1447757517,"limit":180},"BlocksIdsLimit":{"remaining":15,"reset":1447757517,"limit":15},"BlocksListLimit":{"remaining":15,"reset":1447757517,"limit":15},"DeviceTokenLimit":{"remaining":15,"reset":1447757517,"limit":15},"DirectMessagesLimit":{"remaining":15,"reset":1447757517,"limit":15},"DirectMessagesSentLimit":{"remaining":15,"reset":1447757517,"limit":15},"DirectMessagesSentAndReceivedLimit":{"remaining":15,"reset":1447757517,"limit":15},"DirectMessagesShowLimit":{"remaining":15,"reset":1447757517,"limit":15},"FavoritesListLimit":{"remaining":15,"reset":1447757517,"limit":15},"FollowersIdsLimit":{"remaining":15,"reset":1447757517,"limit":15},"FollowersListLimit":{"remaining":15,"reset":1447757517,"limit":15},"FriendsIdsLimit":{"remaining":15,"reset":1447757517,"limit":15},"FriendsListLimit":{"remaining":15,"reset":1447757517,"limit":15},"FriendsFollowingIdsLimit":{"remaining":15,"reset":1447757517,"limit":15},"FriendsFollowingListLimit":{"remaining":15,"reset":1447757517,"limit":15},"FriendshipsIncomingLimit":{"remaining":15,"reset":1447757517,"limit":15},"FriendshipsLookupLimit":{"remaining":15,"reset":1447757517,"limit":15},"FriendshipsNoRetweetsIdsLimit":{"remaining":15,"reset":1447757517,"limit":15},"FriendshipsOutgoingLimit":{"remaining":15,"reset":1447757517,"limit":15},"FriendshipsShowLimit":{"remaining":180,"reset":1447757517,"limit":180},"GeoGetPlaceFromIdLimit":{"remaining":15,"reset":1447757517,"limit":15},"GeoReverseGeoCodeLimit":{"remaining":15,"reset":1447757517,"limit":15},"GeoSearchLimit":{"remaining":15,"reset":1447757517,"limit":15},"GeoSimilarPlacesLimit":{"remaining":15,"reset":1447757517,"limit":15},"HelpConfigurationLimit":{"remaining":15,"reset":1447757517,"limit":15},"HelpLanguagesLimit":{"remaining":15,"reset":1447757517,"limit":15},"HelpPrivacyLimit":{"remaining":15,"reset":1447757517,"limit":15},"HelpSettingsLimit":{"remaining":15,"reset":1447757517,"limit":15},"HelpTosLimit":{"remaining":15,"reset":1447757517,"limit":15},"ListsListLimit":{"remaining":15,"reset":1447757517,"limit":15},"ListsMembersLimit":{"remaining":180,"reset":1447757517,"limit":180},"ListsMembersShowLimit":{"remaining":15,"reset":1447757517,"limit":15},"ListsMembershipsLimit":{"remaining":15,"reset":1447757517,"limit":15},"ListsOwnershipsLimit":{"remaining":15,"reset":1447757517,"limit":15},"ListsShowLimit":{"remaining":15,"reset":1447757517,"limit":15},"ListsStatusesLimit":{"remaining":180,"reset":1447757517,"limit":180},"ListsSubscribersLimit":{"remaining":180,"reset":1447757517,"limit":180},"ListsSubscribersShowLimit":{"remaining":15,"reset":1447757517,"limit":15},"ListsSubscriptionsLimit":{"remaining":15,"reset":1447757517,"limit":15},"MutesUserList":{"remaining":15,"reset":1447757517,"limit":15},"MutesUserIds":{"remaining":15,"reset":1447757517,"limit":15},"SavedSearchDestroyList":{"remaining":15,"reset":1447757517,"limit":15},"SavedSearchesListLimit":{"remaining":15,"reset":1447757517,"limit":15},"SavedSearchesShowIdLimit":{"remaining":15,"reset":1447757517,"limit":15},"SearchTweetsLimit":{"remaining":180,"reset":1447757517,"limit":180},"StatusesFriendsLimit":{"remaining":15,"reset":1447757517,"limit":15},"StatusesHomeTimelineLimit":{"remaining":15,"reset":1447757517,"limit":15},"StatusesLookupLimit":{"remaining":180,"reset":1447757517,"limit":180},"StatusesMentionsTimelineLimit":{"remaining":15,"reset":1447757517,"limit":15},"StatusesOembedLimit":{"remaining":180,"reset":1447757517,"limit":180},"StatusesRetweetersIdsLimit":{"remaining":15,"reset":1447757517,"limit":15},"StatusesRetweetsIdLimit":{"remaining":60,"reset":1447757517,"limit":60},"StatusesRetweetsOfMeLimit":{"remaining":15,"reset":1447757517,"limit":15},"StatusesShowIdLimit":{"remaining":180,"reset":1447757517,"limit":180},"StatusesUserTimelineLimit":{"remaining":180,"reset":1447757517,"limit":180},"TrendsAvailableLimit":{"remaining":15,"reset":1447757517,"limit":15},"TrendsClosestLimit":{"remaining":15,"reset":1447757517,"limit":15},"TrendsPlaceLimit":{"remaining":15,"reset":1447757517,"limit":15},"UsersDerivedInfoLimit":{"remaining":15,"reset":1447757517,"limit":15},"UsersLookupLimit":{"remaining":180,"reset":1447757517,"limit":180},"UsersProfileBannerLimit":{"remaining":180,"reset":1447757517,"limit":180},"UsersReportSpamLimit":{"remaining":15,"reset":1447757517,"limit":15},"UsersSearchLimit":{"remaining":180,"reset":1447757517,"limit":180},"UsersShowIdLimit":{"remaining":180,"reset":1447757517,"limit":180},"UsersSuggestionsLimit":{"remaining":15,"reset":1447757517,"limit":15},"UsersSuggestionsSlugLimit":{"remaining":15,"reset":1447757517,"limit":15},"UsersSuggestionsSlugMembersLimit":{"remaining":15,"reset":1447757517,"limit":15},"resources":{"account":{"/account/login_verification_enrollment":{"remaining":15,"reset":1447757517,"limit":15},"/account/update_profile":{"remaining":15,"reset":1447757517,"limit":15},"/account/verify_credentials":{"remaining":15,"reset":1447757517,"limit":15},"/account/settings":{"remaining":15,"reset":1447757517,"limit":15}},"application":{"/application/rate_limit_status":{"remaining":179,"reset":1447757517,"limit":180}},"blocks":{"/blocks/list":{"remaining":15,"reset":1447757517,"limit":15},"/blocks/ids":{"remaining":15,"reset":1447757517,"limit":15}},"device":{"/device/token":{"remaining":15,"reset":1447757517,"limit":15}},"direct_messages":{"/direct_messages/sent":{"remaining":15,"reset":1447757517,"limit":15},"/direct_messages":{"remaining":15,"reset":1447757517,"limit":15},"/direct_messages/sent_and_received":{"remaining":15,"reset":1447757517,"limit":15},"/direct_messages/show":{"remaining":15,"reset":1447757517,"limit":15}},"favorites":{"/favorites/list":{"remaining":15,"reset":1447757517,"limit":15}},"followers":{"/followers/ids":{"remaining":15,"reset":1447757517,"limit":15},"/followers/list":{"remaining":15,"reset":1447757517,"limit":15}},"friends":{"/friends/following/ids":{"remaining":15,"reset":1447757517,"limit":15},"/friends/following/list":{"remaining":15,"reset":1447757517,"limit":15},"/friends/list":{"remaining":15,"reset":1447757517,"limit":15},"/friends/ids":{"remaining":15,"reset":1447757517,"limit":15}},"friendships":{"/friendships/outgoing":{"remaining":15,"reset":1447757517,"limit":15},"/friendships/no_retweets/ids":{"remaining":15,"reset":1447757517,"limit":15},"/friendships/lookup":{"remaining":15,"reset":1447757517,"limit":15},"/friendships/incoming":{"remaining":15,"reset":1447757517,"limit":15},"/friendships/show":{"remaining":180,"reset":1447757517,"limit":180}},"geo":{"/geo/similar_places":{"remaining":15,"reset":1447757517,"limit":15},"/geo/id/:place_id":{"remaining":15,"reset":1447757517,"limit":15},"/geo/reverse_geocode":{"remaining":15,"reset":1447757517,"limit":15},"/geo/search":{"remaining":15,"reset":1447757517,"limit":15}},"help":{"/help/tos":{"remaining":15,"reset":1447757517,"limit":15},"/help/configuration":{"remaining":15,"reset":1447757517,"limit":15},"/help/settings":{"remaining":15,"reset":1447757517,"limit":15},"/help/privacy":{"remaining":15,"reset":1447757517,"limit":15},"/help/languages":{"remaining":15,"reset":1447757517,"limit":15}},"lists":{"/lists/list":{"remaining":15,"reset":1447757517,"limit":15},"/lists/memberships":{"remaining":15,"reset":1447757517,"limit":15},"/lists/subscribers/show":{"remaining":15,"reset":1447757517,"limit":15},"/lists/members":{"remaining":180,"reset":1447757517,"limit":180},"/lists/subscriptions":{"remaining":15,"reset":1447757517,"limit":15},"/lists/show":{"remaining":15,"reset":1447757517,"limit":15},"/lists/ownerships":{"remaining":15,"reset":1447757517,"limit":15},"/lists/subscribers":{"remaining":180,"reset":1447757517,"limit":180},"/lists/members/show":{"remaining":15,"reset":1447757517,"limit":15},"/lists/statuses":{"remaining":180,"reset":1447757517,"limit":180}},"mutes":{"/mutes/users/list":{"remaining":15,"reset":1447757517,"limit":15},"/mutes/users/ids":{"remaining":15,"reset":1447757517,"limit":15}},"saved_searches":{"/saved_searches/destroy/:id":{"remaining":15,"reset":1447757517,"limit":15},"/saved_searches/show/:id":{"remaining":15,"reset":1447757517,"limit":15},"/saved_searches/list":{"remaining":15,"reset":1447757517,"limit":15}},"search":{"/search/tweets":{"remaining":180,"reset":1447757517,"limit":180}},"statuses":{"/statuses/retweeters/ids":{"remaining":15,"reset":1447757517,"limit":15},"/statuses/retweets_of_me":{"remaining":15,"reset":1447757517,"limit":15},"/statuses/home_timeline":{"remaining":15,"reset":1447757517,"limit":15},"/statuses/show/:id":{"remaining":180,"reset":1447757517,"limit":180},"/statuses/user_timeline":{"remaining":180,"reset":1447757517,"limit":180},"/statuses/friends":{"remaining":15,"reset":1447757517,"limit":15},"/statuses/retweets/:id":{"remaining":60,"reset":1447757517,"limit":60},"/statuses/mentions_timeline":{"remaining":15,"reset":1447757517,"limit":15},"/statuses/oembed":{"remaining":180,"reset":1447757517,"limit":180},"/statuses/lookup":{"remaining":180,"reset":1447757517,"limit":180}},"trends":{"/trends/closest":{"remaining":15,"reset":1447757517,"limit":15},"/trends/available":{"remaining":15,"reset":1447757517,"limit":15},"/trends/place":{"remaining":15,"reset":1447757517,"limit":15}},"users":{"/users/report_spam":{"remaining":15,"reset":1447757517,"limit":15},"/users/show/:id":{"remaining":180,"reset":1447757517,"limit":180},"/users/search":{"remaining":180,"reset":1447757517,"limit":180},"/users/suggestions/:slug":{"remaining":15,"reset":1447757517,"limit":15},"/users/derived_info":{"remaining":15,"reset":1447757517,"limit":15},"/users/profile_banner":{"remaining":180,"reset":1447757517,"limit":180},"/users/suggestions/:slug/members":{"remaining":15,"reset":1447757517,"limit":15},"/users/lookup":{"remaining":180,"reset":1447757517,"limit":180},"/users/suggestions":{"remaining":15,"reset":1447757517,"limit":15}}}}

**Comment by gsogol** [comment]
Also, just saw another one :
"Fundly - Setup a Donation Page and Start Fundraising Online Now http://bit.ly/1HWG6K3"
description:
statusCode:-1
url:https://upload.twitter.com/1.1/media/upload.js

**Comment by linvi** [comment]
Hello there, I have tried many different ways to reproduce your issue.
What is confusing is the fact that you receive a status code of -1. I never receive such a status code and I cannot find out about this on the Twitter website. I think it could be a network/communication issue of the WebRequest sent to Twitter.

In order to investigate further and find out more regarding this issue would you agree to have a Skype discussion and let me take a look at your code?

I understand that you receive this error rarely but I think we could use the Source Code of Tweetinvi to get more info regarding this.

Please let me know.

**Comment by gsogol** [comment]
Sure thing. I'm gsogol on Skype

**Comment by linvi** [comment]
Thanks, I have added you on Skype. See you there.

**Comment by linvi** [comment]
Please accept me on skype. I'd like to release 0.9.10.1 with a fix for this issue this weekend.

**Comment by gsogol** [comment]
Don't see an invite. What is yours?

**Comment by linvi** [comment]
Hi gsogol, I have messaged you on Gitter. Join me! https:/gitter.im/linvi

**Comment by linvi** [comment]
I am confident that this is a bug but I have never been able to reproduce it in 6 months.

Therefore I am closing this issue for now.

If anyone happen to reproduce it please reopen this issue.
