### ISSUE TITLE
perform boolean search for multiple search queries

### ISSUE THREAD

**Issue by Frankofoedu** [linvi/tweetinvi#835]
How do i perform a boolean search using the search apis?

**Comment by linvi** [comment]
I do not understand your question, could you please elaborate?

Thanks

**Comment by Frankofoedu** [comment]
Hi @linvi. What I am saying is, how do I search for multiple hashtags? I have two words e.g bag and cap. How do I get tweets that contain bag and cap and also tweets containing bag or cap.

I e a simple and / or query

**Comment by linvi** [comment]
You can find all operators and information here : 

https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators

I have also update the links in the documentation.

https://github.com/linvi/tweetinvi/wiki/Searches#tweet-searches
