### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by user156** [linvi/tweetinvi#84]
Start DateTime: 
10/11/2015 16:37:47

Exception DateTime: 
10/11/2015 21:56:53

Exception.Message:
Object reference not set to an instance of an object.

Exception.StackTrace:   
 
at Tweetinvi.Factories.Tweet.TweetFactory.GenerateTweetFromJson(String jsonTweet)
   at Tweetinvi.Streams.FilteredStream.<StartStreamMatchingAllConditionsAsync>b__17_1(String json)
   at Tweetinvi.Streams.Helpers.StreamResultGenerator.<>c__DisplayClass20_0.<StartStreamAsync>b__0(String json)
   at Tweetinvi.Streams.StreamTask.Start()

**Comment by linvi** [comment]
Associate with issue #60.

**Comment by rotem156** [comment]
I am getting this a lot, i can't start the stream now because of this exception, please put this exception as top priority to fix it.

**Comment by Hasgassa** [comment]
Hello,

I'm facing the same issue. Is there any workarround? Thank you.
My code is:

        private static void Stream_SampleStreamSearch()
        {
            // When a new thread is created, the default credentials will be the Application Credentials
            Auth.SetUserCredentials(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET);
            Console.Write("\nVai executar for...");
            for (; ; )
            {
                try
                {
                    var stream = Stream.CreateFilteredStream();

                    stream.AddTrack("#farfetch");

                    var tweetCount = 0;
                    var timer = Stopwatch.StartNew();

                    stream.MatchingTweetReceived += (sender, args) =>
                    {
                        tweetCount++;
                        var tweet = args.Tweet;

                        if (timer.ElapsedMilliseconds > 1000)
                        {
                            if (tweet.Coordinates != null)
                            {
                                Console.ForegroundColor = ConsoleColor.Green;
                                Console.WriteLine("\n{0}: {1} {2}", tweet.Id, tweet.Language.ToString(), tweet.Text);
                                Console.ForegroundColor = ConsoleColor.White;
                                Console.WriteLine("\tLocation: {0}, {1}", tweet.Coordinates.Longitude, tweet.Coordinates.Latitude);
                            }

                            timer.Restart();
                            Console.WriteLine("\tTweets/sec: {0}", tweetCount);
                            tweetCount = 0;
                        }
                    };
                    

                    stream.StreamStopped += (sender, args) =>
                    {
                        var exceptionThatCausedTheStreamToStop = args.Exception;
                        var twitterDisconnectMessage = args.DisconnectMessage;
                        Console.WriteLine("\n" + exceptionThatCausedTheStreamToStop);
                        Console.WriteLine("\n" + twitterDisconnectMessage);
                    };

                    stream.StartStreamMatchingAllConditions();

                    //Espera 5 segundos
                    Thread.Sleep(5000);
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Exception: {0}", ex.Message);
                }
            }
        }

**Comment by user156** [comment]
Why are you creating multiple streams inside an endless loop ?

**Comment by Hasgassa** [comment]
Without loop it returnes the same error. It is for testing purposes, never used this lib before.

**Comment by linvi** [comment]
Hello there, I am closing the issue as I think it is solved but please let me know if you still encounter this issue.

**Comment by linvi** [comment]
Verify StreamTask error handling line 133
