### ISSUE TITLE
StringExtension.ReplaceNonPrintableCharacters doesn't replace characters

### ISSUE THREAD

**Issue by sam-simpleclick** [linvi/tweetinvi#841]
https://github.com/linvi/tweetinvi/blob/a5dd374d951c25b29f9770927a102da07fb28afd/Tweetinvi.Core/Core/Extensions/StringExtension.cs#L166-L171

The if is missing an else, meaning that characters are inserted and not removed.

**Comment by linvi** [comment]
Thank you for reporting the issue, I will be fixing it for next release.
