### ISSUE TITLE
Unable to publish only image

### ISSUE THREAD

**Issue by prasadraja07** [linvi/tweetinvi#843]
I am trying to publish only the image(Single) without any text. Cant able to publish

-- getting the error message,  "The text message of a tweet cannot be null or empty."

Earliest reply will be highly appreciated

**Comment by redapollos** [comment]
I got by this by adding text of a space " ".

**Comment by linvi** [comment]
I will verify but I don't think Twitter Public API authorizes to do so.

**Comment by linvi** [comment]
This is now working in 5.0:

``` c#
var image = File.ReadAllBytes("/Users/tiimart/dev/tweetinvi/tweetinvi-logo-purple.png");
var media = await client.Upload.UploadBinary(image);
var tweet = await client.Tweets.PublishTweet(new PublishTweetParameters()
{
    Medias = { media }
});
```

**Comment by prasadraja07** [comment]
Kindly ensure this features has been updated in the .net core..
