### ISSUE TITLE
Tweetinvi equivalent to Tweepy "api.statuses_lookup"?

### ISSUE THREAD

**Issue by grindthemall** [linvi/tweetinvi#847]
I've been using Tweetinvi to grab streams of tweets with great success (especially love that I get ALL the fields back).

I have run into another use case where I need to go back in time and grab tweets by their "id_str", or "status" (i.e. https://twitter.com/web/status/<id_str>).

Tweepy has a way to do this via their api.statuses_lookup call, which retrieves up to 100 tweets at a time (the max you can return in a single call).  However Tweepy does not give me all the data, and it formats and removes a lot of fields that I need to make decisions.

I have searched through the Users, Timelines and several other sections of Tweetinvi but cannot find a Tweetinvi equivalent to grabbing a tweet by its status or id_str.

Am I missing something, or does this capability not exist within Tweetinvi currently?

**Comment by linvi** [comment]
Please use the following: `Tweet.GetTweets(new long[] { 1, 2, 3 });`
