### ISSUE TITLE
Can we send multiple tweets?

### ISSUE THREAD

**Issue by jesxs** [linvi/tweetinvi#848]
Im trying to send multiple tweet with this function 
```
for (int i = tweetTimes; i > 0; i--)
            {
                Tweet.PublishTweet(actualTweet);
                Thread.Sleep(10000);
                drawTextProgressBar(i, tweetTimes);
            }
```
But is only tweeting 1 time. I tried also tweeting elements from an array and the result is the same. What is the cause of this?

**Comment by jgmdavies** [comment]
Is the text in the tweet the same each time?  If so, Twitter will reject the duplicates.

**Comment by linvi** [comment]
@jgmdavies is correct, a user cannot send a duplicate tweet within a specific time frame.
If you do so Twitter will reject the tweet.

**Comment by jesxs** [comment]
Do we know that time frame?

**Comment by linvi** [comment]
This is very low priority so please implement it on your own for now.
