### ISSUE TITLE
Namespace conflicts renders Webhooks unusable

### ISSUE THREAD

**Issue by tmarkovski** [linvi/tweetinvi#849]
It is currently impossible to use the WebHooksPlugin and the core package to work with Webhooks.
I see this is fixed in upcoming 5.0 - are there any nightly or pre-release package I can reference in the meantime?

```
Error CS0434: The namespace 'Tweetinvi.Webhooks' in 'Tweetinvi.Controllers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7247f14397bf67b9' conflicts with the type 'Webhooks' in 'Tweetinvi, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7247f14397bf67b9' (CS0434) (Bot.Builder.Community.Twitter.Adapter)
```

**Comment by linvi** [comment]
I am aware of this, this will be taken care of by 5.0.
