### ISSUE TITLE
Search.SearchRepliesTo sometimes hangs indefinitely

### ISSUE THREAD

**Issue by NibblyPig** [linvi/tweetinvi#85]
My code grabs all mentions and pulls down replies to each one in a loop.

Multiple calls to `Search.SearchRepliesTo` hangs indefinitely.

I have set both timeout values:

```
                TweetinviConfig.CURRENT_WEB_REQUEST_TIMEOUT = 5000;
                TweetinviConfig.APPLICATION_WEB_REQUEST_TIMEOUT = 5000;
```

But it is not affected by them. Monitoring active threads I can see the thread is stuck on that line indefinitely.

**Comment by linvi** [comment]
Hello,

Few questions for you:
* Are you using version 0.9.10?
* Are you setting up the RateLimit config?
* Which type of application is this (ASP.NET, WPF, Windows Phone, Mono...)

Thanks

**Comment by NibblyPig** [comment]
Hello

I am using 0.9.10.0
I am not using any ratelimit - this may be the problem, but there is no Exception, the line just hangs forever
This is a C# windows forms application running on windows

**Comment by linvi** [comment]
Hello there, I know it has been a while but I am going to work on this bug. Would you please share the code you use to invoke the SearchRepliesTo.

Thanks

**Comment by linvi** [comment]
I really need to know whether you are using recursive queries or not.

``` c#
// Are you doing :
var replies = Search.SearchRepliesTo(tweet, true);
// OR
var replies = Search.SearchRepliesTo(tweet, false);
```

Please let me know quickly as I'd like to release 0.9.10.1 in the coming days,

**Comment by linvi** [comment]
Without any further comment I am closing this issue. Feel free to reopen it.
