### ISSUE TITLE
Filtered stream stopped working?

### ISSUE THREAD

**Issue by jdahan91** [linvi/tweetinvi#851]
Using filtered stream, lately I'm getting my event handlers called pretty slow (3-4 seconds [sometimes more] after the event occured). Any ideas?

Edit: Now the stream api stopped working all of the sudden, anyone encounters the same issue?

**Comment by chethi666** [comment]
Yes I'm having the same issue..
Did you find any workarounds. 
I tried with the version 4 as well as with version 2.1. All of the cases the Filtered stream doesn't work.

**Comment by jdahan91** [comment]
No, I did not find a workaround.

**Comment by myblindy** [comment]
I'm also having the same issue, none of the API is working.

**Comment by nikop** [comment]
I think it's because twitter added delay to at least non-paid users.

**Comment by jdahan91** [comment]
> I think it's because twitter added delay to at least non-paid users.

If that's true, then this is Twitter's way to fight auto responders.

**Comment by myblindy** [comment]
Even the first call fails though, it doesn’t feel like a delay.

**Comment by nikop** [comment]
> Even the first call fails though, it doesn’t feel like a delay.

You need fixes from #850 otherwise it will fail to decode events and thus nothing will be posted.

**Comment by linvi** [comment]
Will be fixed by #850
