### ISSUE TITLE
getting "Object reference not set to an instance of an object" when running StartStreamMatchingAllConditions

### ISSUE THREAD

**Issue by chenKerman** [linvi/tweetinvi#855]
Hi,
I have a crawler that use Tweetinvi to collect twitts from twitter's stream API , by keywords.
Until a few hours, it works fine, but now, when it getting to the line
stream.StartStreamMatchingAllConditions();
i get the error : "Object reference not set to an instance of an object"

Can any one help me?

Chen

**Comment by dontbesorry80** [comment]
I have just started getting the same error today. Has Twitter changed something to stop this from working?

**Comment by jxlarrea** [comment]
Yes, there were changest o the Twitter API. The issue is already covered in #850, the only fix is to clone the repo, apply the patch #852 and rebuild the solution. Then remove Tweetinvi nuget package from your own solution and replace it with the rebuilt assemblies.

**Comment by rooonikz** [comment]
@chenKerman @dontbesorry80 just posted my solution in #850

**Comment by chenKerman** [comment]
Thanks, Now it's working!

**Comment by linvi** [comment]
Follow #850
