### ISSUE TITLE
Tweetinvi stopped working.

### ISSUE THREAD

**Issue by DavidBusayo** [linvi/tweetinvi#866]
i am using tweetinvi from last several month. now i am facing error "reference null" in same code which is running fine last week. 
i am using TweetInvi 4.0 right now.
any help regarding this will be highly appreciated!
Regards

**Comment by GodsWithin** [comment]
Duplicate of #850

**Comment by DavidBusayo** [comment]
can you upload modified DLL which is working?

**Comment by DavidBusayo** [comment]
@GodsWithin i have modified the dll can you explain step by step how to replace DLL in the project. because i am still facing errors

**Comment by GodsWithin** [comment]
Just replace the one you're using with the modified one in the references of your project.

**Comment by DavidBusayo** [comment]
@GodsWithin ok thanks

**Comment by linvi** [comment]
Please follow #850 .
