### ISSUE TITLE
Modified DLL Tweetinivi.Logic also throwing error

### ISSUE THREAD

**Issue by DavidBusayo** [linvi/tweetinvi#867]
![image](https://user-images.githubusercontent.com/51048612/58398329-2f4f6100-806e-11e9-9c20-72bf7e69f13a.png)

**Comment by GodsWithin** [comment]
Looks like it's just missing a reference to the System.Reflection.TypeExtensions assembly?
Should be available through entering `Install-Package System.Reflection.TypeExtensions -Version 4.5.1` in the NuGet console.

**Comment by linvi** [comment]
Please install the latest version of Tweetinvi 4.0.1.

``` sh
Install-Package TweetinviAPI -Version 4.0.1
```

**Comment by linvi** [comment]
Duplicate of #850
