### ISSUE TITLE
the application is in break mode

### ISSUE THREAD

**Issue by muratyagis** [linvi/tweetinvi#870]
Hi,
My all codes is working until few days ago.
2 days ago i open my project for keep going develop program and i saw program is not working.
I waited 1 day and i saw TweetinVi getting updated. I did update quickly.

And I'm getting error like this; https://prnt.sc/numizr and https://prnt.sc/numiq0

by the way, i'm using TweetSharp and TweetinVi API together

please help me! thanx <3

**Comment by linvi** [comment]
Hello there, I would suggest that you follow the issue #850.

As I asked previously, would it be possible for you to share a project where you can reproduce the issue.

Thanks,
Linvi

**Comment by muratyagis** [comment]
can you give me an e-mail address? i will send you my project as a .rar

**Comment by linvi** [comment]
Hi, sorry for very long reply. You can contact me directly on gitter.

https://gitter.im/linvi
