### ISSUE TITLE
Friendship.FriendshipController.DestroyFriendshipWith(uvm.ScreenName);

### ISSUE THREAD

**Issue by jamiemaguiredotnet** [linvi/tweetinvi#872]
Friendship.FriendshipController.DestroyFriendshipWith(uvm.ScreenName);

This always returns true bu isnt removing the user I follow?

Any ideas?  This use to remove accounts that I was following.

**Comment by linvi** [comment]
Hello,

I will investigate the problem. 
Thanks for reporting it.

Linvi

**Comment by linvi** [comment]
Tweetinvi 5.0 `client.Account.UnFollowUser` has been tested and works successfully.

In 5.0 a `Task` will be returned instead of boolean. If the task fails it means the operation was unsuccessful.
