### ISSUE TITLE
TweetInvi causing application failure on test servers

### ISSUE THREAD

**Issue by mpm01** [linvi/tweetinvi#874]
We have an application that is running fine on a dev box but when installed on two test servers fails as soon as it encounters any code accessing the TweetInvi library (4.0.1).  The following line causes an exception:

`ExceptionHandler.SwallowWebExceptions = false;`

This is odd as ExceptionHandler is a static class.  We tried commenting out this line but then hit the same issue with this one (again a static class):

`RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackOnly;`

Can anyone explain what might be causing this issue?  Thanks in advance.

**Comment by mpm01** [comment]
This seems to be some oddity with our continuous integration build server.  Builds fine on other machines.  Closing this issue.

**Comment by prakash-patel** [comment]
@mpm01  Do you know what was the oddity with your continuous integration build server? I am having same issue.
