### ISSUE TITLE
NullReferenceException on Timeline.GetUserTimeline

### ISSUE THREAD

**Issue by Jozeevis** [linvi/tweetinvi#875]
We have an application that tries to request the past couple of tweets from a specific user account. To do this, we have implemented the following piece of code:
```cs
 var appCreds = Auth.SetApplicationOnlyCredentials(_consumerKey, _consumerSecret, true);
				Auth.SetCredentials(appCreds);

 var timeLineTweets = Timeline.GetUserTimeline(userScreenName, new UserTimelineParameters() 
 {MaximumNumberOfTweetsToRetrieve = numberOfTweets});
```
This used to work fine, but suddenly we started getting a NullReferenceException from this piece of code. After some exploring, it seems that the error occurs in the last line.

Does anybody have any idea why this might be happening and how to solve it?

**Comment by intergleam** [comment]
https://github.com/linvi/tweetinvi/issues/850

**Comment by linvi** [comment]
Thanks @d668.

Please update to latest version of Tweetinvi.
