### ISSUE TITLE
Tweetinvi cannot get tweet's reply 

### ISSUE THREAD

**Issue by te94moo** [linvi/tweetinvi#877]
When I try to retrieve the tweet, I got it with the number of retweets only, I could not see the number of replies. It always show null even the tweet has number of replies.

**Comment by linvi** [comment]
I will investigate.
In the meantime if you can send me the tweet id for which you can reproduce the issue it will be idea.

Thanks,
Linvi

**Comment by linvi** [comment]
As documented to the field, 

``` c#
/// <summary>
/// This property is only available with the Premium and Enterprise tier products.
/// </summary>
```
