### ISSUE TITLE
Deserialize method throws Null Reference Exception

### ISSUE THREAD

**Issue by trex77** [linvi/tweetinvi#880]
I am using Tweetinvi API for almost 2 years for getting tweets from Search API. It was working fine until this morning. But suddenly my deserialize part of Json started to give "null reference exception". The exception is thrown from the code below. Have any idea or suggestion to fix this?

var tweetDTO = JsonConvert.DeserializeObject<ITweetDTO>(returnedJson, JsonPropertiesConverterRepository.Converters);

**Comment by trex77** [comment]
Finally i found the problem. The returned json tweet file contains user json which has a **Lang** property and it is **null** somehow. The deserialize method returns "null reference exception" due to this behaviour. As a workaround, before sending the tweet json to the deserialize method, i updated the null value with an not null value (i.e "en"). It fixed the problem temporarily. I hope this behaviour can be fixed in future releases.

**Comment by linvi** [comment]
Hi there,

There was a bug fix release for that problem which started to occur because Twitter changed their Lang object.

Please update to any version above 4.0.1.

Thanks
