### ISSUE TITLE
How to create user tweet stream

### ISSUE THREAD

**Issue by mmodsgtav** [linvi/tweetinvi#882]
I'm trying to make a program which writes every mention I get in the console. I have this code but I can't get it work. I hope you can help me. Thanks.

```
static void Mentions()
        {
            Auth.SetUserCredentials(key1, key2, key3, key4);
            User.GetAuthenticatedUser();
            var stream = Stream.CreateTweetStream();
            Console.WriteLine("Loading…");
            stream.TweetReceived += Stream_TweetReceived;
            stream.StartStream("");
        }

        private static void Stream_TweetReceived(object sender, Tweetinvi.Events.TweetReceivedEventArgs e)
        {
            
            Console.WriteLine(e.Tweet.Text);
        }
```
I also don't understand what I have to write in "url" argument in stream.StartStream() void.

**Comment by linvi** [comment]
Hello, if you want to get all events from a user you will want to use WebHooks. Read the following

* https://github.com/linvi/tweetinvi/wiki/Webhooks
* https://github.com/linvi/tweetinvi/wiki/Account-Activity
* https://github.com/linvi/tweetinvi/wiki/Webhooks-&-Account-Activity-Tutorial

If you only want to follow a user you will want to use the FilteredStream:

* https://github.com/linvi/tweetinvi/wiki/Filtered-Streams#filter-by-users
