### ISSUE TITLE
Custom query in advanced search

### ISSUE THREAD

**Issue by nohack12** [linvi/tweetinvi#89]
Hello,

I have a problem I don't know how to solve. I want to use an advanced search using custom querys.
What I need is to find tweets published from an account, ex: '@shakira' and also containing the hashtag,  ex: '#FightUnfair'

This is de query i have:
https://api.twitter.com/1.1/search/tweets.json?q=%23FightUnfair%20from%3AShakira

And my code:
var tweetsDTO = TwitterAccessor.ExecuteGETQuery<IEnumerable<ITweetDTO>>(query);
var tweets = Tweet.GenerateTweetsFromDTO(tweetsDTO);    

But i get the following error: 
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Tweetinvi.Core.Interfaces.DTO.ITweetDTO]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly. To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.

What am I doing wrong? Than you very much

**Comment by linvi** [comment]
Hello there, Sorry for not replying earlier. Do you still need help concerning this issue?
If I take some time I think I can definitely help you with this.

Please reopen the issue if you need help.
