### ISSUE TITLE
System.Runtime Issue

### ISSUE THREAD

**Issue by shivprasad-kharade** [linvi/tweetinvi#890]
while starting application getting this error

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.'

**Comment by linvi** [comment]
Please check https://github.com/linvi/tweetinvi/issues/871 and let me know if you can test .NET Framework 4.8.

Thanks

**Comment by linvi** [comment]
#871 got resolved as part of 5.0
