### ISSUE TITLE
Underlying Connection was closed, blank response from Twitter?

### ISSUE THREAD

**Issue by IanGlidewell** [linvi/tweetinvi#891]
I'm having a problem with my Twitter bot.  I'm having a hard time tracking down the issue.  The exception that is thrown.   I looked at the contents of the Twitter exception and the message from Twitter is just empty.  The issue started yesterday around 1:30 PM Eastern, and looking through their API status, the forums, and this, I'm not entirely sure what's gone wrong.   It was operating normally and abruptly stopped mid-day.

I'm guessing there's something going on with my authentication, either my credentials are bunk now and they haven't told me or I'm sending them the wrong way, or maybe some third thing that someone might be aware off.  I turned off the exception swallowing and output the response, but it's completely blank outside of what's in the exception itself, which is below:

  HResult=-2146233079
  Message=The underlying connection was closed: An unexpected error occurred on a send.
  Source=Tweetinvi.Credentials
  StatusCode=-1
  URL=https://api.twitter.com/oauth/request_token
  StackTrace:
       at Tweetinvi.Credentials.WebTokenFactory.LogExceptionOrThrow(TwitterException ex)
       at Tweetinvi.Credentials.WebTokenFactory.InitAuthenticationProcess(IConsumerCredentials appCredentials, String callbackURL, String credsIdentifier)
       at Tweetinvi.AuthFlow.InitAuthentication(IConsumerCredentials appCredentials, String callbackURL)

**Comment by olilittle** [comment]
I too am having an issue with Authentication today, my connection was dropped sometime during the night (GMT) and this morning all calls to GetAuthenticatedUser are returning a null value.

**Comment by IanGlidewell** [comment]
Authflow.Initauthentication is returning null for me.  I assumed I was doing something wrong but it was working fine up until yesterday.

I've been searching the forums and the past issues for the problem.  I've tried updating to 4.8, rebuilding the project, updating TweetInvi, and I followed a few other steps in similar looking issues, but they haven't really lead anywhere.  Have you found anything promising since your's went down?

**Comment by SlackerP** [comment]
Authflow.Initauthentication is returning null for me as well, it could be because Twitter is now requiring TLS 1.2 as stated here: https://api.twitterstat.us/ (scroll down to update on 25/7/2019)

**Comment by peterwtux** [comment]
Thanks, @SlackerP 

Alternate, code-based solution for older runtimes:
`System.Net.ServicePointManager.SecurityProtocol |= System.Net.SecurityProtocolType.Tls12;`

**Comment by ahmad-atallah** [comment]
> Thanks, @SlackerP
> 
> Alternate, code-based solution for older runtimes:
> `System.Net.ServicePointManager.SecurityProtocol |= System.Net.SecurityProtocolType.Tls12;`

@peterwtux where you made this change? and did it work?

**Comment by IanGlidewell** [comment]
I've added the servicepointmanager.sercurity protocol change.  I'm not getting a blank response anymore, so that seems like progress.  I'm getting 401 unauthorized now, so I may have broken it during troubleshooting the keys.

**Comment by olilittle** [comment]
> Thanks, @SlackerP
> 
> Alternate, code-based solution for older runtimes:
> `System.Net.ServicePointManager.SecurityProtocol |= System.Net.SecurityProtocolType.Tls12;`

This worked for me too, many thanks!

**Comment by IanGlidewell** [comment]
Yep.  Back up and running now.  TLS1.2 not being used was the problem.  Thanks for the help!

**Comment by ahmad-atallah** [comment]
I still not able to fix the issue, I changed the whole application framewrok to 4.7.2 and I tried to add `System.Net.ServicePointManager.SecurityProtocol |= System.Net.SecurityProtocolType.Tls12;`
before the authentication attempts and yet, not working

**Comment by CarlosFVSeetech** [comment]
Thanks for the hint! Project up and running again :)
Updated target framework from 4.5 to 4.6 and Tls1.2 started being used automatically.

**Comment by linvi** [comment]
Thanks for sharing your fix.

**Comment by Johnt201** [comment]
I updated framework to 4.7.2 and still needed
Alternate, code-based solution for older runtimes:
System.Net.ServicePointManager.SecurityProtocol |= System.Net.SecurityProtocolType.Tls12;

and that solved the problem for me.

**Comment by williamblacutt** [comment]
@Johnt201 Can you help me?

I don't know where i can put this "System.Net.ServicePointManager.SecurityProtocol |= System.Net.SecurityProtocolType.Tls12;"

**Comment by linvi** [comment]
@williamblacutt This is static, you can do this anywhere.

**Comment by farid-ics** [comment]
i fixe my issue  with System.Net.ServicePointManager.SecurityProtocol |= System.Net.SecurityProtocolType.Tls12;
thanks lots you save my day.

**Comment by peterwtux** [comment]
Adding this for posterity: https://johnlouros.com/blog/enabling-strong-cryptography-for-all-dot-net-applications shows how to modify the Registry so older .Net applications can connect to TLS 1.2 services without needng to manipulate System.Net.ServicePointManager.SecurityProtocol in code. I verified this on Server 2012 R2 (not with Tweetinvi but generic System.Net.WebRequest connections to a web server that requires TLS 1.2). Specifically, John recommends the following at an admin powershell prompt; in my experience a reboot may be required:

```
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord 

```
