### ISSUE TITLE
Hello world example not working on Ubuntu

### ISSUE THREAD

**Issue by aelassas** [linvi/tweetinvi#893]
I've set up my credentials and tested the Hello world example on Ubuntu:
```
// Set up your credentials (https://apps.twitter.com)
Auth.SetUserCredentials("CONSUMER_KEY", "CONSUMER_SECRET", "ACCESS_TOKEN", "ACCESS_TOKEN_SECRET");

// Publish the Tweet "Hello World" on your Timeline
var tweet = Tweet.PublishTweet("Hello World!");
```
But it's not working. tweet is always null and there's nothing on my twitter account.

I'm using the latest version of tweetinvi.

Can you help me please?

**Comment by Scobiform** [comment]
It is not related to ubuntu, catch the tweetinvi error

**Comment by aelassas** [comment]
How do i catch tweetinvi error?

**Comment by Scobiform** [comment]
Like usual....

catch (TwitterNullCredentialsException ex)

^^

**Comment by aelassas** [comment]
@Scobiform On Windows it's working fine but on Ubuntu I get the following error: 'Twitter is unable to perform your query within the timeout limit of 10000ms'.

**Comment by aelassas** [comment]
@Scobiform I changed ApplicationSettings.HttpRequestTimeout and now it's working fine on Ubuntu.

Thank you.
