### ISSUE TITLE
AutoFac runtime error when attempting to initialize TweetInvi in Xamarin Android

### ISSUE THREAD

**Issue by sirkris** [linvi/tweetinvi#896]
This one has me stumped.  When I build using Debug configuration, everything runs fine.  But when I build using Release configuration, the build goes fine but then the app crashes as soon as I try to initialize the TweetInvi library.  I wasn't able to find anything helpful on Google/SO/etc.

Here's the adb stack dump:

> --------- beginning of crash
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime: FATAL EXCEPTION: main
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime: Process: com.companyname.BirdieMobileApp, PID: 9382
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.TypeInitializationException: The type initializer for 'Tweetinvi.TweetinviConfig' threw an exception. ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = TweetinviSettingsAccessor (ReflectionActivator), Services = [Tweetinvi.Core.ITweetinviSettingsAccessor], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> No constructors on type 'Tweetinvi.Core.TweetinviSettingsAccessor' can be found with the constructor finder 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'. (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: No constructors on type 'Tweetinvi.Core.TweetinviSettingsAccessor' can be found with the constructor finder 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'.
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00051] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.Core.Resolving.InstanceLookup.Activate (System.Collections.Generic.IEnumerable`1[T] parameters) [0x0001a] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:    --- End of inner exception stack trace ---
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.Core.Resolving.InstanceLookup.Activate (System.Collections.Generic.IEnumerable`1[T] parameters) [0x0004d] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0 () [0x00007] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare (System.Guid id, System.Func`1[TResult] creator) [0x0002f] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.Core.Resolving.InstanceLookup.Execute () [0x00051] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance (Autofac.Core.ISharingLifetimeScope currentOperationScope, Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x0005f] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent (Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.Core.Resolving.ResolveOperation.Execute (Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00013] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent (Autofac.Core.IComponentRegistration registration, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00041] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.ResolutionExtensions.TryResolveService (Autofac.IComponentContext context, Autofac.Core.Service service, System.Collections.Generic.IEnumerable`1[T] parameters, System.Object& instance) [0x00023] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.ResolutionExtensions.ResolveService (Autofac.IComponentContext context, Autofac.Core.Service service, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00030] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.ResolutionExtensions.Resolve (Autofac.IComponentContext context, System.Type serviceType, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00007] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Autofac.ResolutionExtensions.Resolve[TService] (Autofac.IComponentContext context, System.Collections.Generic.IEnumerable`1[T] parameters) [0x00000] in <773915280c53497dbfb0899f8d1f1426>:0 
> 08-19 00:34:44.475  9382  9382 E AndroidRuntime:   at Tweetinvi.Injectinvi.AutofacThreadContainer.Resolve[T] (Tweetinvi.Core.Injectinvi.IConstructorNamedParameter[] parameters) [0x0002b] in <93de26df2bc84d029febbba83cd5d75f>:0 
> 08-19 00:34:44.476  9382  9382 E AndroidRuntime:   at Tweetinvi.Injectinvi.AutofacContainer.Resolve[T] (Tweetinvi.Core.Injectinvi.IConstructorNamedParameter[] parameters) [0x00005] in <93de26df2bc84d029febbba83cd5d75f>:0 
> 08-19 00:34:44.476  9382  9382 E AndroidRuntime:   at Tweetinvi.TweetinviContainer.Resolve[T] () [0x00020] in <93de26df2bc84d029febbba83cd5d75f>:0 
> 08-19 00:34:44.476  9382  9382 E AndroidRuntime:   at Tweetinvi.TweetinviConfig..cctor () [0x00000] in <93de26df2bc84d029febbba83cd5d75f>:0 
> 08-19 00:34:44.476  9382  9382 E AndroidRuntime:    --- End of inner exception stack trace ---
> 

I don't know why Release is causing it to throw up like this.  I tried reinstalling TweetInvi in the NuGet console but that had no effect.

Any ideas?  Releasing the app in Debug configuration is obviously not an option.

Thanks!

**Comment by sirkris** [comment]
Here's the exact line where it's failing:

TweetinviConfig.CurrentThreadSettings.TweetMode = TweetMode.Extended;

I've tried everything I can think of in terms of fiddling with the app settings but TweetInvi just won't work in Xamarin unless I run it in Debug configuration.  Does anybody know why this is happening?

**Comment by linvi** [comment]
Hi @sirkris , I have never encountered such a problem but will be looking into it.

Though please note that at the moment there is a more urgent issue (#850)  that I would like to solve as top 1 priority.

**Comment by linvi** [comment]
I have updated the version of Tweetinvi to 4.0.2 so that it becomes compatible with .NET Framework 4.7.2.

Please note that the it came with a cost which is the fact that for the moment Tweetinvi is no longer a StrongName package.

I will be glad to hear feedback on the subject before I close the issue.

**Comment by linvi** [comment]
5.0 has been tested with Xamarin Android.
