### ISSUE TITLE
Assembly References and Build Warnings

### ISSUE THREAD

**Issue by atlastodor** [linvi/tweetinvi#898]
First, great project!

When I build a very simple solution, I get build warnings.
1. Create an empty .Net Framework class library targeting v4.8
2. Use **PackageReference** format to reference TweetinviAPI 4.0.1
3. Build. You get:

```
warning MSB3277: Found conflicts between different versions of "System.Runtime" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
warning MSB3277: Found conflicts between different versions of "System.Security.Cryptography.Primitives" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
```
This is a conflict between many **_Tweetinvi.x.dll_**, **_Nitro.x.dll_** and **.Net Framework 4.8**. Often, this has no side effects, but as the project grows and when other components start to use other versions of for example System.Runtime, we start getting real problems (at runtime). So, the warnings become justified.

Additionally, in larger projects with many NuGet references, there is often a mismatch of references and versions. In our production project, we cannot get the referenced assembly versions to compile correctly, and at runtime, there is always a version mismatch.

My questions:
1. Can you solve the problem in the NuGet package, so that the TweetinviAPI automatically references the correct assemblies without interfering with .Net Framework 4.8 or other NuGet packages.
2. If not, what is the correct way to work around this and make TweetinviAPI co-exists with .Net Framework 4.8 and other NuGet packages.
3. Can you provide an App.Config with the necessary configuration and some instructions on how to use it.

Thanks!

**Comment by linvi** [comment]
Please try the latest version of Tweetinvi 4.0.2 and let me know if you still have the problem.

Thank you.

**Comment by atlastodor** [comment]
Sorry for the delayed response, I was on vacation. Yes, version 4.0.2 fixes the version related build warnings. Thank you.

**Comment by linvi** [comment]
Great, happy to hear about it :)
