### ISSUE TITLE
Issue with GetUsersFromIds and null data

### ISSUE THREAD

**Issue by nokturnal** [linvi/tweetinvi#9]
Hey,

Try out this little code snippet:

    Auth.SetUserCredentials("xxxxxx", "xxxxxx", "xxxxxx", "xxxxxx");
    var z = Tweetinvi.User.GetUsersFromIds(new List<long> { 1, 2, 3 }); // or any twitter Id's that do not exist

This will error yielding the following:

    Value cannot be null.
    at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
    at Tweetinvi.Factories.User.UserFactoryQueryExecutor.GetUsersDTOFromIds(IEnumerable`1 userIds)
    at Tweetinvi.Factories.User.UserFactory.GetUsersFromIds(IEnumerable`1 userIds)
    at Tweetinvi.User.GetUsersFromIds(IEnumerable`1 userIds)

If you put a twitter id that is known to exist with the other Id's that are known to NOT exist:

    Auth.SetUserCredentials("xxxxxx", "xxxxxx", "xxxxxx", "xxxxxx");
    var z = Tweetinvi.User.GetUsersFromIds(new List<long> { 783214, 1, 2, 3 });

... everything works as expected.

**Comment by linvi** [comment]
Thanks, I will take a look into it.

**Comment by nokturnal** [comment]
No worries, thanks for the quick response!

**Comment by linvi** [comment]
Hi, I have been able to reproduce the issue and I can say that this is a bug.
Now what would you expect from such a query, `null` or an empty collection?

**Comment by nokturnal** [comment]
I would return an empty collection as it is the expected return type... but a null would work... what do you think @linvi

**Comment by linvi** [comment]
Whilst I would normally return null if an error occurs in the WebRequest I think that in this context returning an Empty collection makes more sense.

I am working on this. A version 0.9.9.4 will be released tomorrow with non critical bug fixes.

**Comment by nokturnal** [comment]
Sweet!  Thanks for addressing this so quickly

**Comment by linvi** [comment]
Hi,

Knowing that I am taking a 2 weeks off I have reconsidered the release of version 0.9.9.4 on nuget.
This new version will be available on nuget as hidden (not main). I will post here how to update to 0.9.9.4 with nuget tomorrow.

I do not want to publish a main release only 2 days prior to leaving. The source code will also be available on github and codeplex.

For more information concerning the dates of limited support please visit here:

https://github.com/linvi/tweetinvi/issues/10

Cheers,
Linvi

**Comment by linvi** [comment]
You can now use nuget to get version 0.9.9.4 with the following command line.

`Install-Package TweetinviAPI -Version 0.9.9.4`

I am now closing the issue.
