### ISSUE TITLE
Always getting null from User.GetAuthenticatedUser();

### ISSUE THREAD

**Issue by kjpluck** [linvi/tweetinvi#902]
Hi, totally new to developing twitter bots. I have a fresh twitter API account only hours old and am trying to do the simplest thing on version 4.0.2.0.

I have entered valid credentials and also deliberately entered invalid ones. When I run the following code I always get a null authenticatedUser.

Fiddler tells me nothing, there is a 200 http request to the API on both valid and invalid creds. Would've though a 403 response would happen here.

 ```
using System;
using Tweetinvi;

namespace TestTwitter
{
    class Program
    {
        static void Main(string[] args)
        {
            Auth.SetUserCredentials("xxx", "xxx", "xxx-xxx", "xxx");
            
            var authenticatedUser = User.GetAuthenticatedUser();

            // authenticatedUser user is NULL here.

            var settings = authenticatedUser.GetAccountSettings();  // So fails with a null reference error here.

            Console.WriteLine(settings);
            Console.ReadKey();

            Tweet.PublishTweet("Beep bop! Testing automatic tweeting!");
        }
    }
}
```

Without getting the authenticated User and simply running Tweet.PublishTweet() the code runs without error with valid and invalid creds but no tweet is published.

I added the authenticatedUser lines to investigate the problem.

**Comment by kjpluck** [comment]
Without getting the authenticated User and simply running `Tweet.PublishTweet()` the code runs without error but no tweet is published.

I added the authenticatedUser lines to investigate the problem.

**Comment by kjpluck** [comment]
I'm using version 4.0.2.0

**Comment by linvi** [comment]
Have you updated to the latest version of Tweetinvi (4.0.2)?

**Comment by kjpluck** [comment]
Thank you.
Ok now I'm getting:

```Exception thrown: 'Tweetinvi.Exceptions.TwitterException' in Tweetinvi.Credentials.dll
An unhandled exception of type 'Tweetinvi.Exceptions.TwitterException' occurred in Tweetinvi.Credentials.dll
Additional information: The underlying connection was closed: An unexpected error occurred on a send.```

**Comment by kjpluck** [comment]
That happen with both valid and invalid creds

**Comment by kjpluck** [comment]
That exception is thrown on `var authenticatedUser = User.GetAuthenticatedUser();` and `Tweet.PublishTweet("Beep bop! Testing automatic tweeting!");`

**Comment by kjpluck** [comment]
Could this be due to a fresh twitter developer account? I've jumped through all the necessary hoops and my "app" is listed in my app list with no warnings or anything. It's freely giving me api keys etc.

**Comment by linvi** [comment]
I am not sure I will investigate tonight and see if I can reproduce it.

**Comment by kjpluck** [comment]
Cheers Mate!

I'll keep trying, wondering if it's a problem at twitter's end.

**Comment by kjpluck** [comment]
Just tried it using python with the same creds and it worked just fine so no problems with my account.

Just to be sure I tried again with tweetinvi which still showed the same issue.

**Comment by linvi** [comment]
Hello,

Could you please run the following code and send me the result from the log :

``` cs
TweetinviEvents.QueryAfterExecute += (sender, eventArgs) =>
{
    // I NEED TO KNOW ABOUT THIS
    Console.WriteLine(eventArgs.HttpContent);
    Console.WriteLine(eventArgs.Exception?.ToString());
};

Auth.SetUserCredentials("xxx", "xxx", "xxx-xxx", "xxx");

var authenticatedUser = User.GetAuthenticatedUser();
```

**Comment by kjpluck** [comment]
Will do this this UK evening.

Thank you.

**Comment by kjpluck** [comment]
Hi, looks like my problem was using VS2015!

I've updated to VS2019 and is all tikkateeboo!

I humbly apologise for wasting your time and thank you for your patience and help!

**Comment by linvi** [comment]
Great happy to hear that you solved the problem.
