### ISSUE TITLE
Unable To Get Screen Name From ID

### ISSUE THREAD

**Issue by nani2232** [linvi/tweetinvi#908]
``` c#
 var firstBatchOfFollowerIds = Userfollowerscraper.GetFollowerIds("iamdeathbringer", nextCursor, out nextCursor);
                followerIds.AddRange(firstBatchOfFollowerIds.SelectMany(x => x.Ids));
                foreach (var eFollowerId in followerIds)
                {
                    try
                    {
                        var followerName = User.GetUserFromId(eFollowerId);
                        dataGridView1.Invoke(new Action(() =>
                        {
                            dataGridView1.Rows.Add(followerName);
                        }));
                    }
                    catch(Exception ex)
                    {
                        MessageBox.Show(ex.ToString());
                    }
```

The above code is giving name of the account how can I get screen name (ex: @nani123)

**Comment by linvi** [comment]
I think the main problem you have here are the rate limits which will be met quickly.
You probably are better off using `User.GetUsersFromIds()`.

**Comment by nani2232** [comment]
U didnt understand  my query, Twitter profile shows two names, one starts with (@twitteruser)  and the other one is (twitter user name). I want to get @twitteruser .

**Comment by linvi** [comment]
Hello, I am not sure if this is what you are looking for but `User` objects have 2 properties:

* `ScreenName`
* `Name`

**Comment by linvi** [comment]
> https://github.com/linvi/tweetinvi/blob/d3c006af6bd751f4e090c41e4dadd812245c2fcf/Tweetinvi.Factories/Properties/Resources.cs#L40
> 
> it seems this is relavent. Not sure how to utilize it checking into it.

What is your question?

If your question is how can I use this:

``` c#
var user = User.GetUserFromId(42);
```
