### ISSUE TITLE
Amazing Library!

### ISSUE THREAD

**Issue by mikemike396** [linvi/tweetinvi#910]
Hey, I just want to say thank you for this library! We have been using LinqToTwitter but recently our users have had very inconsistent results when Tweeting with video media. Some posts would go out others would not attach the video. I found your library and noticed you wrote a custom chunking method that works with Twitter's new requirements for chunking all video uploads. 

Anyway, its working perfect now with your library! Thanks again we will recommend to anyone looking for a C# Twitter library. 

![image](https://user-images.githubusercontent.com/14999806/65742456-38088000-e0be-11e9-91ac-086f00d6c303.png)

![](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/apple/225/beer-mug_1f37a.png)

**Comment by linvi** [comment]
Hello,

I would like to say that I really appreciate this message. It is really nice to receive positive feedback from the community but even more when someone just open an issue to say it.

So thank you very much for this message, you have made my day :)

Cheers,
Thomas
