### ISSUE TITLE
User authentication in angular ASP.NET Core.

### ISSUE THREAD

**Issue by SabirHossain** [linvi/tweetinvi#921]
How can I authenticate an user while I'm using ASP.NET Core as backend and angular as frontend framework, The redirect is not work like MVC in angular so what is the best way get the user while using angular?

**Comment by linvi** [comment]
I am not sure what you mean by `The redirect is not work like MVC in angular so what is the best way get the user while using angular`. Tweetinvi is frontend agnostic. If you wish redirection in angular it will have to be something that you do in your logic.

**Comment by SabirHossain** [comment]
Yes, I managed to do it. thank you.
