### ISSUE TITLE
'Tweetinvi.Exceptions.TwitterNullCredentialsException'

### ISSUE THREAD

**Issue by pkjisssk** [linvi/tweetinvi#924]
Hi, my GetAuthenticatedUser() calls works but PublishTweet() calls is not working.
I got user informations. GetAuthenticatedUser() calls were ok.
PublishTweet() calls give me 'TwitterNullCredentialsException'.
What's wrong with my code.
I used Tweetinvi 4.0.2
Help plz…
Thanks

        public void SendTwitterUser(string ConsumerKey, string ConsumerSecret, string authToken, string secretToken)
        {
            string sRet = "hello";

            var userCredentials = Tweetinvi.Auth.CreateCredentials(ConsumerKey, ConsumerSecret, authToken, secretToken);
            var authenticatedUser = Tweetinvi.User.GetAuthenticatedUser(userCredentials);
            if (authenticatedUser == null)
            {
                var latestException = Tweetinvi.ExceptionHandler.GetLastException();
                Console.WriteLine("The following error occured : '{0}'", latestException.TwitterDescription);

            }
            else
            {
                /*Here excepction occurs*/
                var tweet = Tweetinvi.Tweet.PublishTweet(sRet);
            }
        }

**Comment by linvi** [comment]
Could you provide the exception that you receive?

**Comment by GodsWithin** [comment]
@linvi Isn't this just not working because he isn't calling the ``PublishTweet()`` method on the authenticated user? He's using the static method from the ``Tweet`` class.

**Comment by linvi** [comment]
@GodsWithin you are totally right.
