### ISSUE TITLE
Tweet.PublishTweetInReplyToId with media ?

### ISSUE THREAD

**Issue by linkthehylian** [linvi/tweetinvi#925]
According to the current version of the API, the Tweet.PublishTweetInReplyToId only has two required parameters. Which are a string and the original tweet's ID. Do you think you could add an optional parameter for media too ? Because right now if you want to publish two tweets that contain media. They have to be separate tweets.

Thanks.

**Comment by GodsWithin** [comment]
You can already do this by using

```cs
Tweet.PublishTweet("My Tweet's Text", new PublishTweetOptionalParameters
{
    InReplyToTweetId = <IdToReplyTo>,
    MediaBinaries = List<byte[]>,      // method 1
    MediaIds = List<long>,             // method 2
    Medias = List<IMedia>              // method 3
});
```

If you are dealing with videos, I'd advise you to read https://github.com/linvi/tweetinvi/wiki/Upload#upload-status-video.

**Comment by linkthehylian** [comment]
Thank you! This helps tremendously.
