### ISSUE TITLE
[question]Doing an interactive bot

### ISSUE THREAD

**Issue by KakCAT** [linvi/tweetinvi#931]
Hi, I'm trying to make a twitter bot. I want that some users can DirectMessage the bot with commands and the bot to respond.

One of my problems is that Message.GetLatestMessages has a limit of 1 query per minute  (15/15), so interactivity is hard to achieve when you only can respond once in a minute. Is there a way to get a continuous stream of direct messages like CreateFilteredStream but with DMs?

Another of the problems is that even with GetLatestMessage the system seems easy to DoS with several users continuously sending DMs to the bot. Is there any way to limit the received DMs to a few users? (I know this can be fixed by twitter DM configuration, not allowing strangers to message you, but I'd like to know if it's possible)

Thanks!

**Comment by linvi** [comment]
Hello there,

Webhooks will allow you to avoid the limits you currently face regarding retrieving DirectMessages.

You can find an example project `Examplinvi.WebhooksServer`.
And you can find about the subscription here : 

https://github.com/linvi/tweetinvi/blob/master/Examplinvi.WebhooksServer/Controllers/TweetinviWebhookController.cs#L113

Webhooks just came in version 4.0 and I want to simplify the development process in next release of Tweetinvi.

I hope this helps.

**Comment by KakCAT** [comment]
Hi linvi, thanks for the answer, I'll have the example as soon as I can. 

I know this is not the scope of the forum, but could you confirm me that webhooks are a premium-only feature? I think I had a look at it when browsing the twitter developer documentation but discarded it because of the premium restriction. It was a month ago and my memory is not as good as it used to be, and probably won't be able to have a look at it in some time :(

**Comment by linvi** [comment]
Webhooks have 2 levels,  free tier and not free. I don't remember the restrictions (I am in the train right now) but i think it should fit your purpose.

**Comment by KakCAT** [comment]
Thanks for the answer! As this is what I was searching for I'll close the issue. If more problems arise with webhooks when I finally can try it I'll reopen the issue.
