### ISSUE TITLE
Filtered Stream Had Two Error

### ISSUE THREAD

**Issue by fightlikeagirl** [linvi/tweetinvi#936]
Hello, 
I use .net framework with tweetinvi,  I started filtered stream and log it. Although the stream didn't close completely, just stopped and restarted again, I had two errors in the logs. So should I need a solution ? Or dont I just need anything because of stream always work except two times stopped and restarted?
I had these errors :

`Date : 4.12.2019 06:35:13
URL : https://stream.twitter.com/1.1/statuses/filter.json?track=son%20dakika%2Chaber&stall_warnings=true&tweet_mode=extended
Code : 408
Error documentation description : Twitter was not able to perform your query within the Timeout limit of -1 ms.
Error message : https://stream.twitter.com/1.1/statuses/filter.json?track=son%20dakika%2Chaber%2Cjandarma%2Cpkk%2Cter%C3%B6r%2Cypg%2Cbomba&stall_warnings=true&tweet_mode=extended web request timed out.` ,

And second error : 

`Hata:System.IO.IOException : Unable to read data from the transport connection : An existing connection was forcibly closed by the remote host
System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   location: System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   location: System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   location: System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
    location: System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
    location: System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
    location: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    location: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    location: System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
    location: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    location: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    location: System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
    location: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    location: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    location: System.IO.StreamReader.<ReadLineAsyncInternal>d__60.MoveNext()Mesaj
`

**Comment by linvi** [comment]
You should be expecting errors.

* The first one usually comes when Twitter API is being overwhelmed.
* The second is an expected one which is that Twitter document that they can close a connection on their end if needs be.

For both of these problems are expected and you should restart the stream when you face them. 

Cheers,
Linvi

**Comment by fightlikeagirl** [comment]
Thank you so much  linvi ,do you think is there any configuration when I run this app on docker container ? @linvi

**Comment by linvi** [comment]
I have not done any but I want to build one for version 5.0.

If you do build one I would be happy for you to share it.
