### ISSUE TITLE
Trouble with AuthFlow.InitAuthentication()

### ISSUE THREAD

**Issue by BobDenny** [linvi/tweetinvi#955]
Perhaps similar to (locked) https://github.com/linvi/tweetinvi/issues/850?

`ConsumerCredentials applicationCredentials = new ConsumerCredentials(OAuthSecrets.Apikey, OAuthSecrets.ApiSecretkey);
IAuthenticationContext authenticationContext = AuthFlow.InitAuthentication(applicationCredentials);`

applicationCredentials looks good, I can see the ConsumerKey and ConsumerSecret fields have the correct info.  I set Exceptions.SwallowExecptions to False.  I call AuthFlow.InitAuthentication() and I get an exception -2146233079 "The underlying connection was closed: An unexpected error occurred on a send.".  Looking at the Exception I see that it is coming from Tweetinvi.Credentials:

* HttpMethod: POST
* AuthorizationHeader: OAuth oauth_callback="oob",oauth_consumer_key="xxxxxxxxxxxxxxxxxxx",oauth_nonce="5056309",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1576209156",oauth_version="1.0",oauth_signature="45rtgj3IbQNaKWnGgkEoqeaGPBs%3D"
* QueryURL: https://api.twitter.com/oauth/request_token

This gets rejected by Twitter instantly.  I'm stuck at the gate to the world of Tweetinvi! Per packages.config I am running with 4.0.3. I have a feeling I am doing something stupid since so many people love this library ha ha. 

This is a Win7 system, but it has KB3154518 installed so it is capable of TLS 1.2 which Twitter started requiring last Summer. I have an old .NET 3.5 app running an updated version of Duane Roelands' TwitterVB2 library which I am dying to leave behind(!) and I can't use on .NET Core. Anyway this system is fine with .NET Framework 3.5 even and 4.8 to use TLS 1.2. That old app works fine, I just tested it. So I am stuck here.

**Comment by linvi** [comment]
Hello there,

First things first, I will need more context:

* What type of application are you building? (console, library, desktop app, web app)
* What version of the .NET Framework / .NETCore are you targeting? From my understanding you are targeting .NET Framework 4.8.
* Have you set the your ServicePointManager as explained [here](https://github.com/linvi/tweetinvi/wiki/ASP.NET-consideration)?
* Have you verified that the clock and region of your computer is properly configured?
* Have you tried building a new application on Windows 10, Visual Studio 2019 and tested that your code works? 

Cheers,
Linvi

**Comment by BobDenny** [comment]
Linvi -- thanks very much for the fast response!!! :-)

* Console application
* .Net Framework 4.7.2 (why? I can change it to 4.8, I just came back to this project after a pause)
* No ServicePointManager!! This may be it!!! I remember needing this to get TLS 1.2 on the old TwitterVB library (and I really dislike VB.net, ugh!)
*Region and clock are OK. I develop astronomy software, ha ha. The NTP updating is working.
* I was going to build a test app this morning. 

I am in a coffee shop now, and when I return I'll add that ServiceManager code.  I will follow up here. Thank you again!!

**Comment by BobDenny** [comment]
That was it! I am on my way. 

Would it make sense to just enable these protocols by default? I can't see a disadvantage, especially since Twitter is now *requiring* TLS 1.2. I'm not doing ASP.NET so I didn't see it in the Tweetinvi docs. I should have just tried it anyway since I had to do this in that old VB library. 

Thanks again!

**Comment by BobDenny** [comment]
OK, I'm receiving tweets, etc. Once again, thank you. I just donated to your project. Closing this ticket (which was resolved so quickly).

**Comment by linvi** [comment]
This is good to hear. Would you mind sharing solution for people having the same problem and reading this issue?

**Comment by linvi** [comment]
Thank you very much for the donation this is greatly appreciated :)
