### ISSUE TITLE
Rate limit info not updating, or ??

### ISSUE THREAD

**Issue by BobDenny** [linvi/tweetinvi#957]
I am using the TrackOnly mode for the rate limiter. I added the event handler, and I am logging from within it, so I know it is being fired on each request. See the attached: Snap1 is the relevant code, Snap2 is an annotated piece of the log, and log.txt is the entire (Twitter to Morse Code bot) log, ending in the 429 rates exceeded error. You can see requests being issued - the "remaining" stays at 15 (rem=15) but it should be decreasing by 1 with each request. The "time to reset" appears to be updated though. The results are being issued in a separate thread (and there may be many of these threads, one for each bot). 
[log.txt](https://github.com/linvi/tweetinvi/files/3964349/log.txt)
![Snap1](https://user-images.githubusercontent.com/1538556/70854622-64d96180-1e7b-11ea-8265-04cfc516889b.png)
![Snap2](https://user-images.githubusercontent.com/1538556/70854623-64d96180-1e7b-11ea-9c46-2da7feb5dfa0.png)

**Comment by linvi** [comment]
I will investigate but effectively if you use `Timeline.GetHomeTimeline` this should be detected by the `RateLimitUpdater`

**Comment by BobDenny** [comment]
I cannot use the static methods because each thread implements a separate bot with its own code speed and possible American/Railroad or International Code settings. Within each bot there may be multiple sources of news, coming from separate Twitter or RSS sources. Thus each thread may have multiple AuthenticatedUsers, each of which may be reading from multiple sources (timeline, direct messages, other users' timelines, mentions, etc). Thus the time limits must be applied to each AuthenticatedUser, not across an entire thread or the entire process.  How is Tweetinvi matching up the qargs.QueryURL with the AuthenticatedUser? I have not tested anything yet with multiple AuthenticatedUsers in a single thread. If this can't be supported it will be OK, I can live with that limitation.

I cloned the complete library solution as a way to more clearly understand how to use it. I have to say you have done an amazing project! THANK YOU.

**Comment by linvi** [comment]
Hello there,

Effectively you are pointing out the weak point of Tweetinvi library that I currently addressing as part of Tweetinvi 5.0.

Until the release of 5.0 I would strongly suggest to use `Auth.ExecuteOperationWithCredentials`.

https://github.com/linvi/tweetinvi/wiki/Credentials#lets-code

Let me know if this solved the problem?

Cheers,
Linvi

**Comment by BobDenny** [comment]
The code with `Auth.ExecuteOperationWithCredentials()` works OK for a single user, but the Rate Limits are not updating anyway. now I tried to log into two Twitter accounts on the same thread. The call to `AuthFlow.InitAuthentication()` is failing for the second twitter user. The image shows that I am using the form without the callback URL. ;

Message: `Object reference not set to an instance of an object.`
StackTrace:
```   at Tweetinvi.Credentials.RateLimit.RateLimitCacheManager.GetTokenRateLimitsFromTwitter(ITwitterCredentials credentials)
   at Tweetinvi.Credentials.RateLimit.RateLimitCacheManager.RefreshCredentialsRateLimits(ITwitterCredentials credentials)
   at Tweetinvi.Credentials.RateLimit.RateLimitCacheManager.GetQueryRateLimit(String query, ITwitterCredentials credentials)
   at Tweetinvi.RateLimit.GetQueryRateLimit(String query)
   at com.dc3.cwcom.CwNewsBot.<>c.<Main>b__74_0(Object sender, QueryBeforeExecuteEventArgs qargs) in D:\dev\misc\MorseTools\cwrss\cwrss.cs:line 1942
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Tweetinvi.Core.Events.EventHelpers.Raise[T](Object o, EventHandler`1 handler, T arg)
   at Tweetinvi.Core.Events.InternalTweetinviEvents.RaiseBeforeQueryExecute(QueryBeforeExecuteEventArgs queryAfterExecuteEventArgs)
   at Tweetinvi.WebLogic.TwitterRequestHandler.TryPrepareRequest(IHttpRequestParameters requestParameters, RateLimitTrackerMode rateLimitTrackerMode, ITwitterCredentials credentials, Boolean raiseEvents, ITwitterQuery& twitterQuery)
   at Tweetinvi.WebLogic.TwitterRequestHandler.ExecuteQuery(String queryURL, HttpMethod httpMethod, TwitterClientHandler handler, ITwitterCredentials credentials, HttpContent httpContent)
   at Tweetinvi.Credentials.WebTokenFactory.InitAuthenticationProcess(IConsumerCredentials appCredentials, String callbackURL, String credsIdentifier)
   at Tweetinvi.AuthFlow.InitAuthentication(IConsumerCredentials appCredentials, String callbackURL)
   at com.dc3.cwcom.CwNewsBot.LoginTwitter(String uname, Feed feed) in D:\dev\misc\MorseTools\cwrss\cwrss.cs:line 785```

![Snap1](https://user-images.githubusercontent.com/1538556/70870245-0e892300-1f4e-11ea-95f9-20364303ef27.png)

**Comment by BobDenny** [comment]
I am OK for now with not being able to get info from multiple Twitter user timelines/direct messages. I will leave the credentials-specific calls there though.

Meanwhile, I have been reading your library code and found

`ICredentialsRateLimits rateLimits = RateLimit.GetCredentialsRateLimits(twCreds, false);`

This is just what I need to implement the rate limiting strategy I had before, where instead of blocking the entire thread, I simply skip trying to get info from Twitter and instead read the RSS feeds only, waiting until after the reset time for the Twitter info type. The fact that I can pass the credentials means that eventually I might be able to support multiple twitter users within a thread.

**Comment by BobDenny** [comment]
Even better news... Once I removed the static RateLimits mode setting stuff, and went to retrieving the rate limits via credentials (as above), I can now log into multiple Twitter accounts within a single thread! This is looking better all the time. I do not need the rate limits to be "fixed" now, the static schemes don't work and I am happier to selectively retrieve data based on the limits for each feed (I check the *appropriate* limits before doing any requests.

**Comment by linvi** [comment]
This is great news. I am happy to great that you managed to make it work for you. 

If you find a work around I will leave this as is as 5.0 has and will continue to refactor RateLimits.

**Comment by BobDenny** [comment]
I have found a way to use the library fully,  They key was discovering RateLimit.GetCredentialsRateLimits(). I can now get status/hometimeline and direct messages from multiple Twitter accounts logged in simultaneously, on the same thread. THANK YOU AGAIN for helping me :-)

**Comment by linvi** [comment]
I am happy to hear this. I hope Tweetinvi 5.0 will make your problematic easier to fix.
In the meantime I am closing this issue :)
