### ISSUE TITLE
FilteredStream AddFollow

### ISSUE THREAD

**Issue by raghu11111111** [linvi/tweetinvi#96]
Hi Linvi,

Working with FilteredStream and follow 2+ accounts without adding any track.
stream.AddFollow(account1);
stream.AddFollow(account2);
..........
I don't see something like args.MatchingFollows, so tried below method to derive accounted.
But few tweets doesn't fall under any of the case below to get AccountID. Does it cover all the streaming cases? 
Please let me know, if anything I am missing.

stream.MatchingTweetReceived += (sender, args) =>
 {
                    long? accountid = null;
                    var streamFollowers = ((Tweetinvi.Streams.FilteredStream)sender).FollowingUserIds;
                    var tweet = args.Tweet;
                    if (tweet.InReplyToUserId != null && streamFollowers.ContainsKey(tweet.InReplyToUserId))
                    {
                        accountid = tweet.InReplyToUserId;
                    }
                    else if (tweet.IsRetweet && streamFollowers.ContainsKey(tweet.RetweetedTweet.CreatedBy.Id))
                    {
                        accountid = tweet.RetweetedTweet.CreatedBy.Id;
                    }
                    else if (streamFollowers.ContainsKey(tweet.CreatedBy.Id))
                    {
                        accountid = tweet.CreatedBy.Id;
                    }

                    // To do something
                    Console.WriteLine(tweet.Text);
                    if (accountid != null)
                    {
                        Console.WriteLine(accountid.ToString());
                    }
                    else
                    {
                        Console.WriteLine("Unknown AddFollow");
                    }
                };

Thanks

**Comment by linvi** [comment]
Hi,

There is no method `MatchingFollows` as all the Tweets contains a `CreatedBy.Id` that you can simply compare to a `HashSet<long>` containing the user ids you followed.

Because it is so simple for the developer to do it, I decided not to add this extra step to the matching logic which is already quite heavy and would support in theory 500 million tweets per day.

Does that make sense?

Cheers,
Linvi
