### ISSUE TITLE
API returning sporadic results.

### ISSUE THREAD

**Issue by pauldotknopf** [linvi/tweetinvi#961]
I don't think this is a problem with your API, as I am seeing the same issue with ```twurl```. However, maybe you guys would have some insight.

I'm trying to archive all tweets for a specific user. However, the number of tweets returned is sporadic, and sometimes empty.

```
var result = new List<Tweetinvi.Models.ITweet>();

var tweets =  Tweetinvi.Timeline.GetUserTimeline("realDonaldTrump", new Tweetinvi.Parameters.UserTimelineParameters
{
    MaximumNumberOfTweetsToRetrieve = 200,
}).ToList();

if (tweets.Count == 0)
{
    tweets =  Tweetinvi.Timeline.GetUserTimeline("realDonaldTrump", new Tweetinvi.Parameters.UserTimelineParameters
    {
        MaximumNumberOfTweetsToRetrieve = 200,
    }).ToList();
}

while (tweets.Count > 0)
{
    result.AddRange(tweets);
    
    tweets =  Tweetinvi.Timeline.GetUserTimeline("realDonaldTrump", new Tweetinvi.Parameters.UserTimelineParameters
    {
        MaximumNumberOfTweetsToRetrieve = 200,
        MaxId = result.Last().Id - 1
    }).ToList();
    
    if (tweets.Count == 0)
    {
        // Sometimes, this returns "0", but then returns results later.
        tweets =  Tweetinvi.Timeline.GetUserTimeline("realDonaldTrump", new Tweetinvi.Parameters.UserTimelineParameters
        {
            MaximumNumberOfTweetsToRetrieve = 200,
            MaxId = result.Last().Id - 1
        }).ToList();
        if (tweets.Count == 0)
        {
            // Empty again?
            Console.WriteLine("What?");
        }
    }
}
```

Any ideas? The ```result``` will be random. Obviously, I'm not doing something right.

**Comment by linvi** [comment]
Hello there,

Effectively you encountered one of the problem of the api. Whilst it is very rare to receive empty set from twitter the number of returned items is effectively sporadic for Timelines.

The best approach to that solution is to perform the request twice when receiving an empty result.
Unfortunately it is an issue with Twitter. You can speak with the developers on https://twittercommunity.com/.

Cheers,
Linvi
