### ISSUE TITLE
GetAuthenticatedUser

### ISSUE THREAD

**Issue by vinceweeks-69** [linvi/tweetinvi#973]
using AuthFlow in our .NET MVC app, we ask for a user's Twitter name/pwd to establish a connection to Twitter. Our registered "confirmation" callback function looks like:

``` c#
[AllowAnonymous]
public ActionResult Confirmation(long hash, string oauth_token, string oauth_verifier, string authorization_id)  

// Using the last 3 parameters we then call
ITwitterCredentials newCredentials = AuthFlow.CreateCredentialsFromVerifierCode(oauth_verifier, authorization_id);

// and get a non null response 
```

We then call:

``` c#
Auth.SetCredentials(newCredentials);

// But, when we try:
 
 string connected_as = null;
 IAuthenticatedUser authenticatedUser = null;

 Auth.ExecuteOperationWithCredentials(newCredentials, () =>
 {
    // Get the IAuthenticatedUser from the specified credentials
    authenticatedUser = User.GetAuthenticatedUser(newCredentials);
    if (authenticatedUser != null)
         connected_as = authenticatedUser.ScreenName;
 });

// We get an exception.

// I've tried: 
Tweetinvi.ExceptionHandler.SwallowWebExceptions = false;
try
{
}
catch(Tweetinvi.Exceptions.TwitterException tweetEx)
{
    //Execution never gets here
}
 // I've tried:
try
{
}
catch(Exception ex)
{
     //always returns null
     var lastEx = Tweetinvi.ExceptionHandler.GetLastException();
}
```

I've spent several days on this - I've tried many different approaches and it just doesn't work - Any help you could provide would be greatly appreciated

**Comment by vinceweeks-69** [comment]
Forgot to mention TweetInvi version 4.0 - .NET framework 4.6.1 - Windows 10

**Comment by linvi** [comment]
Hello @vinceweeks-69,

Unfortunately as you did not manage to get out an exception out of Tweetinvi it will actually be impossible for me to help you without having access to your code.

Is it possible for you to share some code that reproduces this issue?

Thanks
Linvi

**Comment by vinceweeks-69** [comment]
Thanks for your response but, I'm confused. The code that I've sent, is the code that fails. The call to GetAuthenticatedUser is the one that fails. Further, the code to retrieve credentials also goes through TweetInvi. There isn't any code of ours that could possibly participate in this.

**Comment by linvi** [comment]
Hello there,

I don't think there is a problem with your code per say. What I meant is that as you could not get some exception details, I would need to have access to a project that reproduces your issue.

If you could share a project on github or via a zip file I will be able to test it and provide further help.

Cheers,
Linvi

**Comment by vinceweeks-69** [comment]
Thanks for your response. I'll have to see if I can get permission.

**Comment by linvi** [comment]
Closing as receiving no more feedback.
