### ISSUE TITLE
AuthFlow.InitAuthentication() returns null

### ISSUE THREAD

**Issue by Manjinder70** [linvi/tweetinvi#974]
Hi, we have tried using Tweetinvi 4.0.3 and I am getting a null back from InitAuthentication() and I believe my keys are correct:

        Dim appCredentials As ITwitterCredentials = New TwitterCredentials(userKey, userSecret, consumerKey, consumerSecret)
        Dim authenticationContext As IAuthenticationContext = AuthFlow.InitAuthentication(appCredentials, "https://localhost:70")

        Process.Start(authenticationContext.AuthorizationURL)
        Dim pinCode As String = Console.ReadLine()
        Dim userCredentials As ITwitterCredentials = AuthFlow.CreateCredentialsFromVerifierCode(pinCode, authenticationContext)
        Auth.SetCredentials(userCredentials)

        user = User.GetAuthenticatedUser(userCredentials)

I have set the callback URL in my Twitter app to "https://locahost:70". Even if I choose another web address like "https://www.twitter.com", it still does not work.

**Comment by linvi** [comment]
Hello,

What do you mean by "it does not work"?
What is your experience?

Thanks,
Linvi

**Comment by linvi** [comment]
This flow will no longer be available in 5.0. Closing.
