### ISSUE TITLE
Unable to publish Tweet with image using MediaIds

### ISSUE THREAD

**Issue by dev-bre** [linvi/tweetinvi#977]
Trying to publish a tweet referencing a MediaId results in the following exception:

> Bad Request - The request was invalid or cannot be otherwise served. An accompanying error message will explain further. In API v1.1, requests without authentication are considered invalid and will yield this response.

I am uploading the image and then publishing the tweet in 2 steps:

I upload the image using this snippet:
```
 var media = Auth.ExecuteOperationWithCredentials(creds, () =>
 {
       return Upload.UploadBinary(imageBinary);
 });
```

And then I try to publish the tweet using the mediaId retrieved from the previous response:

```
    var options = new PublishTweetOptionalParameters();
    options.MediaIds.Add(long.Parse(mediaId));
     var tweet = Auth.ExecuteOperationWithCredentials(creds, () =>
     {
         return Tweet.PublishTweet(post.PostContent, options);
     });
```

Any idea how to solve this?

**Comment by linvi** [comment]
Hello,

I am not sure what is the problem you are facing but the code looks correct to me.

Could you please share the exception you are receiving?

Cheers,
Linvi

**Comment by dev-bre** [comment]
Hi,
The error message was the one I added to my previous comment.

Anyways, in order to make it work I had to submit the media byte array straight into the publish tweet method.

This is something you might look into anyways.

**Comment by linvi** [comment]
Will be looking into it for next release. Thanks for the comment.

**Comment by linvi** [comment]
Checked and everything work as expected in 5.0
