### ISSUE TITLE
fix upload video and add Unblock Methods

### ISSUE THREAD

**Issue by ON-MX** [linvi/tweetinvi#98]
hi there
thanks for this library its really awesome ^__^.
i see two issue in side it and i fix it.
first issue is uploadVideo now using POST media/upload (chunked) which have limit from twitter in upload "For chunked uploads, the maximum chunk size is 5MB"
i fix it by divide each video in three chunk (Max video 15MB)
Tweetinvi.Controllers.Upload.UploadQueryExecutor

          public IMedia ChunkUploadBinary(byte[] binary, string mediaType)
        {
            //problem we upload more than 5MB for chunk
            //we solve it by divide all binary in three chunk
            var uploader = CreateChunkedUploader();
            int len = binary.Length / 3;

            if (uploader.Init(mediaType, binary.Length))
            {
                int x;
                for(int i=0;i<3;i++)
                {
                    x =(i==2)? binary.Length - (len * i) : len;
                    if (!uploader.Append(binary.Skip(len * i).Take(x).ToArray()))
                    {
                        return null;
                    }
                }
                return uploader.Complete();
            }

            return null;
        }

2) Second issue is UnBlock method not accessible from outside library 
i just add public to User class
Tweetinvi.User

        // UnBlockUser User
            public static bool UnBlockUser(IUserIdentifier userIdentifier)
        {
            return UserController.UnBlockUser(userIdentifier);
        }

        public static bool UnBlockUser(long userId)
        {
            return UserController.UnBlockUser(userId);
        }

        public static bool UnBlockUser(string userScreenName)
        {
            return UserController.UnBlockUser(userScreenName);
        }

thanks you again for this library

**Comment by linvi** [comment]
**First issue is uploadVideo now using POST media/upload (chunked) which have limit from twitter in upload "For chunked uploads, the maximum chunk size is 5MB"
i fix it by divide each video in three chunk (Max video 15MB)**

Hi, I am aware of the POST media/upload and the 5MB limitation. For some reason I never intended to do more than 1 call to the Chunked Upload. I left that to the user. But thinking about it, I think you are right and this should be automatically done.

**Second issue is UnBlock method not accessible from outside library 
i just add public to User class
Tweetinvi.User**

Thanks for reporting this. I will add it for the next release.
Please know that you can create pull requests in which you can do the changes on github and send them to me. This way you will have the credit for the changes ;)

Thanks again
