### ISSUE TITLE
InvalidOperationException: Build() or Update() can only be called once on a ContainerBuilder.

### ISSUE THREAD

**Issue by mphacker** [linvi/tweetinvi#998]
When calling Auth.SetApplicationOnlyCredentials(appKey, appSecret, true) I started getting the error: InvalidOperationException: Build() or Update() can only be called once on a ContainerBuilder.  when running my app locally in Visual Studio.   The call stack shows:  

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Tweetinvi.Auth' threw an exception.
  Source=Tweetinvi
  StackTrace:
   at Tweetinvi.Auth.SetApplicationOnlyCredentials(String consumerKey, String consumerSecret, Boolean initializeBearerToken)
   at ArchobotCore.Services.Twitter.TwitterClient..ctor(MainViewModel mainView) in D:\Source\Repos\ArchobotCore\ArchobotCore\ArchoBotCore\Services\Twitter\TwitterClient.cs:line 49

  This exception was originally thrown at this call stack:
	Autofac.ContainerBuilder.Build(Autofac.Core.IComponentRegistry, bool)
	Autofac.ContainerBuilder.Build(Autofac.Builder.ContainerBuildOptions)
	Tweetinvi.Injectinvi.AutofacContainer.Initialize()
	Tweetinvi.TweetinviContainer.Resolve<T>()
	Tweetinvi.Auth.Initialize()
	Tweetinvi.Auth.Auth()

Inner Exception 1:
InvalidOperationException: Build() or Update() can only be called once on a ContainerBuilder.

This is a .NET Core 3.1 App.   I haven't changed any code related to Twitter in my app and this just started happening today when I went to run my app in Visual Studio 2019.

**Comment by mphacker** [comment]
Strange thing is it seems to only happen when running in debug mode in  Visual Studio 2019 v16.4.6.  If I publish the app and run it I don't hit this issue.

**Comment by mphacker** [comment]
Workaround.  Compile app for debug.  Launch app and then attach VS Debugger.

**Comment by mphacker** [comment]
Seems like the issue is occurring when I have code that tries to change the credentials using Auth.SetApplicationOnlyCredentials(appKey, appSecret, true);  After it has already been set.   I am doing this when my configuration for the key / secret changes.

**Comment by mphacker** [comment]
Seems like I might have another NuGet package that is using Autofac and they are conflicting.  Trying to track it down.  If I move my auth call up sooner in my code it works fine.

**Comment by linvi** [comment]
Hello,

Thanks, for the feedback and sorry for the late reply.
Tweetinvi 5.0 container initialisation lifecycle has been drastically changed and should avoid this issue.

Thanks for getting back and explaining how you fixed your problem.

Cheers,
Linvi
