### ISSUE TITLE
GetAuthenticatedUser returning null

### ISSUE THREAD

**Issue by narikn** [linvi/tweetinvi#999]
var test = Auth.SetUserCredentials("xx", "xxxx", "xxx", "xxxxx");

            TweetinviEvents.QueryAfterExecute += (sender, eventArgs) =>
            {
                // I NEED TO KNOW ABOUT THIS
                Console.WriteLine(eventArgs.HttpContent);
                Console.WriteLine(eventArgs.Exception?.ToString());
            };

            var user = User.GetAuthenticatedUser();

            Console.ReadKey();

I am getting following message:

--- Date : 15/03/2020 6:13:23 PM
URL : https://api.twitter.com/1.1/account/verify_credentials.json?skip_status=true&include_entities=true&include_email=true
Code : 401
Error documentation description : Unauthorized -  Authentication credentials were missing or incorrect.
Error message : https://api.twitter.com/1.1/account/verify_credentials.json?skip_status=true&include_entities=true&include_email=true web request failed.
Invalid or expired token. (89)

Please help

**Comment by linvi** [comment]
Here you go `Invalid or expired token. (89)`

This means that the toke you are using is no longer valid.
You can refresh a token by reauthenticating the user.

If you are using credentials from apps.twitter.com you should go on your app and refresh your credentials.

Thanks,
Linvi
